### ISSUE TITLE
Problems creating config.json

### ISSUE THREAD

**Issue by bereklauw** [homebridge/homebridge#2084]
My config.json keeps having errors and I cannot figure out what is wrong. I've tested it on jsonLint.com and it says the file is valid. But stil:

[2018-12-9 13:25:37] There was a problem reading your config.json file.
[2018-12-9 13:25:37] Please try pasting your config.json file here to validate it: http://jsonlint.com
[2018-12-9 13:25:37] 
/usr/local/lib/node_modules/homebridge/lib/server.js:214
    throw err;
    ^

SyntaxError: Unexpected token \ in JSON at position 1
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:208:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:30:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

and this is my config file:

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

"platforms": [
        {
                "platform": "HarmonyHub",
                "name": "Harmony Hub"
        }
   ] 
}

I retyped the file over several times, but nothing changed. I'm lost......

Maybe someone can help me out.....

**Comment by 400HPMustang** [comment]
> My config.json keeps having errors and I cannot figure out what is wrong. I've tested it on jsonLint.com and it says the file is valid. But still:

> Maybe someone can help me out.....

I think you need a description, it's not optional...I can't remember if an accessory is optional or not but try this:

`{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"description": "Lorem Ipsum",

	"accessories": [{}],

	"platforms": [{
		"platform": "HarmonyHub",
		"name": "Harmony Hub"
	}]
}`

**Comment by bereklauw** [comment]
Found it: a matter of RTFM. The Readme file provided the answer: I used the Mac Textedit app. The readme said not to use this. I've downloaded the suggested Atom app, created a new config file and everything worked flawless. 

Thanks for the help!

**Comment by bereklauw** [comment]
Absolutely! Thanks for the support

**Comment by MartinNuc** [comment]
@bereklauw you should be able to close it
