### ISSUE TITLE
there's a problem reading my config.json file

### ISSUE THREAD

**Issue by ofekRDT** [homebridge/homebridge#2301]
Hi, I tried to download homebridge via curl (-sSL goo.gl/Ksdhph | bash)
everything went fine till I tried to run Homebridge 
its says that:
Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at Server.listen (net.js:1467:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:616:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:132:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:101:10)
[2019-9-10 12:47:52] Got SIGTERM, shutting down Homebridge...
please help!!

**Comment by mafyata** [comment]
Is your config.json ok ?

**Comment by buenyamin-olgun** [comment]
Seems like that the port 51826 is already blocked.
Maybe you are running the same instance twice?

You could try changing the port in your config.json
