### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/var/homebridge'

### ISSUE THREAD

**Issue by redfirebrooks** [homebridge/homebridge#2312]
Hello,
Checking my  /var/log/syslog I discovered a lot of errors
I am running domoticz Version: 4.10717 on
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch

```
Sep 18 22:49:08 domoticz systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Sep 18 22:49:08 domoticz systemd[1]: Stopped Node.js HomeKit Server.
Sep 18 22:49:08 domoticz systemd[1]: Started Node.js HomeKit Server.
Sep 18 22:49:10 domoticz homebridge[1787]: /usr/lib/node_modules/homebridge/node_modules/mkdirp/index.js:90
Sep 18 22:49:10 domoticz homebridge[1787]:                     throw err0;
Sep 18 22:49:10 domoticz homebridge[1787]:                     ^
Sep 18 22:49:10 domoticz homebridge[1787]: Error: EACCES: permission denied, mkdir '/var/homebridge'
Sep 18 22:49:10 domoticz homebridge[1787]:     at Object.fs.mkdirSync (fs.js:885:18)
Sep 18 22:49:10 domoticz homebridge[1787]:     at sync (/usr/lib/node_modules/homebridge/node_modules/mkdirp/index.js:71:13)
Sep 18 22:49:10 domoticz homebridge[1787]:     at Function.sync (/usr/lib/node_modules/homebridge/node_modules/mkdirp/index.js:77:24)
Sep 18 22:49:10 domoticz homebridge[1787]:     at LocalStorage.parseDirSync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:642:20)
Sep 18 22:49:10 domoticz homebridge[1787]:     at LocalStorage.parseDataDirSync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:572:21)
Sep 18 22:49:10 domoticz homebridge[1787]:     at LocalStorage.initSync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:145:14)
Sep 18 22:49:10 domoticz homebridge[1787]:     at Object.nodePersist.initSync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/node-persist.js:41:29)
Sep 18 22:49:10 domoticz homebridge[1787]:     at Object.init (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js:31:13)
Sep 18 22:49:10 domoticz homebridge[1787]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:28:7)
Sep 18 22:49:10 domoticz homebridge[1787]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Sep 18 22:49:10 domoticz systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Sep 18 22:49:10 domoticz systemd[1]: homebridge.service: Unit entered failed state.
Sep 18 22:49:10 domoticz systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

Dont know how to fix it...

**Comment by codyc1515** [comment]
You may need to create the directory /var/homebridge. If it exists you will need to change the permissions to make it work.
