### ISSUE TITLE
homebridge service error

### ISSUE THREAD

**Issue by matty0511** [homebridge/homebridge#2317]
Im getting this error constantly..
Error: listen EADDRINUSE :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1345:14)
    at listenInCluster (net.js:1386:12)
    at Server.listen (net.js:1474:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:616:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:132:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:101:10)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
Got SIGTERM, shutting down Homebridge...

**Comment by vdcore** [comment]
change the port from config plugin (8080 to 8081) ... 
port 8080 using by home bridge (display devices) and 8081 (display the old missing config-x-ui)

**Comment by luixiuno** [comment]
I got a problem with hoobs and I got this error: Got SIGTERM, shutting down Homebridge...

I can't change the port because of the service not running

**Comment by luixiuno** [comment]
I can't belive it, I just solved it by making a factory reset

**Comment by LeonC169** [comment]
> I can't belive it, I just solved it by making a factory reset

How do you make a factory reset?

I have the same error and I tried changing the port but the error continue.

**Comment by LeonC169** [comment]
I have the same error:

Error: listen EADDRINUSE: address already in use :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:616:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:132:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:101:10)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
[3/24/2020, 7:37:51 PM] Got SIGTERM, shutting down Homebridge...
[3/24/2020, 7:37:53 PM] [Config] Homebridge Config UI X v4.13.0 is listening on :: port 8081
[3/24/2020, 7:37:54 PM] [Config] Error: listen EADDRINUSE: address already in use :::8081
[3/24/2020, 7:37:54 PM] [Config] Another process or service on this host is using port 8081.
[3/24/2020, 7:37:54 PM] [Config] Please stop the other service or change the port you have assigned to homebridge-config-ui-x.
[3/24/2020, 7:37:54 PM] [Config] Ending process now.
MacBook-Pro-de-Luciano:~ lucianoperez$

**Comment by LeonC169** [comment]
Y changed the port to: 8080, 8081 and 8580 but the error continue.

**Comment by oznu** [comment]
How have you setup your service? It looks like you are getting stale process which is resulting in multiple copies of Homebridge running.

I would recommend removing any exisiting services, doing a full reboot, then following the guide in the wiki to get setup properly:

https://github.com/homebridge/homebridge/wiki
