### ISSUE TITLE
Startup aborts with port error after updating- checked port not in use

### ISSUE THREAD

**Issue by Josh3955** [homebridge/homebridge#2320]
### Expected Behavior
Startup of Homebridge without error.

### Current Behavior
Homebridge parses the config.json and begins its startup process. When it gets to the point where it should be up, it throws an error about the port being in use then sends a SIGTERM. Despite this, at least parts of it keep running.

### Steps to Reproduce (for bugs)
I updated my Raspberry to the latest updates for raspberian and npm. I'm assuming right now the issue is introduced in one of the later updates as my setup has been working flawlessly for months.

### Versions
pi@Pi:~/.homebridge $ homebridge --version
0.4.50
pi@Pi:~/.homebridge $ node --version
v10.10.0
pi@Pi:~/.homebridge $ uname -a
Linux Pi 4.19.66+ #1253 Thu Aug 15 11:37:30 BST 2019 armv6l GNU/Linux
pi@Pi:~/.homebridge $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

### Configuration

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "B6:27:EB:7B:59:B7",
        "port": 51826,
        "pin": "031-45-154"
    },


    "accessories": [
        {
        "accessory": "Chamberlain",
        "name": "Garage Door",
        "username": "############",
        "password": "###########" 
        },

        {
        "accessory": "Roomba",
        "name": "Rosie",
        "blid":"3164420C51533740",
        "robotpwd": "###############",
        "ipaddress": "192.168.11.94"
        }

                   ],

    "platforms": [
        {
            "platform" : "Nest",
            "clientId": "###############",
            "token": "##################" 
         }
                  ]
}

```

### Homebridge Log / Command Output

```
pi@Pi:~/.homebridge $ netstat -tulpn
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
tcp6       0      0 :::445                  :::*                    LISTEN      -                   
tcp6       0      0 :::139                  :::*                    LISTEN      -                   
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -                   
udp        0      0 192.168.11.255:137      0.0.0.0:*                           -                   
udp        0      0 192.168.11.210:137      0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:137             0.0.0.0:*                           -                   
udp        0      0 192.168.11.255:138      0.0.0.0:*                           -                   
udp        0      0 192.168.11.210:138      0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:138             0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:43487           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -                   
pi@Pi:~/.homebridge $ homebridge -D
[9/27/2019, 7:28:05 PM] Loaded config.json with 2 accessories and 1 platforms.
[9/27/2019, 7:28:05 PM] ---
[9/27/2019, 7:28:07 PM] Loaded plugin: homebridge-chamberlain
[9/27/2019, 7:28:07 PM] Registering accessory 'homebridge-chamberlain.Chamberlain'
[9/27/2019, 7:28:07 PM] ---
[9/27/2019, 7:28:20 PM] Loaded plugin: homebridge-nest
[9/27/2019, 7:28:21 PM] Registering platform 'homebridge-nest.Nest'
[9/27/2019, 7:28:21 PM] ---
[9/27/2019, 7:28:31 PM] Loaded plugin: homebridge-roomba
[9/27/2019, 7:28:31 PM] Registering accessory 'homebridge-roomba.Roomba'
[9/27/2019, 7:28:31 PM] ---
[9/27/2019, 7:28:31 PM] Loading 1 platforms...
[9/27/2019, 7:28:31 PM] [Nest] Initializing Nest platform...
[9/27/2019, 7:28:31 PM] [Nest] Fetching Nest devices.
[9/27/2019, 7:28:31 PM] Loading 2 accessories...
[9/27/2019, 7:28:31 PM] [Garage Door] Initializing Chamberlain accessory...
[9/27/2019, 7:28:32 PM] [Rosie] Initializing Roomba accessory...
[9/27/2019, 7:28:35 PM] [Nest] [NestFirebase] User null is logged in with custom
[9/27/2019, 7:28:35 PM] [Nest] initing thermostat "Nest Thermostat": deviceId: lqRyGeCgw0II84D2IoSfR5WpJAujdPfm structureId: JGDC99j_sn6qy06pRkEi1roUIyCmpvzxC-XzN_cqR6cHeZ1UrT7QTA
[9/27/2019, 7:28:35 PM] [Nest] { ambient_temperature_c: 21.5,
  ambient_temperature_f: 72,
  away_temperature_high_c: 25,
  away_temperature_high_f: 78,
  away_temperature_low_c: 15.5,
  away_temperature_low_f: 60,
  can_cool: true,
  can_heat: true,
  device_id: 'lqRyGeCgw0II84D2IoSfR5WpJAujdPfm',
  eco_temperature_high_c: 25,
  eco_temperature_high_f: 78,
  eco_temperature_low_c: 15.5,
  eco_temperature_low_f: 60,
  fan_timer_active: false,
  fan_timer_duration: 15,
  fan_timer_timeout: '1970-01-01T00:00:00.000Z',
  has_fan: true,
  has_leaf: false,
  humidity: 55,
  hvac_mode: 'cool',
  hvac_state: 'off',
  is_locked: false,
  is_online: true,
  is_using_emergency_heat: false,
  label: '',
  last_connection: '2019-09-28T00:25:00.046Z',
  locale: 'en-US',
  locked_temp_max_c: 22,
  locked_temp_max_f: 72,
  locked_temp_min_c: 20,
  locked_temp_min_f: 68,
  name: 'Nest',
  name_long: 'Nest Thermostat',
  previous_hvac_mode: '',
  software_version: '5.9.4-5',
  structure_id: 'JGDC99j_sn6qy06pRkEi1roUIyCmpvzxC-XzN_cqR6cHeZ1UrT7QTA',
  sunlight_correction_active: false,
  sunlight_correction_enabled: false,
  target_temperature_c: 22.5,
  target_temperature_f: 73,
  target_temperature_high_c: 24,
  target_temperature_high_f: 75,
  target_temperature_low_c: 20,
  target_temperature_low_f: 68,
  temperature_scale: 'F',
  time_to_target: '~0',
  time_to_target_training: 'ready',
  where_id: '1i7LbrlZQVa5fKqbZB3Yr5FQYhZFwh5noOEz0xAFZfFpfrwrSk7c4A',
  where_name: 'Nest' }
[9/27/2019, 7:28:35 PM] [Nest] Temperature unit for Nest Thermostat is: Fahrenheit
[9/27/2019, 7:28:35 PM] [Nest] Current temperature for Nest Thermostat is: 22.2 °C and 71.96000000000001 °F
[9/27/2019, 7:28:35 PM] [Nest] Current humidity for Nest Thermostat is: 55%
[9/27/2019, 7:28:35 PM] [Nest] Target temperature for Nest Thermostat is: 22.7 °C and 72.86 °F
[9/27/2019, 7:28:36 PM] [Nest] Target heating/cooling state for Nest Thermostat is: Cool
[9/27/2019, 7:28:36 PM] [Nest] Cooling threshold temperature for Nest Thermostat is: 23.8 °C and 74.84 °F
[9/27/2019, 7:28:36 PM] [Nest] Heating threshold temperature for Nest Thermostat is: 20 °C and 68 °F
[9/27/2019, 7:28:36 PM] [Nest] Home Occupied for Nest Thermostat is: true
[9/27/2019, 7:28:36 PM] [Nest] Initializing platform accessory 'Nest Thermostat'...
Setup Payload:
X-HM://0023ISYWY3683
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                          
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[9/27/2019, 7:28:37 PM] Error: listen EADDRINUSE :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:616:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:132:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:421:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/local/lib/node_modules/homebridge-nest/index.js:268:11
    at tryCatcher (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
[9/27/2019, 7:28:37 PM] Got SIGTERM, shutting down Homebridge...

```

**Comment by codyc1515** [comment]
You need to file this in the Nest plug-in issues as this issue is caused by the Nest plug-in. Nothing to do with HomeBridge itself.
