### ISSUE TITLE
HAP-NodeJS

### ISSUE THREAD

**Issue by netRunner0** [homebridge/homebridge#2323]
@KhaosT @nfarina 

When can I wait for an update to meet the new features already introduced in HAP-NodeJS?

Thank!

**Comment by KhaosT** [comment]
I’m super busy recently 😅 I’ll probably try to bump dependent HAP-NodeJS a bit later.

**Comment by stephenstarkie** [comment]
I don’t know if this is related; I have upgraded homebridge and homebridge-indigo today and am now running into the following error;


                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[10/2/2019, 11:06:11 PM] Homebridge is running on port 51826.
[10/2/2019, 11:06:41 PM] TypeError: buf.copy is not a function
    at Function.Buffer.concat (buffer.js:239:9)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairStepFive (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:459:21)
    at HAPServer._handlePairStepFour (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:439:8)
    at HAPServer._handlePairStepThree (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:413:8)
    at HAPServer._handlePair (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:315:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:80:13)
[10/2/2019, 11:06:41 PM] Got SIGTERM, shutting down Homebridge...

**Comment by codyc1515** [comment]
@stephenstarkie Your issue seems related to the TLV file which was changed recently in HAP-NodeJS, so you may be right https://github.com/KhaosT/HAP-NodeJS/commit/2cc06c2058380dbe07356c2b705377289e0ccee2

**Comment by KhaosT** [comment]
@codyc1515 we haven't bump homebridge to start using HAP-NodeJS 0.5.x so it's unlikely to be related.

@stephenstarkie what's the version of `nodejs` you are running?

**Comment by stephenstarkie** [comment]
@codyc1515 & @KhaosT Thanks - I am running nodejs v5.5.0

**Comment by stephenstarkie** [comment]
Also worth giving the package versions I guess;

$ npm list | grep homebridge
├─┬ homebridge@0.4.50
└─┬ homebridge-indigo@0.3.11

**Comment by KhaosT** [comment]
Can you try update nodejs to a newer version? v5.5 was released in 2016, and probably doesn’t have the Buffer.copy API with expected signature 😅

**Comment by NorDroN** [comment]
Any updates?
