### ISSUE TITLE
EACCES Error

### ISSUE THREAD

**Issue by recom273** [homebridge/homebridge#2332]
### Pre Steps

l am using a preconfigured image from a manufacturers site, its configured to use a shield - setup is through an app DeConz / Phoscon.

The creator of the plug-in says its not an issue with his plug-in - more of a permissions issue.

> The EACCES error is not good, but it's not caused by homebridge-hue. I think you previously ran homebridge as root (using sudo or as a service without specifying a user) and now as user pi. The user running homebridge needs permissions to read and write the files in ~/.homebridge/persist and in ~/.homebridge/accessories.

I didn't run anything as sudo or root. 

Does anyone know how I can fix this?

pi@phoscon:~ $ homebridge
[10/11/2019, 2:12:41 PM] Loaded config.json with 0 accessories and 1 platforms.
[10/11/2019, 2:12:41 PM] ---
[10/11/2019, 2:12:41 PM] Plugin /usr/lib/node_modules/homebridge-lib package.json does not contain the keyword 'homebridge-plugin'.
[10/11/2019, 2:12:45 PM] Loaded plugin: homebridge-hue
[10/11/2019, 2:12:45 PM] Registering platform 'homebridge-hue.Hue'
[10/11/2019, 2:12:45 PM] ---
[10/11/2019, 2:12:45 PM] Loading 1 platforms...
[10/11/2019, 2:12:45 PM] [Hue] Initializing Hue platform...
[10/11/2019, 2:12:45 PM] [Hue] homebridge-hue v0.11.37, node v10.16.3, homebridge v0.4.50
[10/11/2019, 2:12:45 PM] [Hue] warning: latest version: homebridge-hue v0.11.41
[10/11/2019, 2:12:45 PM] [Hue] Phoscon-GW: dresden elektronik deCONZ gateway v2.5.69, api v1.16.0
[10/11/2019, 2:12:45 PM] [Hue] Phoscon-GW: warning: not using recommended deCONZ gateway version 2.5.67
[10/11/2019, 2:12:46 PM] [Hue] Phoscon-GW: 2 accessories
[10/11/2019, 2:12:46 PM] [Hue] masked debug info dumped to /home/pi/.homebridge/homebridge-hue.json.gz
[10/11/2019, 2:12:46 PM] [Hue] Initializing platform accessory 'Phoscon-GW'...
[10/11/2019, 2:12:46 PM] [Hue] Phoscon-GW: 3 services
[10/11/2019, 2:12:46 PM] [Hue] Initializing platform accessory 'Motion Sensor'...
[10/11/2019, 2:12:46 PM] [Hue] { Error: EACCES: permission denied, open '/home/pi/.homebridge/persist/AccessoryInfo.2EFFFF0405B1.json'
at Object.openSync (fs.js:443:3)
at Object.writeFileSync (fs.js:1194:35)
at LocalStorage.persistKeySync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:476:16)
at LocalStorage.setItemSync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:277:14)
at Object.nodePersist.setItemSync (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/node-persist.js:99:29)
at AccessoryInfo.save (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/model/AccessoryInfo.js:163:11)
at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:552:23)
at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:132:16)
at Server. (/usr/lib/node_modules/homebridge/lib/server.js:421:14)
at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
errno: -13,
syscall: 'open',
code: 'EACCES',
path:
'/home/pi/.homebridge/persist/AccessoryInfo.2EFFFF0405B1.json' }
[10/11/2019, 2:12:48 PM] [Hue] Motion Sensor: set homekit light level from 51.9996 lux to 50.9918 lux
[10/11/2019, 2:14:45 PM] [Hue] Motion Sensor: set homekit motion from 1 to 0
[10/11/2019, 2:14:51 PM] [Hue] Motion Sensor: set homekit light level from 50.9918 lux to 51.9996 lux
[10/11/2019, 2:14:51 PM] [Hue] Motion Sensor: set homekit motion from 0 to 1
[10/11/2019, 2:14:56 PM] [Hue] Motion Sensor: set homekit light level from 51.9996 lux to 49.9919 lux
[10/11/2019, 2:15:01 PM] [Hue] Motion Sensor: set homekit light level from 49.9919 lux to 32.9989 lux

### Expected Behavior
Homebridge functions, it exposes the sensor I have added to the web GUI, but won't produce a QR code, however it allows me to manually enter the PIN and all seem to function in iOS.

### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **OS**:         

### Configuration

Raspberry Pi B / Raspbee Shield / DeConz / Phoscon

```json

```

### Homebridge Log / Command Output

```

```

**Comment by dxdc** [comment]
Looks like a permissions issue:

```sh
cd /home/pi/
sudo chown -R pi:pi .homebridge
```

> I didn't run anything as sudo or root.

You must have, otherwise, how did you get modules installed in `/usr/lib/`?

**Comment by recom273** [comment]
> Looks like a permissions issue:
> 
> ```shell
> cd /home/pi/
> sudo chown -R pi:pi .homebridge
> ```
> 
> > I didn't run anything as sudo or root.
> 
> You must have, otherwise, how did you get modules installed in `/usr/lib/`?

It was a preconfigured image from the manufacturer of the shield. 

Thanks, I will give it a try, I have Ben changing other permissions and ended up losing connection with the shield on the serial port.

**Comment by Garia666** [comment]
i have the same issue sadly
