### ISSUE TITLE
Unable to add Homebridge to HomeKit

### ISSUE THREAD

**Issue by forresthamilton** [homebridge/homebridge#2369]
When attempting to add home bridge to HomeKit I receive the following in terminal:
Homebridge is running on port 51826.
[12/17/2019, 8:00:26 PM] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:315:13)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at Object.encode (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairStepFive (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:459:21)
    at HAPServer._handlePairStepFour (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:439:8)
    at HAPServer._handlePairStepThree (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:413:8)
    at HAPServer._handlePair (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:315:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[12/17/2019, 8:00:26 PM] Got SIGTERM, shutting down Homebridge...

Any ideas on what this could mean? Any help is appreciated.

**Comment by sintezcs** [comment]
I'm experiencing the same error..

**Comment by forresthamilton** [comment]
I was able to get it working last night. Go to https://nodejs.org/en/ and download the most recent version. Also, clean up your config.json file to where it looks only like this:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [ ],
    "platforms": []
}

Once all of that is done, run homebridge in Terminal and you should be good to go. Then you can go into the config.json file and add platforms and accessories as desired. Hope this helps, this is what worked for me.

**Comment by bastelbert** [comment]
I had the same problem after updating my homebridge installation.
Reason was most likely the very old node.js version v7.10.1 installed on my pi.
I updated to v13, afterwards the error was gone:
curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
sudo apt-get install -y nodej
