### ISSUE TITLE
Homebridge won't start - problem with homebridge or plugin?

### ISSUE THREAD

**Issue by alexbohariuc** [homebridge/homebridge#2386]
Hey guys,

I installed the [homebridge-http-webhooks plugin](https://github.com/benzman81/homebridge-http-webhooks)  
After installing it and editing the config.json homebridge won't start or restart anymore. If i'm deleting the configuration of the json it works. 

This is the content of the config.json file for the http-webhooks plugin:
```
{
            "platform": "HttpWebHooks",
            "webhook_port": "51828",
            "lights": [
                {
                    "id": "light1",
                    "name": "Light name 1"
                }
            ]
        }
```
The file is saved, i checked it for errors. But if i try to restart homebridge it doesn't work.

If i check the homebridge status with  `sudo journalctl -f -n 200 -u homebridge`  i see this error:

```
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6335 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6345 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6401 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6404 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6411 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6414 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6473 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6476 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6483 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6552 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6555 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6562 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6565 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6622 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6625 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6632 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6635 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6697 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6707 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6710 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6767 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6889 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6892 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6899 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6902 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6959 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6962 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6969 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 6972 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7028 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7031 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7038 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7041 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7109 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7112 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7121 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7214 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7217 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7224 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7227 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7289 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7292 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7299 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7302 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7358 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7368 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7371 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7427 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7430 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7437 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7496 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7499 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7506 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7509 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7565 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7568 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7575 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7578 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7634 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7637 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7644 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7647 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7704 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7707 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7714 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7717 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7758 (homebridge-conf) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7922 (sudo) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 7928 (journalctl) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 8048 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 8066 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 8114 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: homebridge.service: Found left-over process 8117 (coap-client) in control group while starting unit. Ignoring.
Jan 13 14:56:12 lemurianPi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 13 14:56:12 lemurianPi systemd[1]: Started Homebridge.
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] Loaded config.json with 0 accessories and 4 platforms.
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] ---
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] Plugin /usr/lib/node_modules/homebridge-ikea-tradfri-gateway does not contain a package.json.
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] Loaded plugin: homebridge-config-ui-x
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] Registering platform 'homebridge-config-ui-x.config'
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] ---
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] Loaded plugin: homebridge-http-webhooks
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] Registering platform 'homebridge-http-webhooks.HttpWebHooks'
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] Registering accessory 'homebridge-http-webhooks.HttpWebHookSensor'
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] Registering accessory 'homebridge-http-webhooks.HttpWebHookSwitch'
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] Registering accessory 'homebridge-http-webhooks.HttpWebHookPushButton'
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] Registering accessory 'homebridge-http-webhooks.HttpWebHookLight'
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] Registering accessory 'homebridge-http-webhooks.HttpWebHookThermostat'
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] Registering accessory 'homebridge-http-webhooks.HttpWebHookOutlet'
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] Registering accessory 'homebridge-http-webhooks.HttpWebHookSecurity'
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] Registering accessory 'homebridge-http-webhooks.HttpWebHookGarageDoorOpener'
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] Registering accessory 'homebridge-http-webhooks.HttpWebHookStatelessSwitch'
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] Registering accessory 'homebridge-http-webhooks.HttpWebHookLockMechanism'
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] Registering accessory 'homebridge-http-webhooks.HttpWebHookWindowCovering'
Jan 13 14:56:14 lemurianPi homebridge[8118]: [1/13/2020, 2:56:14 PM] ---
Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] Loaded plugin: homebridge-samsung-tizen
Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] ---
Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] Loaded plugin: homebridge-tradfri-plugin
Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] Registering platform 'homebridge-tradfri.IkeaTradfri'
Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] ---
Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] Loading 4 platforms...
Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] [Config] Initializing config platform...
Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] [Config] Spawning homebridge-config-ui-x with PID 8141
Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] [SamsungTizen] Initializing SamsungTizen platform...
Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] [Tradfri] Initializing IkeaTradfri platform...
**Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] [HttpWebHooks] Initializing HttpWebHooks platform...
Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] Error: EACCES: permission denied, mkdir '/.node-persist'
Jan 13 14:56:15 lemurianPi homebridge[8118]:     at Object.mkdirSync (fs.js:823:3)
Jan 13 14:56:15 lemurianPi homebridge[8118]:     at sync (/usr/lib/node_modules/homebridge-http-webhooks/node_modules/mkdirp/index.js:71:13)
Jan 13 14:56:15 lemurianPi homebridge[8118]:     at Function.sync (/usr/lib/node_modules/homebridge-http-webhooks/node_modules/mkdirp/index.js:77:24)
Jan 13 14:56:15 lemurianPi homebridge[8118]:     at LocalStorage.parseStorageDirSync (/usr/lib/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/local-storage.js:600:20)
Jan 13 14:56:15 lemurianPi homebridge[8118]:     at LocalStorage.initSync (/usr/lib/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/local-storage.js:141:14)
Jan 13 14:56:15 lemurianPi homebridge[8118]:     at Object.nodePersist.initSync (/usr/lib/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/node-persist.js:37:32)
Jan 13 14:56:15 lemurianPi homebridge[8118]:     at new HttpWebHooksPlatform (/usr/lib/node_modules/homebridge-http-webhooks/index.js:48:16)
Jan 13 14:56:15 lemurianPi homebridge[8118]:     at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:337:32)
Jan 13 14:56:15 lemurianPi homebridge[8118]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
Jan 13 14:56:15 lemurianPi homebridge[8118]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] Got SIGTERM, shutting down Homebridge...**
Jan 13 14:56:15 lemurianPi homebridge[8118]: { '9029': '1.9.0027', '9091': 'iDp6ScfqFIKsuUdw' }
Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] [Tradfri] Initializing platform accessory 'bucătărie 2 - 65544'...
Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] [Tradfri] Initializing platform accessory 'bucătarie 1 - 65545'...
Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] [Tradfri] Initializing platform accessory 'dormitor 1 - 65541'...
Jan 13 14:56:15 lemurianPi homebridge[8118]: [1/13/2020, 2:56:15 PM] [Tradfri] Initializing platform accessory 'dormitor 2 - 65540'...
Jan 13 14:56:20 lemurianPi homebridge[8118]: [1/13/2020, 2:56:20 PM] [Config] Homebridge Config UI X v4.7.0 is listening on :: port 8080
Jan 13 14:56:20 lemurianPi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Jan 13 14:56:20 lemurianPi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Jan 13 14:56:23 lemurianPi systemd[1]: homebridge.service: Service RestartSec=3s expired, scheduling restart.
Jan 13 14:56:23 lemurianPi systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 1.
Jan 13 14:56:23 lemurianPi systemd[1]: Stopped Homebridge.

```
Any ideas?

**Comment by Supereg** [comment]
stale bot seemed to be bugged, closing stale issue
