### ISSUE TITLE
Issue starting homebridge

### ISSUE THREAD

**Issue by leesoyavh** [homebridge/homebridge#2412]
### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by leesoyavh** [comment]
I have this problem with Tuya, on startup it always shows red errors. the time seems to be incorrect too

HAVE I GOT 3 HOME BRIDGES RUNNING?

any advice ?

[2/1/2020, 7:53:57 AM] [Config] [HapClient] [192.168.1.7:51076 (74:80:B9:BA:B9:35)] Disconnected
[2/1/2020, 7:53:57 AM] [Config] [HapClient] [192.168.1.7:51075 (DF:CD:15:22:7B:7A)] Disconnected
[2/1/2020, 7:53:57 AM] [Config] [HapClient] [192.168.1.7:51826 (CC:22:3D:E3:CE:30)] Disconnected
[2/1/2020, 7:54:18 AM] [Config] [HapClient] Discovery :: Ended
[2/1/2020, 7:54:20 AM] [Camera ffmpeg] Snapshot from Default Camera at 480x270
ffmpeg -i http://faster_still_image_grab_url/this_is_optional.jpg -t 1 -s 480x270 -f image2 -
[2/1/2020, 7:54:24 AM] [Camera ffmpeg] Snapshot from TestCam1 at 480x270
ffmpeg -i http://192.168.1.18:80/cgi-bin/api.cgi?cmd=Snap&channel=0&user=admin&password=PRIVATE -t 1 -s 480x270 -f image2 -
[2/1/2020, 10:56:09 AM] [TuyaWebPlatform] Error retrieving devices states Error: getaddrinfo ENOTFOUND px1.tuyaeu.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'px1.tuyaeu.com'
}
[2/1/2020, 3:10:25 PM] [TuyaWebPlatform] Error retrieving devices states Error: getaddrinfo ENOTFOUND px1.tuyaeu.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'px1.tuyaeu.com'
}
[2/1/2020, 3:10:35 PM] [TuyaWebPlatform] Error retrieving devices states Error: getaddrinfo ENOTFOUND px1.tuyaeu.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'px1.tuyaeu.com'
}
[2/1/2020, 4:07:58 PM] [TuyaWebPlatform] Error retrieving devices states Error: getaddrinfo ENOTFOUND px1.tuyaeu.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'px1.tuyaeu.com'
}
[2/2/2020, 8:47:12 AM] [TuyaWebPlatform] Error retrieving devices states Error: getaddrinfo ENOTFOUND px1.tuyaeu.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'px1.tuyaeu.com'
}
[2/2/2020, 8:47:12 AM] [TuyaWebPlatform] Error retrieving devices states Error: getaddrinfo ENOTFOUND px1.tuyaeu.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'px1.tuyaeu.com'
}
[2/2/2020, 8:47:12 AM] [TuyaWebPlatform] Error retrieving devices states Error: getaddrinfo ENOTFOUND px1.tuyaeu.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'px1.tuyaeu.com'
}
[2/2/2020, 8:50:49 AM] [Config] [HapClient] [192.168.1.7:51076 (74:80:B9:BA:B9:35)] Connected
[2/2/2020, 8:50:49 AM] [Config] [HapClient] [192.168.1.7:51075 (DF:CD:15:22:7B:7A)] Connected
[2/2/2020, 8:50:49 AM] [Config] [HapClient] [192.168.1.7:51826 (CC:22:3D:E3:CE:30)] Connected
[2/2/2020, 8:50:49 AM] [Config] [HapClient] Discovery :: Started
[2/2/2020, 8:50:50 AM] [Config] [HapClient] Discovery :: Found HAP device with username DF:CD:15:22:7B:7A
[2/2/2020, 8:50:50 AM] [Config] [HapClient] Discovery :: Found HAP device with username 74:80:B9:BA:B9:35
[2/2/2020, 8:50:50 AM] [Config] [HapClient] Discovery :: Found HAP device with username CC:22:3D:E3:CE:30
[2/2/2020, 8:51:49 AM] [Config] [HapClient] Discovery :: Ended

**Comment by brandrik** [comment]
Same problem here: 
05/02/2022, 11:56:44Tuya Web Bridge stopping
05/02/2022, 11:57:20hub is running on port 81
05/02/2022, 11:57:21Tuya Web Bridge starting
05/02/2022, 11:57:24Tuya Web BridgeLoaded plugin '@milo526/homebridge-tuya-web'
05/02/2022, 11:57:24Tuya Web BridgeLoading 1 platforms...
05/02/2022, 11:57:25Tuya Web BridgeBridge is running on port 51836.
05/02/2022, 11:57:34Tuya Web BridgeTuyaWebPlatformERRORgetaddrinfo EAI_AGAIN px1.tuyaeu.com
22/02/2022, 06:16:36WARNINGunhandled rejection: Error: getaddrinfo EAI_AGAIN dl.hoobs.org
22/02/2022, 06:16:42WARNINGplugin site unavailable
22/02/2022, 06:18:39WARNINGplugin site unavailable
22/02/2022, 06:18:44tuyawebbridge stopping
22/02/2022, 06:18:49Tuya Web Bridge starting
22/02/2022, 06:18:52Tuya Web BridgeLoaded plugin '@milo526/homebridge-tuya-web'
22/02/2022, 06:18:52Tuya Web BridgeLoading 1 platforms...
22/02/2022, 06:18:52Tuya Web BridgeBridge is running on port 51836.
22/02/2022, 06:19:02Tuya Web BridgeTuyaWebPlatformERRORgetaddrinfo EAI_AGAIN px1.tuyaeu.com
