### ISSUE TITLE
Newbie Problem starting homebridge on mac

### ISSUE THREAD

**Issue by LeonC169** [homebridge/homebridge#2414]
Dears,

I am a newbie with hombreidge. This are mis first steps.
I install homebridge and when I tried to start this error appear:

MacBook-Pro-de-Luciano:~ lucianoperez$ homebridge
[2/8/2020, 8:02:47 PM] Loaded config.json with 0 accessories and 2 platforms.
[2/8/2020, 8:02:47 PM] ---
[2/8/2020, 8:02:47 PM] No plugins found. See the README for information on installing plugins.
[2/8/2020, 8:02:47 PM] Loading 2 platforms...
[2/8/2020, 8:02:47 PM] Error: The requested platform 'config' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[2/8/2020, 8:02:47 PM] Got SIGTERM, shutting down Homebridge...

Some idea to help?

Thanks!

**Comment by identd113** [comment]
You have config ui x specified in the config.json but that plugin is not installed

**Comment by LeonC169** [comment]
Okey, that now is correct. but this error now appear:

Error: listen EADDRINUSE: address already in use :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:616:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:132:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:101:10)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)

**Comment by LeonC169** [comment]
This is my config.json:

{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:EB:83:F1:63:C8",
        "port": 51826,
        "pin": "517-30-669"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "ports": {
        "start": 52100,
        "end": 52150,
        "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8081,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "es",
            "log": {
                "method": "file",
                "path": "/var/log/homebridge.log"
            },
            "platform": "config"
        }
    ]
}

**Comment by ayanm00** [comment]
Try changing the port from 51826 to something else. The first line of the error says something about address 51826 already being in use. Hope that helps!

**Comment by AppleTechy** [comment]
@LeonC169 Were you able to solve your issue? As stated above EADDRINUSE is generated when something is already using the port homebridge is trying to use. If you don't know what is causing that error, I would suggest you start the machine. If you didn't solve your issue, did you attempt to setup auto start of Homebridge that sometimes can be the culprit. It auto starting in the background and then you try to start it from terminal. Otherwise I would try switching the port as suggested above.
