### ISSUE TITLE
No reaction from all devices due to 1 device being offline

### ISSUE THREAD

**Issue by JHurk** [homebridge/homebridge#2424]
### Pre Steps
I have Homebridge running in Docker, it works like a charm.
I have 3 plugins running:
- Homebridge Config UI X
- Homebridge EDomoticz
- Homebridge Nefit Easy

I noticed that my devices become unresponsive at random times.
When I look at the log it seems as though Homebridge is stuck in getting temperature from the Nefit plugin. Resulting in all devices giving a 'No reaction'.

### Expected Behavior
I thought when the Nefit servers (external from the manufacturer) would be offline, the rest of my devices would work as normal.

### Current Behavior
All devices become unresponsive from the Homekit app (in Homebridge UI it still works).

### Steps to Reproduce (for bugs)
Have a Nefit Easy and the Nefit servers become unresponsive.
The log seems to imply that it is stuck in getting the temperature.

### Versions

- **Homebridge**: `0.4.50`
- **Node**:       `10.14.1`
- **OS**:         Synology DSM 6 latest in Docker container (latest) -  Alpine Linux (3.11.2)
-**NPM**:  6.13.4

### Configuration

    "bridge": {
        "name": "Homebridge",
        "username": "_USERNAME_",
        "port": _PORT_,
        "pin": "_PIN_"
    },
    "accessories": [
        {
            "accessory": "NefitEasy",
            "name": "thermostaat",
            "options": {
                "serialNumber": "_SERIALNUMBER_",
                "accessKey": "_ACCESSKEY_",
                "password": "_PASSWORD_"
            }
        }
    ],
    "platforms": [
        {
            "name": "eDomoticz",
            "server": "192.168.1.7",
            "port": "8084",
            "roomid": 0,
            "mqtt": true,
            "ssl": false,
            "dimFix": 0,
            "excludedDevices": [
                "1",
                "8",
                "11",
                "12",
                "16",
                "21",
                "25",
                "27",
                "52",
                "57",
                "58",
                "73",
                "68",
                "70",
                "65"
            ],
            "platform": "eDomoticz"
        }
    ]
}

### Homebridge Log / Command Output
[2/19/2020, 6:28:06 PM] [thermostaat] Getting current temperature...
[2/19/2020, 6:28:06 PM] [thermostaat] Getting target temperature...
[2/19/2020, 6:28:06 PM] [thermostaat] Getting current state..
Error: MAX_RETRIES_REACHED
    at /homebridge/node_modules/homebridge-nefit-easy/node_modules/nefit-easy-core/lib/index.js:179:51
    at tryCatcher (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
Error: MAX_RETRIES_REACHED
    at /homebridge/node_modules/homebridge-nefit-easy/node_modules/nefit-easy-core/lib/index.js:179:51
    at tryCatcher (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
Error: MAX_RETRIES_REACHED
    at /homebridge/node_modules/homebridge-nefit-easy/node_modules/nefit-easy-core/lib/index.js:179:51
    at tryCatcher (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/homebridge/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)

**Comment by JHurk** [comment]
And as soon as the Nefit external server I up again, everything starts working and all device become responsive again.

**Comment by muzzymate** [comment]
I utilize some plugins that cause similar behavior. They can take a few extra seconds to pull their data which cause other devices to hang and report No Response.

As a result, I ended up running a separate Hombridge instance for each individual plugin (19 in total). I've found that eliminates the above issue when a plugin takes too long to respond. It also seems to help improve the overall experience making navigating the Home app speedier. While moving between rooms, Home app only seems to pull what it needs to show you the room data.  19 instances is probably overkill, I could realistically probably get it down to 5 or 6. But I run Homebridge on my Plex Windows machine with plenty of spare RAM and CPU cycles.

**Comment by lukasa1993** [comment]
will this be fixed?

**Comment by donavanbecker** [comment]
@lukasa1993 recommendation would be to setup multiple instances

**Comment by lukasa1993** [comment]
any quick way of doing it? without lossing config? and not reuquiring tos can qrcode for each one

**Comment by donavanbecker** [comment]
What is your setup?

**Comment by lukasa1993** [comment]
rpi 4 with npm i -g

**Comment by donavanbecker** [comment]
[Config-UI-X Wiki](https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-&-Systemd-(Raspbian,-Ubuntu,-Debian))
