### ISSUE TITLE
TypeError: platformInstance.accessories is not a function Error presenting

### ISSUE THREAD

**Issue by kavacon1** [homebridge/homebridge#2465]
**Describe Your Problem:**
Hi Guys,
I recently decided to write my first plugin as a little project but have ran into an issue with the quoted error everytime I attempt to start up homebridge with my platform. I have ran it with other plugins and the error doesn't occur so I'm sure that its my code but I can't pinpoint what's causing it. I believe its happening during or just after the platform constructor is called, logs below as well as a redacted config and code sample, TIA :)

**Logs:**

```
[3/29/2020, 12:37:12 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[3/29/2020, 12:37:12 PM] [HB Supervisor] Starting Homebridge with custom env: {"DEBUG":"*"}
[3/29/2020, 12:37:12 PM] [HB Supervisor] Started Homebridge with PID: 13798
[3/29/2020, 12:37:12 PM] Loaded config.json with 0 accessories and 3 platforms.
[3/29/2020, 12:37:12 PM] ---
[3/29/2020, 12:37:12 PM] Loaded plugin: homebridge-config-ui-x
[3/29/2020, 12:37:12 PM] Registering platform 'homebridge-config-ui-x.config'
[3/29/2020, 12:37:12 PM] ---
[3/29/2020, 12:37:12 PM] Loaded plugin: homebridge-ewelink-with-api
[3/29/2020, 12:37:12 PM] Registering platform 'homebridge-ewelink-with-api.EweLink'
[3/29/2020, 12:37:12 PM] ---

....
....

[3/29/2020, 12:36:51 PM] TypeError: platformInstance.accessories is not a function
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:403:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:341:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
[3/29/2020, 12:36:51 PM] Got SIGTERM, shutting
```

**Homebridge Config:**

```json
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Belkin Wemo",
            "platform": "BelkinWeMo"
        },
        {
            "name": "EweLink",
            "platform": "EweLink",
            "email": "email@email",
            "password": "password",
            "region": "cn"
        }
    ]
```

**Code Snippet:**
```
function EweLink(log, config, api) {
    (async () => {
        log("Ewelink bridge starting up");

        //configure for external access
        const platform = this;
        const connection = new ewelink({
            email: config["email"],
            password: config["password"],
            region: config["region"],
        });
        this.auth = await connection.getCredentials();
        this.log = log;
        this.config = config;
        this.api = api;
        this.accessories = new Map();
        this.api.on("didFinishLaunching", apiDidFinishLaunching.bind(platform))
    })();
}
```
**Environment:**

* **Node.js Version**: 12.16.1
* **NPM Version**: 6.14.4
* **Homebridge Version**: 0.4.53
* **Operating System**: Raspbian  and macOS
* **Process Supervisor**: hb-service

**Comment by kavacon1** [comment]
I tried removing the empty accessories from the config, that allowed the startup to get further but the same error eventually presented

**Comment by kavacon1** [comment]
Hi guys, solved it finally haha the issue was that I hadn't defined a configureAccessory function from my platform which was causing the server to think it's accessories were already defined, defined this function and now homebridge starts up
