### ISSUE TITLE
error service name is already in use on the network

### ISSUE THREAD

**Issue by flejta** [homebridge/homebridge#2467]
Hi,
i have Raspberry Pi 4 B and clean installation of Raspbian Buster Lite + latest Homebridge.
This works OK.
After install of Domoticz i get error in Homebridge:
"error service name is already in use on the network"

What i can do?
<img width="682" alt="1" src="https://user-images.githubusercontent.com/62942043/78026621-3e710080-735c-11ea-82ca-d6901891ac64.png">

**Comment by ceraz68** [comment]
I also have this "Error: Service name is already in use on the network" and spent days looking for the root cause and still can't find it and don't which code triggers it. 

For example if the service name could be output to console at the same time it would be really help to fix the issue :-)

Below is my error (I'm running Homebridge in a docker on Synology and managing via config-ui-x). I get at HB reboot max 5 times before HB launches. I tried debug mode, disabling Bonjour on the synology etc.

Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:223:5)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:223:5)
    at UDP.onMessage [as onmessage] (dgram.js:874:8)

**Comment by Riekusvdwest** [comment]
@ceraz68 Did you Resolve this? I have the same isseu

**Comment by ceraz68** [comment]
Yes but don't know how:

(1) I made sure all my home-made plugins were generating unique short mqtt client ids and deleted all the cached information (I now console log mqtt connection establishment on plugin startup to detect anything suspicious)
(2) Changed the homebridge id /pin in the config.json file
(3) Upgraded homebridge to the latest version

I suspect a combination of (1) and (3) resolved my issue as the HB change log mentions 'service name' related changes on many occasions.
