### ISSUE TITLE
TypeError: Cannot read property 'UUID' of undefined

### ISSUE THREAD

**Issue by VaderMester** [homebridge/homebridge#2477]
TypeError Issue when registering a plugin. I am not sure if it is plugin related, but based on the log I get, it isn't.

- There are no other accessories with the same name
- Already tried deleting the .Homebridge/.AccessoryCache and .Persist folder contents.
Any other ideas?

Is there any method, file etc, I can check the generated UUID?

Board: RPi 3B,
OS: Raspbian Buster latest

Homebridge version:
├─┬ homebridge@0.4.53
│ ├── chalk@1.1.3
│ ├── commander@2.8.1
│ ├── hap-nodejs@0.4.51
│ ├── node-persist@0.0.8
│ ├── qrcode-terminal@0.11.0
│ └── semver@5.0.3

Node ver: v12.16.1

Log:
```
Registering 'Thermostat' accessory....
TypeError: Cannot read property 'UUID' of undefined
at Accessory.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:149:35)
at /usr/lib/node_modules/homebridge/lib/server.js:471:19
at Array.forEach (<anonymous>)
at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:451:14)
at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:309:26)
at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:1158:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
```

**Comment by VaderMester** [comment]
Solved. Can be removed from issues!

**Comment by davidjbradshaw** [comment]
What was the solution? I have the same issue
