### ISSUE TITLE
Homebridge crash when adding to apple home.

### ISSUE THREAD

**Issue by mikeleijs** [homebridge/homebridge#2490]
All of a sudden homebridge stopped working. So i reinstalled my raspberry as i couldn't fix it anymore inside homebridge, but now i keep getting this when adding my homebridge to apple home. Homebridge starts fine, plugins load perfect, but when adding it through QR and also manually with the pin to apple home it instantly crashes. Please help.

ReferenceError: N is not defined
    at server_getS (/usr/lib/node_modules/homebridge/node_modules/fast-srp-hap/lib/srp.js:259:38)
    at Server.setA (/usr/lib/node_modules/homebridge/node_modules/fast-srp-hap/lib/srp.js:401:17)
    at HAPServer._handlePairStepTwo (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:353:13)
    at HAPServer._handlePair (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:313:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:310:20)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by ImKyleJK** [comment]
Yeah. Same i get that issue. I just accidentally opened an issue with the same as you: 
[4/12/2020, 11:17:39] Homebridge is running on port 51986.
[4/12/2020, 11:17:41] [Config] Homebridge Config UI X v4.14.0 is listening on :: port 8581
[4/12/2020, 11:17:40] [ImKyleJK-Pi] warning: ImKyleJK: 192.168.0.22:8888: cannot connect: ECONNREFUSED
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 16, drift 33624
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 17, drift 32626
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 18, drift 31628
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 19, drift 30630
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 20, drift 29631
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 21, drift 28633
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 22, drift 27634
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 23, drift 26636
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 24, drift 25638
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 25, drift 24639
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 26, drift 23641
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 27, drift 22642
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 28, drift 21644
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 29, drift 20645
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 30, drift 19647
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 31, drift 18653
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 32, drift 17655
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 33, drift 16656
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 34, drift 15658
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 35, drift 14660
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 36, drift 13662
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 37, drift 12664
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 38, drift 11666
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 39, drift 10667
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 40, drift 9669
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 41, drift 8671
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 42, drift 7672
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 43, drift 6674
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 44, drift 5675
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 45, drift 4677
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 46, drift 3679
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 47, drift 2680
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 48, drift 1682
[4/12/2020, 11:18:29] [ImKyleJK-Pi] warning: heartbeat 49, drift 684
[4/12/2020, 11:19:05] ReferenceError: N is not defined
    at server_getS (/usr/lib/node_modules/homebridge/node_modules/fast-srp-hap/lib/srp.js:259:38)
    at Server.setA (/usr/lib/node_modules/homebridge/node_modules/fast-srp-hap/lib/srp.js:401:17)
    at HAPServer._handlePairStepTwo (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:353:13)
    at HAPServer._handlePair (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:313:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:310:20)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[4/12/2020, 11:19:05] Got SIGTERM, shutting down Homebridge...
[4/12/2020, 11:19:10] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[4/12/2020, 11:19:15] [HB Supervisor] Restarting Homebridge...
[4/12/2020, 11:19:15] [HB Supervisor] Starting Homebridge with extra flags: -I
[4/12/2020, 11:19:15] [HB Supervisor] Started Homebridge with PID: 1353
[4/12/2020, 11:19:17] Loaded config.json with 0 accessories and 2 platforms.
[4/12/2020, 11:19:17] ---
[4/12/2020, 11:19:17] Loaded plugin: homebridge-config-ui-x
[4/12/2020, 11:19:17] Registering platform 'homebridge-config-ui-x.config'
[4/12/2020, 11:19:17] ---
[4/12/2020, 11:19:17] Loaded plugin: homebridge-rpi
[4/12/2020, 11:19:17] Registering platform 'homebridge-lib.Lib'
[4/12/2020, 11:19:17] Registering platform 'homebridge-rpi.RPi'
[4/12/2020, 11:19:17] ---
[4/12/2020, 11:19:17] Loading 2 platforms...
[4/12/2020, 11:19:17] [Config] Initializing config platform...
[4/12/2020, 11:19:17] [Config] Running in Service Mode
[4/12/2020, 11:19:17] [ImKyleJK-Pi] Initializing RPi platform...
[4/12/2020, 11:19:17] [ImKyleJK-Pi] homebridge-rpi v1.0.2, node 12.16.2, homebridge v0.4.53, homebridge-lib v4.5.7

**Comment by Fillip38** [comment]
Here the same. I have new install Homebridge (0.4.53) and Homebridge UI. When i was add my iPhone to the bridge whith the QR Code, Homebridge crashed and shutdown / restarted...
`[2020-4-12 12:39:34] ReferenceError: N is not defined
    at server_getS (/usr/lib/node_modules/homebridge/node_modules/fast-srp-hap/lib/srp.js:259:38)
    at Server.setA (/usr/lib/node_modules/homebridge/node_modules/fast-srp-hap/lib/srp.js:401:17)
    at HAPServer._handlePairStepTwo (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:353:13)
    at HAPServer._handlePair (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:313:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:310:20)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2020-4-12 12:39:34] Got SIGTERM, shutting down Homebridge...`

**Comment by jw1986** [comment]
I'm getting the same error too with a fresh install of Node.js (latest version) and a fresh install of homebridge and homebridge-nest only.
```
[4/12/2020, 11:46:53] Homebridge is running on port 51826.
[4/12/2020, 11:47:03] ReferenceError: N is not defined
    at server_getS (/usr/local/lib/node_modules/homebridge/node_modules/fast-srp-hap/lib/srp.js:259:38)
    at Server.setA (/usr/local/lib/node_modules/homebridge/node_modules/fast-srp-hap/lib/srp.js:401:17)
    at HAPServer._handlePairStepTwo (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:353:13)
    at HAPServer._handlePair (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:313:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:310:20)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[4/12/2020, 11:47:03] Got SIGTERM, shutting down Homebridge...
```

**Comment by Roxiun** [comment]
Same:

`ReferenceError: N is not defined
    at server_getS (/usr/lib/node_modules/homebridge/node_modules/fast-srp-hap/lib/srp.js:259:38)
    at Server.setA (/usr/lib/node_modules/homebridge/node_modules/fast-srp-hap/lib/srp.js:401:17)
    at HAPServer._handlePairStepTwo (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:353:13)
    at HAPServer._handlePair (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:313:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:310:20)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21`

**Comment by oznu** [comment]
Can you try reinstall homebidge?

```
sudo npm install -g homebridge@latest
```

If it's still not working after that, please clean npm cache then try again:


```
sudo npm cache clean --force
sudo npm install -g homebridge@latest
```

**Comment by HazzardV** [comment]
Having same issue, On third reinstall on MAC osx, First time user so may be something simple ive overlooked

ReferenceError: N is not defined
    at server_getS (/usr/local/lib/node_modules/homebridge/node_modules/fast-srp-hap/lib/srp.js:259:38)
    at Server.setA (/usr/local/lib/node_modules/homebridge/node_modules/fast-srp-hap/lib/srp.js:401:17)
    at HAPServer._handlePairStepTwo (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:353:13)
    at HAPServer._handlePair (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:313:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:310:20)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by oznu** [comment]
@HazzardV see https://github.com/homebridge/homebridge/issues/2490#issuecomment-612597766

**Comment by jw1986** [comment]
> Can you try reinstall homebidge?
> 
> ```
> sudo npm install -g homebridge@latest
> ```
> 
> If it's still not working after that, please clean npm cache then try again:
> 
> ```
> sudo npm cache clean --force
> sudo npm install -g homebridge@latest
> ```
> 
> There was an issue with a new dependency version being included when it should not have been.

This fixed it with the first command.  Thanks for the quick response. :)

**Comment by HazzardV** [comment]
> Can you try reinstall homebidge?
> 
> ```
> sudo npm install -g homebridge@latest
> ```
> 
> If it's still not working after that, please clean npm cache then try again:
> 
> ```
> sudo npm cache clean --force
> sudo npm install -g homebridge@latest
> ```
> 
> There was an issue with a new dependency version being included when it should not have been.

Awsome @oznu - first time I've managed to progress with this in the last 4 hours - cheers :)

**Comment by joshfarrant** [comment]
Thank you for the very quick resolution @oznu :+1:

**Comment by mikeleijs** [comment]
Thanks @oznu it worked!
