### ISSUE TITLE
xpc-connection error on HomeBridge startup

### ISSUE THREAD

**Issue by 0neGuyDev** [homebridge/homebridge#2514]
**Describe The Bug:**
I am unable to start HomeBridge as I get an error that xpc-connection is not installed, when trying to install it I get errors

**To Reproduce:**
Start HomeBridge 

**Expected behavior:**
HomeBridge starts with no problems

**Logs:**

HomeBridge logs:
```
[4/26/2020, 3:10:33 PM] config.json (/Users/0neguy/.homebridge/config.json) not found.
[4/26/2020, 3:10:34 PM] Loaded plugin: homebridge-bluetooth
Homebridge API version: 2.4
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'xpc-connection'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-bluetooth/node_modules/noble/lib/mac/highsierra.js:7:21)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)

```
Logs when installing xpc-connection:
```
> xpc-connection@0.1.4 install /usr/local/lib/node_modules/xpc-connection
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/XpcConnection.o
../src/XpcConnection.cpp:103:41: warning: 'IntegerValue' is deprecated: Use
      maybe version [-Wdeprecated-declarations]
    xpcObject = xpc_int64_create(value->IntegerValue());
                                        ^
/Users/0neguy/Library/Caches/node-gyp/11.14.0/include/node/v8.h:2570:3: note: 
      'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/0neguy/Library/Caches/node-gyp/11.14.0/include/node/v8config.h:326:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/XpcConnection.cpp:113:40: warning: 'ToObject' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
    Local<Object> valueObject = value->ToObject();
                                       ^
/Users/0neguy/Library/Caches/node-gyp/11.14.0/include/node/v8.h:2549:10: note: 
      'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/0neguy/Library/Caches/node-gyp/11.14.0/include/node/v8config.h:326:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/XpcConnection.cpp:123:40: warning: 'ToObject' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
    Local<Object> valueObject = value->ToObject();
                                       ^
/Users/0neguy/Library/Caches/node-gyp/11.14.0/include/node/v8.h:2549:10: note: 
      'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/0neguy/Library/Caches/node-gyp/11.14.0/include/node/v8config.h:326:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/XpcConnection.cpp:143:89: error: too few arguments to function call,
      expected 2, have 1
  ...propertyValue = object->GetRealNamedProperty(propertyName->ToString());
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~                         ^
/Users/0neguy/Library/Caches/node-gyp/11.14.0/include/node/v8.h:3668:3: note: 
      'GetRealNamedProperty' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(
  ^
/Users/0neguy/Library/Caches/node-gyp/11.14.0/include/node/v8config.h:418:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/XpcConnection.cpp:143:79: warning: 'ToString' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
  ...propertyValue = object->GetRealNamedProperty(propertyName->ToString());
                                                                ^
/Users/0neguy/Library/Caches/node-gyp/11.14.0/include/node/v8.h:2548:10: note: 
      'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/0neguy/Library/Caches/node-gyp/11.14.0/include/node/v8config.h:326:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/XpcConnection.cpp:254:12: warning: 'MakeCallback' is deprecated
      [-Wdeprecated-declarations]
      Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").T...
           ^
../node_modules/nan/nan.h:1047:3: note: 'MakeCallback' has been explicitly
      marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../node_modules/nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/XpcConnection.cpp:263:12: warning: 'MakeCallback' is deprecated
      [-Wdeprecated-declarations]
      Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").T...
           ^
../node_modules/nan/nan.h:1047:3: note: 'MakeCallback' has been explicitly
      marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../node_modules/nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
6 warnings and 1 error generated.
make: *** [Release/obj.target/binding/src/XpcConnection.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/xpc-connection
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xpc-connection@0.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xpc-connection@0.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/0neguy/.npm/_logs/2020-04-26T13_17_17_631Z-debug.log
```

**Homebridge Config:**
I haven't gotten to that point yet...

**Environment:**

* **Node.js Version**: 11.14.0
* **NPM Version**: 6.14.4
* **Homebridge Version**: 0.4.53
* **Operating System**: macOS 10.15.5 Beta

**Comment by NorthernMan54** [comment]
Please read the setup instructions fully

This error is critical

config.json (/Users/0neguy/.homebridge/config.json) not found.

**Comment by 0neGuyDev** [comment]
Oh yeah I forgot to say, I did see that part of the log and tried creating the file, doesn't change anything and I removed it because I was testing something else... Anyway the error still appears, later I just found out that apparently this is because of a plugin named `homebridge-bluetooth`, which uses the `xpc-connection` package, which supposedly is outdated on newer Node versions... After removing the plugin the issue is no longer present...

It just took me a bit of time to think that maybe I should uninstall plugins :p
