### ISSUE TITLE
Upgrade from 0.4.53 to 1.02 - Homebridge crashes

### ISSUE THREAD

**Issue by twynne** [homebridge/homebridge#2533]
After the upgrade, I get the following when starting 1.02:

Error: Cannot find module 'safe-buffer'
Require stack:

/usr/local/lib/node_modules/homebridge/node_modules/dns-packet/index.js
/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js
/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Server.js
/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/index.js
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Advertiser.js
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/AccessoryLoader.js
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/index.js
/usr/local/lib/node_modules/homebridge/lib/index.js
/usr/local/lib/node_modules/homebridge/lib/cli.js
/usr/local/lib/node_modules/homebridge/bin/homebridge
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
at Function.Module._load (internal/modules/cjs/loader.js:859:27)
at Module.require (internal/modules/cjs/loader.js:1036:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object. (/usr/local/lib/node_modules/homebridge/node_modules/dns-packet/index.js:8:16)
at Module._compile (internal/modules/cjs/loader.js:1147:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
at Module.load (internal/modules/cjs/loader.js:996:32)
at Function.Module._load (internal/modules/cjs/loader.js:896:14)
at Module.require (internal/modules/cjs/loader.js:1036:19)
�[37m[4/28/2020, 5:18:35 PM]�[0m �[36m[HB Supervisor]�[0m Homebridge Process Ended. Code: 1, Signal: null

Reverting to 0.4.53 (tried both via manual downgrade and also full restore of backup via config-ui), I now get:

internal/modules/cjs/loader.js:979
throw err;
^

Error: Cannot find module 'array-flatten'
Require stack:

/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js
/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/index.js
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js
/usr/local/lib/node_modules/homebridge/lib/cli.js
/usr/local/lib/node_modules/homebridge/bin/homebridge
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
at Function.Module._load (internal/modules/cjs/loader.js:859:27)
at Module.require (internal/modules/cjs/loader.js:1036:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object. (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:3:15)
at Module._compile (internal/modules/cjs/loader.js:1147:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
at Module.load (internal/modules/cjs/loader.js:996:32)
at Function.Module._load (internal/modules/cjs/loader.js:896:14)
at Module.require (internal/modules/cjs/loader.js:1036:19) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js',
'/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/index.js',
'/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js',
'/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js',
'/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js',
'/usr/local/lib/node_modules/homebridge/lib/cli.js',
'/usr/local/lib/node_modules/homebridge/bin/homebridge'
]
}
[4/28/2020, 5:33:23 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[4/28/2020, 5:33:28 PM] [HB Supervisor] Restarting Homebridge...
[4/28/2020, 5:33:28 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -R
[4/28/2020, 5:33:28 PM] [HB Supervisor] Started Homebridge with PID: 97228
internal/modules/cjs/loader.js:979
throw err;
^

Node:  13.12
NPM:  6.14.4

**Comment by twynne** [comment]
Got there with some help... you can ignore this for now.

**Comment by Supereg** [comment]
I though this issue was resolved?

**Comment by twynne** [comment]
> I though this issue was resolved?

As per my note above, yes

**Comment by twynne** [comment]
Unless of course someone wants to figure out why it happened to begin with...

**Comment by Supereg** [comment]
Seems like there was something messed up with npm installing dependencies.
For further notice a reinstall solved the problem using:

```
sudo npm uninstall -g homebridge
sudo npm install -g homebridge
```
