### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by haekkebraeker** [homebridge/homebridge#2559]
**Describe The Bug:**

When I want to switch a Switch with the homebridge-servo-switch plugin, it throws an error.

**To Reproduce:**

Installing the homebridge-servo-switch plugin make a switch and then try to use it

**Logs:**

```
TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type function ([Function])
    at validateString (internal/validators.js:117:11)
    at normalizeSpawnArguments (child_process.js:406:3)
    at spawn (child_process.js:542:16)
    at Object.execFile (child_process.js:232:17)
    at exec (child_process.js:153:25)
    at ServoSwitch.setPowerState (/usr/lib/node_modules/homebridge-servo-switch/index.js:151:3)
    at On.emit (events.js:310:20)
    at On.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at On.Characteristic._this.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:614:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1441:24
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge AFEE",
        "username": "xxxxxxxxx",
        "port": 51156,
        "pin": "xxxxxxxx"
    },
    "accessories": [
        {
            "accessory": "Dht",
            "name": "Sensoren",
            "name_temperature": "Temperatur",
            "name_humidity": "Luftfeuchtigkeit",
            "service": "dht11",
            "gpio": "4"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": true,
            "platform": "config"
        },
        {
            "name": "Alexa",
            "username": "xxxxxxxx",
            "password": "xxxxxxx",
            "pin": "xxxxxxxxxxx",
            "platform": "Alexa"
        },
        {
            "platform": "ServoSwitch",
            "name": "Switches",
            "switches": [
                {
                    "name": "big light",
                    "gpioPin": 21,
                    "onPulse": 5.7,
                    "offPulse": 8.3
                },
                {
                    "name": "small light",
                    "gpioPin": 13,
                    "onPulse": 5.7,
                    "offPulse": 8.3
                }
            ]
        }
    ]
}
```

**Environment:**

* **Node.js Version**: v12.16.3 
* **NPM Version**: v6.14.5 
* **Homebridge Version**: 1.0.4 
* **Operating System**: Raspbian GNU/Linux Buster (10) 
* **Process Supervisor**: Systemd

**Comment by Supereg** [comment]
This is not an issue caused by homebridge in any way. Your plugin `homebridhe-servo-switch` doesn't user nodes `child_process` [exec](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) function as it should be used. A function is supplied instead of string: https://github.com/allistoncarlos/homebridge-servo-switch/blob/e5eaa4a6dfe324e94edd19103af8ed99a8a802f3/index.js#L151-L160

**Comment by haekkebraeker** [comment]
And how do I solve the issue? I don't have any experience with node.js...
