### ISSUE TITLE
Homebridge won't start when required as a peerDependency

### ISSUE THREAD

**Issue by mgcrea** [homebridge/homebridge#2569]
**Describe The Bug:**

I've recently updated my plugin to depend explicitly on homebridge@>=1.0.0 that enables me to drop the hacky node-hapjs dep. However it won't start this way:

https://github.com/mgcrea/homebridge-tydom/blob/v0.18.1/package.json 

Any ideas? Adding an explicit dependency might fix it but shouldn't be required, no?

[**Logs:**]()

```
homebridge    | [5/10/2020, 10:51:25 AM] ====================
homebridge    | [5/10/2020, 10:51:25 AM] ERROR LOADING PLUGIN homebridge-tydom:
homebridge    | [5/10/2020, 10:51:26 AM] Error: Cannot find module 'homebridge'
homebridge    | Require stack:
homebridge    | - /homebridge/node_modules/homebridge-tydom/lib/platform.js
homebridge    | - /homebridge/node_modules/homebridge-tydom/lib/index.js
homebridge    | - /usr/local/lib/node_modules/homebridge/lib/plugin.js
homebridge    | - /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
homebridge    | - /usr/local/lib/node_modules/homebridge/lib/api.js
homebridge    | - /usr/local/lib/node_modules/homebridge/lib/index.js
homebridge    | - /usr/local/lib/node_modules/homebridge/lib/cli.js
homebridge    | - /usr/local/lib/node_modules/homebridge/bin/homebridge
homebridge    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
homebridge    |     at Function.Module._load (internal/modules/cjs/loader.js:840:27)
homebridge    |     at Module.require (internal/modules/cjs/loader.js:1019:19)
homebridge    |     at require (internal/modules/cjs/helpers.js:77:18)
homebridge    |     at Object.<anonymous> (/homebridge/node_modules/homebridge-tydom/src/platform.ts:1:1)
homebridge    |     at Module._compile (internal/modules/cjs/loader.js:1133:30)
homebridge    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
homebridge    |     at Module.load (internal/modules/cjs/loader.js:977:32)
homebridge    |     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
homebridge    |     at Module.require (internal/modules/cjs/loader.js:1019:19)
homebridge    | [5/10/2020, 10:51:26 AM] ====================

```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

Using an up-to-date docker oznu/homebridge:latest image

```
homebridge    | [5/10/2020, 10:51:19 AM] [HB Supervisor] Homebridge Storage Path: /homebridge
homebridge    | [5/10/2020, 10:51:19 AM] [HB Supervisor] Homebridge Config Path: /homebridge/config.json
homebridge    | [5/10/2020, 10:51:19 AM] [HB Supervisor] Logging to /homebridge/homebridge.log
homebridge    | [5/10/2020, 10:51:20 AM] [HB Supervisor] OS: Linux 5.3.0-51-generic x64
homebridge    | [5/10/2020, 10:51:20 AM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
homebridge    | [5/10/2020, 10:51:20 AM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
homebridge    | [5/10/2020, 10:51:20 AM] [HB Supervisor] Starting Homebridge with extra flags: -P /homebridge/node_modules
homebridge    | [5/10/2020, 10:51:22 AM] [HB Supervisor] Started Homebridge v1.0.4 with PID: 356
```

**Comment by mgcrea** [comment]
Answered there: https://github.com/oznu/docker-homebridge/issues/303
