### ISSUE TITLE
Homebridge crashing after recent updates

### ISSUE THREAD

**Issue by Olepir** [homebridge/homebridge#2592]
Homebridge crashing after recent updates
Main issue is with this plugin
https://github.com/bstuff/haier-ac-remote
I don’t know if it’s plugin or Homebridge issue, but before recent updates all worked

```
[5/26/2020, 1:40:25 PM] [Living Room AC] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
at doWrite (_stream_writable.js:411:19)
at writeOrBuffer (_stream_writable.js:399:5)
at Socket.Writable.write (_stream_writable.js:299:11)
at send (/usr/local/lib/node_modules/homebridge-haier-ac/node_modules/haier-ac-remote/dist/HaierAC.js:37:8)
at HaierAC._sendRequest (/usr/local/lib/node_modules/homebridge-haier-ac/node_modules/haier-ac-remote/dist/HaierAC.js:141:9)
at HaierAC.on (/usr/local/lib/node_modules/homebridge-haier-ac/node_modules/haier-ac-remote/dist/HaierAC.js:112:21)
at HaierAC. (/usr/local/lib/node_modules/homebridge-haier-ac/node_modules/haier-ac-remote/dist/HaierAC.js:120:28)
at Generator.next ()
at /usr/local/lib/node_modules/homebridge-haier-ac/node_modules/haier-ac-remote/dist/HaierAC.js:8:71
at new Promise ()
at __awaiter (/usr/local/lib/node_modules/homebridge-haier-ac/node_modules/haier-ac-remote/dist/HaierAC.js:4:12)
at HaierAC.changeState (/usr/local/lib/node_modules/homebridge-haier-ac/node_modules/haier-ac-remote/dist/HaierAC.js:118:16)
at HapHaierAC. (/usr/local/lib/node_modules/homebridge-haier-ac/dist/haier.js:60:48)
at Generator.next ()
at /usr/local/lib/node_modules/homebridge-haier-ac/dist/haier.js:8:71
at new Promise ()
```
* **Node.js Version**: 12.16.3
* **NPM Version**: 6.14.4
* **Homebridge Version**: 1.1.0
* **Operating System**: Raspbian / Windows / Docker
* **Process Supervisor**: hb-service

**Comment by NorthernMan54** [comment]
Looking at the log you shared the error is coming from the plugin.  Can you close this, and raise it against the plugin.
