### ISSUE TITLE
homebridge with the plugin homebridge-blynk can't start on new version (>= 1.0)

### ISSUE THREAD

**Issue by pfox7** [homebridge/homebridge#2596]
**Describe The Bug:**
doesn't start after update

**To Reproduce:**
install homebridge from the version one and later

**Expected behavior:**
start

[**Logs:**]()
[2020-6-7 0:56:14] TypeError: Cannot read property 'getCharacteristic' of undefined
    at /usr/local/lib/node_modules/homebridge/src/server.ts:511:32
    at Array.map (<anonymous>)
    at Server.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:505:40)
    at HomebridgeAPI.emit (events.js:310:20)
    at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:316:10)
    at BlynkAccessory.registerUpdateAccessory (/usr/local/lib/node_modules/homebridge-blynk/dist/blynkaccessory.js:82:8)
    at Blynk.addAccessory (/usr/local/lib/node_modules/homebridge-blynk/src/index.ts:178:3)
    at /usr/local/lib/node_modules/homebridge-blynk/dist/index.js:101:9
    at Array.map (<anonymous>)
    at Blynk.LoadAccessories (/usr/local/lib/node_modules/homebridge-blynk/src/index.ts:141:3)

```
[2020-6-7 0:56:25] TypeError: Cannot read property 'getCharacteristic' of undefined
    at Accessory._this._sideloadServices (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1045:17)
    at Function.Accessory.deserialize (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1716:15)
    at Function.deserialize (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:150:33)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:262:34
    at Array.map (<anonymous>)
    at Server.loadCachedPlatformAccessoriesFromDisk (/usr/local/lib/node_modules/homebridge/src/server.ts:261:58)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:148:10)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v12.16.3
* **NPM Version**: 6.14.5
* **Homebridge Version**: 1.1.0
* **Operating System**: Ubuntu
* **Process Supervisor**: hb-service

**Comment by mpw-eng** [comment]
Issue still exists - see link to homebridge-blynk issue;
[https://github.com/ilcato/homebridge-blynk/issues/30#issuecomment-729622533](url)
