### ISSUE TITLE
homebridge-beta: unhandled exception thrown by Ciao

### ISSUE THREAD

**Issue by adriancable** [homebridge/homebridge#2606]
Testing homebridge-beta. Ciao throws an unhandled exception if you run avahi-browse -at on the same device that is running homebridge.

[2296]: [6/13/2020, 11:00:47 AM] Error: Truncated messages are currently unsupported
[2296]:     at Responder.handleQuery (/root/node_modules/homebridge/node_modules/@homebridge/ciao/lib/Responder.js:232:19)
[2296]:     at MDNSServer.handleMessage (/root/node_modules/homebridge/node_modules/@homebridge/ciao/lib/MDNSServer.js:243:26)
[2296]:     at Socket.emit (events.js:315:20)
[2296]:     at UDP.onMessage (dgram.js:908:8)
[2296]: [6/13/2020, 11:00:47 AM] Got SIGTERM, shutting down Homebridge...

-Adrian

**Comment by oznu** [comment]
@Supereg

**Comment by Supereg** [comment]
I‘m aware of this, working to implement support for this. Thanks for reporting
