### ISSUE TITLE
Upgraded to v1.1.1 - now cannot start (Error: ELOOP: too many symbolic links encountered, stat '/usr/lib/node_modules/npm')

### ISSUE THREAD

**Issue by rjblake** [homebridge/homebridge#2617]
**Describe The Bug:**
Was running fine on v0.4.5 and upgraded to v1.1.1

**To Reproduce:**
Now, when running homebridge from command line or PM2, I get the following:

```
[7/1/2020, 4:23:12 PM] Error: ELOOP: too many symbolic links encountered, stat '/usr/lib/node_modules/npm'
    at Object.statSync (fs.js:874:3)
    at fs_1.default.readdirSync.filter.relativePath (/usr/lib/node_modules/homebridge/src/pluginManager.ts:291:38)
    at Array.filter (<anonymous>)
    at searchPaths.forEach.searchPath (/usr/lib/node_modules/homebridge/src/pluginManager.ts:291:12)
    at Set.forEach (<anonymous>)
    at PluginManager.loadInstalledPlugins (/usr/lib/node_modules/homebridge/src/pluginManager.ts:277:22)
    at PluginManager.initializeInstalledPlugins (/usr/lib/node_modules/homebridge/src/pluginManager.ts:116:10)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:150:24)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
```

**Expected behavior:**

[**Logs:**]()
```
[7/1/2020, 4:45:34 PM] Error: ELOOP: too many symbolic links encountered, stat '/usr/lib/node_modules/npm'
    at Object.statSync (fs.js:874:3)
    at fs_1.default.readdirSync.filter.relativePath (/usr/lib/node_modules/homebridge/src/pluginManager.ts:291:38)
    at Array.filter (<anonymous>)
    at searchPaths.forEach.searchPath (/usr/lib/node_modules/homebridge/src/pluginManager.ts:291:12)
    at Set.forEach (<anonymous>)
    at PluginManager.loadInstalledPlugins (/usr/lib/node_modules/homebridge/src/pluginManager.ts:277:22)
    at PluginManager.initializeInstalledPlugins (/usr/lib/node_modules/homebridge/src/pluginManager.ts:116:10)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:150:24)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
```

**Environment:**

* **Node.js Version**:  11.3.0
* **NPM Version**:  6.4.1
* **Homebridge Version**:  v1.1.1
* **Operating System**: Raspbian 
* **Process Supervisor**: command line (or pm2)

**Comment by rjblake** [comment]
Seems there was a Symlink created (npm->npm) that shouldn't have been there. Deleted and seems to be working

**Comment by briandeitch-sase** [comment]
I have no idea how to remove the symlinks. I have a similar issue. Please advise.

```
2/11/2021, 11:01:15 AM] ---
/bin/sh: 1: npm: not found
[2/11/2021, 11:01:15 AM] Error: ELOOP: too many symbolic links encountered, stat '/usr/lib/node_modules/npm'
    at Object.statSync (fs.js:1016:3)
    at /usr/lib/node_modules/homebridge/src/pluginManager.ts:291:38
    at Array.filter (<anonymous>)
    at /usr/lib/node_modules/homebridge/src/pluginManager.ts:291:12
    at Set.forEach (<anonymous>)
    at PluginManager.loadInstalledPlugins (/usr/lib/node_modules/homebridge/src/pluginManager.ts:277:22)
    at PluginManager.initializeInstalledPlugins (/usr/lib/node_modules/homebridge/src/pluginManager.ts:116:10)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:150:24)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
```

**Comment by oznu** [comment]
@briandeitch-sase see https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux
