### ISSUE TITLE
homebridge startup error

### ISSUE THREAD

**Issue by denz1968** [homebridge/homebridge#2631]
**Describe Your Problem:**

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by denz1968** [comment]
[7/16/2020, 21:55:17] Error: listen EADDRINUSE: address already in use :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at EventedHTTPServer._this.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:85:21)
    at HAPServer._this.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:236:22)
    at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:974:18)
    at Server.publishBridge (/usr/local/lib/node_modules/homebridge/src/server.ts:192:17)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:164:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:163:5)
[7/16/2020, 21:55:17] Got SIGTERM, shutting down Homebridge...
[7/16/2020, 21:55:20] [Config] Homebridge Config UI X v4.23.2 is listening on :: port 8581
[7/16/2020, 21:55:21] [Config] Error: listen EADDRINUSE: address already in use :::8581
[7/16/2020, 21:55:21] [Config] Another process or service on this host is using port 8581.
[7/16/2020, 21:55:21] [Config] Please stop the other service or change the port you have assigned to homebridge-config-ui-x.
[7/16/2020, 21:55:21] [Config] Ending process now.

**Comment by oznu** [comment]
You have another instance of Homebridge running already. You will need to figure out where that is and stop it.
