### ISSUE TITLE
SIGTERM Error. Constant restarts on Raspberry Pi. 

### ISSUE THREAD

**Issue by felibrown2** [homebridge/homebridge#2657]
My Homebridge is constantly restarting and showing this error message:

Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:315:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:910:8)
[8/15/2020, 19:42:28] Got SIGTERM, shutting down Homebridge...
[8/15/2020, 19:42:28] Got SIGTERM, shutting down Homebridge...
[8/15/2020, 19:42:41] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[8/15/2020, 19:42:46] [HB Supervisor] Restarting Homebridge...
[8/15/2020, 19:42:46] [HB Supervisor] Starting Homebridge with extra flags: -I
[8/15/2020, 19:42:46] [HB Supervisor] Started Homebridge v1.1.2 with PID: 1072
[8/15/2020, 19:42:46] [HB Supervisor] Started Homebridge v1.1.2 with PID: 1072

**Comment by Supereg** [comment]
Should be fixed soon. You may want to install the latest homebridge v1.2.0 beta. See #2619 
v1.2.0 is scheduled to be released in the next few days.
