### ISSUE TITLE
Updating to the latest v1.1.4 breaks my homebridge.

### ISSUE THREAD

**Issue by bkarakashev** [homebridge/homebridge#2671]
**Describe The Bug:**

The homebrige won't even start.

**To Reproduce:**

**Expected behavior:**

[**Logs:**]()

```
/usr/local/lib/node_modules/homebridge/node_modules/commander/index.js:685
      throw new Error('call .storeOptionsAsProperties() before adding options');
            ^
Error: call .storeOptionsAsProperties() before adding options
    at Command.storeOptionsAsProperties (/usr/local/lib/node_modules/homebridge/node_modules/commander/index.js:685:13)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:30:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/6206509/92412042-39ea1880-f142-11ea-8e67-299ba0fb06b6.png)

**Environment:**

* **Node.js Version**:  v12.13.0
* **NPM Version**:  6.14.4
* **Homebridge Version**:   v1.1.4
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other:  Raspbian
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none: hb-service

**Comment by adamrzanek** [comment]
i have the same problem

**Comment by stevehoek** [comment]
Same here

[9/7/2020, 2:43:33 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[9/7/2020, 2:43:38 PM] [HB Supervisor] Restarting Homebridge...
[9/7/2020, 2:43:38 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[9/7/2020, 2:43:38 PM] [HB Supervisor] Started Homebridge v1.1.4 with PID: 804

/usr/local/lib/node_modules/homebridge/node_modules/commander/index.js:685
      throw new Error('call .storeOptionsAsProperties() before adding options');
            ^
Error: call .storeOptionsAsProperties() before adding options
    at Command.storeOptionsAsProperties (/usr/local/lib/node_modules/homebridge/node_modules/commander/index.js:685:13)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:30:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
[9/7/2020, 2:43:39 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[9/7/2020, 2:43:44 PM] [HB Supervisor] Restarting Homebridge...
[9/7/2020, 2:43:44 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[9/7/2020, 2:43:44 PM] [HB Supervisor] Started Homebridge v1.1.4 with PID: 812

/usr/local/lib/node_modules/homebridge/node_modules/commander/index.js:685
      throw new Error('call .storeOptionsAsProperties() before adding options');
            ^
Error: call .storeOptionsAsProperties() before adding options
    at Command.storeOptionsAsProperties (/usr/local/lib/node_modules/homebridge/node_modules/commander/index.js:685:13)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:30:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
[9/7/2020, 2:43:44 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[9/7/2020, 2:43:49 PM] [HB Supervisor] Restarting Homebridge...
[9/7/2020, 2:43:49 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[9/7/2020, 2:43:49 PM] [HB Supervisor] Started Homebridge v1.1.4 with PID: 824

**Comment by okonet** [comment]
Interestingly it prints this before throwing:

```
[9/7/2020, 20:45:14] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[9/7/2020, 20:45:19] [HB Supervisor] Restarting Homebridge...
[9/7/2020, 20:45:19] [HB Supervisor] Starting Homebridge with extra flags: -I
[9/7/2020, 20:45:19] [HB Supervisor] Started Homebridge v1.1.2 with PID: 7710

/usr/local/lib/node_modules/homebridge/node_modules/commander/index.js:685
      throw new Error('call .storeOptionsAsProperties() before adding options');
            ^
```

**Comment by bkarakashev** [comment]
I think they realise that they have pushed bad release and there is a new release now. Installing it just now will let you know if this fixed it.

**Comment by bkarakashev** [comment]
Yes, guys just update to Version 1.1.5 it is all fixed.

**Comment by stevehoek** [comment]
Confirmed, 1.1.5 resolves it
