### ISSUE TITLE
ENOENT no such file or directory 

### ISSUE THREAD

**Issue by avacyb** [homebridge/homebridge#2678]
Hi, the installation works fine, but the homebridge is not up because this error.
What should i do?

```
[14.9.2020, 15:52:37] Error: ENOENT: no such file or directory, stat '/usr/lib/node_modules/JStillery_Server'
    at Object.statSync (fs.js:1042:3)
    at /usr/lib/node_modules/homebridge/src/pluginManager.ts:291:38
    at Array.filter (<anonymous>)
    at /usr/lib/node_modules/homebridge/src/pluginManager.ts:291:12
    at Set.forEach (<anonymous>)
    at PluginManager.loadInstalledPlugins (/usr/lib/node_modules/homebridge/src/pluginManager.ts:277:22)
    at PluginManager.initializeInstalledPlugins (/usr/lib/node_modules/homebridge/src/pluginManager.ts:116:10)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:150:24)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
```

**Comment by NorthernMan54** [comment]
This is not a homebridge package, do you have any other modules installed that could be triggering this?

Do the messages prior to this indicate what package/plugin it is from?

**Comment by Supereg** [comment]
`JStillery_Server` doesn't seem to be a npm package either. Can you check what's located there? maybe just a stuck inode?
Does this happen on every reboot?

We may want to improve robustness of the plugin loader in any way. Such a scenario shouldn't kill the whole bridge imo.

**Comment by oznu** [comment]
How to reproduce:

Create a symlink to a file or folder in your global `node_modules` folder, then delete the target.

**Comment by oznu** [comment]
@avacyb - you can run this to fix your immidate issue:

```
/usr/lib/node_modules/JStillery_Server
```

**Comment by oznu** [comment]
This will go out with the next release.

**Comment by richierockskool** [comment]
cmd: npm install -g homebridge-inkbird-wifi-gateway@1.0.3npm ERR! code ENOENTnpm ERR! path /usr/local/lib/node_modules/homebridge-inkbird-wifi-gateway/node_modules/homebridge-inkbird-wifi-gatewaynpm ERR! enoent ENOENT: Cannot cd into '/usr/local/lib/node_modules/homebridge-inkbird-wifi-gateway/node_modules/homebridge-inkbird-wifi-gateway'npm ERR! enoent This is related to npm not being able to find a file.npm ERR! enoent npm ERR! A complete log of this run can be found in:npm ERR!     /Users/richjagger/.npm/_logs/2023-04-19T15_59_00_920Z-debug-0.logOperation failed. Please review log for details.
