### ISSUE TITLE
Raspberry Pi OS installation fails at hb-service step

### ISSUE THREAD

**Issue by kjlynn** [homebridge/homebridge#2707]
Instructions to install fail on step **sudo hb-service install --user homebridge**  with error: 
Error: Cannot find module 'commander'
Require stack:
- /usr/local/bin/hb-service
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/bin/hb-service:17:19)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/bin/hb-service' ]
}

All preceding steps listed at https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian appear to complete normally.  "Commander" appears to have been installed in 2 places: /usr/lib/node_modules/homebridge/node_modules/commander
/usr/lib/node_modules/homebridge-config-ui-x/node_modules/commander

Any help appreciated.

one more note: attempting to run homebridge manually also fails with a missing module: 
homebridge
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '/usr/local/lib/cli'
Require stack:
- /usr/local/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/bin/homebridge:17:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/bin/homebridge' ]
}

**Comment by oznu** [comment]
The logs tell me you have multiple copies of Node.js installed on your system:

* /usr/bin/node
* /usr/local/bin/node

This is causing conflicts and will continue to cause your grief until resolved.

See https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux for instructions on how to resolve the issue.

If you don't presently have a Homebridge setup, you can skip to Step 2 and just run this command to remove all instances of Node.js:

```
sudo curl -fL https://git.io/JfFFM | sudo bash
```

Once done, you can follow the wiki guide for installing on Raspbian from the start.
