### ISSUE TITLE
[beta14] AssertionError: iid of linked service '' is undefined

### ISSUE THREAD

**Issue by mik9** [homebridge/homebridge#2708]
**Describe The Bug:**
Tried 1.3.0-Beta14 and got crash. Can be reproduced with single plugin https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum and config below.
```
AssertionError [ERR_ASSERTION]: iid of linked service '' is undefined on service 'Vaccum'
    at Fan.Service.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:645:15)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:972:54
    at Array.map (<anonymous>)
    at Accessory.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:972:31)
    at Bridge.Accessory.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:979:36)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1075:25)
    at Server.publishBridge (/usr/local/lib/node_modules/homebridge/src/server.ts:201:17)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:171:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:170:5)
```

**Homebridge Config:**
```json
{
    "bridge": {
        "name": "Homebridge CD93",
        "username": "0E:18:3C:E5:CD:93",
        "port": 53891,
        "pin": "031-45-154"
    },
    "accessories": [
        {
            "name": "Vaccum",
            "ip": "192.168.1.222",
            "token": "22222",
            "waterBox": false,
            "pause": false,
            "pauseWord": "pause",
            "findMe": false,
            "findMeWord": "where are you",
            "dock": false,
            "delay": false,
            "cleanword": "clean",
            "autoroom": false,
            "accessory": "XiaomiRoborockVacuum"
        }
],
    "platforms": []
}
```

**Screenshots:**
<img width="1020" alt="Знімок екрана 2020-10-24 о 20 59 42" src="https://user-images.githubusercontent.com/244760/97088776-db1e2700-163b-11eb-871b-3e3dfac7af11.png">

**Environment:**

* **Node.js Version**: v12.19.0
* **NPM Version**: 6.14.8
* **Homebridge Version**: 1.3.0-beta.14
* **Operating System**: Docker
* **Process Supervisor**: Docker

**Comment by bwt615** [comment]
+1, same plugin, windows
