### ISSUE TITLE
1.3.0-beta14 fails, 1.1.6 is OK: The requested platform 'Cmd4' was not registered by any plugin.

### ISSUE THREAD

**Issue by jsiegenthaler** [homebridge/homebridge#2709]
**Describe The Bug:**

Homebridge 1.1.6 works and 1.2.3 works, but when running 1.3.0-beta14 Homebridge cannot start
See logs below

**To Reproduce:**

Install and configure Cmd4 plugin
Observe that the plugin worksfin in 1.1.6 and 1.2.3
Upgrade to 1.3.0-beta 14
Observe that Homebridge cannot start

**Expected behavior:**

Given that the Cmd4 plugin works error free in 1.1.6 and 1.2.4, I expect it to work error free in 1.3.0-beta14

[**Logs:**]()

```
[10/25/2020, 06:46:06] ---
[10/25/2020, 06:46:06] Loading 8 platforms...
[10/25/2020, 06:46:06] [Shelly] Initializing Shelly platform...
[10/25/2020, 06:46:06] [Config] Initializing config platform...
[10/25/2020, 06:46:07] [Config] Running in Service Mode
[10/25/2020, 06:46:07] [Hue] Initializing Hue platform...
[10/25/2020, 06:46:07] [Hue] homebridge-hue v0.11.77, node v12.19.0, homebridge v1.3.0-beta.14
[10/25/2020, 06:46:07] Error loading platform requested in your config.json at position 4
[10/25/2020, 06:46:07] Error: The requested platform 'Cmd4' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/lib/node_modules/homebridge/src/server.ts:398:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:385:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:160:29)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
[10/25/2020, 06:46:07] Got SIGTERM, shutting down Homebridge...
[10/25/2020, 06:46:07] [Hue] searching bridges and gateways
[10/25/2020, 06:46:12] [Hue] goodbye
[10/25/2020, 06:46:12] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
```

```
[10/25/2020, 06:46:19] ---
[10/25/2020, 06:46:19] Loaded plugin: homebridge-cmd4@2.4.0
[10/25/2020, 06:46:19] ====================
[10/25/2020, 06:46:19] ERROR INITIALIZING PLUGIN homebridge-cmd4:
[10/25/2020, 06:46:19] TypeError: Cannot read property 'EXCELLENT' of undefined
    at Object.init (/usr/lib/node_modules/homebridge-cmd4/lib/CMD4_ACC_TYPE_ENUM.js:1918:66)
    at Plugin.default [as pluginInitializer] (/usr/lib/node_modules/homebridge-cmd4/index.js:76:36)
    at Plugin.initialize (/usr/lib/node_modules/homebridge/src/plugin.ts:197:10)
    at /usr/lib/node_modules/homebridge/src/pluginManager.ts:135:16
    at Map.forEach (<anonymous>)
    at PluginManager.initializeInstalledPlugins (/usr/lib/node_modules/homebridge/src/pluginManager.ts:118:18)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:157:24)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
[10/25/2020, 06:46:19] ====================
```

**Homebridge Config:**

```json
       {
            "platform": "Cmd4",
            "name": "Cmd4",
            "outputConstants": false,
            "accessories": [
                {
                    "type": "LockMechanism",
                    "displayName": "Front Door",
                    "lockCurrentState": "SECURED",
                    "lockTargetState": "SECURED",
                    "name": "Front Door",
                    "Manufacturer": "Jochens Cmd4 Plugin",
                    "Model": "Cmd4 LockMechanism",
                    "SerialNumber": "12345",
                    "stateChangeResponseTime": 0,
                    "state_cmd": "node ./Cmd4Scripts/State.js"
                },
                {
                    "type": "Switch",
                    "displayName": "Samsung HT-D5500",
                    "on": "FALSE",
                    "name": "Samsung Stereo",
                    "manufacturer": "Samsung",
                    "model": "HT-D5500",
                    "serialNumber": "HTB-D6500EUB-1023.1",
                    "polling": [
                        {
                            "on": "FALSE",
                            "interval": 2000,
                            "timeout": 10000
                        }
                    ],
                    "state_cmd_prefix": "bash",
                    "state_cmd": "./Cmd4Scripts/Stereo.sh",
                    "state_cmd_suffix": ""
                },
                {
                    "type": "Switch",
                    "displayName": "Samsung UE40D5000",
                    "on": "FALSE",
                    "name": "Samsung TV",
                    "manufacturer": "Samsung",
                    "model": "UE40D5000",
                    "serialNumber": "T-MSV4DEUC-1005.0",
                    "polling": [
                        {
                            "on": "FALSE",
                            "interval": 2000,
                            "timeout": 10000
                        }
                    ],
                    "state_cmd_prefix": "bash",
                    "state_cmd": "./Cmd4Scripts/TV.sh",
                    "state_cmd_suffix": ""
                },
                {
                    "type": "Switch",
                    "displayName": "Desktop PC",
                    "on": "FALSE",
                    "name": "Desktop PC",
                    "manufacturer": "xx",
                    "model": "xx",
                    "serialNumber": "abc123",
                    "polling": [
                        {
                            "on": "FALSE",
                            "interval": 2000,
                            "timeout": 10000
                        }
                    ],
                    "state_cmd_prefix": "bash",
                    "state_cmd": "./Cmd4Scripts/networkdevice.sh",
                    "state_cmd_suffix": ""
                },
                {
                    "type": "Television",
                    "displayName": "SamsungStereo",
                    "active": "ACTIVE",
                    "activeIdentifier": 1,
                    "configuredName": "SamsungStereo",
                    "sleepDiscoveryMode": "ALWAYS_DISCOVERABLE",
                    "brightness": 8,
                    "closedCaptions": "DISABLED",
                    "currentMediaState": "STOP",
                    "targetMediaState": "STOP",
                    "pictureMode": "STANDARD",
                    "remoteKey": "SELECT",
                    "linkedTypes": [
                        {
                            "type": "InputSource",
                            "displayName": "HDMI1",
                            "configuredName": "HDMI1",
                            "currentVisibilityState": "SHOWN",
                            "inputSourceType": "HDMI",
                            "isConfigured": "CONFIGURED",
                            "identifier": 1,
                            "targetVisibilityState": "SHOWN",
                            "name": "HDMI1",
                            "Manufacturer": "Somebody",
                            "Model": "Anything",
                            "SerialNumber": "12345"
                        },
                        {
                            "type": "InputSource",
                            "displayName": "HDMI2",
                            "configuredName": "HDMI2",
                            "currentVisibilityState": "SHOWN",
                            "inputSourceType": "HDMI",
                            "isConfigured": "CONFIGURED",
                            "identifier": 2,
                            "targetVisibilityState": "SHOWN",
                            "name": "HDMI2",
                            "Manufacturer": "Somebody",
                            "Model": "Anything",
                            "SerialNumber": "12345"
                        },
                        {
                            "type": "TelevisionSpeaker",
                            "displayName": "TVSpeaker",
                            "mute": "FALSE",
                            "active": "ACTIVE",
                            "volume": 10,
                            "volumeControlType": "RELATIVE",
                            "volumeSelector": "INCREMENT",
                            "name": "TVSpeaker",
                            "Manufacturer": "Somebody",
                            "Model": "Anything",
                            "SerialNumber": "12345"
                        },
                        {
                            "type": "Switch",
                            "displayName": "Samsung UE40D5000",
                            "on": "FALSE",
                            "name": "Samsung TV",
                            "manufacturer": "Samsung",
                            "model": "UE40D5000",
                            "serialNumber": "T-MSV4DEUC-1005.0",
                            "polling": [
                                {
                                    "on": "FALSE",
                                    "interval": 2000,
                                    "timeout": 10000
                                }
                            ],
                            "state_cmd_prefix": "bash",
                            "state_cmd": "./Cmd4Scripts/TV.sh",
                            "state_cmd_suffix": ""
                        }
                    ],
                    "polling": [
                        {
                            "active": "ACTIVE",
                            "interval": 2000,
                            "timeout": 5000
                        },
                        {
                            "currentMediaState": "STOP",
                            "interval": 540,
                            "timeout": 5000
                        }
                    ],
                    "stateChangeResponseTime": 3,
                    "state_cmd": "bash ./Cmd4Scripts/TV.sh"
                }
            ]
```

**Screenshots:**

**Environment:**
* **Node.js Version**: v12.19.0
* **NPM Version**: v6.14.8
* **Homebridge Version**:  1.3.0-beta 14
* **Operating System**: Raspbian GNU/Linux Buster (10)
* **Process Supervisor**: ??

**Comment by Supereg** [comment]
This issue is fixed with 1.3.0-beta.15. Thanks for reporting.
