### ISSUE TITLE
homebridge-homematic: beta v1.3.0 // error: characteristic value NaN is not contained in valid values array!

### ISSUE THREAD

**Issue by j-p-l** [homebridge/homebridge#2713]
Hey there, 
I am getting this error when trying to run v1.3.0-beta16 (also on the prior betas). 

**LOG:** 
```
Error: characteristic value NaN is not contained in valid values array!
at Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1683:15)
at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1155:24
at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
at /homebridge/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitContactService.js:229:11
at /homebridge/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:473:13
at /homebridge/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:685:13
at /homebridge/node_modules/homebridge-homematic/HomeMaticCCU.js:124:11
at /homebridge/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:66:9
at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:42:9)
at IncomingMessage.emit (events.js:327:22)
```
Is that an error, which needs to be solved in **homebridge beta16** or in the node module **homebridge-homematic**? In v1.2.3 everything is working fine. 

Thanks! 
Jannis

**Comment by Supereg** [comment]
First of all this should most likely be an issue with the plugin. With the latest beta we increased the amount of sanity checks made to supplied characteristic values whereas previously weird values were accepted and could lead to non responsive accessories and services.

I tried to look at the plugin code to verify my suspicion, but couldn't quite line up the files and lines shown in the provided error trace with the code what is publish on npm/GitHub.

Could you quickly verify that you are indeed running the latest version of homebridge-homematic?

**Comment by j-p-l** [comment]
I saw that I am running on homebridge-homematic v0.1.230 beta. I just upgraded to v0.1.231 (which is the same as v0.1.229 if I recall that correctly) and received the following error after installing homebridge beta v1.3.0:
```
TypeError: Cannot read property 'split' of undefined
at HomeMaticHomeKitValveService.createDeviceService (/homebridge/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitValveService.js:16:21)
at HomeMaticHomeKitValveService.HomeKitGenericService (/homebridge/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:110:8)
at new HomeMaticHomeKitValveService (/homebridge/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitValveService.js:7:39)
at HomeMaticServiceClassLoader.loadChannelService (/homebridge/node_modules/homebridge-homematic/HomeMaticServiceClassLoader.js:130:23)
at /homebridge/node_modules/homebridge-homematic/index.js:383:29
at Array.map (<anonymous>)
at /homebridge/node_modules/homebridge-homematic/index.js:343:25
at Array.map (<anonymous>)
at HomeMaticPlatform.buildaccesories (/homebridge/node_modules/homebridge-homematic/index.js:331:18)
at /homebridge/node_modules/homebridge-homematic/index.js:278:12
```

**Comment by Supereg** [comment]
I think best would be if you raise an issue with homebridge-homematic

https://github.com/thkl/homebridge-homematic/blob/35ad0f21331b23935d51a93c4c7ce5c1282f80c2/ChannelServices/HomeMaticHomeKitValveService.js#L16

This error is definitely not an issue with homebridge.

Will close this issue for now, if that's okay. Feel free to reopen if I mistakenly assumed fault at the plugin side.

**Comment by j-p-l** [comment]
Will raise an issue with homebridge-homematic. Thanks for your investigation and quick responses!
