### ISSUE TITLE
Homebridge stopped working - Error: Cannot create a string longer than 0xffffff0 characters

### ISSUE THREAD

**Issue by atajik** [homebridge/homebridge#2736]
I had Homebridge working for a while and suddenly it stopped working giving errors below. I initially thought it might an issue with one of the plug-ins or accessories, so unistalled all of them and removed the config.json and still see the same error

```
[12/4/2020, 23:13:47] Error: Cannot create a string longer than 0xffffff0 characters
    at Object.slice (buffer.js:606:37)
    at Buffer.toString (buffer.js:803:14)
    at Object.readFileSync (fs.js:408:41)
    at LocalStorage.parseDirSync (/usr/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:637:35)
    at LocalStorage.parseDataDirSync (/usr/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:572:21)
    at LocalStorage.initSync (/usr/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:145:14)
    at HAPStorage.storage (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/model/HAPStorage.ts:23:25)
    at Function.HAPStorage.storage (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/model/HAPStorage.ts:11:26)
    at Function.AccessoryInfo.load (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/model/AccessoryInfo.ts:204:28)
    at Bridge.Accessory._this.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:890:41)
```

**Comment by Supereg** [comment]
What version of homebridge are you running?

Can you verify the following. Can you navigate into your homebridge directory (if you provide more info about your installation I can maybe give a hint where the directory is located) navigate into the `persist` directory and verify that there is some file called `AccessoryInfo.xxx.json`. And also what is the size of the file? Does it exceed 256 MB?

**Comment by Supereg** [comment]
Or is there any other file in the `persist` folder that exceeds 256 MB and if so how is it called?

**Comment by atajik** [comment]
Hi Andy, thanks a lot for your help. There was a file names core that was about 256MB. I removed it and it resolved the issue. I appreciate your help.

pi@raspberrypi:~/.homebridge/persist $ ls -sh
total 258M
4.0K AccessoryInfo.CC223DE3CE30.json  
258M core   
48K IdentifierCache.CC223DE3CE30.json

**Comment by Supereg** [comment]
Great to hear. Thanks for reporting the issue, in any case homebridge shouldn't crash when trying to load "big" files. So this definitely needs to be fixed to fail gracefully ☺️

**Comment by atajik** [comment]
haha, fair point, do you want me to re-open the issue?

**Comment by Supereg** [comment]
no need. Already tracked that for our next release
