### ISSUE TITLE
Installing HomeBridge on MacOs

### ISSUE THREAD

**Issue by Phobos23** [homebridge/homebridge#2745]
/usr/local/lib/node_modules/homebridge/node_modules/chalk/source/index.js:106
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/src/logger.ts:3:1)

**Comment by oznu** [comment]
Your node.js version is out of date.

See step 1:

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-macOS
