### ISSUE TITLE
Homebridge errorrs on restart

### ISSUE THREAD

**Issue by vzlgdu** [homebridge/homebridge#2761]
Hi, every time I restart HB, I receive the following errors (see log); after this all seems to work. This happens always. 
The HB support told me that this seems not to be an error introduced from his plugin...
Can you help me?
Thanks

HB v1.2.5
Node.js v13.13.0
npm v6.14.4
Alexa Plugin v0.5.21

Stopping Node.js HomeKit Server...
[29/12/2020, 08:50:16] Got SIGTERM, shutting down Homebridge...
[29/12/2020, 08:50:16] TypeError: Cannot read property 'toString' of undefined
at Object.eventMessage (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaMessages.js:592:47)
at /usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:963:35
at Array.forEach ()
at alexaHome.alexaEvent (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:953:10)
at EventEmitter.emit (events.js:315:20)
at HAPNodeJSClient. (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:48:22)
at HAPNodeJSClient.emit (events.js:315:20)
at HAPNodeJSClient._reconnectServer (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:309:8)
at EventEmitter.emit (events.js:315:20)
at Socket. (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/eventedHttpClient.js:90:24)
homebridge.service: Main process exited, code=exited, status=143/n/a
Stopped Node.js HomeKit Server.
homebridge.service: Unit entered failed state.
homebridge.service: Failed with result 'exit-code'.
Started Node.js HomeKit Server.
pam_unix(sudo:session): session closed for user root

**Comment by NorthernMan54** [comment]
@vzlgdu This does not cause an issue, and as I indicated it is triggered by shutdown.

https://github.com/NorthernMan54/homebridge-alexa/issues/404

**Comment by Supereg** [comment]
afaik the issues was isolated and fixed 👍

**Comment by vzlgdu** [comment]
so, what should I do to avoid this?

**Comment by Supereg** [comment]
I assume update to the latest version of the Alexa Plugin?

**Comment by vzlgdu** [comment]
Yes: v0.5.22

**Comment by Shep084** [comment]
I’ve updated to the latest version v5.22 but I’m still getting this error. Any ideas?
