### ISSUE TITLE
Homebridge won't start

### ISSUE THREAD

**Issue by leon38** [homebridge/homebridge#2762]
**Describe The Bug:**

When I start homebridge with the command, there is an error and the server shuts off

**To Reproduce:**
Just start homebridge on Mac Os X Big Sur

**Expected behavior:**

Starting the homebridge server

[**Logs:**]()

```
[29/12/2020 à 17:54:08] Loaded config.json with 3 accessories and 5 platforms.
[29/12/2020 à 17:54:08] ---
[29/12/2020 à 17:54:09] Loaded plugin: homebridge-config-ui-x@4.36.0
[29/12/2020 à 17:54:09] Registering platform 'homebridge-config-ui-x.config'
[29/12/2020 à 17:54:09] ---
[29/12/2020 à 17:54:09] Loaded plugin: homebridge-harmony@1.4.1
[29/12/2020 à 17:54:09] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
[29/12/2020 à 17:54:09] ---
[29/12/2020 à 17:54:10] Loaded plugin: homebridge-hue@0.12.12
[29/12/2020 à 17:54:10] Registering platform 'homebridge-hue.Hue'
[29/12/2020 à 17:54:10] ---
[29/12/2020 à 17:54:10] Loaded plugin: homebridge-network-presence@1.1.2
[29/12/2020 à 17:54:10] Registering platform 'homebridge-network-presence.NetworkPresence'
[29/12/2020 à 17:54:10] ---
[29/12/2020 à 17:54:10] Loaded plugin: homebridge-plex-v2@1.2.1
[29/12/2020 à 17:54:10] Registering accessory 'homebridge-plex-v2.Plex'
[29/12/2020 à 17:54:10] ---
[29/12/2020 à 17:54:10] Loaded plugin: homebridge-sonos@0.4.0
[29/12/2020 à 17:54:10] Registering accessory 'homebridge-sonos.Sonos'
[29/12/2020 à 17:54:10] ---
[29/12/2020 à 17:54:11] Loaded plugin: homebridge-tplink-smarthome@6.1.0
[29/12/2020 à 17:54:11] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[29/12/2020 à 17:54:11] ---
[29/12/2020 à 17:54:11] Loaded plugin: homebridge-twinkly@0.3.4
[29/12/2020 à 17:54:11] Registering accessory 'homebridge-twinkly.Twinkly'
[29/12/2020 à 17:54:11] ---
[29/12/2020 à 17:54:11] Loaded plugin: homebridge-zp@1.1.4
[29/12/2020 à 17:54:11] Registering platform 'homebridge-zp.Lib'
[29/12/2020 à 17:54:11] Registering platform 'homebridge-zp.ZP'
[29/12/2020 à 17:54:11] Registering platform 'homebridge-zp.ZPS1'
[29/12/2020 à 17:54:11] ---
[29/12/2020 à 17:54:11] Loading 5 platforms...
[29/12/2020 à 17:54:11] [Config] Initializing config platform...
[29/12/2020 à 17:54:11] [Config] Spawning homebridge-config-ui-x with PID 3109
[29/12/2020 à 17:54:11] [Salon] Initializing HarmonyHubWebSocket platform...
[29/12/2020 à 17:54:11] [Salon] HarmonyPlatform Init
[29/12/2020 à 17:54:11] [Sonos] Initializing ZP platform...
[29/12/2020 à 17:54:11] [Sonos] homebridge-zp v1.1.4, node v14.15.3, homebridge v1.2.5, homebridge-lib v4.8.4
[29/12/2020 à 17:54:11] [Sonos] warning: not using recommended node v14.15.2 LTS
[29/12/2020 à 17:54:11] [Sapin de noël] Initializing TplinkSmarthome platform...
[29/12/2020 à 17:54:11] [Sapin de noël] homebridge-tplink-smarthome v6.1.0, node v14.15.3, homebridge v1.2.5
[29/12/2020 à 17:54:11] [Config] Initializing config platform...
[29/12/2020 à 17:54:11] Error: option 'no-timestamp' clashes with existing property 'timestamp' on Command
- call storeOptionsAsProperties(false) to store option values safely,
- or call storeOptionsAsProperties(true) to suppress this check,
- or change option name

Read more on https://git.io/JJc0W
    at Command._checkForOptionNameClash (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/commander/index.js:472:13)
    at Command._optionEx (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/commander/index.js:499:10)
    at Command.option (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/commander/index.js:622:17)
    at new HomebridgeConfigUi (/usr/local/lib/node_modules/homebridge-config-ui-x/src/index.ts:31:8)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:395:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
[29/12/2020 à 17:54:11] Got SIGTERM, shutting down Homebridge...
[29/12/2020 à 17:54:11] [Salon] INFO - shutdown
[29/12/2020 à 17:54:13] [Homebridge UI] Homebridge Config UI X v4.36.0 is listening on :: port 8581
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge 4AC0",
        "username": "0E:EB:71:E8:4A:C0",
        "port": 51204,
        "pin": "697-29-539"
    },
    "accessories": [
        {
            "accessory": "Plex",
            "name": "Plex",
            "plex_token": "2yxrwsRz3Ge81Dg-YNED",
            "filter": [
                {
                    "player": "Salon"
                }
            ]
        },
        {
            "name": "Sonos",
            "room": "Pièce à vivre",
            "groupCacheLifetime": 15,
            "deviceCacheLifetime": 3600,
            "accessory": "Sonos"
        },
        {
            "accessory": "Twinkly",
            "name": "Sapin",
            "ip": "192.168.1.45",
            "allowBrightnessControl": true
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Salon",
            "hubIP": "192.168.1.16",
            "hubName": "Salon",
            "TVAccessory": true,
            "switchAccessories": true,
            "playPauseBehavior": true,
            "showTurnOffActivity": "true",
            "addAllActivitiesToSkippedIfSameStateActivitiesList": true,
            "platform": "HarmonyHubWebSocket"
        },
        {
            "name": "Sonos",
            "brightness": true,
            "nameScheme": "Pièce à vivre",
            "service": "speaker",
            "speakers": true,
            "platform": "ZP"
        },
        {
            "name": "Sapin de noël",
            "addCustomCharacteristics": false,
            "deviceTypes": [
                "plug"
            ],
            "platform": "TplinkSmarthome"
        },
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "log": {
                "method": "file",
                "path": "/Users/damiencorona/.homebridge/homebridge.log"
            }
        }
    ]
}
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v14.15.3
* **NPM Version**: 6.14.9
* **Homebridge Version**: 1.2.5
* **Operating System**: macOS
* **Process Supervisor**: none

**Comment by paulw11** [comment]
This seems to be related to #2670 
A workaround is to comment line 499 of commander/index.js, but every time you update Homebridge UI you need to re-make this change.  A proper fix would be very welcome.

**Comment by nowtp** [comment]
Same issue here has well, just doesn't seem to start! Was working fine yesterday with no changes apart from a machine restart; so unsure what could have occurred to stop the service from starting.

Tried the above commenting out of the line 499 in the commander/index.js to stop the duplication check but no dice.

**Comment by nowtp** [comment]
Just an FYI, I stopped the service from running (sudo hb-service stop) then ran the service installer (sudo hb-service install) again and this fixed mine to be working again. Not sure why it worked though ...

**Comment by paulw11** [comment]
I still get this issue every time I update Homebridge UI and need to edit commander to comment the line again.

**Comment by gillesguillemin** [comment]
> I still get this issue every time I update Homebridge UI and need to edit commander to comment the line again.

Yup, same for me. Pretty annoying. Commenting line 499 every single time is getting old by now.
