### ISSUE TITLE
Error on reboot

### ISSUE THREAD

**Issue by dcaccount** [homebridge/homebridge#2809]
Hello,
Homebridge is running in my Raspberry pi4, under Node.js v14.15.4 and npm v7.5.2.

When I reboot Homebridge I get following error:

> TypeError: Cannot read property 'forEach' of undefined
    at HAPNodeJSClient._reconnectServer (/usr/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:301:39)
    at EventEmitter.emit (events.js:315:20)
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/eventedHttpClient.js:90:24)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

Any idea, how can I solve it?

Thanks,
Dan

**Comment by dcaccount** [comment]
Error has dissapeard after having having reinstalled plugin!

**Comment by Supereg** [comment]
Thanks for the update. I then just assume the error might have been already fixed and was fix by reinstalling the plugin and its dependencies.

**Comment by NorthernMan54** [comment]
Thanks for reporting that updating to the latest resolved the issue. I had fixed a couple of these recently, and glad to that it resolved this.
