### ISSUE TITLE
Problem with web UI.

### ISSUE THREAD

**Issue by lightingcze** [homebridge/homebridge#2811]
Everything looks ok.No problem with install.But not reachable web page.

[**Logs:**](
SyntaxError: Unexpected string
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/ajv/lib/compile/resolve.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[2/15/2021, 10:18:52 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[2/15/2021, 10:18:53 AM] [Homebridge UI] TypeError: Cannot read property 'setHomebridgeProcess' of undefined
[2/15/2021, 10:18:53 AM] [Homebridge UI] Caught Unhandled Rejection Error :: Details Below
TypeError: Cannot read property 'setHomebridgeProcess' of undefined
    at HomebridgeServiceHelper.runHomebridge (/usr/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js:307:25)
    at HomebridgeServiceHelper.launch (/usr/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js:252:18)
[2/15/2021, 10:19:03 AM] [HB Supervisor] OS: Linux 4.19.66-v7+ arm
[2/15/2021, 10:19:03 AM] [HB Supervisor] Node.js v14.15.5 /usr/bin/node
[2/15/2021, 10:19:03 AM] [HB Supervisor] Homebridge Path: /usr/lib/node_modules/homebridge/bin/homebridge
[2/15/2021, 10:19:03 AM] [HB Supervisor] UI Path: /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[2/15/2021, 10:19:03 AM] [HB Supervisor] ERROR: The user interface threw an unhandled error
/usr/lib/node_modules/homebridge-config-ui-x/node_modules/uri-js/dist/es5/uri.all.js:85
"   	PV6ADDRESW7$!=
^^^^^^^^^^^^^^^^^^^)

```
Secondary Homebridge Logs here
```
pi@homebridge_unifi:~ $ sudo hb-service statusℹ Testing hb-service is running on port 8581...
✖ Homebridge UI Not Running

**Environment:**

* **Node.js Version**: v14.15.5
* **NPM Version**:  6.14.11
* **Homebridge Version**: 1.1.7
* **Operating System**: Raspbian 
* **Process Supervisor**:  hb-service

**Comment by oznu** [comment]
Re-install:

```bash
# cleanup
sudo npm uninstall -g homebridge-config-ui-x

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```

**Comment by lightingcze** [comment]
thank you, ill try ;-)

Ondřej Bylok
LD / Avolites & gMA2 operator-programmer / 
+420604830049
Prague CZE
