### ISSUE TITLE
Homebridge 1.3 not able to read CCU3 HM-Sec-SC-2 window sensor

### ISSUE THREAD

**Issue by BerndGewehr** [homebridge/homebridge#2821]
Not sure whether this relates to bridge or plugin... Error appeared after 1.3 update for the forst time.

**Describe The Bug:**

HM-Sec-SC-2 window sensor causes an error in HB1.3
The device is inactive in Homekit

[**Logs:**]()
```
[2/20/2021, 1:51:10 PM] [homebridge-homematic] This plugin generated a warning from the characteristic 'Contact Sensor State': Unhandled error thrown inside read handler for characteristic: Error: characteristic value NaN is not contained in valid values array!
    at ContactSensorState.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2028:15)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1490:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /homebridge/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitContactService.js:241:9
    at HomeMaticHomeKitContactService.query (/homebridge/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:404:11)
    at ContactSensorState.<anonymous> (/homebridge/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitContactService.js:234:12)
    at ContactSensorState.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1466:14
    at new Promise (<anonymous>)
    at ContactSensorState.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1464:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at ContactSensorState.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:632:24)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1507:27)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16) See https://git.io/JtMGR for more info.
 ```

**Homebridge Config:**
```json
        {
            "name": "HomeMatic CCU",
            "ccu_ip": "192.168.178.XXX",
            "subsection": "Homebridge",
            "enable_hmip": true,
            "enable_wired": false,
            "ios10": true,
            "platform": "HomeMatic"
        },```

**Environment:**
latest Raspberrymatic
latest Homebridge

**Comment by BerndGewehr** [comment]
Same for Smoke-Detector:

```
[2/20/2021, 2:04:21 PM] [homebridge-homematic] This plugin generated a warning from the characteristic 'Smoke Detected': Unhandled error thrown inside read handler for characteristic: Error: characteristic value NaN is not contained in valid values array!
    at SmokeDetected.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2028:15)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1490:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /homebridge/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitSmokeDetectorService.js:18:23
    at HomeMaticHomeKitSmokeDetectorService.query (/homebridge/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:404:11)
    at SmokeDetected.<anonymous> (/homebridge/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitSmokeDetectorService.js:17:12)
    at SmokeDetected.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1466:14
    at new Promise (<anonymous>)
    at SmokeDetected.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1464:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at SmokeDetected.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:632:24)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1507:27)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16) See https://git.io/JtMGR for more info.
```

**Comment by BerndGewehr** [comment]
Maybe NaN should be accepted?

**Comment by oznu** [comment]
Please see https://git.io/JtMGR

**Comment by oznu** [comment]
Also not this is a just a warning - the issue was still present in the plugin prior to 1.3.0 - it was just hidden from view.

As per link in log / above - such warnings need to be reported to the plugin developer.

https://github.com/thkl/homebridge-homematic

**Comment by BerndGewehr** [comment]
Ok but previous to 1.3 the devices worked as expected while they are now inactive
