### ISSUE TITLE
homebridge-broadlink-rm-pro stop working

### ISSUE THREAD

**Issue by rucanunes** [homebridge/homebridge#2836]
Hello,

I'm running the latest Homebridge Raspbian Image on a Raspberry PI 4b connected via LAN.
I use the homebridge-broadlink-rm-pro to open my blinds and for some Broadlink outlets.

Can someone please help me?

Here's the main errors I get:

`[23/02/2021, 12:09:02] [HB Supervisor] Restarting Homebridge...
[23/02/2021, 12:09:02] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[23/02/2021, 12:09:02] [HB Supervisor] Started Homebridge v1.3.1 with PID: 2970
Initializing HAP-NodeJS v0.9.2...
[23/02/2021, 12:09:03] Loaded config.json with 7 accessories and 3 platforms.
[23/02/2021, 12:09:03] Loaded 5 cached accessories from cachedAccessories.
[23/02/2021, 12:09:03] ---
[23/02/2021, 12:09:04] Loaded plugin: homebridge-broadlink-rm-pro@4.4.1
[23/02/2021, 12:09:04] Plugin 'homebridge-broadlink-rm-pro' tried to register with an incorrect plugin identifier: 'homebridge-broadlink-rm'. Please report this to the developer!
[23/02/2021, 12:09:04] Registering platform 'homebridge-broadlink-rm-pro.BroadlinkRM'
[23/02/2021, 12:09:04] ---
[23/02/2021, 12:09:04] Loaded plugin: homebridge-broadlink-sp@0.1.3
[23/02/2021, 12:09:04] Registering accessory 'homebridge-broadlink-sp.broadlinkSP'
[23/02/2021, 12:09:04] ---
[23/02/2021, 12:09:04] Loaded plugin: homebridge-config-ui-x@4.39.0
[23/02/2021, 12:09:04] Registering platform 'homebridge-config-ui-x.config'
[23/02/2021, 12:09:04] ---
[23/02/2021, 12:09:04] Loaded plugin: homebridge-mi-hygrothermograph@3.0.3
[23/02/2021, 12:09:06] Registering accessory 'homebridge-mi-hygrothermograph.Hygrotermograph'
[23/02/2021, 12:09:06] ---
[23/02/2021, 12:09:06] Loaded plugin: homebridge-network-presence@1.2.3
[23/02/2021, 12:09:06] Registering platform 'homebridge-network-presence.NetworkPresence'
[23/02/2021, 12:09:06] ---`

`[23/02/2021, 11:28:35] [homebridge-broadlink-rm-pro] Error: 
    at On.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at On.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at SwitchAccessory.getCharacteristicValue (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:158:5)
    at On.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1493:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1491:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)`

`[23/02/2021, 12:09:11] [homebridge-broadlink-rm-pro] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[23/02/2021, 12:09:11] [homebridge-broadlink-rm-pro] Error: 
    at On.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at On.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at SwitchAccessory.getCharacteristicValue (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/base/accessory.js:158:5)
    at On.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1493:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1491:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)`

`[23/02/2021, 12:09:13] [homebridge-broadlink-sp] This plugin slows down Homebridge. The read handler for the characteristic On was slow to respond! See https://git.io/JtMGR for more info.
[23/02/2021, 12:09:14] [homebridge-broadlink-sp] This plugin slows down Homebridge. The read handler for the characteristic On was slow to respond! See https://git.io/JtMGR for more info.
[23/02/2021, 12:09:14] [homebridge-broadlink-sp] This plugin slows down Homebridge. The read handler for the characteristic On was slow to respond! See https://git.io/JtMGR for more info.
[23/02/2021, 12:09:14] [homebridge-broadlink-sp] This plugin slows down Homebridge. The read handler for the characteristic On was slow to respond! See https://git.io/JtMGR for more info.
[23/02/2021, 12:09:14] [homebridge-broadlink-sp] This plugin slows down Homebridge. The read handler for the characteristic On was slow to respond! See https://git.io/JtMGR for more info.`

`[23/02/2021, 12:09:20] [homebridge-broadlink-sp] This plugin slows down Homebridge. The read handler for the characteristic On didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[23/02/2021, 12:09:20] [homebridge-broadlink-sp] This plugin slows down Homebridge. The read handler for the characteristic On didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[23/02/2021, 12:09:20] [homebridge-broadlink-sp] This plugin slows down Homebridge. The read handler for the characteristic On didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[23/02/2021, 12:09:20] [homebridge-broadlink-sp] This plugin slows down Homebridge. The read handler for the characteristic On didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[23/02/2021, 12:09:20] [homebridge-broadlink-sp] This plugin slows down Homebridge. The read handler for the characteristic On didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.`

**Comment by donavanbecker** [comment]
@rucanunes As the logs say:

```
Please report this to the developer!
```

Thanks
