### ISSUE TITLE
Issue with BLEBOX plugin TypeError: Cannot read property 'r' of null

### ISSUE THREAD

**Issue by staryga** [homebridge/homebridge#2848]
I struggling with following plugin to work after 1.3.0 (and 1.3.1)
https://github.com/Actardnes/homebridge-blebox

plugin do not work as standard or child bridge and keep on restarting

/usr/local/lib/node_modules/homebridge-blebox/common/colorHelper.js:4
            r = rgb.r / 255,
                    ^
TypeError: Cannot read property 'r' of null
    at Object.rgbToHsv (/usr/local/lib/node_modules/homebridge-blebox/common/colorHelper.js:4:21)
    at WLightBoxAccessoryWrapper._getRgbAsHsv (/usr/local/lib/node_modules/homebridge-blebox/blebox/wLightBox.js:111:28)
    at WLightBoxAccessoryWrapper.updateStateInfo (/usr/local/lib/node_modules/homebridge-blebox/blebox/wLightBox.js:88:36)
    at WLightBoxAccessoryWrapper.init (/usr/local/lib/node_modules/homebridge-blebox/blebox/abstractBox.js:29:18)
    at new WLightBoxAccessoryWrapper (/usr/local/lib/node_modules/homebridge-blebox/blebox/wLightBox.js:25:14)
    at Object.create (/usr/local/lib/node_modules/homebridge-blebox/blebox/wLightBox.js:299:16)
    at BleBoxPlatform.createAndAddAccessoryWrapper (/usr/local/lib/node_modules/homebridge-blebox/platform/bleboxPlatform.js:161:60)
    at Object.onSuccess (/usr/local/lib/node_modules/homebridge-blebox/platform/bleboxPlatform.js:174:26)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-blebox/common/communication.js:91:27)
    at listOnTimeout (node:internal/timers:556:17)
[2/25/2021, 9:23:39 AM] [BleBoxkuba] Child bridge process ended
[2/25/2021, 9:23:39 AM] [BleBoxkuba] Process Ended. Code: 1, Signal: null
[2/25/2021, 9:23:46 AM] [BleBoxkuba] Restarting Process...

**Comment by staryga** [comment]
this problem still has not be resolved. after homebridge update to 1.3 the plugin for BleBox wLightBoxS is crashing the homebridge instance. Other blebox devices are working fine. The work arround is to block the device from the network. I guess the plugin is not supported anymore

**Comment by oznu** [comment]
See https://github.com/Actardnes/homebridge-blebox/issues/14 - this issue is not something we can fix in Homebridge.
