### ISSUE TITLE
Error: Service name is already in use on the network

### ISSUE THREAD

**Issue by krharrison1** [homebridge/homebridge#2854]
After upgrading to HB v1.3.1, I am getting this error on restart ...

[3/2/2021, 10:21:57 AM] Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:108:27)
    at Prober.done (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:315:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)

HB crashes, restarts, crashes, restarts ... at some point it will start up but it takes a while, don't know why it eventually starts. It screws up some of my plugins because of excessive login attempts during startup. The other issues I've found about this error say to turn off mDNS ... I am using a Unifi USG and checked the settings, mDNS is already off.  Are there other ways to resolve this error?

**Comment by krharrison1** [comment]
The issue has once again disappeared but I have no idea why. I upgraded to v1.3.2 and HB is shutting down and restarting with no problems. I don't see any reason to keep the issue open, especially since it's not occurring now and I can't reproduce it. But if anyone has found a resolution not related to mDNS settings, please share.

**Comment by tonyduanesmith** [comment]
Also seeing this bug using 1.3.4, sometimes power cycling the raspberry pi fixes the issue

**Comment by 1Wheeler** [comment]
fyi I ran into this after upgrade too, editing the config and renaming a platforms.name for a plugin resolved
