### ISSUE TITLE
Filter out duplicate UUIDs when restoring cache

### ISSUE THREAD

**Issue by GRClark** [homebridge/homebridge#2856]
Hoping someone can help me with errors I’m getting after updating Homebridge this morning.  Worked fine beforehand but now I can’t even get Homebridge running - UI X comes up fine.  

[3/4/2021, 11:59:13 AM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: a67be37e-2900-43f3-97bd-cf9dee2bc67e
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:563:15)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:326:19
    at Array.filter (<anonymous>)
    at BridgeService.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:283:69)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:128:24)

**Comment by oznu** [comment]
Delete the cachedAccessories file. It's in the "accessories" folder of your homebridge storage directory.

**Comment by GRClark** [comment]
Thanks for the help that solved the issue.

**Comment by oznu** [comment]
We should check for duplicate UUIDs when restoring and handle it gracefully.

**Comment by oznu** [comment]
Homebridge 1.3.3 will gracefully handle and resolve this error itself.

https://github.com/homebridge/homebridge/wiki/Homebridge-Beta-Testing
