### ISSUE TITLE
SET handler returned write response value, though the characteristic doesn't support write response

### ISSUE THREAD

**Issue by shimi269** [homebridge/homebridge#2860]
When I try to use commands to interface with the thermostats, I get following errors below, but the thermostats do change to the temperature I asked for, so unsure what the exact issue is. 

[3/5/2021, 1:14:48 PM] [Nest] Setting temperature to 25 °C / 77 °F
[3/5/2021, 1:14:48 PM] [Nest] Setting target temperature for Upstairs Thermostat to: 25
[3/5/2021, 1:14:48 PM] [Nest] shared.xxxxxxxxxxxxxxx target_temperature 25
[3/5/2021, 1:14:48 PM] [homebridge-nest] This plugin generated a warning from the characteristic 'Target Temperature': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/5/2021, 1:14:48 PM] [homebridge-nest] Error: 
    at TargetTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1645:22
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /homebridge/node_modules/homebridge-nest/index.js:16:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[3/5/2021, 1:14:48 PM] [Nest] Target temperature for Upstairs Thermostat is: 25 °C / 77 °F
[3/5/2021, 1:14:50 PM] [homebridge-nest-cam] Checking for alerts on Front Door
[3/5/2021, 1:14:51 PM] [Hue] Philips hue: request 13: GET /lights
[3/5/2021, 1:14:51 PM] [Hue] Philips hue: request 13: 200 OK
[3/5/2021, 1:14:51 PM] [homebridge-nest-cam] Setting Front Door Person Motion to false
[3/5/2021, 1:14:51 PM] [homebridge-nest-cam] Setting Front Door Package Delivered Motion to false
[3/5/2021, 1:14:51 PM] [homebridge-nest-cam] Setting Front Door Person Motion to false
[3/5/2021, 1:14:51 PM] [homebridge-nest-cam] Setting Front Door Package Delivered Motion to false
[3/5/2021, 1:14:51 PM] [Nest] Cooling threshold temperature for Upstairs Thermostat is: 25 °C / 77 °F
[3/5/2021, 1:14:51 PM] [Nest] Heating threshold temperature for Upstairs Thermostat is: 25 °C / 77 °F

**Comment by donavanbecker** [comment]
@shimi269 this looks like something you need to bring to the attention of the plugin developer for homebridge-nest.

**Comment by shimi269** [comment]
Just realised, posted on the appropriate github now

**Comment by oznu** [comment]
We should move this message to debug level

**Comment by oznu** [comment]
Done in https://github.com/homebridge/homebridge/commit/3c9bb365fc22d3c4ad910f63cce78c3c14cb28e0.

**Comment by OspreyBoat** [comment]
I have the same error although Nest works ok: Nest BridgeERROR[Nest Bridge A028@Entryway Thermostat@@Target Temperature] SET handler returned write response value, though the characteristic doesn't support write response
