### ISSUE TITLE
Need help getting homebridge on hyper-v to execute commands on another windows 10 pc

### ISSUE THREAD

**Issue by UnbendableStraw** [homebridge/homebridge#2865]
**Describe Your Problem:**
I am running Homebridge on a HyperV vm (Windows Server 2019 host). I want to be able to run batch scripts that are on various windows 10 PCs on my local network.

I am trying to use a wake on lan plugin, simply because they let me specify a ping command for online status and I can run a custom command for on and off, but this isn't a problem with the plugin.

I installed openssh on my windows 10 pc and made my batch scripts, but I can't find a way to actually get the ssh command frmo homebridge to windows to succeed. 

An example shutdown command I use for the wake on lan plugin: `\"shutdownCommand\": \"ssh 192.168.1.241 'cmd.exe \/c C:\\Users\\UnbendableStraw\\Desktop\\stop.bat'\",`

The error I see in homebridge console:

```
Attempting to shut down "Main PC" (192.168.1.241) using "ssh"
[3/8/2021, 5:46:22 PM] [Main PC] An error occured while trying to shut down "Main PC" (192.168.1.241): Error: Command failed: ssh 192.168.1.241 'cmd.exe /c C:UsersUnbendableStrawDesktopstop.bat'
Host key verification failed.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 255,
  signal: null,
  cmd: "ssh 192.168.1.241 'cmd.exe /c C:UsersUnbendableStrawDesktopstop.bat'",
  stdout: '',
  stderr: 'Host key verification failed.\r\n'
}
```

I've tried creating ssh keys and trusting them on the homebridge os but I get permission denied.

```docker@homebridge-vm:~$ cat id_rsa.pub >> ~/.ssh/authorized_keys               
-bash: /home/docker/.ssh/authorized_keys: Permission denied```

I'm open to ideas!

**Environment:**

* **Node.js Version**: v14.16.0
* **NPM Version**: 6.14.11
* **Homebridge Version**: 1.3.1
* **Operating System**: Windows Server 2019 Hyper-V Homebridge Image
* **Process Supervisor**: docker...right?

**Comment by oznu** [comment]
> I've tried creating ssh keys and trusting them on the homebridge os but I get permission denied.

Do it inside the container, using the terminal via the UI will get you into the right spot.

you could also run your ssh command with `-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no` to skip host checking.
