### ISSUE TITLE
Homebridge all of a sudden won't load

### ISSUE THREAD

**Issue by gigecogary** [homebridge/homebridge#2885]
Homebridge-UI also just hangs. Here is the tail end of the log file. Not sure what broke it?

3/26/2021, 1:14:15 AM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: dd0c01d4-fa4d-4fbf-907c-96474f02f174
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:416:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:310:19
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:270:69)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:158:10)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
[3/26/2021, 1:14:15 AM] Got SIGTERM, shutting down Homebridge...
[3/26/2021, 1:14:17 AM] [Homebridge UI] Homebridge Config UI X v4.41.0 is listening on :: port 9090

**Comment by oznu** [comment]
> 3/26/2021, 1:14:15 AM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: dd0c01d4-fa4d-4fbf-907c-96474f02f174

This issue is automatically fixed as of 1.3.3, update Homebridge to the latest version and you should be good. 

Also consider re-doing your setup using the current wiki guides, this will ensure the Homebridge UI remains online even if homebridge or a plugin is having issues.
