### ISSUE TITLE
My Homebridge (raspi 2) keep shutting down after a few hours

### ISSUE THREAD

**Issue by GenreDown** [homebridge/homebridge#2893]
Hi,
I'm using homebridge on a raspi 2 b+ on raspbian. Was working perfectly. Recently moved in a new flat, everything seemed to work until I noticed that after a few hours it wasn't working anymore, I have to restart it to make it work again. 
Here is a pastebin of the logs if it can help 

https://pastebin.com/QDhMjwrS

Thanks a lot

**Comment by GenreDown** [comment]
Please...nobody ?

**Comment by oznu** [comment]
It looks like the `BroadlinkRM-Enhanced` plugin is crashing the bridge, you should report the issue to the plugin author.

**Comment by GenreDown** [comment]
> It looks like the `BroadlinkRM-Enhanced` plugin is crashing the bridge, you should report the issue to the plugin author.

Hello, thank you very much for answering. The problem was there before I installed the Broadcom plugin. I really don't understand what is causing the issue

**Comment by NorthernMan54** [comment]
@GenreDown These are the problematic lines in your log


```
[08/04/2021 à 07:55:44] [BroadlinkRM-Enhanced] Broadlink RM device at 192.168.1.143 (34:ea:34:b2:e7:2d) is no longer reachable. (192.168.1.143, Network is unreachable)
[08/04/2021 à 07:56:18] Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:692:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:430:12)
    at afterDns (dgram.js:638:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
 
[08/04/2021 à 07:56:18] Got SIGTERM, shutting down Homebridge...
[08/04/2021 à 07:56:18] [ZigBee] Stopping zigbee service
[08/04/2021 à 07:56:18] [ZigBee] Zigbee: disabling joining new devices.
[08/04/2021 à 07:56:18] [ZigBee] Error while stopping ZigBee service TypeError: Cannot read property 'permitJoin' of null
    at ZigBeeController.<anonymous> (/usr/lib/node_modules/homebridge-zigbee-nt/dist/zigbee/zigBee-controller.js:163:33)
    at Generator.next (<anonymous>:null:null)
    at /usr/lib/node_modules/homebridge-zigbee-nt/dist/zigbee/zigBee-controller.js:8:71
```

With this occurring right at the time homebridge exited

```
[08/04/2021 à 07:55:44] [BroadlinkRM-Enhanced] Broadlink RM device at 192.168.1.143 (34:ea:34:b2:e7:2d) is no longer reachable. (192.168.1.143, Network is unreachable)
[08/04/2021 à 07:56:18] Error: send ENETUNREACH 224.0.0.251:5353
```

As Oznu suggested, try removing that plugin or others from the config ( trial and error ) until you identify the plugin that triggers this.  Is your network stable ?  As you indicated that you just moved, is your new router causing issues?

**Comment by oznu** [comment]
```
[08/04/2021 à 07:56:18] Error: send ENETUNREACH 224.0.0.251:5353
```

@Supereg is this situation handled in bonjour/ciao?

**Comment by Supereg** [comment]
@oznu 
It’s handled in ciao https://github.com/homebridge/ciao/blob/3ce9b350117206ee80234d6dbed9bc54003deff1/src/MDNSServer.ts#L589

and is also handled in the ˋmulticast-dnsˋ Package used im Bonjour-hap

**Comment by GenreDown** [comment]
Hi guys. Thank you for your answer ! I disabled the broadcom plugin yesterday. I just woke up to homebridge not responding... so this is not related to the plugin I think
