### ISSUE TITLE
Homebridge crashed and cannot start now due to missing config

### ISSUE THREAD

**Issue by CatalinMustata** [homebridge/homebridge#2894]
**Describe Your Problem:**

While trying to get a plugin to work properly (for a Philips air purifier), Homebridge suddenly stopped working. Tried to restart it from the terminal, but it then failed and I noticed there is no `.homebridge` dir in my home dir.

[**Logs:**]()

```
[catalin@rooncore ~]$ homebridge -D
Initializing HAP-NodeJS v0.9.4...
[4/9/2021, 6:44:16 PM] config.json (/home/catalin/.homebridge/config.json) not found.
Error: ENOENT: no such file or directory, mkdir '/home/catalin/.homebridge/accessories'
    at Object.mkdirSync (node:fs:1023:3)
    at Object.module.exports.makeDirSync (/usr/lib/node_modules/homebridge/node_modules/fs-extra/lib/mkdirs/make-dir.js:101:15)
    at StorageService.initSync (/usr/lib/node_modules/homebridge/src/storageService.ts:10:15)
    at new BridgeService (/usr/lib/node_modules/homebridge/src/bridgeService.ts:130:25)
    at new Server (/usr/lib/node_modules/homebridge/src/server.ts:119:26)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:79:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
```

**Homebridge Config:**
Well... I guess that's gone...

**Environment:**

* **Node.js Version**: v15.14.0
* **NPM Version**: 7.8.0
* **Homebridge Version**: 1.3.4
* **Operating System**: Arch Linux
* **Process Supervisor**:  other / none

**Comment by oznu** [comment]
I've created an install guide for arch linux. Using `hb-service` the config.json will automatically be created.

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Arch-Linux
