### ISSUE TITLE
Homebridge devices not reachable 

### ISSUE THREAD

**Issue by wou5er** [homebridge/homebridge#2902]
*Problem*
Homebridge cannot show devices in Google Home... Google home assistant cannot control devices anymore

*What causes the problem*
This happened after updating the User Interface of Homebridge and de eDomoticz plugin.

*LOG*

```
Starting to advertise 'Homebridge 0A78 1C36' using bonjour-hap backend!
[4/15/2021, 19:54:33] Homebridge v1.3.4 (Homebridge 0A78) is running on port 51713.
(node:6177) UnhandledPromiseRejectionWarning: Error: Cannot find module 'bonjour'
Require stack:
- /usr/lib/node_modules/homebridge-gsh/node_modules/hap-node-client/HAPNodeJSClient.js
- /usr/lib/node_modules/homebridge-gsh/dist/hap.js
- /usr/lib/node_modules/homebridge-gsh/dist/main.js
- /usr/lib/node_modules/homebridge-gsh/dist/platform.js
- /usr/lib/node_modules/homebridge-gsh/dist/index.js
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-gsh/node_modules/hap-node-client/HAPNodeJSClient.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
(node:6177) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6177) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.



```

What to do to solve this?

**Comment by vespino** [comment]
Same here with Google Home plugin 2.10, so I reverted to an older version and everything is working again.
