### ISSUE TITLE
Looping Crash with yallist.js in HAP-NodeJS

### ISSUE THREAD

**Issue by nickv2002** [homebridge/homebridge#2905]
**Describe The Bug:**

Homebridge is caught in a restart loop during startup. It starts up get's to the point below, crashes and then repeats:

```
[17/04/2021, 22:14:41] [HB Supervisor] Started Homebridge v1.3.4 with PID: 4395
Initializing HAP-NodeJS v0.9.4...
Initializing HAP-NodeJS v0.9.4...
/usr/local/lib/node_modules/homebridge/node_modules/yallist/yallist.js:174
  if (i === n &&walker !== null( {
                

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/lru-cache/index.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

**To Reproduce:**
Happens automatically when starting Homebridge.
I tried disabling all but the HomeBridge UI plugin but still had the same problem. Also, FWIW problem was happening on earlier versions of the OS/Homebridge/Plugins (~ 3 months old config) so I updated everything but still have the same problems.

**Expected behavior:**
Start homebrdige.

**Logs:**
see above

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge 9B82",
        "username": "12:12:12:12:12:12",
        "port": 51828,
        "pin": "123-12-123"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "email": "user@host.com",
            "password": "password",
            "platform": "myQ"
        },
        {
            "name": "deCONZ",
            "anyOn": true,
            "hosts": [
                "localhost:80"
            ],
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "platform": "Hue",
            "sensors": true,
            "excludeSensorTypes": [
                "Daylight"
            ],
            "users": {
                "asdf": "asdf"
            }
        },
        {
            "name": "Harmony",
            "hubIP": "10.0.1.33",
            "hubName": "Harmony Hub",
            "TVAccessory": true,
            "mainActivity": "Watch Apple TV",
            "activitiesToPublishAsInputForTVMode": [
                "Watch Apple TV",
                "Watch OSMC Rasberry Pi",
                "Watch a Disc"
            ],
            "linkVolumeControlToTV": true,
            "platform": "HarmonyHubWebSocket"
        }
    ]
}
```

**Screenshots:**

**Environment:**
Defaults from Rpi image:
OS: Raspbian GNU/Linux Buster (10)
Hostname: homebridge
NodeJS Version: v14.16.1
Npm Version: v6.14.12
User: pi
Storage Path: /var/lib/homebridge
Config Path: /var/lib/homebridge/config.json
Service Mode: Yes

**Comment by oznu** [comment]
Uninstall re-install homebridge.

```
npm uninstall -g homebridge
npm install -g --unsafe-perm homebridge
```

**Comment by nickv2002** [comment]
Uninstall/re-install homebridge kinda worked. My Harmony and myQ connections came back but my Hue connection to deCONZ is broken now. I think I'll have to reinstall that software to get it set up again. Thanks for the support
