### ISSUE TITLE
Error shutting down Homebridge

### ISSUE THREAD

**Issue by dcaccount** [homebridge/homebridge#2910]
Hello,
I have restarted Homebridge and I have got following error.

> [23/4/2021, 12:12:09] Got SIGTERM, shutting down Homebridge...
[23/4/2021, 12:12:09] TypeError: Cannot read property 'forEach' of undefined
    at HAPNodeJSClient._reconnectServer (/usr/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:301:39)
    at EventEmitter.emit (events.js:315:20)
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/eventedHttpClient.js:90:24)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

It seems to have restated correctly but I would like to understand if this might be an issue and how to correct it.

Thanks,
Dan

**Environment:**

* **Node.js Version**: v14.16.1
* **NPM Version**: v6.14.12
* **Homebridge Version**: v.1.3.4
* **Operating System**: Raspbian
* **Process Supervisor**: Systemd

**Comment by oznu** [comment]
You can probably safely ignore this, if you find it's causing problems, the error is being thrown by the `homebridge-alexa` plugin.
