### ISSUE TITLE
EHOSTUNREACH

### ISSUE THREAD

**Issue by boudi22** [homebridge/homebridge#2959]
Hey I am new to home bridge. I have setup my devices and now this error keeps on popping up every 10 minutes. 

Error: send EHOSTUNREACH 224.0.0.251:5353
    at doSend (dgram.js:714:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:435:18)
    at afterDns (dgram.js:660:5)
    at processTicksAndRejections (internal/process/task_queues.js:83:21

**Comment by donavanbecker** [comment]
@boudi22 We need more info. Setup, more logs so we can see what's happening before and after those logs.
