### ISSUE TITLE
This plugin generated a warning from the characteristic

### ISSUE THREAD

**Issue by wdylag** [homebridge/homebridge#2964]
[20/08/2021, 11:23:17] [homebridge-airrohr] This plugin generated a warning from the characteristic 'PM2.5 Density': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[20/08/2021, 11:23:17] [homebridge-airrohr] Error: 
    at PM2_5Density.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at PM2_5Density.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at PM2_5Density.<anonymous> (/usr/local/lib/node_modules/homebridge-airrohr/index.js:188:32)
    at PM2_5Density.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at PM2_5Density.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)

**Comment by oznu** [comment]
See https://git.io/JtMGR

> These warnings / errors do not indicate a problem with Homebridge, but with offending plugin. Any issues should be directed to the plugin's project page, not the Homebridge project.
