### ISSUE TITLE
Issue after clean re install

### ISSUE THREAD

**Issue by pwascheul** [homebridge/homebridge#2968]
After some issues with my previous SD Card I made a Clean install (RPI Zero + home bridge 1.0.24 + node v14.17.4). 
After setting up the device to my network I can see this error popping up, looks like a version is not defined somewhere but wonder if anyone have any insight and tips to solve this shortly.

**Describe Your Problem:**

[**Logs:**]()
[29/08/2021, 11:05:05] [Homebridge UI] TypeError: Invalid Version: undefined
[29/08/2021, 11:05:06] [Homebridge UI] Caught Unhandled Rejection Error :: Details Below
TypeError: Invalid Version: undefined
    at new SemVer (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/semver.js:19:13)
    at compare (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/functions/compare.js:3:3)
    at Object.gt (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/functions/gt.js:2:29)
    at StatusService.checkHomebridgeStatus (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71495:54)
    at StatusService.getHomebridgeStats (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71491:32)
    at StatusService.watchStats (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71461:53)
    at StatusGateway.serverStatus (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71123:28)
    at /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/context/ws-context-creator.js:43:33
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at StatusGateway.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/context/ws-proxy.js:12:32)
    at WebSocketsController.pickResult (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/web-sockets-controller.js:86:24)

** config.json:**
{
    "bridge": {
        "name": "Homebridge 72BC",
        "username": "MACADDRESS",
        "port": 51789,
        "pin": "123-45-678",
        "bind": [
            "wlan0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
**Environment:**

* **Node.js Version**: 14.17.4
* **NPM Version**: 
* **Homebridge Version**: 1.3.4
* **Operating System**: homebridge rpi image

**Comment by bjacobel** [comment]
I have this issue as well, curious if you found a resolution @pwascheul?
