### ISSUE TITLE
Errors (homebridge stopped) after update to v1.3.5

### ISSUE THREAD

**Issue by drheck** [homebridge/homebridge#2986]
**Describe The Bug:**

After installing this version, homebridge stopped and restarts continously.
After going back to version 1.3.4 all works fine (line 900).

I see the following errors in the homebridge.log (see line 80 in the attached logfile).
Any idea?
Thanks,
Peter

[37m[10.10.2021, 09:08:12] [39m[36m[WeatherPlus][39m Adding station with weather service OpenWeatherMap named 'ORT-OW'
(node:2855) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token } in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.parseSourceMapInput (/usr/local/lib/node_modules/homebridge/node_modules/source-map/lib/util.js:433:15)
    at new SourceMapConsumer (/usr/local/lib/node_modules/homebridge/node_modules/source-map/lib/source-map-consumer.js:17:22)
    at mapSourcePosition (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:220:14)
    at wrapCallSite (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:397:20)
    at Function.prepareStackTrace (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:446:39)
    at maybeOverridePrepareStackTrace (internal/errors.js:90:29)
    at prepareStackTrace (internal/errors.js:69:5)
    at errorHandler (/usr/local/lib/node_modules/homebridge/src/cli.ts:96:15)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2855) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[37m[10.10.2021, 09:08:13] [39mInitializing platform accessory 'Phone: iPhone 0'...
[37m[10.10.2021, 09:08:13] [39mInitializing platform accessory 'DummyP1'...
[37m[10.10.2021, 09:08:13] [39m[31mSyntaxError: Unexpected token } in JSON at position 1[39m
[31m    at JSON.parse (<anonymous>)[39m
[31m    at Object.parseSourceMapInput (/usr/local/lib/node_modules/homebridge/node_modules/source-map/lib/util.js:433:15)[39m
[31m    at new SourceMapConsumer (/usr/local/lib/node_modules/homebridge/node_modules/source-map/lib/source-map-consumer.js:17:22)[39m
[31m    at mapSourcePosition (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:220:14)[39m
[31m    at wrapCallSite (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:397:20)[39m
[31m    at Function.prepareStackTrace (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:446:39)[39m
[31m    at maybeOverridePrepareStackTrace (internal/errors.js:90:29)[39m
[31m    at prepareStackTrace (internal/errors.js:69:5)[39m
[31m    at trackRejection (/usr/local/lib/node_modules/homebridge-zway-lopify/node_modules/q/q.js:1086:33)[39m
[31m    at reject (/usr/local/lib/node_modules/homebridge-zway-lopify/node_modules/q/q.js:1151:5)[39m
[31m    at _fulfilled (/usr/local/lib/node_modules/homebridge-zway-lopify/node_modules/q/q.js:856:20)[39m
[31m    at /usr/local/lib/node_modules/homebridge-zway-lopify/node_modules/q/q.js:883:30[39m
[31m    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/homebridge-zway-lopify/node_modules/q/q.js:816:13)[39m
[31m    at /usr/local/lib/node_modules/homebridge-zway-lopify/node_modules/q/q.js:624:44[39m
[31m    at runSingle (/usr/local/lib/node_modules/homebridge-zway-lopify/node_modules/q/q.js:137:13)[39m
[31m    at flush (/usr/local/lib/node_modules/homebridge-zway-lopify/node_modules/q/q.js:125:13)[39m
[37m[10.10.2021, 09:08:13] [39mGot SIGTERM, shutting down Homebridge...

**To Reproduce:**

**Expected behavior:**

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**:  v14.16.0
* **NPM Version**: v7.16.0
* **Homebridge Version**: 
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service
[homebridge.log](https://github.com/homebridge/homebridge/files/7317197/homebridge.log)

**Comment by drheck** [comment]
Hi Donavan,
yes. It seems, but disabling the plugin will remove alle devices and all automation rules from apple home.
I will test it with a homebridge-test and a disabled homebridge if i have time for this.
Peter

**Comment by drheck** [comment]
Hi all,
after unimstall and a new installation the error has gone?!
I close this issue.
Peter
