### ISSUE TITLE
 Failed to check for Node.js version updates

### ISSUE THREAD

**Issue by Tapsel99** [homebridge/homebridge#2991]
[10/12/2021, 11:47:01 PM] [HB Supervisor] Delaying Homebridge startup by 20 seconds on low powered server
[10/12/2021, 11:47:16 PM] [Homebridge UI] TypeError: Invalid Version: undefined
[10/12/2021, 11:47:16 PM] [Homebridge UI] Caught Unhandled Rejection Error :: Details Below
TypeError: Invalid Version: undefined
    at new SemVer (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/semver.js:19:13)
    at compare (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/functions/compare.js:3:3)
    at Object.gt (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/functions/gt.js:2:29)
    at StatusService.checkHomebridgeStatus (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71495:54)
    at StatusService.getHomebridgeStats (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71491:32)
    at StatusService.watchStats (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71461:53)
    at StatusGateway.serverStatus (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71123:28)
    at /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/context/ws-context-creator.js:43:33
    at process._tickCallback (internal/process/next_tick.js:68:7)
[10/12/2021, 11:47:30 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[10/12/2021, 11:47:30 PM] [HB Supervisor] Started Homebridge v1.3.5 with PID: 8552
[10/12/2021, 11:47:34 PM] [Homebridge UI] Failed to check for Node.js version updates - check your internet connection.
[10/12/2021, 11:47:35 PM] [Homebridge UI] [npm] Failed to check registry.npmjs.org for updates: "timeout of 5000ms exceeded" - see https://git.io/JJSz6 for help.
[10/12/2021, 11:47:35 PM] [Homebridge UI] [homebridge] Failed to check registry.npmjs.org for updates: "timeout of 5000ms exceeded" - see https://git.io/JJSz6 for help.
Initializing HAP-NodeJS v0.9.6...

**Comment by AlphaDE** [comment]
Same issue after update to 1.3.5

**Comment by PuzzledUser** [comment]
Me too
```
[09/11/2021, 09:20:17] [HB Supervisor] OS: Linux 5.4.79+ arm
[09/11/2021, 09:20:17] [HB Supervisor] Node.js v14.15.1 /usr/local/bin/node
[09/11/2021, 09:20:17] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[09/11/2021, 09:20:17] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[09/11/2021, 09:22:37] [HB Supervisor] OS: Linux 5.4.79+ arm
[09/11/2021, 09:22:37] [HB Supervisor] Node.js v14.15.1 /usr/local/bin/node
[09/11/2021, 09:22:37] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[09/11/2021, 09:22:37] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[09/11/2021, 09:23:47] [Homebridge UI] Homebridge Config UI X v4.41.2 is listening on :: port 8581
[09/11/2021, 09:23:56] [HB Supervisor] Delaying Homebridge startup by 20 seconds on low powered server
[09/11/2021, 09:24:09] [Homebridge UI] TypeError: Invalid Version: undefined
[09/11/2021, 09:24:09] [Homebridge UI] Caught Unhandled Rejection Error :: Details Below
TypeError: Invalid Version: undefined
    at new SemVer (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/semver.js:19:13)
    at compare (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/functions/compare.js:3:3)
    at Object.gt (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/functions/gt.js:2:29)
    at StatusService.checkHomebridgeStatus (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71495:54)
    at StatusService.getHomebridgeStats (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71491:32)
    at StatusService.watchStats (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71461:53)
    at StatusGateway.serverStatus (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71123:28)
    at /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/context/ws-context-creator.js:43:33
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at StatusGateway.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/context/ws-proxy.js:12:32)
    at WebSocketsController.pickResult (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/web-sockets-controller.js:86:24)
```

**Comment by marmitol** [comment]
Hi
Same mistake.
I have already updated the RPM and all the components. I have uninstalled Homebridge UI. And I have launched sudo npm install -g --unsafe-perm homebridge-config-ui-x
But the issue is not resolved.


[26/11/2021, 17:00:05] [Homebridge UI] TypeError: Invalid Version: undefined
[26/11/2021, 17:00:05] [Homebridge UI] Caught Unhandled Rejection Error :: Details Below
TypeError: Invalid Version: undefined
    at new SemVer (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/semver.js:19:13)
    at compare (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/functions/compare.js:3:3)
    at Object.gt (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/functions/gt.js:2:29)
    at StatusService.checkHomebridgeStatus (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71076:54)
    at StatusService.getHomebridgeStats (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71072:32)
    at StatusService.watchStats (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71042:53)
    at StatusGateway.serverStatus (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:70704:28)
    at /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/context/ws-context-creator.js:43:33
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at StatusGateway.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/context/ws-proxy.js:12:32)
    at WebSocketsController.pickResult (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/web-sockets-controller.js:86:24)

**Comment by PuzzledUser** [comment]
Just updated to v4.41.3. No change:

```
[26/11/2021, 16:21:51] [Homebridge UI] Homebridge Config UI X v4.41.3 is listening on :: port 8581
[26/11/2021, 16:21:55] [HB Supervisor] Delaying Homebridge startup by 20 seconds on low powered server
[26/11/2021, 16:21:59] [Homebridge UI] TypeError: Invalid Version: undefined
[26/11/2021, 16:21:59] [Homebridge UI] Caught Unhandled Rejection Error :: Details Below
TypeError: Invalid Version: undefined
    at new SemVer (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/classes/semver.js:19:13)
    at compare (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/functions/compare.js:3:3)
    at Object.gt (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/semver/functions/gt.js:2:29)
    at StatusService.checkHomebridgeStatus (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71076:54)
    at StatusService.getHomebridgeStats (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71072:32)
    at StatusService.watchStats (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:71042:53)
    at StatusGateway.serverStatus (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:70704:28)
    at /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/context/ws-context-creator.js:43:33
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at StatusGateway.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/context/ws-proxy.js:12:32)
    at WebSocketsController.pickResult (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/websockets/web-sockets-controller.js:86:24)
[26/11/2021, 16:22:15] [HB Supervisor] Starting Homebridge with extra flags: -I
[26/11/2021, 16:22:15] [HB Supervisor] Started Homebridge v1.3.8 with PID: 2508
```
