### ISSUE TITLE
Continual restarts and no device access

### ISSUE THREAD

**Issue by hepcat72** [homebridge/homebridge#2996]
**Describe The Bug:**

Homebridge never finishes starting up and pm2 keeps continually restarting it.  Not sure if this is due to the fs-extras dependency, but I created an issue ther: https://github.com/jprichardson/node-fs-extra/issues/926 as well.

**To Reproduce:**

I performed a series of updates (npm, node, & homebridge) to address an issue with the homebridge-chamberlain node (which was deprecated) and installed homebridge-myq, but it seems like the updates put me in a non-functional state.

For me, the issue can be reproduced by simply starting homebridge with `pm2 start homebridge`.

**Expected behavior:**

Homebridge starts and I can access my devices in the home app.

[**Logs:**]()

Error log is filled with:
```
TypeError: Cannot read property 'name' of undefined
    at exports.fromCallback (/usr/lib/node_modules/homebridge/node_modules/universalify/index.js:15:26)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/fs-extra/lib/fs/index.js:57:27)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/@pm2/io/src/metrics/httpMetrics.ts:190:35)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/fs-extra/lib/index.js:5:6)
```
The STDOUT log has this upon start and nothing else ever outputs, just this line every second:
```
Initializing HAP-NodeJS v0.9.6...
Initializing HAP-NodeJS v0.9.6...
Initializing HAP-NodeJS v0.9.6...
Initializing HAP-NodeJS v0.9.6...
Initializing HAP-NodeJS v0.9.6...
```
**Homebridge Config:**

I tried a sanity check with the simplest of configs and it still behaves the same way:

```json
{
  "bridge": {
        "name": "Homebridge",
        "username": "[REDACTED]",
        "manufacturer": "homebridge.io",
        "model": "homebridge",
        "port": [REDACTED],
        "pin": "[REDACTED]"
  },
  
  "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
  "ports": {
    "start": 52100,
    "end": 52150,
    "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
  },
  "accessories": [
  ],

  "platforms": [
  ]
}
```

**Screenshots:**

none applicable

**Environment:**

* **Node.js Version**: `v14.18.1`
* **NPM Version**: `8.1.0`
* **Homebridge Version**: `1.3.5`
* **Operating System**: Raspbian
* **Process Supervisor**: pm2

**Comment by hepcat72** [comment]
I'm guessing this is specific to `pm2`?  I was able to install the UI and reset everything using the hb-service instead of pm2.

A few notes... since it creates a new `homebridge` user all of my commands in the config that started with `~/` had to be edited.

After eliminating pm2, a plugin error popped up for my cec plugin.
