### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by bwp91** [homebridge/homebridge#3002]
**Describe The Bug:**

Using `hb-service` to update node to v16.13.0 fails at the rebuilding stage. See below logs. Error also presents itself when then restarting Homebridge each time, but doesn't actually seem to affect Homebridge functionality. Using the command to downgrade node back to 14.18.1 runs and rebuilds successfully, removing all errors.

**To Reproduce:**

Running in terminal:

```bash
sudo hb-service update-node 16.13.0
```

**Logs**

When running the command to update node:

```bash
pi@homebridge:~ $ sudo hb-service update-node 16.13.0
ℹ Installing Node.js v16.13.0 over v14.18.1...
ℹ Target: /usr/local
✔ Download complete.
✔ Installed Node.js v16.13.0
ℹ Rebuilding for Node.js v16.13.0...
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/agent.js:114:44)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:161:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/agent.js:114:44)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:161:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
Error: Command failed: npm rebuild --unsafe-perm
✖ ERROR: Failed Operation
ℹ Restarting Homebridge Service...
✔ Homebridge Restarted
pi@homebridge:~ $ 
```

From then restarting Homebridge each time:

```bash
[27/10/2021, 09:34:39] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[27/10/2021, 09:34:44] [HB Supervisor] Restarting Homebridge...
[27/10/2021, 09:34:44] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[27/10/2021, 09:34:45] [HB Supervisor] Started Homebridge v1.3.6-beta.1 with PID: 10554
Initializing HAP-NodeJS v0.9.6...
[27/10/2021, 09:34:46] Loaded config.json with 0 accessories and 8 platforms.
[27/10/2021, 09:34:46] Loaded 0 cached accessories from cachedAccessories.
[27/10/2021, 09:34:46] ---
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/agent.js:114:44)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:161:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
[27/10/2021, 09:34:47] Loaded plugin: homebridge-config-ui-x@4.41.3-test.2
[27/10/2021, 09:34:47] Registering platform 'homebridge-config-ui-x.config'
[27/10/2021, 09:34:47] ---
```

**Environment:**

* **Node.js Version**: 14.18.1 -> 16.13.0
* **NPM Version**: 6.14.15 -> 8.1.0
* **Homebridge Version**: 1.3.6-beta.1
* **Operating System**: Raspbian (HB Image)

**Comment by sw33tT** [comment]
Try install node with n (Node-Package-Manager)

-> sudo hb-service stop

-> sudo npm cache clean -f

-> sudo npm install -g n

-> sudo n lts

-> sudo reboot

new ssh connection to your homebridge

-> cd /usr/local/lib/node_modules/

-> sudo npm rebuild --unsafe-perm

This steps are working for me.

sudo hb-service update-node give me the same errors.

**Comment by SeydX** [comment]
Had the same problem, went back to Node v14.x, installed the latest NPM (v8) and then was able to successfully update Node via hb-service

**Comment by Damianod27** [comment]
I have the same problem.  Maybe it's a general error?

**Comment by bwp91** [comment]
Thanks to @sw33tT and @SeydX for your fixes. I will rewrite here what seems to be working for most users (seydx solution):

1. Downgrade node to 14.18.1
    ```
    sudo hb-service update-node 14.18.1
    ```
2. Update npm to the latest version 8
    ```
    sudo npm i -g npm
    ```
3. Update node to 16.13.0
    ```
    sudo hb-service update-node 16.13.0
    ```
4. Re-update npm to the latest version 8
    ```
    sudo npm i -g npm
    ```

**Comment by athal7** [comment]
I tried the seydx solution and had some new errors: 
![B94AD015-A740-4925-B6A6-04B69C08F0DA](https://user-images.githubusercontent.com/467872/139684306-d59c614f-5a50-48ad-ae3e-2af404fbc072.jpeg)
![FCD28760-2634-4C72-AA52-0F5E3EDDEED4](https://user-images.githubusercontent.com/467872/139684309-5e92309e-63ac-43e0-8dc1-722ae8389811.png)

this is on raspberry pi zero w

**Comment by athal7** [comment]
![0D7CFD4C-2110-4B90-BCAF-BAC85535DBDC](https://user-images.githubusercontent.com/467872/139684582-7e3c1498-773e-4588-974b-60e2fa23944c.jpeg)

**Comment by bwp91** [comment]
> I tried the seydx solution and had some new errors: ![B94AD015-A740-4925-B6A6-04B69C08F0DA](https://user-images.githubusercontent.com/467872/139684306-d59c614f-5a50-48ad-ae3e-2af404fbc072.jpeg)
> 
> this is on raspberry pi zero w

Looks like npm isn’t installed at all?
What’s the output if you run `sudo hb-service update-node 14.18.1`?

**Comment by athal7** [comment]
@bwp91 yea it’s super weird. I went back to 14.18.1 successfully and still have that npm not found error but the service is running successfully 🤔

the armv6 error I posted in the second comment was just on node 16

**Comment by bubffm** [comment]
Try to run the commnd from core directory, not the homebridge sub directory.

**Comment by athal7** [comment]
As in npm or the update command? Somehow the npm command is available again after trying and rolling back the update another time

**Comment by bubffm** [comment]
you have run the sudo commands from 
pi@homebridge: /var/lib/homebridge

IT should be run from:
pi@homebridge:     

i.e. not in some sub-directory. You might have installed twice now...

**Comment by athal7** [comment]
Got it. I’ll try that thanks!

**Comment by christiantschoerner** [comment]
> Thanks to @sw33tT and @SeydX for your fixes. I will rewrite here what seems to be working for most users (seydx solution):
> 
> 1. Downgrade node to 14.18.1
>    ```
>    sudo hb-service update-node 14.18.1
>    ```
> 2. Update npm to the latest version 8
>    ```
>    sudo npm i -g npm
>    ```
> 3. Update node to 16.13.0
>    ```
>    sudo hb-service update-node 16.13.0
>    ```
> 4. Re-update npm to the latest version 8
>    ```
>    sudo npm i -g npm
>    ```

Had the same error. This worked for me thanks!

**Comment by bwp91** [comment]
@christiantschoerner you should avoid using odd (as opposed to even) version numbers off node as they aren’t supported by homebridge. doesn’t mean it won’t work… but it’s not recommended

**Comment by NorthernMan54** [comment]
Pinned this for easy reference

**Comment by pietje63** [comment]
I followed the steps as described by @christiantschoerner (go to main directory, downgrade node, update npm, update node, update npm) but remain getting the error. More and more plugins require a node update..

[quote]

#
# Fatal error in , line 0
# 

#
# Fatal error in , line 0
# Liftoff bailout should not happen. Cause: Armv6 not supported

#
#
#
#FailureMessage Object: 0xb61fdf70
[/quote]

Any more ideas?

**Comment by christiantschoerner** [comment]
> I followed the steps as described by @christiantschoerner (go to main directory, downgrade node, update npm, update node, update npm) but remain getting the error. More and more plugins require a node update..
> 
> ```
> #
> # Fatal error in , line 0
> # 
> 
> #
> # Fatal error in , line 0
> # Liftoff bailout should not happen. Cause: Armv6 not supported
> 
> #
> #
> #
> #FailureMessage Object: 0xb61fdf70
> ```
> 
> Any more ideas?

Old Raspberry Pi?

**Comment by pietje63** [comment]
It is a Pi Zero. Not the newest.

**Comment by mpagz** [comment]
> Thanks to @sw33tT and @seydx for your fixes. I will rewrite here what seems to be working for most users (seydx solution):
> 
> 1. Downgrade node to 14.18.1
>    ```
>    sudo hb-service update-node 14.18.1
>    ```
> 2. Update npm to the latest version 8
>    ```
>    sudo npm i -g npm
>    ```
> 3. Update node to 16.13.0
>    ```
>    sudo hb-service update-node 16.13.0
>    ```
> 4. Re-update npm to the latest version 8
>    ```
>    sudo npm i -g npm
>    ```

This worked for me! Thanks!

**Comment by bjornand1** [comment]
Hi, I have been reading this thread with great interest since upgrading my Homebridge install from 1.3.5 to 1.3.6 messed up everything. I see this is mostly about Pi, I run Homebridge in Docker on a Synology - does that make any difference? Would these steps by @seydx work for me?

Really afraid of messing up again, it took hours to reconstruct everything!

**Comment by cleversmart** [comment]
Hi, I have the same problem, but I don't know which version was the privious version of node.js. How can I find the privious version on my pi?

**Comment by n-mcnulty** [comment]
I don’t know which stable version of node you had but if you type:

`sudo hb-service update-node 14.18.1 `

that will downgrade you to a working version (at least for most people)

**Comment by macjeff** [comment]
This works great and I am running fine but wanted to ask this question.

This command (just tried again) sudo npm i -g npm brings me to 8.1.4 and I see an 8.3.0 version of NPM.  Why wont it update NPM to the true latest?

I could reinstall NPM and get the latest but wanted to ask first.

Not sure if it makes any difference but on older mac and putting command in terminal.  Running Homebridge UI and just updated today to latest.

**Comment by macjeff** [comment]
> This works great and I am running fine but wanted to ask this question.
> 
> This command (just tried again) sudo npm i -g npm brings me to 8.1.4 and I see an 8.3.0 version of NPM. Why wont it update NPM to the true latest?
> 
> I could reinstall NPM and get the latest but wanted to ask first.
> 
> Not sure if it makes any difference but on older mac and putting command in terminal. Running Homebridge UI and just updated today to latest.

Responding to my own post.  LOL.  Anyways even after restarting homebridge, the NPM was reporting as older version but I did an NPM -V and found it is 8.3.0.  So I rebooted the mac and now its showing.  So maybe the NPM updates require a full reboot of the machine when running old mac?

**Comment by bwp91** [comment]
Closing this issue now as I believe homebridge-config-ui-x has been updated to resolve this error.

And the solution for any future user who experiences this issue can be seen in this comment:
https://github.com/homebridge/homebridge/issues/3002#issuecomment-955994607

Thanks!

**Comment by GitHubGoody** [comment]
@mpagz @sw33tT @seydx When you all run these commands, are you entering them from the terminal in Homebridge or via ssh? I tried the steps exactly as provided by @mpagz, but still cannot update the Homebridge UI.

**Comment by n-mcnulty** [comment]
> @mpagz @sw33tT @seydx When you all run these commands, are you entering them from the terminal in Homebridge or via ssh? I tried the steps exactly as provided by @mpagz via the Homebridge terminal (in the default /var/lib/homebridge directory), but still cannot update the Homebridge UI.

To answer your question this the commands could be run by ssh or the homebridge ui terminal window. 

Not entirely sure what you mean in the rest of your question. This thread is about an issue which is unrelated to homebridge UI.. 

This issue was as a result of trying to update Node to v 16. It would not work.

May I first ask if your using the plugin homebridge-nest? 

If you are saying that if after stopping homebridge you still cannot rollback to node 14 then let us know.

**Comment by gh0sti** [comment]
so downgrading nodejs to 14 updated the homebridge UI to 1.4. Should I stay on nodejs 14 or can I go back up to 16?

**Comment by n-mcnulty** [comment]
if it’s working at the moment leave it. There is a known bug that there may be a potential workaround for, but unless a plugin / homebridge itself suddenly stops working then stay on node 14.

**Comment by nrngooooo** [comment]
![global state management redux](https://github.com/user-attachments/assets/0c378b9c-2853-4a39-903a-4bf02d21b761)
