### ISSUE TITLE
Homebridge not updating to 1.3.6

### ISSUE THREAD

**Issue by mpagz** [homebridge/homebridge#3010]
USER: pi
DIR: /usr/local
CMD: sudo -E -n npm install -g homebridge@1.3.6

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/agent.js:114:44)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:161:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

Command failed. Please review log for details.

**Comment by bwp91** [comment]
See these steps:

https://github.com/homebridge/homebridge/issues/3002#issuecomment-955994607

Then try updating homebridge again

**Comment by sogarthm** [comment]
For what it’s worth, this doesn’t work on Alpine images, as those aren’t set up to support running hb-service. 😅

```
/homebridge # hb-service update-node 14.18.1
ℹ Installing Node.js v14.18.1 over v16.13.0...
✖ Updating Node.js on Alpine Linux / Docker is not supported by this command.
✖ To update Node.js you should pull down the latest version of the oznu/homebridge Docker image.
```
