### ISSUE TITLE
Control Daikin Perfera with homebridge. 

### ISSUE THREAD

**Issue by davideser** [homebridge/homebridge#3015]
### Current Situation

Hi good Sunday at everybody, The configuration for my home is with Raspberry pi with Homebridge, I used homebridge for connect, Btcino living now, some Tuya devices and LG Tv's, Now I can't connect my Daikin air conditioning with Homekit or Homebridge. I can only control them via their official app. I preferred to connect them to homekit to have everything in one app.

My is Daikin Condizionatore 2 x FTXM25R 2MXM40N Dual Split Perfera Gas R-32 Bluevolution 9+9 WiFi .

Thanks for any reply.

### Logs

```markdown
[21/11/2021, 13:43:18] [Daikin Livingroom] _doSendGetRequest: ERROR: API request to http://192.168.1.4/aircon/get_control_info returned error Error: Not Found
    at Request.callback (/usr/lib/node_modules/homebridge-daikin-local/node_modules/superagent/src/node/index.js:879:15)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-daikin-local/node_modules/superagent/src/node/index.js:1130:18)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  status: 404,
  response: [Response],
  retries: 0
```

### Configuration

```json
{
    "platforms": [
        {
            "platform": "MyHome Gateway",
            "ipaddress": "192.168.X.X",
            "password": "12345",
            "discovery": false,
            "devices": []
        },
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "options": {
                "username": "MYEMAIL",
                "password": "MYPASS",
                "accessId": "ID",
                "accessKey": "KEY",
                "lang": "en",
                "projectType": "2",
                "appSchema": "tuyaSmart",
                "countryCode": 39,
                "debug": false
            },
            "name": "TuyaPlatform",
            "_bridge": {
                "username": "USERNAME",
                "port": 55149
            },
            "platform": "TuyaPlatform"
        },
        {
            "devices": [
                {
                    "name": "LG TV SALONE",
                    "host": "IP",
                    "mac": "MAC",
                    "refreshInterval": 2500,
                    "disableLogInfo": false,
                    "switchInfoMenu": false,
                    "getInputsFromDevice": false,
                    "filterSystemApps": false,
                    "pictureModeControl": false,
                    "brightnessControl": false,
                    "backlightControl": false,
                    "contrastControl": false,
                    "colorControl": false
                },
                {
                    "name": "LG TV CAMERA DA LETTO",
                    "host": "",
                    "mac": "",
                    "refreshInterval": 2500,
                    "disableLogInfo": false,
                    "switchInfoMenu": false,
                    "getInputsFromDevice": false,
                    "filterSystemApps": false,
                    "pictureModeControl": false,
                    "brightnessControl": false,
                    "backlightControl": false,
                    "contrastControl": false,
                    "colorControl": false
                }
            ],
            "_bridge": {
                "username": "USERNAME",
                "port": 54103
            },
            "platform": "LgWebOsTv"
        },
        {
            "name": "Alexa",
            "username": "MYUSERNAME",
            "password": "MYPASSWORD",
            "pin": "342-52-220",
            "routines": false,
            "blind": false,
            "door": false,
            "debug": false,
            "deviceListHandling": "allow",
            "platform": "Alexa",
            "_bridge": {
                "username": "USERNAME",
                "port": 52369
            }
        }
    ],
    "bridge": {
        "username": "MYUSERNAME",
        "name": "MyHome HomeBridge Adapter",
        "pin": "342-52-220",
        "port": 51826
    },
    "description": "My Fantastic Legrand MyHome System",
    "accessories": [
        {
            "name": "Daikin Livingroom",
            "apiroute": "http://192.168.1.4",
            "temperature_unit": "C",
            "uuid": "MYUUID",
            "system": "Default",
            "swingMode": "1",
            "disableFan": false,
            "fanMode": "FAN",
            "fanPowerMode": "FAN only",
            "fanName": "Livingroom FAN",
            "defaultMode": "0",
            "response": 2000,
            "deadline": 60000,
            "retries": 5,
            "accessory": "Daikin-Local"
        }
    ],
    "disabledPlugins": [
        "homebridge-daikin-local"
    ]
```

### Environment

- OS: Raspberry Pi
- Software: Homebridge UI , Homebridge Alexa , Homebridge Daikin Local , LG webOS TV , Homebridge Tuya Platform , Homebridge Myhome Tng
- Node: v16.13.0 
- npm: 8.1.4

### Process Supervisor

systemd

PS: If you get any advice, they are welcome thanks again

**Comment by NorthernMan54** [comment]
A couple of comments

1 - opening the issue against the plugin rather than homebridge is more likely to get the plugin developers attention.  Please close this and open an issue against the plugin itself.

2 - looking at the error message, it shows an issue connecting to something at 192.168.1.4
  Is that the correct IP and is it powered on?

**Comment by davideser** [comment]
Sorry for category.

yes Is correct IP address!

**Comment by NorthernMan54** [comment]
Closing this
