### ISSUE TITLE
Install on mac mini M1 - error messages - looking for confirmation on my actions 

### ISSUE THREAD

**Issue by TCMITS-12866** [homebridge/homebridge#3027]
### Current Situation

I'm installing Homebridge for the first time on mac mini (with M1 chip). 
Installed node.js without an issue.
Ran the install script for homebridge and got some warning messages: 

npm WARN deprecated class-transformer@0.3.2: This release contains a breaking change from 0.3.1 but otherwise functions properly. Please read the changelog on Github to learn more.
...
5 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

...

I ran "npn audit fix --force"  ... but I think that didn't work

### Logs

```markdown
npm WARN deprecated class-transformer@0.3.2: This release contains a breaking change from 0.3.1 but otherwise functions properly. Please read the changelog on Github to learn more.

added 434 packages, and audited 435 packages in 4m

68 packages are looking for funding
  run `npm fund` for details

5 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice 
npm notice New minor version of npm available! 8.1.0 -> 8.2.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.2.0
npm notice Run npm install -g npm@8.2.0 to update!
npm notice 
------------------
and here's the log after trying to do the "npm audit fix --force":

0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'audit',
0 verbose cli   'fix',
0 verbose cli   '--force'
0 verbose cli ]
1 info using npm@8.1.0
2 info using node@v16.13.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 0ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 0ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/stephenfox/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 4ms
18 timing npm:load:configload Completed in 5ms
19 timing npm:load:setTitle Completed in 5ms
20 timing npm:load:setupLog Completed in 0ms
21 timing config:load:flatten Completed in 1ms
22 timing npm:load:cleanupLog Completed in 1ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 warn using --force Recommended protections disabled.
26 timing npm:load Completed in 13ms
27 timing arborist:ctor Completed in 0ms
28 timing command:audit Completed in 3ms
29 verbose stack Error: loadVirtual requires existing shrinkwrap file
29 verbose stack     at Arborist.loadVirtual (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:62:18)
29 verbose stack     at async Arborist.audit (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/audit.js:25:18)
29 verbose stack     at async Audit.audit (/usr/local/lib/node_modules/npm/lib/audit.js:66:5)
30 verbose cwd /Users/stephenfox
31 verbose Darwin 21.1.0
32 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "audit" "fix" "--force"
33 verbose node v16.13.0
34 verbose npm  v8.1.0
35 error code ENOLOCK
36 error audit This command requires an existing lockfile.
37 error audit Try creating one first with: npm i --package-lock-only
38 error audit Original error: loadVirtual requires existing shrinkwrap file
39 verbose exit 1
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge 7E24",
        "username": "0E:A5:8C:B3:7E:24",
        "port": 51868,
        "pin": "191-69-099"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

### Environment

- OS: 12.0.1
- Software: Homebridge 1.3.8
- Node: v16.13.0
- npm: 8.1.0

### Process Supervisor

hb-service

### Additional Context

I think Homebridge is working ... submitting this as I'm installing ...

**Comment by donavanbecker** [comment]
@TCMITS-12866 This is only a warning

**Comment by TCMITS-12866** [comment]
Thank you Donavan - my system is working well; thank you for confirmation that this was just a warning.
