### ISSUE TITLE
Homebridge 1.3.8 will not connect to anything and shows wrong time and date in logs.

### ISSUE THREAD

**Issue by ShaunRoberts543** [homebridge/homebridge#3030]
### Current Situation

I upgraded to 1.3.8 and everything was fine.  Then all of a sudden my system went down.  I did the usual reboot, and physical restart, disconnect/reconnect, etc to no avail.  Then I noticed in the logs that it is showing a date of 8/12/21 and the wrong time also.  None of my plug-ins will connect.  I will put a snapshot of some red-lines in my log, but the entire string seems to be forever long and I do not know what to even grab and post.

### Logs

```markdown
Error: getaddrinfo ENOTFOUND accounts.google.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'accounts.google.com',
  config: {
    url: 'https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&login_hint=.com',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Sec-Fetch-Mode': 'cors',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36',
      'X-Requested-With': 'XmlHttpRequest',
      Referer: 'https://accounts.google.com/o/oauth2/iframe',
      cookie: '__Secure-
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 40000,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: destroyOnTimeout]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&login_hint=AJDLj6LQu-
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'accounts.google.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/o/oauth2/iframerpc',
      search: '?action=
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /o/ 
plain, */*\r\n' +
        'Sec-Fetch-Mode: cors\r\n' +
        'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36\r\n' +
        'X-Requested-With: XmlHttpRequest\r\n' +
        'Referer: https://accounts.google.com/o/oauth2/iframe\r\n' +
        'cookie: __Secure-3PSID=AAiAkGzuvJxbay6lk6T4A.; __Secure-3PAPISID=YH5HqXswMh0um1Be/A5p6CO23QlaihhREh; NID \r\n' +
        'Host: accounts.google.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&login_hint=AJDLj6LQu-.nest.com',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'accounts.google.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token%20id%2F%2Fhome.nest.com',
    _timeout: null,
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON],
  status: undefined
}
[08/12/2021, 22:03:07] [Nest] Access token acquisition via googleAuth failed (code ENOTFOUND).
[08/12/2021, 22:03:07] [Nest] Retrying in 15 second(s).
[08/12/2021, 22:03:07] [Meross] Unable to reach Meross, retrying in 30 seconds [login() - ENOTFOUND].
[08/12/2021, 22:03:13] [Ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  getaddrinfo ENOTFOUND oauth.ring.com.  Trying again in 5 seconds...
[08/12/2021, 22:03:24] [Ring] Failed to reach Ring server at https://oauth.ring.com/oauth/token.  getaddrinfo ENOTFOUND oauth.ring.com.  Trying again in 5 seconds...
Error: getaddrinfo ENOTFOUND accounts.google.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'accounts.google.com',
  config: {
    url: 'https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&login_hint=AJDLj6LQu- %2Fhome.nest.com',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Sec-Fetch-Mode': 'cors',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36',
      'X-Requested-With': 'XmlHttpRequest',
      Referer: 'https://accounts.google.com/o/oauth2/iframe',
      cookie: '__Secure-3PSID=AAiAkRIVPszrMkCxoUGfEMqXWyfzbNDvqgmkRJFezK0q2votrjBPPTGzuvJxbay6lk6T4A.; __Secure-3PSIDCC=AJi4QfFu1EQ4CIADKdCzrmbrf6QlQkgDTM8kx4K4gJhw441VqQaPDfdSY1m27cemk9lc7xmfJA'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 40000,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: destroyOnTimeout]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&login_hint=AJDLj6LQu- %2Fhome.nest.com',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'accounts.google.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/o/oauth2/iframerpc',
```

### Configuration

```json
{
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "green",
            "tempUnits": "f",
            "lang": "auto",
            "proxyHost": "homebridge.local",
            "platform": "config"
        },
        {
            "name": "Nest",
            "platform": "Nest",
            "options": [
                "Thermostat.Fan.Disable",
                "Thermostat.Eco.Disable",
                "HomeAway.Disable",
                "Protect.MotionSensor.Disable"
            ],
            "googleAuth": {
                "cookies": "",
                "apiKey": "",
                "issueToken": ""
            }
        },
        {
            "buslog": "monitor",
            "servers": [
                {
                    "switches": [
                        {
                            "pico": [
                                4
                            ],
                            "name": "Garage Entry Pico 4 4B",
                            "type": "PJ2-4B-XXX-L31"
                        },
                        {
                            "pico": [
                                5
                            ],
                            "name": "Master Bedroom Pico 5 2B",
                            "type": "PJ2-2B"
                        },
                        {
                            "pico": [
                                6
                            ],
                            "name": "Master Bedroom Pico 6 2B",
                            "type": "PJ2-2B"
                        },
                        {
                            "pico": [
                                7
                            ],
                            "name": "Audio Pico 7",
                            "type": "PJ2-3BRL"
                        },
                        {
                            "pico": [
                                8
                            ],
                            "name": "Audio Pico 8",
                            "type": "PJ2-3BRL"
                        },
                        {
                            "pico": [
                                9
                            ],
                            "name": "Office Pico 9 4B",
                            "type": "PJ2-4B-XXX-L31"
                        },
                        {
                            "pico": [
                                10
                            ],
                            "name": "Office Pico 10 2B",
                            "type": "PJ2-2B"
                        },
                        {
                            "pico": [
                                12
                            ],
                            "name": "Sam's Bedroom Pico 12 4B",
                            "type": "PJ2-4B-XXX-L31"
                        },
                        {
                            "pico": [
                                13
                            ],
                            "name": "Family Room Pico 13 4B",
                            "type": "PJ2-4B-XXX-L31"
                        },
                        {
                            "pico": [
                                14
                            ],
                            "name": "Basement Pico 14 4B",
                            "type": "PJ2-4B-XXX-L31"
                        },
                        {
                            "pico": [
                                15
                            ],
                            "name": "Basement Pico 15 2B",
                            "type": "PJ2-2B"
                        },
                        {
                            "pico": [
                                17
                            ],
                            "name": "Dining room Pico 17 2B",
                            "type": "PJ2-2B"
                        },
                        {
                            "pico": [
                                18
                            ],
                            "name": "Dining Room Pico 18 2B",
                            "type": "PJ2-2B"
                        },
                        {
                            "pico": [
                                19
                            ],
                            "name": "Playroom Pico 19 2B",
                            "type": "PJ2-2B"
                        },
                        {
                            "pico": [
                                20
                            ],
                            "name": "Pergola Pico 20 4B",
                            "type": "PJ2-4B-XXX-L31"
                        },
                        {
                            "pico": [
                                22
                            ],
                            "name": "Garage Pico 22 B4B",
                            "type": "PJ2-4B-XXX-L31"
                        },
                        {
                            "pico": [
                                23
                            ],
                            "name": "Garage Pico 23 B4B",
                            "type": "PJ2-4B-XXX-L31"
                        },
                        {
                            "pico": [
                                24
                            ],
                            "name": "Kitchen Pico 24 2B",
                            "type": "PJ2-2B"
                        },
                        {
                            "pico": [
                                25
                            ],
                            "name": "Open Pico 25 2B",
                            "type": "PJ2-2B"
                        },
                        {
                            "pico": [
                                26
                            ],
                            "name": "Basement Pico 26 4B",
                            "type": "PJ2-4B-XXX-L31"
                        },
                        {
                            "pico": [
                                27
                            ],
                            "name": "Office Fan Pico 27 5B",
                            "type": "PJ2-3BRL"
                        },
                        {
                            "pico": [
                                28
                            ],
                            "name": "Pico 28 3B",
                            "type": "PJ2-3B"
                        },
                        {
                            "pico": [
                                29
                            ],
                            "name": "Pico 29 3B",
                            "type": "PJ2-3B"
                        },
                        {
                            "pico": [
                                30
                            ],
                            "name": "Pico 30 3B",
                            "type": "PJ2-3B"
                        },
                        {
                            "pico": [
                                32
                            ],
                            "name": "Pico 32 3B",
                            "type": "PJ2-3B"
                        },
                        {
                            "pico": [
                                33
                            ],
                            "name": "Pico 33 3B",
                            "type": "PJ2-3B"
                        }
                    ],
                    "host": "192.168.4.143",
                    "port": 23
                }
            ],
            "longname": true,
            "platform": "Pico"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": @gmail.com",
                "password": "R",
                "countryCode": "1",
                "platform": "tuya",
                "pollingInterval": 600
            },
            "scenes": true,
            "platform": "TuyaWebPlatform"
        },
        {
            "password": "",
            "platform": "Meross",
            "username": "@gmail.com",
            "name": "Meross",
            "ignoreHKNative": false,
            "disableDeviceLogging": true,
            "cloudRefreshRate": 400
        },
        {
            "refreshToken": "",
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "sendCameraMotionNotificationsToTv": true,
            "sendDoorbellMotionNotificationsToTv": true,
            "platform": "Ring"
        },
        {
            "name": "Govee",
            "username": "",
            "password": "",
            "apiKey": "",
            "debug": true,
            "lightDevices": [
                {
                    "label": "Desk 2",
                    "deviceId": "0F:79:D4:AD:FC:01:34:29",
                    "scene": "MwUEEAAAAAAAAAAAAAAAAAAAACI=,qgUBAAAAAAAAAAAAAAAAAAAAAK4=||ptReal||",
                    "musicMode": "MwUTBWMAAAAAAAAAAAAAAAAAAEM=||ptReal||"
                }
            ],
            "platform": "Govee"
        },
        {
            "platform": "WLED",
            "wleds": [
                {
                    "name": "Christmas WLED",
                    "host": "192.168.4.255",
                    "log": true,
                    "effects": [
                        "Bouncing Balls",
                        "Bpm"
                    ]
                }
            ]
        }
    ],
    "disabledPlugins": [
        "homebridge-denon-tv",
        "homebridge-weather-plus",
        "homebridge-hue",
        "homebridge-broadlink-easy",
        "homebridge-tuya-platform"
    ],
    "bridge": {
        "username": "",
        "pin": "",
        "name": "Homebridge 2472",
        "port": 51804
    },
    "accessories": [
        {
            "name": "Fake Garage Switch",
            "stateful": true,
            "reverse": false,
            "time": 1000,
            "resettable": false,
            "accessory": "DummySwitch"
        }
    ]
}
```

### Environment

- OS: Raspbian GNU/Linux Buster (10)
- Software:  Homebridge 1.3.8
- Node: 14.18.1
- npm: 8.1.0

### Process Supervisor

hb-service

### Additional Context

![Plug-Ins](https://user-images.githubusercontent.com/84977157/145338306-1e0f2c03-70b9-4680-9567-109f46b7eea9.png)
![Log](https://user-images.githubusercontent.com/84977157/145338318-80fc46cd-847f-4dc3-bbda-e1492f5ac19b.png)

**Comment by oznu** [comment]
Your device is not able to connect to the internet, this is why it can't set the time correctly and plugins can't access web services.

Check your router is not blocking access to the internet - especially if you have an Eero.
