### ISSUE TITLE
Homebridge not communicating with home app since Mac OS restore

### ISSUE THREAD

**Issue by semnol78** [homebridge/homebridge#3033]
### Current Situation

I had to erase my iMac HD and completely restore my Mac OS and files from backup. My homebridge was not accessible via web browser so I uninstalled and reinstalled homebridge. I can now open homebridge in Safari. I can now see my Habitat accessories in homebridge and control them via the accessories tab in homebridge but the Apple Home app does not see them. Plus I have a error in my logs. I seem to have a duplicate service running perhaps from the original install. 
Ignore the Wink3 log notes as I disabled and no longer use. Same with the OMNI plug in. I don't believe I need it either.

### Logs

```markdown
[12/10/2021, 5:23:28 PM] Error: listen EADDRINUSE: address already in use :::51674
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:316:21)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1252:18)
    at BridgeService.publishBridge (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:215:17)
    at Server.publishBridge (/usr/local/lib/node_modules/homebridge/src/server.ts:186:24)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:177:24
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:176:5)
[12/10/2021, 5:23:28 PM] Got SIGTERM, shutting down Homebridge...
[12/10/2021, 5:23:28 PM] [Omni] TCP Connection: Closed
[12/10/2021, 5:23:29 PM] [Hubitat-v2] Temperature Unit is Now: (F)
[12/10/2021, 5:23:29 PM] [Hubitat-v2] Updating Global Values | HubIP: 192.168.1.84 | UsingCloud: false
[12/10/2021, 5:23:29 PM] [Hubitat-v2] Devices to Remove: (0) 
[12/10/2021, 5:23:29 PM] [Hubitat-v2] Devices to Update: (63)
[12/10/2021, 5:23:29 PM] [Hubitat-v2] Devices to Create: (0) 
[12/10/2021, 5:23:29 PM] [Hubitat-v2] Total Initialization Time: (0 seconds)
[12/10/2021, 5:23:29 PM] [Hubitat-v2] Unknown Capabilities: ["Initialize"]
[12/10/2021, 5:23:29 PM] [Hubitat-v2] Hubitat DeviceCache Size: (63)
[12/10/2021, 5:23:29 PM] [Hubitat-v2] WebServer Initiated...
[12/10/2021, 5:23:29 PM] [Hubitat-v2] Sending StartDirect Request to Hubitat | UsingCloud: (false)
[12/10/2021, 5:23:29 PM] [Hubitat-v2] Direct Connect Active | Listening at 192.168.1.77:8001
[12/10/2021, 5:23:29 PM] [Hubitat-v2] Hubitat-v2 Hub Communication Established
[12/10/2021, 5:23:30 PM] [Hubitat-v2] INFO: Your plugin version is up-to-date
[12/10/2021, 5:23:30 PM] [Hubitat-v2] Sending Plugin Status to Hubitat | UpdateAvailable: false | newVersion: 2.5.12
[12/10/2021, 5:23:35 PM] [HB Supervisor] Homebridge Storage Path: /Users/garywesson/.homebridge
[12/10/2021, 5:23:35 PM] [HB Supervisor] Homebridge Config Path: /Users/garywesson/.homebridge/config.json
[12/10/2021, 5:23:35 PM] [HB Supervisor] Logging to /Users/garywesson/.homebridge/homebridge.log
[12/10/2021, 5:23:35 PM] [HB Supervisor] OS: Darwin 19.6.0 x64
[12/10/2021, 5:23:35 PM] [HB Supervisor] Node.js v14.15.4 /usr/local/bin/node
[12/10/2021, 5:23:35 PM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[12/10/2021, 5:23:35 PM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[12/10/2021, 5:23:37 PM] [Homebridge UI] Homebridge Config UI X v4.41.3 is listening on :: port 8581
[12/10/2021, 5:23:37 PM] [HB Supervisor] ERROR: The user interface threw an unhandled error
Error: listen EADDRINUSE: address already in use :::8581
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at doListen (net.js:1503:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 8581
}
[12/10/2021, 5:23:37 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[12/10/2021, 5:23:37 PM] [HB Supervisor] Started Homebridge v1.3.8 with PID: 84782
[12/10/2021, 5:23:37 PM] Loaded config.json with 0 accessories and 4 platforms.
[12/10/2021, 5:23:37 PM] Loaded 63 cached accessories from cachedAccessories.
[12/10/2021, 5:23:37 PM] ---
[12/10/2021, 5:23:38 PM] Loaded plugin: homebridge-config-ui-x@4.41.3
[12/10/2021, 5:23:38 PM] Registering platform 'homebridge-config-ui-x.config'
[12/10/2021, 5:23:38 PM] ---
[12/10/2021, 5:23:38 PM] Loaded plugin: homebridge-hubitat-tonesto7@2.5.12
[12/10/2021, 5:23:38 PM] Registering platform 'homebridge-hubitat-tonesto7.Hubitat-v2'
[12/10/2021, 5:23:38 PM] ---
[12/10/2021, 5:23:38 PM] Loaded plugin: homebridge-omnilink-platform@1.4.5
[12/10/2021, 5:23:38 PM] Registering platform 'homebridge-omnilink-platform.OmniLinkPlatform'
[12/10/2021, 5:23:38 PM] ---
[12/10/2021, 5:23:38 PM] Disabled plugin: homebridge-wink3@3.0.1
[12/10/2021, 5:23:38 PM] ---
[12/10/2021, 5:23:38 PM] Loading 4 platforms...
[12/10/2021, 5:23:38 PM] [Config] Initializing config platform...
[12/10/2021, 5:23:38 PM] [Config] Running in Service Mode
[12/10/2021, 5:23:38 PM] [Hubitat-v2] Initializing Hubitat-v2 platform...
[12/10/2021, 5:23:38 PM] [Hubitat-v2] Homebridge Version: 2.7
[12/10/2021, 5:23:38 PM] [Hubitat-v2] Plugin Version: 2.5.12
[12/10/2021, 5:23:38 PM] [Hubitat-v2] Checking Package Version for Updates...
[12/10/2021, 5:23:38 PM] Ignoring config for the platform "Wink" in your config.json as the plugin "homebridge-wink3" has been disabled.
[12/10/2021, 5:23:38 PM] [Omni] Initializing OmniLinkPlatform platform...
[12/10/2021, 5:23:38 PM] [Hubitat-v2] Fetching Hubitat-v2 Devices. NOTICE: This may take a moment if you have a large number of devices being loaded!
[12/10/2021, 5:23:38 PM] [Hubitat-v2] Refreshing All Device Data | Source: (First Launch)
[12/10/2021, 5:23:38 PM] [Omni] Cannot start plugin as settings are invalid
Setup Payload:
X-HM://0024F2EIHMCBH
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge C16C",
        "username": "xxx",
        "port": 51674,
        "pin": "xxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Hubitat-v2",
            "app_url_local": "http://192.168.1.84/apps/api/",
            "app_url_cloud": "https://cloud.hubitat.com/api/xxx/apps/",
            "use_cloud": false,
            "app_id": 60,
            "access_token": "xxx",
            "direct_port": 8000,
            "temperature_unit": "F",
            "round_levels": true,
            "adaptive_lighting": true,
            "adaptive_lighting_offset": 0,
            "validateTokenId": false,
            "logConfig": {
                "debug": false,
                "showChanges": true
            },
            "platform": "Hubitat-v2"
        },
        {
            "name": "Wink",
            "client_id": "xxx",
            "client_secret": "xxx",
            "direct_access": true,
            "platform": "Wink"
        },
        {
            "name": "Omni",
            "port": 4369,
            "includeAreas": true,
            "includeZones": true,
            "includeBypassZones": false,
            "includeButtons": true,
            "includeUnits": true,
            "includeThermostats": true,
            "includeEmergencyAlarms": true,
            "setHomeToAway": false,
            "setNightToAway": false,
            "garageDoors": [
                {
                    "openTime": 10
                }
            ],
            "pushover": {
                "alarms": {
                    "burglary": false,
                    "fire": false,
                    "gas": false,
                    "auxiliary": false,
                    "freeze": false,
                    "water": false,
                    "duress": false,
                    "temperature": false
                },
                "troubles": {
                    "freeze": false,
                    "batterylow": false,
                    "acpower": false,
                    "phoneline": false,
                    "digitalcommunicator": false,
                    "fuse": false
                }
            },
            "mqtt": {
                "showMqttEvents": false
            },
            "syncTime": false,
            "showHomebridgeEvents": false,
            "showOmniEvents": false,
            "clearCache": false,
            "forceAutoDiscovery": false,
            "platform": "OmniLinkPlatform"
        }
    ],
    "disabledPlugins": [
        "homebridge-wink3"
    ]
}
```

### Environment

- OS: MAC 10.15.7
- Software: v1.3.8
- Node: v14.15.4
- npm: v6.14.10

### Process Supervisor

hb-service

### Additional Context

I think the 'hb-service' process supervisor is correct but I am not sure.

Also, I don't know why but apparently I have two copies of the com.homebridge.server.plist now in two different folders. I don't know why but I wonder if that is related?

Thanks so much!

**Comment by oznu** [comment]
> Also, I don't know why but apparently I have two copies of the com.homebridge.server.plist now in two different folders.

This is your problem. 

The correct one is `/Library/LaunchDaemons/com.homebridge.server.plist` - stop and remove any others.
