### ISSUE TITLE
Error installing on MacBook Pro

### ISSUE THREAD

**Issue by jfransen44** [homebridge/homebridge#3083]
### Current Situation

I'm trying to install on a MacBook Pro running Catalina that's about 5 years old. I'm getting the following error in the log attached.  Any help is appreciated, thanks.

### Logs

```markdown
node:internal/bootstrap/switches/does_own_process_state:126 cachedCwd = rawMethods.cwd(); ^
Error: ENOENT: no such file or directory, uv_cwd at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:126:28) at process.cwd (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19) at new Config (/usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:92:19) at new <anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:83:19) at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:71:30) at Module._compile (node:internal/modules/cjs/loader:1101:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Module.require (node:internal/modules/cjs/loader:1005:19) { errno: -2, code: 'ENOENT', syscall: 'uv_cwd' }
```

### Configuration

```json
n/a
```

### Environment

- OS: MacOS 10.15.7
- Software:
- Node: 16.13.2
- npm: 8.1.2

### Process Supervisor

not applicable

### Additional Context

n/a

**Comment by oznu** [comment]
Have a look at https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-macOS
