### ISSUE TITLE
Cent0S install Homebrige error

### ISSUE THREAD

**Issue by lex1890** [homebridge/homebridge#3085]
### Current Situation

at startup (sudo npm install -g --unsafe-perm homebridge homebridge-config-ui-x) I get the following error, who can tell me what the problem is? Centos is clean, just delivered

### Logs

```markdown
2343 info run node-pty-prebuilt-multiarch@0.10.1-pre.4 install node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch node scripts/check-prebuild.js || prebuild-install || node scripts/install.js
2344 info run node-pty-prebuilt-multiarch@0.10.1-pre.4 install { code: 1, signal: null }
2345 timing reify:rollback:createSparse Completed in 1349ms
2346 timing reify:rollback:retireShallow Completed in 0ms
2347 timing command:install Completed in 10033ms
2348 verbose stack Error: command failed
2348 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
2348 verbose stack     at ChildProcess.emit (node:events:390:28)
2348 verbose stack     at maybeClose (node:internal/child_process:1064:16)
2348 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
2349 verbose pkgid node-pty-prebuilt-multiarch@0.10.1-pre.4
2350 verbose cwd /root
2351 verbose Linux 3.10.0-1160.53.1.el7.x86_64
2352 verbose argv "/usr/bin/node" "/bin/npm" "install" "-g" "--unsafe-perm" "homebridge" "homebridge-config-ui-x"
2353 verbose node v16.13.2
2354 verbose npm  v8.1.2
2355 error code 1
2356 error path /usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch
2357 error command failed
2358 error command sh -c node scripts/check-prebuild.js || prebuild-install || node scripts/install.js
2359 error Prebuild binary exists: /usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/prebuilds/linux-x64/node.abi93.node
2359 error make: Вход в каталог `/usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/build'
2359 error   CXX(target) Release/obj.target/pty/src/unix/pty.o
2359 error make: Выход из каталога `/usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/build'
2360 error Prebuild binary failed test.
2360 error prebuild-install WARN install /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node)
2360 error gyp info it worked if it ends with ok
2360 error gyp info using node-gyp@8.3.0
2360 error gyp info using node@16.13.2 | linux | x64
2360 error gyp info find Python using Python version 3.6.8 found at "/bin/python3"
2360 error gyp info spawn /bin/python3
2360 error gyp info spawn args [
2360 error gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2360 error gyp info spawn args   'binding.gyp',
2360 error gyp info spawn args   '-f',
2360 error gyp info spawn args   'make',
2360 error gyp info spawn args   '-I',
2360 error gyp info spawn args   '/usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch/build/config.gypi',
2360 error gyp info spawn args   '-I',
2360 error gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2360 error gyp info spawn args   '-I',
2360 error gyp info spawn args   '/root/.cache/node-gyp/16.13.2/include/node/common.gypi',
2360 error gyp info spawn args   '-Dlibrary=shared_library',
2360 error gyp info spawn args   '-Dvisibility=default',
2360 error gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.13.2',
2360 error gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
2360 error gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.13.2/<(target_arch)/node.lib',
2360 error gyp info spawn args   '-Dmodule_root_dir=/usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch',
2360 error gyp info spawn args   '-Dnode_engine=v8',
2360 error gyp info spawn args   '--depth=.',
2360 error gyp info spawn args   '--no-parallel',
2360 error gyp info spawn args   '--generator-output',
2360 error gyp info spawn args   'build',
2360 error gyp info spawn args   '-Goutput_dir=.'
2360 error gyp info spawn args ]
2360 error gyp info spawn make
2360 error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2360 error g++: ошибка: unrecognized command line option «-std=gnu++14»
2360 error make: *** [Release/obj.target/pty/src/unix/pty.o] Ошибка 1
2360 error gyp ERR! build error
2360 error gyp ERR! stack Error: `make` failed with exit code: 2
2360 error gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
2360 error gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
2360 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
2360 error gyp ERR! System Linux 3.10.0-1160.53.1.el7.x86_64
2360 error gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2360 error gyp ERR! cwd /usr/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch
2360 error gyp ERR! node -v v16.13.2
2360 error gyp ERR! node-gyp -v v8.3.0
2360 error gyp ERR! not ok
2361 verbose exit 1
```

### Configuration

```json
# setup repo
curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -

# install Node.js
sudo yum install -y nodejs gcc-c++ make net-tools python2 python3

# install build tools
sudo yum groupinstall -y 'Development Tools'

# test node is working
node -v

these commands are executed
```

### Environment

- OS:Centos linux 7 (core)
- Software:
- Node:16.13.2
- npm:8.1.2

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Tks for sharing a detailed issue, this particular error is not from homebridge, but from `homebridge-config-ui-x` and its dependency `node-pty-prebuilt-multiarch`. To get the attention of the developer, please raise this issue against the proper GitHub repository.
