### ISSUE TITLE
Error: Bypass_dialog_timed

### ISSUE THREAD

**Issue by TarkDetrius** [homebridge/homebridge#3111]
### Analysis

Hello,

couple days ago I am getting an error when trying to do any change via the plugin. I am running a docker version of HB on DS920+. I expect it could have something to do with the change in the application where you need to wait or confirm that you want to proceed with the state change right away.

I am running the latest version 2.5.5

### Expected Behavior

To set the arm modes

### Steps To Reproduce

Click any arming button in HK

### Logs

```markdown
[4/15/2022, 8:13:50 AM] [Jablotron] Setting section state: section_1 => 1
[4/15/2022, 8:13:50 AM] [Jablotron] Switching section section_1 (using section_1) to new state: set
[4/15/2022, 8:13:53 AM] [Jablotron] {
  status: false,
  error_status: 'bypass_dialog_timed',
  checksum: '9f785d19e3d329edfb6ebff755a44f79',
  server_id: '9016932-1650003233',
  client_id: null
}
[4/15/2022, 8:13:53 AM] [Jablotron] Error: bypass_dialog_timed
    at /homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:36:31
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-jablotron/lib/jablotron-client.js:68:21)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Configuration

```json
{
    "name": "Jablotron",
    "services": [
        {
            "id": xxxx,
            "name": "Home",
            "username": "xxxxx",
            "password": "xxxx",
            "pincode": "xxxx",
            "autoRefresh": true,
            "poolInterval": 60,
            "refreshOnStateChange": true,
            "debug": false,
            "sections": [
                {
                    "name": "House",
                    "segment_id": "STATE_1",
                    "segment_key": "section_1",
                    "keyboard_key": "keyboard_2_3",
                    "armedMode": "Away",
                    "partiallyArmedMode": "Night"
                }
            ],
            "switches": [
                {
                    "name": "Dům",
                    "segment_id": "STATE_1",
                    "segment_key": "section_1"
                },
                {
                    "name": "Noční režim",
                    "segment_id": "STATE_2",
                    "segment_key": "section_2"
                },
                {
                    "name": "Pohyb",
                    "segment_id": "STATE_3",
                    "segment_key": "section_3"
                }
            ]
        }
    ],
    "platform": "Jablotron"
}
```

### Environment

- OS: DS 920+ docker file
- Software: 2.5.5
- Node:
- npm:

### Process Supervisor

hb-service

**Comment by oznu** [comment]
This is an error in the homebridge-jablotron plugin, please report the issue with them.
