### ISSUE TITLE
Service Loop after Configure homebridge-ezviz Plugin

### ISSUE THREAD

**Issue by ahmadshaugi81** [homebridge/homebridge#3124]
### Current Situation

Hi, I just install the homebridge-ezviz plugin. But everyitme I configured it and add accessories, the Homebridge service are keep restarting. If I remove homebridge-ezviz configuration, without removing the plugin, then Homebridge service run normally and service loop was stopped.

### Logs

```markdown
[5/4/2022, 4:29:10 PM] Homebridge v1.4.1 (HAP v0.10.2) (Homebridge 5237) is running on port 51305.
[5/4/2022, 4:29:10 PM] [EZVIZ] New camera found: X5S(E01076328)
[5/4/2022, 4:29:10 PM] [EZVIZ] Configuring accessory X5SE01076328
[5/4/2022, 4:29:10 PM] TypeError: Cannot read properties of undefined (reading 'find')
    at EZVIZPlatform.configureAccessory (/usr/local/lib/node_modules/homebridge-ezviz/src/index.ts:88:44)
    at /usr/local/lib/node_modules/homebridge-ezviz/src/index.ts:134:14
    at Array.forEach (<anonymous>)
    at EZVIZPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-ezviz/src/index.ts:114:13)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ezviz/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge-ezviz/dist/index.js:4:12)
    at EZVIZPlatform.addCameras (/usr/local/lib/node_modules/homebridge-ezviz/dist/index.js:86:16)
    at EZVIZPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-ezviz/src/index.ts:171:18)
[5/4/2022, 4:29:10 PM] Got SIGTERM, shutting down Homebridge...
```

### Configuration

```json
{
            "region": 245,
            "email": "myemail",
            "password": "mypassword",
            "cameras": [
                {
                    "serial": "myezvizserial",
                    "username": "myezvizusername",
                    "code": "myezvizverificationcode"
                }
            ],
            "options": {
                "sleepSwitch": true,
                "audioSwitch": true
            },
            "platform": "EZVIZ"
        }
```

### Environment

- OS: MacOS Monterrey 12.3.1
- Software: Homebridge v1.4.1 and homebridge-ezviz v1.0.2
- Node: v16.13.2
- npm: 8.3.2

### Process Supervisor

hb-service

**Comment by oznu** [comment]
If your issue is plugin specific, raise an issue with the plugin author on their GitHub page instead - homebridge-ezviz.
