### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by WirthmU** [homebridge/homebridge#3160]
### Analysis

Out of nothing I am no longer able to login into homebridge server;
`http://192.168.1.106:8581/`
gives an "Unable to connect error"

The hombebridge service is running and the log files shows the following:
[6/9/2022, 12:00:07 PM] [HB Supervisor] ERROR: The user interface threw an unhandled error
```
TypeError: definePropertyModule.f is not a function
    at module.exports (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/core-js-pure/internals/create-non-enumerable-property.js:6:31)
    at module.exports (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/core-js-pure/internals/export.js:50:48)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/core-js-pure/modules/es.object.define-property.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/core-js-pure/es/object/define-property.js:1:1)
```

### Expected Behavior

Homebridge running as usual

### Steps To Reproduce

PC restarted
homebridge service restarted

### Logs

```markdown
Setup Payload:
X-HM://0023T26BYG2LL
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 203-70-830 │     
    └────────────┘     
                       
[6/9/2022, 11:59:49 AM] Homebridge v1.4.1 (HAP v0.10.2) (Homebridge 3BFF) is running on port 51548.
[6/9/2022, 11:59:49 AM] TypeError: packet.encode is not a function
    at onbind (/usr/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:87:28)
    at apply (/usr/lib/node_modules/homebridge/node_modules/thunky/index.js:44:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[6/9/2022, 11:59:49 AM] Got SIGTERM, shutting down Homebridge...
[6/9/2022, 11:59:49 AM] [HomeMatic CCU] [RPC] Removing Event Server for Interface BidCos-RF.
[6/9/2022, 11:59:49 AM] [HomeMatic CCU] [RPC] Removing Event Server for Interface BidCos-Wired.
[6/9/2022, 11:59:49 AM] [HomeMatic CCU] [RPC] Removing Event Server for Interface HmIP-RF.
[6/9/2022, 11:59:49 AM] [HB Supervisor] Homebridge Process Ended. Code: 0, Signal: null
[6/9/2022, 11:59:54 AM] [HB Supervisor] OS: Linux 5.13.0-48-generic x64
[6/9/2022, 11:59:54 AM] [HB Supervisor] Node.js v14.19.3 /usr/bin/node
[6/9/2022, 11:59:54 AM] [HB Supervisor] Homebridge Path: /usr/lib/node_modules/homebridge/bin/homebridge
[6/9/2022, 11:59:54 AM] [HB Supervisor] UI Path: /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[6/9/2022, 11:59:57 AM] [HB Supervisor] ERROR: The user interface threw an unhandled error
TypeError: definePropertyModule.f is not a function
    at module.exports (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/core-js-pure/internals/create-non-enumerable-property.js:6:31)
    at module.exports (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/core-js-pure/internals/export.js:50:48)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/core-js-pure/modules/es.object.define-property.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-config-ui-x/node_modules/core-js-pure/es/object/define-property.js:1:1)
[6/9/2022, 11:59:57 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[6/9/2022, 11:59:57 AM] [HB Supervisor] Started Homebridge v1.4.1 with PID: 50597
[6/9/2022, 11:59:57 AM] Loaded config.json with 0 accessories and 3 platforms.
[6/9/2022, 11:59:57 AM] Loaded 0 cached accessories from cachedAccessories.
[6/9/2022, 11:59:57 AM] ---
[6/9/2022, 11:59:58 AM] Loaded plugin: homebridge-config-ui-x@4.46.0
[6/9/2022, 11:59:58 AM] Registering platform 'homebridge-config-ui-x.config'
[6/9/2022, 11:59:58 AM] ---
[6/9/2022, 11:59:59 AM] Loaded plugin: homebridge-fhem@0.5.33
homebridge API version: 2.7
this is homebridge-fhem 0.5.33
error: fakegato-history not installed
[6/9/2022, 11:59:59 AM] Registering platform 'homebridge-fhem.FHEM'
[6/9/2022, 11:59:59 AM] ---
[6/9/2022, 11:59:59 AM] Loaded plugin: homebridge-homematic@0.2.226
[6/9/2022, 11:59:59 AM] Registering platform 'homebridge-homematic.HomeMatic'
[6/9/2022, 11:59:59 AM] ---
[6/9/2022, 11:59:59 AM] The plugin "homebridge-info" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!
[6/9/2022, 11:59:59 AM] Loaded plugin: homebridge-info@1.2.0
[6/9/2022, 11:59:59 AM] Registering platform 'homebridge-info.Info'
[6/9/2022, 11:59:59 AM] ---
[6/9/2022, 11:59:59 AM] Loading 3 platforms...
[6/9/2022, 11:59:59 AM] [Config] Initializing config platform...
[6/9/2022, 11:59:59 AM] [Config] Running in Service Mode
[6/9/2022, 11:59:59 AM] [FHEM] Initializing FHEM platform...
starting longpoll: http://127.0.0.1:8083/fhem?XHR=1&inform=type=status;addglobal=1;filter=.*;since=null;fmt=JSON&timestamp=1654768799538
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] Initializing HomeMatic platform...
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] [Core] merging configurations
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] Homematic Plugin Version 0.2.226
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] Plugin by thkl  https://github.com/thkl
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] running in production mode
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] will connect to your ccu at 192.168.1.153
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] IMPORTANT !! Starting this version, your homematic custom configuration is located in /var/lib/homebridge/homematic_config.json
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] using subsection Homekit
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] [RPC] using xmprpc for communication with BidCos-RF
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] init RPC for BidCos-RF.
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] [RPC] local ip used : 192.168.1.106. you may change that with local_ip parameter in config
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] init RPC for VirtualDevices.
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] [RPC] local ip used : 192.168.1.106. you may change that with local_ip parameter in config
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] [RPC] using xmprpc for communication with BidCos-Wired
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] init RPC for BidCos-Wired.
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] [RPC] local ip used : 192.168.1.106. you may change that with local_ip parameter in config
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] init RPC for HmIP-RF.
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] [RPC] local ip used : 192.168.1.106. you may change that with local_ip parameter in config
Server listening on: http://<ip>:8282
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] [RPC] server for interface BidCos-RF. is listening on port 9090.
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] [RPC] Creating Local HTTP Client for CCU RPC Events
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] [RPC] server for interface VirtualDevices. is listening on port 9093.
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] [RPC] Creating Local HTTP Client for CCU RPC Events
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] [RPC] server for interface BidCos-Wired. is listening on port 9091.
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] [RPC] Creating Local HTTP Client for CCU RPC Events
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] [RPC] server for interface HmIP-RF. is listening on port 9092.
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] [RPC] Creating Local HTTP Client for CCU RPC Events
[6/9/2022, 11:59:59 AM] [HomeMatic CCU] if PONG is PONG CCU is alive
[6/9/2022, 11:59:59 AM] [FHEM] Checking devices and attributes...
[6/9/2022, 11:59:59 AM] [FHEM]   executing: http://127.0.0.1:8083/fhem?cmd=%7BAttrVal(%22global%22,%22userattr%22,%22%22)%7D&XHR=1
[6/9/2022, 11:59:59 AM] [FHEM]   executing: http://127.0.0.1:8083/fhem?cmd=jsonlist2%20TYPE=siri&XHR=1
[6/9/2022, 11:59:59 AM] [FHEM] siri device is siri
[6/9/2022, 11:59:59 AM] [FHEM]   executing: http://127.0.0.1:8083/fhem?cmd=%7B$defs%7Bsiri%7D-%3E%7B%22homebridge-fhem%20version%22%7D%20=%20%220.5.33%22%7D&XHR=1
[6/9/2022, 12:00:00 PM] Initializing platform accessory 'HM LC Sw1 DR QEQ1052231 1'...
[6/9/2022, 12:00:00 PM] Initializing platform accessory 'HM LC Sw1 FM EEQ0001341 1'...
[6/9/2022, 12:00:00 PM] Initializing platform accessory 'HM LC Sw1 FM EEQ0001574 1'...
[6/9/2022, 12:00:00 PM] Initializing platform accessory 'HM LC Sw1 SM FEQ0037508 1'...
[6/9/2022, 12:00:00 PM] Initializing platform accessory 'HM LC Sw1 SM HEQ0101282 1'...
[6/9/2022, 12:00:00 PM] Initializing platform accessory 'HM LC Sw1 SM IEQ0049157 1'...
[6/9/2022, 12:00:00 PM] Initializing platform accessory 'HM LC Sw1 SM IEQ0049328 1'...
[6/9/2022, 12:00:00 PM] [FHEM] Fetching FHEM devices...
[6/9/2022, 12:00:00 PM] [FHEM] fetching: http://127.0.0.1:8083/fhem?cmd=jsonlist2%20room%3DHomekit&XHR=1
[6/9/2022, 12:00:00 PM] [HomeMatic CCU] [Core] will cache ccu response to /var/lib/homebridge/ccu.json
[6/9/2022, 12:00:00 PM] [FHEM] got: 5 results
[6/9/2022, 12:00:00 PM] [FHEM] Mean_Barometer: no service type detected
[6/9/2022, 12:00:00 PM] [FHEM] no accessory created for Mean_Barometer (DOIF)
[6/9/2022, 12:00:00 PM] [FHEM] homebridgeMapping: clear CurrentRelativeHumidity=state
[6/9/2022, 12:00:00 PM] [FHEM] Mean_Humidity_inside_2 is HumiditySensor
[6/9/2022, 12:00:00 PM] [FHEM] Mean_Humidity_inside_2 has
[6/9/2022, 12:00:00 PM] [FHEM]   CurrentRelativeHumidity [state]
  2022-06-09 12:00:00 caching: Mean_Humidity_inside_2-state: 43.7
[6/9/2022, 12:00:00 PM] [FHEM]     caching: CurrentRelativeHumidity: 43.7 (as number; from '43.7')
[6/9/2022, 12:00:00 PM] [FHEM] homebridgeMapping: clear CurrentRelativeHumidity=state
[6/9/2022, 12:00:00 PM] [FHEM] Mean_Humidity_outside is HumiditySensor
[6/9/2022, 12:00:00 PM] [FHEM] Mean_Humidity_outside has
[6/9/2022, 12:00:00 PM] [FHEM]   CurrentRelativeHumidity [state]
  2022-06-09 12:00:00 caching: Mean_Humidity_outside-state: 83.7
[6/9/2022, 12:00:00 PM] [FHEM]     caching: CurrentRelativeHumidity: 83.7 (as number; from '83.7')
[6/9/2022, 12:00:00 PM] [FHEM] homebridgeMapping: clear CurrentTemperature=state
[6/9/2022, 12:00:00 PM] [FHEM] Mean_Temp_inside_2 is thermometer
[6/9/2022, 12:00:00 PM] [FHEM] Mean_Temp_inside_2 has
[6/9/2022, 12:00:00 PM] [FHEM]   CurrentTemperature [state]
  2022-06-09 12:00:00 caching: Mean_Temp_inside_2-state: 20.0
[6/9/2022, 12:00:00 PM] [FHEM]     caching: CurrentTemperature: 20 (as number; from '20.0')
[6/9/2022, 12:00:00 PM] [FHEM] homebridgeMapping: clear CurrentTemperature=state
[6/9/2022, 12:00:00 PM] [FHEM] Mean_Temp_outside is thermometer
[6/9/2022, 12:00:00 PM] [FHEM] Mean_Temp_outside has
[6/9/2022, 12:00:00 PM] [FHEM]   CurrentTemperature [state]
  2022-06-09 12:00:00 caching: Mean_Temp_outside-state: 9.3
[6/9/2022, 12:00:00 PM] [FHEM]     caching: CurrentTemperature: 9.3 (as number; from '9.3')
[6/9/2022, 12:00:00 PM] Initializing platform accessory 'Mean_Humidity_inside_2'...
[6/9/2022, 12:00:00 PM] [FHEM] creating services for Mean_Humidity_inside_2
[6/9/2022, 12:00:00 PM] [FHEM]   information service for Mean_Humidity_inside_2
[6/9/2022, 12:00:00 PM] [FHEM]     manufacturer, model and serial number characteristics for Mean_Humidity_inside_2
[6/9/2022, 12:00:00 PM] [FHEM]     name (siriName) characteristic for Mean_Humidity_inside_2
[6/9/2022, 12:00:00 PM] [FHEM]   HumiditySensor service for Mean_Humidity_inside_2
[6/9/2022, 12:00:00 PM] [FHEM]     CurrentRelativeHumidity characteristic for Mean_Humidity_inside_2:state
[6/9/2022, 12:00:00 PM] Initializing platform accessory 'Mean_Humidity_outside'...
[6/9/2022, 12:00:00 PM] [FHEM] creating services for Mean_Humidity_outside
[6/9/2022, 12:00:00 PM] [FHEM]   information service for Mean_Humidity_outside
[6/9/2022, 12:00:00 PM] [FHEM]     manufacturer, model and serial number characteristics for Mean_Humidity_outside
[6/9/2022, 12:00:00 PM] [FHEM]     name (siriName) characteristic for Mean_Humidity_outside
[6/9/2022, 12:00:00 PM] [FHEM]   HumiditySensor service for Mean_Humidity_outside
[6/9/2022, 12:00:00 PM] [FHEM]     CurrentRelativeHumidity characteristic for Mean_Humidity_outside:state
[6/9/2022, 12:00:00 PM] Initializing platform accessory 'Mean_Temp_inside_2'...
[6/9/2022, 12:00:00 PM] [FHEM] creating services for Mean_Temp_inside_2
[6/9/2022, 12:00:00 PM] [FHEM]   information service for Mean_Temp_inside_2
[6/9/2022, 12:00:00 PM] [FHEM]     manufacturer, model and serial number characteristics for Mean_Temp_inside_2
[6/9/2022, 12:00:00 PM] [FHEM]     name (siriName) characteristic for Mean_Temp_inside_2
[6/9/2022, 12:00:00 PM] [FHEM]   TemperatureSensor service for Mean_Temp_inside_2
[6/9/2022, 12:00:00 PM] [FHEM]     CurrentTemperature characteristic for Mean_Temp_inside_2:state
[6/9/2022, 12:00:00 PM] Initializing platform accessory 'Mean_Temp_outside'...
[6/9/2022, 12:00:00 PM] [FHEM] creating services for Mean_Temp_outside
[6/9/2022, 12:00:00 PM] [FHEM]   information service for Mean_Temp_outside
[6/9/2022, 12:00:00 PM] [FHEM]     manufacturer, model and serial number characteristics for Mean_Temp_outside
[6/9/2022, 12:00:00 PM] [FHEM]     name (siriName) characteristic for Mean_Temp_outside
[6/9/2022, 12:00:00 PM] [FHEM]   TemperatureSensor service for Mean_Temp_outside
[6/9/2022, 12:00:00 PM] [FHEM]     CurrentTemperature characteristic for Mean_Temp_outside:state
```

### Configuration

```json
w@IoT-Chalet:~$ sudo cat /var/lib/homebridge/config.json
{
    "bridge": {
        "name": "Homebridge 3BFF",
        "username": "0E:66:2D:72:3B:FF",
        "port": 51548,
        "pin": "203-70-830"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "platform": "FHEM",
            "name": "FHEM",
            "server": "127.0.0.1",
            "port": "8083",
            "filter": "room=Homekit"
        },
        {
            "name": "HomeMatic CCU",
            "ccu_ip": "192.168.1.153",
            "subsection": "Homekit",
            "enable_hmip": true,
            "enable_wired": true,
            "ios10": true,
            "platform": "HomeMatic"
        }
    ]
}
```

### Environment

- OS: Ubuntu latest
- Software:
- Node:
- npm:

### Process Supervisor

not applicable

**Comment by WirthmU** [comment]
This fixed it - thank you for your support.
