### ISSUE TITLE
Change User Name Password

### ISSUE THREAD

**Issue by mendonsa** [homebridge/homebridge#3186]
### Current Situation

I recently installed Homebridge on Rpi and installed a few plugins. All worked great. When I installed the Ring plugin it was going smoothly then a screen popped up and asked for my ring username and password. I put the correct username in but messed up on the password. Now the plugin is un-usable. I've fully uninstalled several times and re-installed. When it's done now, the gear just spins forever. I looked through files in the OS and config file. No matter how many times I uninstall and re-installed it has never asked me for username/password again. I would like to put the correct one in and make this work. How? Thanks

### Logs

```markdown
Running Command: sudo -E -n npm install -g homebridge-ring@11.0.7
[7/14/2022, 13:44:30] [Homebridge UI] [homebridge-ring] /usr/local/lib/node_modules/homebridge-ring/lib/api/rest-client.js:72
            device_model: this.authOptions.controlCenterDisplayName ?? 'ring-client-api',
                                                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/homebridge/homebridge-ui/server.js:5:23)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
[7/14/2022, 13:44:30] [Homebridge UI] [homebridge-ring] Child process ended
```

### Configuration

```json
{
    "platform": "Ring",
    "name": "Ring"
}
```

### Environment

- OS: Rasperian
- Software:
- Node:
- npm:11.0.7

### Process Supervisor

not applicable

**Comment by mendonsa** [comment]
Disregard, Looking through the logs I noticed the node.js version was old "12", I performed an upgrade to that via: sudo-hb-service update-node  .I let that run then when the server restarted it prompted me for the user name and password. That seemed to work. No more errors.
