### ISSUE TITLE
ERROR: The user interface threw an unhandled error Error: listen EADDRINUSE: address already in use :::8581

### ISSUE THREAD

**Issue by Mike92115** [homebridge/homebridge#3193]
### Analysis

I updated to the latest version of HomeBridge the other day and then updated to the latest version of the UI, since then I have been getting errors.  This is not exactly stopping Homebridge from running, but it is causing problems as it keeps restarting.  

### Expected Behavior

Not to have this error

### Steps To Reproduce

Start Homebridge

### Logs

```markdown
[7/20/2022, 11:00:27 AM] [HB Supervisor] OS: Linux 3.10.108 x64
[7/20/2022, 11:00:27 AM] [HB Supervisor] Node.js v16.16.0 /opt/homebridge/bin/node
[7/20/2022, 11:00:27 AM] [HB Supervisor] Homebridge Path: /var/lib/homebridge/node_modules/homebridge/bin/homebridge
[7/20/2022, 11:00:27 AM] [HB Supervisor] UI Path: /opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[7/20/2022, 11:00:32 AM] [Homebridge UI] Homebridge Config UI X v4.50.0 is listening on :: port 8581
[7/20/2022, 11:00:33 AM] [HB Supervisor] ERROR: The user interface threw an unhandled error
Error: listen EADDRINUSE: address already in use :::8581
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at doListen (node:net:1559:7)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 8581
}
[7/20/2022, 11:00:33 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[7/20/2022, 11:00:33 AM] [HB Supervisor] Started Homebridge v1.5.0 with PID: 408
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge EE5F",
        "username": "0E:45:2C:B8:EE:5F",
        "port": 51252,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Govee",
            "username": "User Name",
            "password": "password",
            "apiKey": "18bf0c12-22c8-4a85-9273-640c30f04a8a",
            "debug": false,
            "thermoDevices": [
                {
                    "label": "Mushrooms",
                    "deviceId": "CC:DB:E3:32:80:C3:14:45"
                },
                {
                    "label": "Freezer Thermometer",
                    "deviceId": "16:7E:E3:8C:81:82:F8:5A"
                }
            ],
            "humidifierDevices": [
                {
                    "label": "Living Room Humidifier",
                    "deviceId": "18:F5:D4:AD:FC:27:00:80"
                }
            ],
            "_bridge": {
                "username": "0E:A2:DA:27:9C:B8",
                "port": 50291
            },
            "platform": "Govee"
        },
        {
            "email": "email address",
            "password": "password",
            "poll_short_delay": 15,
            "poll_long_delay": 90,
            "platform": "ryobi-gdo",
            "_bridge": {
                "username": "0E:53:36:D8:06:8B",
                "port": 38325
            }
        },
        {
            "name": "ADT Pulse",
            "username": "User Name",
            "password": "password",
            "fingerprint": "eyJmaW5nZXJwcmludCI6eyJ1YUJyb3dzZXIiOnsibmFtZSI6IkNocm9tZSIsInZlcnNpb24iOiI5NC4wLjQ2MDYuNjEiLCJtYWpvciI6Ijk0In0sInVhU3RyaW5nIjoiTW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzk0LjAuNDYwNi42MSBTYWZhcmkvNTM3LjM2IiwidWFEZXZpY2UiOnsibW9kZWwiOm51bGwsInR5cGUiOm51bGwsInZlbmRvciI6bnVsbH0sInVhRW5naW5lIjp7Im5hbWUiOiJXZWJLaXQiLCJ2ZXJzaW9uIjoiNTM3LjM2In0sInVhT1MiOnsibmFtZSI6Ik1hYyBPUyIsInZlcnNpb24iOiIxMC4xNS43In0sInVhQ1BVIjp7ImFyY2hpdGVjdHVyZSI6bnVsbH0sInVhUGxhdGZvcm0iOiJNYWNJbnRlbCIsImxhbmd1YWdlIjoiZW4tVVMiLCJjb2xvckRlcHRoIjoyNCwicGl4ZWxSYXRpbyI6Miwic2NyZWVuUmVzb2x1dGlvbiI6IjI1NjB4MTQ0MCIsImF2YWlsYWJsZVNjcmVlblJlc29sdXRpb24iOiIyNTYweDE0NDAiLCJ0aW1lem9uZSI6IkFtZXJpY2EvTG9zX0FuZ2VsZXMiLCJ0aW1lem9uZU9mZnNldCI6NDIwLCJsb2NhbFN0b3JhZ2UiOnRydWUsInNlc3Npb25TdG9yYWdlIjp0cnVlLCJpbmRleGVkRGIiOnRydWUsImFkZEJlaGF2aW9yIjpmYWxzZSwib3BlbkRhdGFiYXNlIjp0cnVlLCJjcHVDbGFzcyI6bnVsbCwicGxhdGZvcm0iOiJNYWNJbnRlbCIsImRvTm90VHJhY2siOiIxIiwicGx1Z2lucyI6IlBvcnRhYmxlIERvY3VtZW50IEZvcm1hdC5hcHBsaWNhdGlvbi9wZGY6OnBkZixQb3J0YWJsZSBEb2N1bWVudCBGb3JtYXQuYXBwbGljYXRpb24vcGRmOjpwZGYsUG9ydGFibGUgRG9jdW1lbnQgRm9ybWF0LmFwcGxpY2F0aW9uL3BkZjo6cGRmLFBvcnRhYmxlIERvY3VtZW50IEZvcm1hdC5hcHBsaWNhdGlvbi9wZGY6OnBkZixQb3J0YWJsZSBEb2N1bWVudCBGb3JtYXQuYXBwbGljYXRpb24vcGRmOjpwZGYiLCJjYW52YXMiOiItMzY4NDcyNDgzIiwid2ViR2wiOiIxMDE2NTk2NzQ3IiwiYWRCbG9jayI6ZmFsc2UsInVzZXJUYW1wZXJMYW5ndWFnZSI6ZmFsc2UsInVzZXJUYW1wZXJTY3JlZW5SZXNvbHV0aW9uIjpmYWxzZSwidXNlclRhbXBlck9TIjpmYWxzZSwidXNlclRhbXBlckJyb3dzZXIiOmZhbHNlLCJ0b3VjaFN1cHBvcnQiOnsibWF4VG91Y2hQb2ludHMiOjAsInRvdWNoRXZlbnQiOmZhbHNlLCJ0b3VjaFN0YXJ0IjpmYWxzZX0sImNvb2tpZVN1cHBvcnQiOnRydWUsImZvbnRzIjoiQWJhZGkgTVQgQ29uZGVuc2VkIExpZ2h0LEFjYWRlbXkgRW5ncmF2ZWQgTEVULEFET0JFIENBU0xPTiBQUk8sQURPQkUgR0FSQU1PTkQgUFJPLEFtZXJpY2FuIFR5cGV3cml0ZXIsQW5kYWxlIE1vbm8sQXBwbGUgQ2hhbmNlcnksQXBwbGUgQ29sb3IgRW1vamksQXBwbGUgU0QgR290aGljIE5lbyxBcmlhbCxBcmlhbCBCbGFjayxBcmlhbCBIZWJyZXcsQXJpYWwgTmFycm93LEFyaWFsIFJvdW5kZWQgTVQgQm9sZCxBcmlhbCBVbmljb2RlIE1TLEFSTk8gUFJPLEFWRU5JUixBeXV0aGF5YSxCYW5nbGEgU2FuZ2FtIE1OLEJhbmsgR290aGljLEJhc2tlcnZpbGxlLEJhc2tlcnZpbGxlIE9sZCBGYWNlLEJhdGFuZyxCYXVoYXVzIDkzLEJlbGwgTVQsQmVybmFyZCBNVCBDb25kZW5zZWQsQmlnIENhc2xvbixCbGFpck1kSVRDIFRULEJvZG9uaSA3MixCb2RvbmkgNzIgT2xkc3R5bGUsQm9kb25pIDcyIFNtYWxsY2FwcyxCb29rIEFudGlxdWEsQm9va21hbiBPbGQgU3R5bGUsQm9va3NoZWxmIFN5bWJvbCA3LEJyYWRsZXkgSGFuZCxCcml0YW5uaWMgQm9sZCxCcnVzaCBTY3JpcHQgTVQsQ2FsaWJyaSxDYWxpc3RvIE1ULENhbWJyaWEsQ2FtYnJpYSBNYXRoLENhbmRhcmEsQ2VudHVyeSxDZW50dXJ5IEdvdGhpYyxDZW50dXJ5IFNjaG9vbGJvb2ssQ2hhbGtib2FyZCxDaGFsa2JvYXJkIFNFLENoYWxrZHVzdGVyLENvY2hpbixDb2xvbm5hIE1ULENvbWljIFNhbnMgTVMsQ29uc29sYXMsQ29uc3RhbnRpYSxDb29wZXIgQmxhY2ssQ29wcGVycGxhdGUsQ29wcGVycGxhdGUgR290aGljIEJvbGQsQ29wcGVycGxhdGUgR290aGljIExpZ2h0LENvcmJlbCxDb3VyaWVyIE5ldyxDdXJseiBNVCxEZXZhbmFnYXJpIFNhbmdhbSBNTixEaWRvdCxFZHdhcmRpYW4gU2NyaXB0IElUQyxFbmdsaXNoIDExMSBWaXZhY2UgQlQsRW5ncmF2ZXJzIE1ULEVyYXMgQm9sZCBJVEMsRXVwaGVtaWEgVUNBUyxFVVJPU1RJTEUsRm9vdGxpZ2h0IE1UIExpZ2h0LEZyYW5rbGluIEdvdGhpYyBCb29rLEZyYW5rbGluIEdvdGhpYyBNZWRpdW0sRnV0dXJhLEZ1dHVyYSBCayBCVCxHYWJyaW9sYSxHYXJhbW9uZCxHZWV6YSBQcm8sR2VuZXZhLEdlb3JnaWEsR2VvU2xhYiA3MDMgTHQgQlQsR2VvU2xhYiA3MDMgWEJkIEJULEdpbGwgU2FucyxHaWxsIFNhbnMgTVQsR2xvdWNlc3RlciBNVCBFeHRyYSBDb25kZW5zZWQsR09USEFNLEdPVEhBTSBCT0xELEdvdWR5IE9sZCBTdHlsZSxHdWphcmF0aSBTYW5nYW0gTU4sR3VsaW0sR3VybXVraGkgTU4sSGFldHRlbnNjaHdlaWxlcixIYXJyaW5ndG9uLEhlaXRpIFNDLEhlaXRpIFRDLEhlbHZldGljYSxIZWx2ZXRpY2EgTmV1ZSxIaXJhZ2lubyBLYWt1IEdvdGhpYyBQcm9OLEhpcmFnaW5vIE1pbmNobyBQcm9OLEhvZWZsZXIgVGV4dCxIdW1hbnN0IDUyMSBDbiBCVCxJbXBhY3QsSW1wcmludCBNVCBTaGFkb3csSmF6eiBMRVQsS2FpbGFzYSxLYW5uYWRhIFNhbmdhbSBNTixLcnVuZ3RoZXAsTHVjaWRhIEJyaWdodCxMdWNpZGEgQ2FsbGlncmFwaHksTHVjaWRhIENvbnNvbGUsTHVjaWRhIEZheCxMVUNJREEgR1JBTkRFLEx1Y2lkYSBIYW5kd3JpdGluZyxMdWNpZGEgU2FucyxMdWNpZGEgU2FucyBUeXBld3JpdGVyLEx1Y2lkYSBTYW5zIFVuaWNvZGUsTWFsYXlhbGFtIFNhbmdhbSBNTixNYXJpb24sTWFya2VyIEZlbHQsTWFybGV0dCxNYXR1cmEgTVQgU2NyaXB0IENhcGl0YWxzLE1laXJ5byxNaWNyb3NvZnQgSGltYWxheWEsTWljcm9zb2Z0IFNhbnMgU2VyaWYsTWljcm9zb2Z0IFRhaSBMZSxNaWNyb3NvZnQgWWkgQmFpdGksTWluZ0xpVSxNaW5nTGlVX0hLU0NTLE1pbmdMaVVfSEtTQ1MtRXh0QixNaW5nTGlVLUV4dEIsTWluaW9uIFBybyxNaXN0cmFsLE1vZGVybiBOby4gMjAsTW9uYSBMaXNhIFNvbGlkIElUQyBUVCxNb25hY28sTW9uZ29saWFuIEJhaXRpLE1vbm90eXBlIENvcnNpdmEsTVMgR290aGljLE1TIE1pbmNobyxNUyBQR290aGljLE1TIFBNaW5jaG8sTVMgUmVmZXJlbmNlIFNhbnMgU2VyaWYsTVMgUmVmZXJlbmNlIFNwZWNpYWx0eSxNVCBFeHRyYSxNWVJJQUQgUFJPLE5hZGVlbSxOb3Rld29ydGh5LE9ueXgsT1BUSU1BLE9yaXlhIFNhbmdhbSBNTixQYWxhdGlubyxQYWxhdGlubyBMaW5vdHlwZSxQYXB5cnVzLFBhcnR5IExFVCxQZXJwZXR1YSxQZXJwZXR1YSBUaXRsaW5nIE1ULFBsYW50YWdlbmV0IENoZXJva2VlLFBsYXliaWxsLFBNaW5nTGlVLFBNaW5nTGlVLUV4dEIsUFJJTkNFVE9XTiBMRVQsUm9ja3dlbGwsUm9ja3dlbGwgRXh0cmEgQm9sZCxTYW50YSBGZSBMRVQsU2F2b3llIExFVCxTaW1IZWksU2ltU3VuLFNpbVN1bi1FeHRCLFNpbmhhbGEgU2FuZ2FtIE1OLFNraWEsU25lbGwgUm91bmRoYW5kLFN0ZW5jaWwsU3luY2hybyBMRVQsVGFob21hLFRhbWlsIFNhbmdhbSBNTixUZWx1Z3UgU2FuZ2FtIE1OLFRob25idXJpLFRpbWVzLFRpbWVzIE5ldyBSb21hbixUUkFKQU4gUFJPLFRyZWJ1Y2hldCBNUyxUdyBDZW4gTVQsVW5pdmVycyxVbml2ZXJzIENFIDU1IE1lZGl1bSxWZXJkYW5hLFdpZGUgTGF0aW4sV2luZ2RpbmdzLFdpbmdkaW5ncyAyLFdpbmdkaW5ncyAzLFphcGZpbm8ifX0=",
            "country": "us",
            "logLevel": 30,
            "logActivity": true,
            "removeObsoleteZones": false,
            "resetAll": false,
            "_bridge": {
                "username": "0E:6B:62:3E:B7:E3",
                "port": 45416
            },
            "platform": "ADTPulse"
        },
        {
            "platform": "yamaha-home",
            "play_volume": -12,
            "setMainInputTo": "HDMI1",
            "show_input_name": "yes",
            "party_switch": "no",
            "inputs_as_accessories": {
                "YamahaReceiver": {
                    "1": {
                        "name": "CABLE",
                        "setInputTo": "HDMI1",
                        "set_default_volume": -12
                    },
                    "2": {
                        "name": "AppleTV",
                        "setInputTo": "HDMI2"
                    },
                    "3": {
                        "name": "Switch",
                        "set_scene": "3",
                        "setInputTo": "HDMI3"
                    }
                }
            },
            "manual_addresses": {
                "Yamaha": "10.0.1.38"
            },
            "_bridge": {
                "username": "0E:DE:58:6D:D2:27",
                "port": 33458
            }
        },
        {
            "app_list": false,
            "devices": [
                {
                    "name": "TV",
                    "ip": "10.0.1.188",
                    "mac": "d0:03:df:ba:df:8a"
                }
            ],
            "_bridge": {
                "username": "0E:D7:5D:AA:11:E8",
                "port": 37099
            },
            "platform": "SamsungTizen"
        },
        {
            "username": "User Name",
            "password": "Password",
            "enableCamera": true,
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "hkDisarmed": 6,
            "_bridge": {
                "username": "0E:56:42:89:DC:4C",
                "port": 47118
            },
            "platform": "EufySecurity",
            "pollingIntervalMinutes": 30,
            "enableDetailedLogging": 0,
            "ignoreStations": [
                ""
            ],
            "ignoreDevices": [
                ""
            ],
            "country": "US"
        },
        {
            "options": {
                "username": "User Name",
                "password": "password",
                "accessId": "cujw3avgavhp7a9xflla",
                "accessKey": "31dd1cee5cb748059a94ea2dee611915",
                "lang": "en",
                "projectType": "2",
                "appSchema": "smartlife",
                "countryCode": 1,
                "debug": false
            },
            "name": "TuyaPlatform",
            "platform": "TuyaPlatform",
            "_bridge": {
                "username": "0E:CB:DA:8E:C8:18",
                "port": 51986
            }
        },
        {
            "country": "US",
            "language": "en-US",
            "auth_mode": "token",
            "refresh_token": "56f6e121fa17a6c2f960c949782ea3ed8de2b9583071b04fa123d54c5c4db24e973910ac07dbb3038ff8530e35802ad2",
            "username": "",
            "password": "",
            "devices": [
                {
                    "id": "60dea180-120f-11e9-b230-0051edf352c3",
                    "name": "REFRIGERATOR",
                    "type": "REFRIGERATOR",
                    "ref_express_freezer": true,
                    "ref_express_fridge": false,
                    "ref_eco_friendly": false
                }
            ],
            "thinq1": true,
            "refresh_interval": 60,
            "platform": "LGThinQ",
            "_bridge": {
                "username": "0E:7D:80:47:05:94",
                "port": 55970
            }
        },
        {
            "bonds": [
                {
                    "ip_address": "10.0.1.64",
                    "token": "b84c3a84864b5cc1"
                }
            ],
            "include_dimmer": false,
            "include_toggle_state": false,
            "fan_speed_values": true,
            "platform": "Bond",
            "_bridge": {
                "username": "0E:35:B3:3F:0B:31",
                "port": 53466
            }
        },
        {
            "devices": [
                {
                    "type": "RGBTWLight",
                    "name": "Dolphin 1",
                    "id": "eb7906b220d8a80148f36q",
                    "key": "228533d9bf27751e",
                    "manufacturer": "Tuya",
                    "model": "HYL5-M44"
                },
                {
                    "type": "RGBTWLight",
                    "name": "Dolphin 2",
                    "id": "eb10d98e6f80426533wzkx",
                    "key": "015f182dc8848b00",
                    "manufacturer": "Tuya",
                    "model": "HYL5-M44"
                },
                {
                    "type": "RGBTWLight",
                    "name": "Dolphin 3",
                    "id": "ebf8f637b1a621f38ewaub",
                    "key": "ffa78305fb2cf458",
                    "manufacturer": "Tuya",
                    "model": "HYL5-M44"
                },
                {
                    "type": "RGBTWLight",
                    "name": "Booty Wall 1",
                    "id": "eb848c159a6769ace3ceng",
                    "key": "a6505f22454df6bc",
                    "manufacturer": "Tuya",
                    "model": "HYL5-M44"
                },
                {
                    "type": "RGBTWLight",
                    "name": "Booty Wall 2",
                    "id": "eb2b47f650ed610aca2d2f",
                    "key": "312480efe316e1a8",
                    "manufacturer": "Tuya",
                    "model": "HYL5-M44"
                }
            ],
            "platform": "TuyaLan",
            "_bridge": {
                "username": "0E:E1:48:57:68:F9",
                "port": 31141
            }
        }
    ],
    "disabledPlugins": [
        "homebridge-camera-ui",
        "homebridge-tuya-lan",
        "homebridge-tuya"
    ]
}
```

### Environment

- OS: Ubuntu Focal Fossa (20.04.4 LTS) Synology NAS Docker
- Software: 
- Node: v16.16.0
- npm: 8.14 (updated from 8.11 to see if that corrected the problem it did not)

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

I am using this image: https://registry.hub.docker.com/r/oznu/homebridge/

**Comment by NorthernMan54** [comment]
The error message `Error: listen EADDRINUSE: address already in use :::8581` likely points to another copy of the UI running at the same time.  Are you possibly running an additional copy?

**Comment by Mike92115** [comment]
That was it, apparently I was having a major case of the stupids and missed that.

Thank you

**Comment by iMonZ** [comment]
I get this error:



[12/6/2022, 10:51:19 PM] Loaded plugin: homebridge-dyson-pure-cool@2.7.5
[12/6/2022, 10:51:19 PM] Registering platform 'homebridge-dyson-pure-cool.DysonPureCoolPlatform'
[12/6/2022, 10:51:19 PM] ---
[12/6/2022, 10:51:19 PM] Loaded plugin: homebridge-gsh@2.2.0
[12/6/2022, 10:51:19 PM] Registering platform 'homebridge-gsh.google-smarthome'
[12/6/2022, 10:51:19 PM] ---
[12/6/2022, 10:51:27 PM] [HB Supervisor] OS: Linux 5.15.0-1021-raspi arm64
[12/6/2022, 10:51:27 PM] [HB Supervisor] Node.js v18.12.1 /opt/homebridge/bin/node
[12/6/2022, 10:51:27 PM] [HB Supervisor] Homebridge Path: /var/lib/homebridge/node_modules/homebridge/bin/homebridge
[12/6/2022, 10:51:27 PM] [HB Supervisor] UI Path: /opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[12/6/2022, 10:51:32 PM] [HB Supervisor] ERROR: The user interface threw an unhandled error
Error: unsupported
    at configSecureContext (node:internal/tls/secure-context:277:15)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1352:27)
    at Server (node:_tls_wrap:1211:8)
    at new Server (node:https:74:3)
    at Object.createServer (node:https:112:10)
    at getServerInstance (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/fastify/lib/server.js:284:22)
    at createServer (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/fastify/lib/server.js:15:18)
    at fastify (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/fastify/fastify.js:185:30)
    at new FastifyAdapter (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:82:37)
    at bootstrap (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/main.js:31743:22)
    at HomebridgeServiceHelper.runUi (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/src/bin/hb-service.ts:528:18)
    at HomebridgeServiceHelper.launch (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/src/bin/hb-service.ts:370:5)
[12/6/2022, 10:51:32 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[12/6/2022, 10:51:32 PM] [HB Supervisor] Started Homebridge v1.6.0 with PID: 9503
[12/6/2022, 10:51:33 PM] Loaded config.json with 0 accessories and 4 platforms.
[12/6/2022, 10:51:33 PM] Loaded 5 cached accessories from cachedAccessories.
[12/6/2022, 10:51:33 PM] ---
[12/6/2022, 10:51:34 PM] Loaded plugin: homebridge-dyson-pure-cool@2.7.5
[12/6/2022, 10:51:34 PM] Registering platform 'homebridge-dyson-pure-cool.DysonPureCoolPlatform'
[12/6/2022, 10:51:34 PM] ---
[12/6/2022, 10:51:34 PM] Loaded plugin: homebridge-gsh@2.2.0
[12/6/2022, 10:51:34 PM] Registering platform 'homebridge-gsh.google-smarthome'
[12/6/2022, 10:51:34 PM] ---
[12/6/2022, 10:51:43 PM] [HB Supervisor] OS: Linux 5.15.0-1021-raspi arm64
[12/6/2022, 10:51:43 PM] [HB Supervisor] Node.js v18.12.1 /opt/homebridge/bin/node
[12/6/2022, 10:51:43 PM] [HB Supervisor] Homebridge Path: /var/lib/homebridge/node_modules/homebridge/bin/homebridge
[12/6/2022, 10:51:43 PM] [HB Supervisor] UI Path: /opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
