### ISSUE TITLE
Rebooting system

### ISSUE THREAD

**Issue by jorgemsccc** [homebridge/homebridge#3226]
### Current Situation

Hello, i have endless restart on my homebridge. Can you help me?

### Logs

```markdown
[08/09/2022, 13:51:19] [miot] [1c cleaner] Successfully created a RobotCleaner device! It is a Xiaomi Mijia 1C Sweeping Vacuum Cleaner.
[08/09/2022, 13:51:19] [miot] [1c cleaner] Initializing accessory!
[08/09/2022, 13:51:20] [miot] [1c cleaner] Accessory successfully initialized!
[08/09/2022, 13:51:20] [miot] [1c cleaner] Registering 1 accessories!
[08/09/2022, 13:51:20] [miot] [1c cleaner] Everything looks good! Initiating property polling!
[08/09/2022, 13:51:30] [G-On Alice] ERROR: HAP Discovery failed, please review config
[08/09/2022, 13:51:34] [Multipurpose Kettle] No kettle was found...
[08/09/2022, 13:51:34] [Multipurpose Kettle] No kettle was found...
[08/09/2022, 13:51:34] [homebridge-smartmi-humidifier] This plugin slows down Homebridge. The read handler for the characteristic 'Rotation Speed' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[08/09/2022, 13:51:34] [homebridge-smartmi-humidifier] This plugin slows down Homebridge. The read handler for the characteristic 'Relative Humidity Humidifier Threshold' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[08/09/2022, 13:51:34] [homebridge-smartmi-humidifier] This plugin slows down Homebridge. The read handler for the characteristic 'Current Temperature' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[08/09/2022, 13:51:38] [homebridge-multipurpose-kettle] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[08/09/2022, 13:51:38] [homebridge-multipurpose-kettle] This plugin slows down Homebridge. The read handler for the characteristic 'Current Temperature' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[08/09/2022, 13:51:38] [miot] [1c cleaner] Device found: dreame.vacuum.mc1808
[08/09/2022, 13:51:38] [miot] [1c cleaner] Setting up miot device!
[08/09/2022, 13:51:38] [miot] [1c cleaner] Device setup finished! Miot device ready!
[08/09/2022, 13:51:38] [miot] [1c cleaner] Connected to device: dreame.vacuum.mc1808
[08/09/2022, 13:51:38] [miot] [1c cleaner] Doing initial property fetch.
[08/09/2022, 13:51:39] [miot] [1c cleaner] Main brush left time: 126 hours.
[08/09/2022, 13:51:39] [miot] [1c cleaner] Main brush life level: 42%.
[08/09/2022, 13:51:39] [miot] [1c cleaner] Filter life level: 20%.
[08/09/2022, 13:51:39] [miot] [1c cleaner] Total clean time: 15552 hours.
[08/09/2022, 13:51:39] [miot] [1c cleaner] Total cleaned: 482 times.
[08/09/2022, 13:51:39] [miot] [1c cleaner] Total clean area: 11907 m2.
[08/09/2022, 13:51:39] [miot] [1c cleaner] Starting property polling.
[08/09/2022, 13:51:39] [Multipurpose Kettle] No kettle was found...
[08/09/2022, 13:51:39] [Multipurpose Kettle] No kettle was found...
[08/09/2022, 13:51:43] [homebridge-multipurpose-kettle] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[08/09/2022, 13:51:43] [homebridge-multipurpose-kettle] This plugin slows down Homebridge. The read handler for the characteristic 'Current Temperature' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[08/09/2022, 13:51:44] [homebridge-multipurpose-kettle] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[08/09/2022, 13:51:44] [homebridge-multipurpose-kettle] This plugin slows down Homebridge. The read handler for the characteristic 'Current Temperature' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[08/09/2022, 13:51:54] [homebridge-multipurpose-kettle] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[08/09/2022, 13:51:54] [homebridge-multipurpose-kettle] This plugin slows down Homebridge. The read handler for the characteristic 'Current Temperature' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[08/09/2022, 13:51:59] [Multipurpose Kettle] No kettle was found...
[08/09/2022, 13:51:59] [Multipurpose Kettle] No kettle was found...
[08/09/2022, 13:52:06] TypeError: Cannot read properties of null (reading 'setNoDelay')
    at HAPConnection.handleHttpServerRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:634:25)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:980:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
[08/09/2022, 13:52:06] Got SIGTERM, shutting down Homebridge...
[08/09/2022, 13:52:11] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[08/09/2022, 13:52:16] [HB Supervisor] Restarting Homebridge...
```

### Configuration

```json
{
    "bridge": {
        "port": ,
        "pin": "",
        "name": "",
        "username": ""
    },
    "platforms": [
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hosts": [
                {
                    "address": "192.168.1.38",
                    "mac": "ec:0b:ae:9e:a3:09",
                    "isRM4": true
                }
            ],
            "accessories": [
                {
                    "name": "AC Swing",
                    "type": "switch",
                    "data": {
                        "on": "
                    },
                    "_bridge": {
                        "username": "0E:83:FD:29:58:C9",
                        "port": 55197
                    }
                },
                {
                    "name": "Living Room Thermometer",
                    "type": "temperatureSensor",
                    "noHumidity": true,
                    "_bridge": {
                        "username": "0E:83:FD:29:58:C9"
                    }
                },
                {
                    "name": "Living Room Humidity Sensor",
                    "type": "humiditySensor",
                    "_bridge": {
                        "username": "0E:83:FD:29:58:C9"
                    }
                },
                {
                    "name": "Hisense",
                    "type": "heater-cooler",
                    "noHumidity": true,
                    "_bridge": {
                        "username": "0E:83:FD:29:58:C9"
                    },
                    "defaultNowTemperature": 25,
                    "minTemperature": 16,
                    "maxTemperature": 23,
                    "coolingThresholdTemperature": 18,
                    "temperatureUnits": "C",
                    "fanStepSize": 25,
                    "tempStepSize": 1,
                    "data": {
                        "cool": {
                     
                                    }
                                }
                            }
                        }
                    }
                }
            ]
        },
        {
            "auth": "form",
            "theme": "blue-grey",
            "lang": "auto",
            "port": 8581,
            "platform": "config",
            "tempUnits": "c",
            "name": "Config"
        },
        {
            "name": "Yeelighter",
            "timeout": 5000,
            "interval": 60000,
            "ctforcolor": true,
            "blocking": true,
            "split": false,
            "override": [
                {
                    "offOnDisconnect": true
                }
            ],
            "platform": "Yeelighter"
        },
        {
            "name": "G-On Alice",
            "username": "",
            "password": "",
            "pin": "",
            "debug": false,
            "platform": "G-On Alice"
        },
        {
            "devices": [
                {
                    "name": "1c cleaner",
                    "ip": "192.168.1.52",
                    "token": "",
                    "pollingInterval": 7,
                    "deepDebugLog": false,
                    "micloud": {
                        "timeout": 5000
                    },
                    "buzzerControl": true,
                    "ledControl": true,
                    "modeControl": false,
                    "mopModeControl": false,
                    "dndControl": false,
                    "showTemperature": true
                }
            ],
            "platform": "miot"
        }
    ],
    "accessories": [
        {
            "showTemperatureDisable": false,
            "ip": "192.168.1.58",
            "updateTimer": 300,
            "token": "",
            "model": "ca1",
            "name": "Увлажнитель",
            "accessory": "MiHumidifier"
        },
        {
            "name": "Xiaomi BLE Temperature sensor",
            "address": "A4:C1:38:29:4C:CB",
            "temperatureName": "Температура BLE Детская",
            "humidityName": "Влажность BLE Детская",
            "fakeGatoEnabled": true,
            "timeout": 15,
            "forceDiscovering": true,
            "forceDiscoveringDelay": 2500,
            "disableBatteryLevel": false,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "bindKey": "",
            "accessory": "Hygrotermograph"
        },
        {
            "name": "Xiaomi BLE Temperature clock",
            "address": "E7:2E:00:E0:C0:6F",
            "temperatureName": "Температура BLE Гостиная",
            "humidityName": "Влажность BLE Гостиная",
            "timeout": 15,
            "accessory": "Hygrotermograph"
        },
        {
            "name": "Multipurpose Kettle",
            "mode": "switch",
            "ip": "192.168.1.47",
            "token": "",
            "switchMode": null,
            "thermostatMode": null,
            "heat": 95,
            "sound": false,
            "temperature": true,
            "sensor": false,
            "interval": 5,
            "accessory": "MiMultipurposeKettle"
        }
    ]
}
```

### Environment

- OS: Raspbian GNU/Linux Buster (10)
- Software: Homebridge v1.5.0
- Node: v16.17.0
- npm 8.15.0

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Looking at the log provided it appears to be triggered by the plugin not finding your kettle.  Can you raise this against the plugin, so the plugin developer has visibility to this.

@Supereg is this an unhandled exception in hapnodejs ?

**Comment by jorgemsccc** [comment]
> Looking at the log provided it appears to be triggered by the plugin not finding your kettle. Can you raise this against the plugin, so the plugin developer has visibility to this.
> 
> @Supereg is this an unhandled exception in hapnodejs ?

I removed the kettle, tried without it. After some time same error and restart. Tried deleting config-ui-x and reinstalling it. The problem went away for a few hours, but then reappeared.

**Comment by NorthernMan54** [comment]
Looking at the section of code around the exception, it is in the request handler for HomeKit messages from iDevices etc.

Is your setup unusual or have odd networking?

**Comment by jorgemsccc** [comment]
> Looking at the section of code around the exception, it is in the request handler for HomeKit messages from iDevices etc.
> 
> Is your setup unusual or have odd networking?

i have "reverse" homekit to other service

**Comment by NorthernMan54** [comment]
Which "reverse" homekit server ?

I'm using HomeKit-controller without issue

**Comment by jorgemsccc** [comment]
> Which "reverse" homekit server ?
> 
> I'm using HomeKit-controller without issue

Spruthub

and the problem appeared again

08/09/2022, 00:31:36] [Yeelighter] [0x00000000076d7104] temperature light updated {"power":false,"color_mode":2,"bright":100,"hue":0,"sat":0,"ct":4500,"bg_power":false,"bg_bright":100,"bg_hue":20,"bg_sat":100,"bg_ct":6494,"bg_lmode":3,"nl_br":0,"active_mode":0,"name":""} []
[08/09/2022, 00:33:49] [G-On Alice] aliceDiscovery - returned 8 devices
[08/09/2022, 00:35:44] [Homebridge UI] Starting terminal session
[08/09/2022, 00:40:23] TypeError: Cannot read properties of null (reading 'setNoDelay')
    at HAPConnection.handleHttpServerRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:634:25)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:980:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
[08/09/2022, 00:40:23] Got SIGTERM, shutting down Homebridge...
[08/09/2022, 00:40:28] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[08/09/2022, 00:40:33] [HB Supervisor] Restarting Homebridge...
[08/09/2022, 00:40:33] [HB Supervisor] Starting Homebridge with extra flags: -I
[08/09/2022, 00:40:33] [HB Supervisor] Started Homebridge v1.5.0 with PID: 2284

**Comment by Supereg** [comment]
For reference, the line of concern: https://github.com/homebridge/HAP-NodeJS/blob/f20ee4ba4f0f5192761e1f36b73bca9a09b1c47b/src/lib/util/eventedhttp.ts#L634

Might be related to some deprecations in the latest node versions? Not sure why it happens irregularly.

**Comment by jorgemsccc** [comment]
what should I do? the problem is floating, it may not appear for several days

**Comment by Supereg** [comment]
I removed the line of code making issues (reasoning explained in the referenced PR https://github.com/homebridge/HAP-NodeJS/pull/968). Will push a homebridge beta update containing the fix soon.
