### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by Olivierbkk** [homebridge/homebridge#3272]
### Analysis

The version 1.6.0 update keeps failing.

### Expected Behavior

It should update.

### Steps To Reproduce

Just run the update

### Logs

```markdown
...
541 timing reify:unpack Completed in 109427ms
542 timing reify:rollback:createSparse Completed in 22031ms
543 timing reify:rollback:retireShallow Completed in 296ms
544 timing command:install Completed in 325863ms
545 verbose stack Error: process terminated
545 verbose stack     at /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:199:39
545 verbose stack     at process.<anonymous> (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:53:5)
545 verbose stack     at process.emit (node:events:525:35)
546 verbose cwd /var/lib/homebridge
547 verbose Linux 5.15.32+
548 verbose node v18.12.1
549 verbose npm  v8.19.2
550 error process terminated
551 error signal SIGTERM
552 verbose exit 1
553 timing npm Completed in 333822ms
554 verbose unfinished npm timer reify 1669529799971
555 verbose code 1
556 error A complete log of this run can be found in:
556 error     /home/ob/.npm/_logs/2022-11-27T06_16_32_253Z-debug-0.log
```

### Configuration

```json
{
    "bridge": {
        "name": "",
        "username": "",
        "port":,
        "pin": "",
        "advertiser": "avahi"
    },
    "accessories": [
        {
            "name": "Security System",
            "default_mode": "Off",
            "arm_seconds": 0,
            "trigger_seconds": 0,
            "reset_minutes": 10,
            "save_state": true,
            "proxy_mode": false,
            "test_mode": false,
            "override_off": false,
            "reset_off_flow": true,
            "double_knock": false,
            "double_knock_seconds": 90,
            "double_knock_modes": [
                "Away"
            ],
            "disabled_modes": [
                "Home"
            ],
            "tripped_sensor": false,
            "tripped_sensor_seconds": 3,
            "siren_sensor": false,
            "siren_sensor_seconds": 2,
            "reset_sensor": false,
            "mode_switches": false,
            "mode_off_switch": false,
            "mode_away_extended_switch": false,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "arming_lock_switch": false,
            "arming_lock_switches": false,
            "siren_switch": false,
            "siren_override_switch": false,
            "siren_mode_switches": true,
            "audio_switch": false,
            "audio": false,
            "audio_language": "en-US",
            "audio_volume": "100",
            "audio_arming_looped": false,
            "audio_alert_looped": false,
            "accessory": "security-system"
        },
        {
            "name": "Presence Simulator",
            "sensors": [
                {
                    "name": "Random Entrance Light"
                },
                {
                    "name": "Random Office Light"
                },
                {
                    "name": "Random Kitchen light"
                },
                {
                    "name": "Random Bedroom light"
                }
            ],
            "minOffTime": 600,
            "maxOffTime": 1200,
            "minOnTime": 60,
            "maxOnTime": 600,
            "activeTimes": [
                {
                    "start": "18:00",
                    "end": "23:20",
                    "absolute": true,
                    "maxActivations": 20
                }
            ],
            "accessory": "AwayMode"
        },
        {
            "name": "Last Arming failed",
            "stateful": true,
            "reverse": false,
            "time": 3000,
            "random": false,
            "resettable": false,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "Guest Mode",
            "stateful": true,
            "reverse": false,
            "time": 1000,
            "random": false,
            "resettable": false,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "Mi Air Purifier Pro",
            "address": "",
            "token": "",
            "enableAirQuality": true,
            "enableTemperature": true,
            "enableHumidity": true,
            "filterChangeThreshold": 5,
            "enableFanSpeedControl": true,
            "enableChildLockControl": false,
            "accessory": "XiaomiMiAirPurifier"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port":,
            "platform": "config"
        },
        {
            "name": "RPi",
            "hosts": [
                {
                    "host": "raspberrypi",
                    "devices": [
                        {
                            "device": "light",
                            "name": "Gate",
                            "gpio": 8,
                            "reversed": true
                        },
                        {
                            "device": "button",
                            "name": "Gate light",
                            "gpio": 25
                        },
                        {
                            "device": "light",
                            "name": "Garage",
                            "gpio": 9,
                            "reversed": true
                        },
                        {
                            "device": "button",
                            "name": "Garage light",
                            "gpio": 27
                        },
                        {
                            "device": "light",
                            "name": "Entrance",
                            "gpio": 10,
                            "reversed": true
                        },
                        {
                            "device": "button",
                            "name": "Entrance light",
                            "gpio": 4
                        },
                        {
                            "device": "light",
                            "name": "Dining area",
                            "gpio": 2,
                            "reversed": true
                        },
                        {
                            "device": "rocker",
                            "name": "Dining area light",
                            "gpio": 7
                        },
                        {
                            "device": "light",
                            "name": "Office",
                            "gpio": 3,
                            "reversed": true
                        },
                        {
                            "device": "rocker",
                            "name": "Office light",
                            "gpio": 11
                        },
                        {
                            "device": "contact",
                            "name": "Gate",
                            "gpio": 14
                        },
                        {
                            "device": "contact",
                            "name": "Entrance",
                            "gpio": 22
                        },
                        {
                            "device": "contact",
                            "name": "Left zone",
                            "gpio": 23
                        },
                        {
                            "device": "contact",
                            "name": "Back zone",
                            "gpio": 24
                        },
                        {
                            "device": "switch",
                            "name": "Gate motor",
                            "gpio": 18,
                            "reversed": true,
                            "pulse": 500
                        },
                        {
                            "device": "contact",
                            "name": "Right zone",
                            "gpio": 17
                        },
                        {
                            "device": "motion",
                            "name": "Down PIR",
                            "gpio": 15,
                            "reversed": true
                        }
                    ]
                }
            ],
            "platform": "RPi"
        },
        {
            "username": "",
            "password": "",
            "disableFan": true,
            "disableDry": true,
            "ignoreHomeKitDevices": false,
            "enableSyncButton": false,
            "syncButtonInAccessory": false,
            "enableOccupancySensor": false,
            "enableClimateReactSwitch": false,
            "enableHistoryStorage": true,
            "disableHorizontalSwing": true,
            "disableLightSwitch": true,
            "externalHumiditySensor": false,
            "allowRepeatedCommands": true,
            "debug": false,
            "platform": "SensiboAC"
        },
        {
            "name": "Plugin Update",
            "sensorType": "motion",
            "platform": "PluginUpdate"
        },
        {
            "devices": [
                {
                    "ipAddress": "",
                    "serialNumber": "",
                    "credentials": "=",
                    "useFahrenheit": false,
                    "enableAutoModeWhenActivating": false,
                    "enableOscillationWhenActivating": true,
                    "enableNightModeWhenActivating": false,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isContinuousMonitoringEnabled": false,
                    "isTemperatureSensorEnabled": true,
                    "isTemperatureIgnored": false,
                    "temperatureOffset": 0,
                    "isHumiditySensorEnabled": true,
                    "isHumidityIgnored": false,
                    "humidityOffset": 0,
                    "isAirQualitySensorEnabled": true,
                    "isAirQualityIgnored": false,
                    "isSingleSensorAccessoryModeEnabled": false,
                    "isSingleAccessoryModeEnabled": false,
                    "isFullRangeHumidity": false,
                    "isHeatingDisabled": false,
                    "isHeatingSafetyIgnored": false
                },
                {
                    "ipAddress": "",
                    "serialNumber": "",
                    "credentials": "",
                    "useFahrenheit": false,
                    "enableAutoModeWhenActivating": false,
                    "enableOscillationWhenActivating": true,
                    "enableNightModeWhenActivating": false,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isContinuousMonitoringEnabled": false,
                    "isTemperatureSensorEnabled": true,
                    "isTemperatureIgnored": false,
                    "temperatureOffset": 0,
                    "isHumiditySensorEnabled": true,
                    "isHumidityIgnored": false,
                    "humidityOffset": 0,
                    "isAirQualitySensorEnabled": true,
                    "isAirQualityIgnored": false,
                    "isSingleSensorAccessoryModeEnabled": false,
                    "isSingleAccessoryModeEnabled": false,
                    "isFullRangeHumidity": false,
                    "isHeatingDisabled": false,
                    "isHeatingSafetyIgnored": false
                },
                {
                    "ipAddress": "",
                    "serialNumber": "A",
                    "credentials": "",
                    "useFahrenheit": false,
                    "enableAutoModeWhenActivating": false,
                    "enableOscillationWhenActivating": true,
                    "enableNightModeWhenActivating": false,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isContinuousMonitoringEnabled": false,
                    "isTemperatureSensorEnabled": true,
                    "isTemperatureIgnored": false,
                    "temperatureOffset": 0,
                    "isHumiditySensorEnabled": true,
                    "isHumidityIgnored": false,
                    "humidityOffset": 0,
                    "isAirQualitySensorEnabled": true,
                    "isAirQualityIgnored": false,
                    "isSingleSensorAccessoryModeEnabled": false,
                    "isSingleAccessoryModeEnabled": false,
                    "isFullRangeHumidity": false,
                    "isHeatingDisabled": false,
                    "isHeatingSafetyIgnored": false
                }
            ],
            "updateInterval": 60000,
            "credentialsGeneratorPort":,
            "platform": "DysonPureCoolPlatform"
        },
        {
            "options": {
                "username": "",
                "password": "",
                "accessId": "",
                "accessKey": "",
                "lang": "en",
                "projectType": "2",
                "appSchema": "tuyaSmart",
                "countryCode": ,
                "debug": false
            },
            "name": "TuyaPlatform",
            "platform": "TuyaPlatform"
        }
    ],
    "disabledPlugins": [
        "homebridge-device-alive",
        "homebridge-delay-switch",
        "homebridge-logic-switch",
        "homebridge-magic-occupancy",
        "homebridge-schedule",
        "homebridge-weather-plus",
        "homebridge-miot"
    ]
}
```

### Environment

- OS: Raspbian GNU/Linux Bullseye (11)
- Software: homebridge 1.5.1
- Node: v18.12.1
- npm: v8.19.2

### Process Supervisor

not applicable

### Additional Context

not sure about the process supervisor

**Comment by cl4udiu5** [comment]
The same error for me
<img width="795" alt="Bildschirm­foto 2022-11-30 um 11 27 31" src="https://user-images.githubusercontent.com/74124378/204773050-d7b6307e-1ea3-4bcc-af25-4d00d049cfd6.png">
<img width="502" alt="Bildschirm­foto 2022-11-30 um 11 27 41" src="https://user-images.githubusercontent.com/74124378/204773061-0a52b3e7-b22d-4532-bcf3-72d6c5e9547f.png">

**Comment by cl4udiu5** [comment]
Updating via macOS Terminal is working, but after restarting (hb-service restart), Homebridge GUI still shows version 1.5.1
<img width="313" alt="Bildschirm­foto 2022-12-01 um 12 39 29" src="https://user-images.githubusercontent.com/74124378/205043905-e80bcc50-8aae-4d54-ac51-6adce2059c36.png">

**Comment by roger-richards** [comment]
Same problem with Pi Zero W

**Comment by Olivierbkk** [comment]
anyone found a solution yet?

**Comment by JurgenLB** [comment]
I would recommend to make a back-up from your config and accessoires.
after that just install Homebridge as described in [https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian]

**Comment by Olivierbkk** [comment]
found a solution that worked: https://github.com/homebridge/homebridge/issues/1870#issuecomment-541853198
