### ISSUE TITLE
ERROR: The user interface threw an unhandled error

### ISSUE THREAD

**Issue by iMonZ** [homebridge/homebridge#3283]
### Current Situation

Neither the Web interface start nor it's accessible from the Home App.

Since Matter for Hue came out, I thought it's a try worth. Since it turns out that it isn't really stable, I returned to Home bridge. Worked before but now suddenly it just doesn't work at all!

### Logs

```markdown
[12/6/2022, 10:51:19 PM] Loaded plugin: homebridge-dyson-pure-cool@2.7.5
[12/6/2022, 10:51:19 PM] Registering platform 'homebridge-dyson-pure-cool.DysonPureCoolPlatform'
[12/6/2022, 10:51:19 PM] ---
[12/6/2022, 10:51:19 PM] Loaded plugin: homebridge-gsh@2.2.0
[12/6/2022, 10:51:19 PM] Registering platform 'homebridge-gsh.google-smarthome'
[12/6/2022, 10:51:19 PM] ---
[12/6/2022, 10:51:27 PM] [HB Supervisor] OS: Linux 5.15.0-1021-raspi arm64
[12/6/2022, 10:51:27 PM] [HB Supervisor] Node.js v18.12.1 /opt/homebridge/bin/node
[12/6/2022, 10:51:27 PM] [HB Supervisor] Homebridge Path: /var/lib/homebridge/node_modules/homebridge/bin/homebridge
[12/6/2022, 10:51:27 PM] [HB Supervisor] UI Path: /opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[12/6/2022, 10:51:32 PM] [HB Supervisor] ERROR: The user interface threw an unhandled error
Error: unsupported
    at configSecureContext (node:internal/tls/secure-context:277:15)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1352:27)
    at Server (node:_tls_wrap:1211:8)
    at new Server (node:https:74:3)
    at Object.createServer (node:https:112:10)
    at getServerInstance (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/fastify/lib/server.js:284:22)
    at createServer (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/fastify/lib/server.js:15:18)
    at fastify (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/fastify/fastify.js:185:30)
    at new FastifyAdapter (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:82:37)
    at bootstrap (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/main.js:31743:22)
    at HomebridgeServiceHelper.runUi (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/src/bin/hb-service.ts:528:18)
    at HomebridgeServiceHelper.launch (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/src/bin/hb-service.ts:370:5)
[12/6/2022, 10:51:32 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[12/6/2022, 10:51:32 PM] [HB Supervisor] Started Homebridge v1.6.0 with PID: 9503
[12/6/2022, 10:51:33 PM] Loaded config.json with 0 accessories and 4 platforms.
[12/6/2022, 10:51:33 PM] Loaded 5 cached accessories from cachedAccessories.
[12/6/2022, 10:51:33 PM] ---
[12/6/2022, 10:51:34 PM] Loaded plugin: homebridge-dyson-pure-cool@2.7.5
[12/6/2022, 10:51:34 PM] Registering platform 'homebridge-dyson-pure-cool.DysonPureCoolPlatform'
[12/6/2022, 10:51:34 PM] ---
[12/6/2022, 10:51:34 PM] Loaded plugin: homebridge-gsh@2.2.0
[12/6/2022, 10:51:34 PM] Registering platform 'homebridge-gsh.google-smarthome'
[12/6/2022, 10:51:34 PM] ---
[12/6/2022, 10:51:43 PM] [HB Supervisor] OS: Linux 5.15.0-1021-raspi arm64
[12/6/2022, 10:51:43 PM] [HB Supervisor] Node.js v18.12.1 /opt/homebridge/bin/node
[12/6/2022, 10:51:43 PM] [HB Supervisor] Homebridge Path: /var/lib/homebridge/node_modules/homebridge/bin/homebridge
[12/6/2022, 10:51:43 PM] [HB Supervisor] UI Path: /opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[12/6/2022, 10:51:48 PM] [HB Supervisor] ERROR: The user interface threw an unhandled error
Error: unsupported
    at configSecureContext (node:internal/tls/secure-context:277:15)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1352:27)
    at Server (node:_tls_wrap:1211:8)
    at new Server (node:https:74:3)
    at Object.createServer (node:https:112:10)
    at getServerInstance (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/fastify/lib/server.js:284:22)
    at createServer (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/fastify/lib/server.js:15:18)
    at fastify (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/fastify/fastify.js:185:30)
    at new FastifyAdapter (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:82:37)
    at bootstrap (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/main.js:31743:22)
    at HomebridgeServiceHelper.runUi (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/src/bin/hb-service.ts:528:18)
    at HomebridgeServiceHelper.launch (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/src/bin/hb-service.ts:370:5)
[12/6/2022, 10:51:48 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[12/6/2022, 10:51:48 PM] [HB Supervisor] Started Homebridge v1.6.0 with PID: 9529
[12/6/2022, 10:51:49 PM] Loaded config.json with 0 accessories and 4 platforms.
[12/6/2022, 10:51:49 PM] Loaded 5 cached accessories from cachedAccessories.
[12/6/2022, 10:51:49 PM] ---
[12/6/2022, 10:51:50 PM] Loaded plugin: homebridge-dyson-pure-cool@2.7.5
[12/6/2022, 10:51:50 PM] Registering platform 'homebridge-dyson-pure-cool.DysonPureCoolPlatform'
[12/6/2022, 10:51:50 PM] ---
[12/6/2022, 10:51:50 PM] Loaded plugin: homebridge-gsh@2.2.0
[12/6/2022, 10:51:50 PM] Registering platform 'homebridge-gsh.google-smarthome'
[12/6/2022, 10:51:50 PM] ---
[12/6/2022, 10:51:58 PM] [HB Supervisor] OS: Linux 5.15.0-1021-raspi arm64
[12/6/2022, 10:51:58 PM] [HB Supervisor] Node.js v18.12.1 /opt/homebridge/bin/node
[12/6/2022, 10:51:58 PM] [HB Supervisor] Homebridge Path: /var/lib/homebridge/node_modules/homebridge/bin/homebridge
[12/6/2022, 10:51:58 PM] [HB Supervisor] UI Path: /opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[12/6/2022, 10:52:03 PM] [HB Supervisor] ERROR: The user interface threw an unhandled error
Error: unsupported
    at configSecureContext (node:internal/tls/secure-context:277:15)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1352:27)
    at Server (node:_tls_wrap:1211:8)
    at new Server (node:https:74:3)
    at Object.createServer (node:https:112:10)
    at getServerInstance (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/fastify/lib/server.js:284:22)
    at createServer (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/fastify/lib/server.js:15:18)
    at fastify (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/fastify/fastify.js:185:30)
    at new FastifyAdapter (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:82:37)
    at bootstrap (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/main.js:31743:22)
    at HomebridgeServiceHelper.runUi (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/src/bin/hb-service.ts:528:18)
    at HomebridgeServiceHelper.launch (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/src/bin/hb-service.ts:370:5)
[12/6/2022, 10:52:03 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[12/6/2022, 10:52:03 PM] [HB Supervisor] Started Homebridge v1.6.0 with PID: 9574
[12/6/2022, 10:52:04 PM] Loaded config.json with 0 accessories and 4 platforms.
[12/6/2022, 10:52:04 PM] Loaded 5 cached accessories from cachedAccessories.
[12/6/2022, 10:52:04 PM] ---
[12/6/2022, 10:52:05 PM] Loaded plugin: homebridge-dyson-pure-cool@2.7.5
[12/6/2022, 10:52:05 PM] Registering platform 'homebridge-dyson-pure-cool.DysonPureCoolPlatform'
[12/6/2022, 10:52:05 PM] ---
[12/6/2022, 10:52:05 PM] Loaded plugin: homebridge-gsh@2.2.0
[12/6/2022, 10:52:05 PM] Registering platform 'homebridge-gsh.google-smarthome'
[12/6/2022, 10:52:05 PM] ---
[12/6/2022, 10:53:00 PM] [HB Supervisor] OS: Linux 5.15.0-1021-raspi arm64
[12/6/2022, 10:53:00 PM] [HB Supervisor] Node.js v18.12.1 /opt/homebridge/bin/node
[12/6/2022, 10:53:00 PM] [HB Supervisor] Homebridge Path: /var/lib/homebridge/node_modules/homebridge/bin/homebridge
[12/6/2022, 10:53:00 PM] [HB Supervisor] UI Path: /opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[12/6/2022, 10:53:05 PM] [HB Supervisor] ERROR: The user interface threw an unhandled error
```

### Configuration

```json
{
    "bridge": {
        "name": "pibridge3",
        "username": "censored",
        "manufacturer": "censored",
        "model": "pibridge3",
        "port": 51827,
        "pin": "censored"
    },
    "description": "This is a Pi Bridge",
    "platforms": [
        {
            "name": "Config",
            "port": 8582,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "de",
            "ssl": {
                "pfx": "censored",
                "passphrase": "censored"
            },
            "platform": "config"
        },
        {
            "devices": [
                {
                    "ipAddress": "censored",
                    "serialNumber": "censored",
                    "credentials": "censored",
                    "enableAutoModeWhenActivating": false,
                    "enableOscillationWhenActivating": false,
                    "isNightModeEnabled": true,
                    "isJetFocusEnabled": true,
                    "isContinuousMonitoringEnabled": true,
                    "isTemperatureSensorEnabled": true,
                    "isHumiditySensorEnabled": true,
                    "isAirQualitySensorEnabled": true,
                    "isSingleSensorAccessoryModeEnabled": false,
                    "isSingleAccessoryModeEnabled": false,
                    "isFullRangeHumidity": false,
                    "isHeatingDisabled": false
                }
            ],
            "updateInterval": 30000,
            "platform": "DysonPureCoolPlatform"
        },
        {
            "name": "Hue",
            "anyOn": true,
            "hosts": [
                "censored"
            ],
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "nupnp": true,
            "resource": true,
            "platform": "Hue",
            "lights": "true",
            "users": {
                "censored": "censored"
            }
        }
    ],
    "accessories": []
}
```

### Environment

- OS: Ubuntu 22.04
- Software: 1.6.0
- Node: v18.12.1

### Process Supervisor

hb-service

**Comment by nebosphere19** [comment]
I had a similar problem - did you find a resolution?
