### ISSUE TITLE
After years, without any change I have Error: listen EADDRINUSE: address already in use :::51774

### ISSUE THREAD

**Issue by acaonweb** [homebridge/homebridge#3288]
### Analysis

This is what I a get
[18/12/2022, 12:02:22] Error: listen EADDRINUSE: address already in use :::51774
    at Server.setupListenHandle [as _listen2] (node:net:1463:16)
    at listenInCluster (node:net:1511:12)
    at Server.listen (node:net:1599:7)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)

### Expected Behavior

no errors

### Steps To Reproduce

I don't know, tried to change port on config, but after that all my plugins doesn't work

### Logs

```markdown
[18/12/2022, 12:02:22] Error: listen EADDRINUSE: address already in use :::51774
    at Server.setupListenHandle [as _listen2] (node:net:1463:16)
    at listenInCluster (node:net:1511:12)
    at Server.listen (node:net:1599:7)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
```

### Configuration

```json
"bridge": {
        "name": "Homebridge",
        "username": "0E:52:F9:17:34:7B",
        "port": 51774,
        "pin": "021-09-968",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8081,
            "auth": "none",
            "theme": "dark-mode-blue-grey",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Domoticz",
            "server": "myusername:mypassword@172.16.1.152",
            "port": "8080",
            "roomid": 7,
            "mqtt": true,
            "ssl": false,
            "dimFix": 0,
            "platform": "eDomoticz"
        },
        {
            "name": "Alexa",
            "username": "acaonweb",
            "password": "Debor@10",
            "pin": "021-09-968",
            "routines": true,
            "blind": false,
            "door": false,
            "debug": false,
            "deviceListHandling": "allow",
            "platform": "Alexa"
        }
    ],
    "disabledPlugins": [
        "homebridge-tasmota"
    ]
}
```

### Environment

- OS:

> RETTY_NAME="Raspbian GNU/Linux 10 (buster)"
> NAME="Raspbian GNU/Linux"
> VERSION_ID="10"
> VERSION="10 (buster)"
> VERSION_CODENAME=buster
> ID=raspbian
> ID_LIKE=debian
> HOME_URL="http://www.raspbian.org/"
> SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
> BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

- Software:

- Node:
  v16.18.1

- npm:
8.19.2

### Process Supervisor

systemd

### Additional Context

help me!!! ;)

**Comment by acaonweb** [comment]
I've resolved changing port, reinstalling my plugins, but question remain...
