### ISSUE TITLE
Homebridge fresh install

### ISSUE THREAD

**Issue by Razahtlab** [homebridge/homebridge#3309]
### Current Situation

Hi all, I recently started using homebridge on a Raspberry Pi 4B. I got it working allright, but in my innocence/negligence/stupidity I screwed something up after I rebooted my TP-Link Deco system.

So when nothing else seemed to work, I formatted the SD-card and made a fresh install of the Homebridge image - but unfortunately, it seems even worse than it was before. I still get this log all the time (as it did just before I reinstalled): [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded"

But now I can't even install new plugins. When I search for a plugin, this is the (similar) message I get: 
Failed to search the npm registry - "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.

My internet connection is fine, so I have no idea where to look, and things like DNS are still complete gobbledygook to me, so I have no idea how to proceed... Should I throw the Raspberry Pi in the trash en buy a new one? :)

I'll add the debug log. Hope someone can help!

### Logs

```markdown
HAP-NodeJS:Advertiser Detected Avahi over DBus interface running version 'avahi 0.8'. +0ms
  HAP-NodeJS:Advertiser Preparing Advertiser for 'Homebridge C838 F2DA' using Avahi backend! +4ms
[18/01/2023, 13:48:18] Error: listen EADDRINUSE: address already in use :::51502
    at Server.setupListenHandle [as _listen2] (node:net:1485:16)
    at listenInCluster (node:net:1533:12)
    at Server.listen (node:net:1621:7)
    at EventedHTTPServer.listen (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:156:20)
    at HAPServer.listen (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:332:21)
    at Bridge.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1281:18)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[18/01/2023, 13:48:18] Got SIGTERM, shutting down Homebridge...
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge C838",
        "username": "",
        "port": 51502,
        "pin": "",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

### Environment

- OS: Raspbian GNU/Linux Bullseye (11)
- Software: Homebridge v1.5.1
- Node: v18.12.1
- npm: 8.19.2

### Process Supervisor

other (Explain in `Additional Context`)

### Additional Context

Not sure...

**Comment by NorthernMan54** [comment]
That log is indicating that something is already running on the RPI

`Error: listen EADDRINUSE: address already in use :::51502`

Since your just starting out, I would recommend just redoing the Homebridge image on the SD card and starting again.

**Comment by Razahtlab** [comment]
Thanks @NorthernMan54. But that is exactly what I did... :( And this log is after the new homebridge install on the SD-card.

**Comment by Razahtlab** [comment]
Unfortunately, yes. So no clue what is wrong

**Comment by NorthernMan54** [comment]
Have you tried changing the port in the config, that is what is being reported as the issue.

**Comment by Razahtlab** [comment]
Wow, that seems to have done the trick! I tried changing it to the port it used before I reinstalled everything.
Thanks a lot!
