### ISSUE TITLE
Thermostat reporting incorrect temp

### ISSUE THREAD

**Issue by Clayton1212** [homebridge/homebridge#3319]
### Analysis

I am using this Tuya 16a thermostat https://www.aliexpress.com/item/1005001891372138.html
the device is reporting correct accurate temperatures in the Tuya app however through this plugin in Homebridge it is reporting 150 celsius instead of 55. 

### Expected Behavior

report correct temps in homekit and Homebridge

### Steps To Reproduce

just run the device and you will see the issue

### Logs

```markdown
[16/02/2023, 07:56:43] [TuyaWebPlatform] [Geyser thermostat] - Requesting device state
[16/02/2023, 07:56:43] [TuyaWebPlatform] [Geyser thermostat] - Creating new debounced promise
[16/02/2023, 07:56:43] [TuyaWebPlatform] [Geyser thermostat] - Triggering debouncedDeviceStateRequest
[16/02/2023, 07:56:43] [TuyaWebPlatform] [Geyser thermostat] - Requesting device state
[16/02/2023, 07:56:43] [TuyaWebPlatform] [Geyser thermostat] - Triggering debouncedDeviceStateRequest
[16/02/2023, 07:56:43] [TuyaWebPlatform] [Geyser thermostat] - Requesting device state
[16/02/2023, 07:56:43] [TuyaWebPlatform] [Geyser thermostat] - Triggering debouncedDeviceStateRequest
[16/02/2023, 07:56:43] [TuyaWebPlatform] [Geyser thermostat] - Requesting device state
[16/02/2023, 07:56:43] [TuyaWebPlatform] [Geyser thermostat] - Triggering debouncedDeviceStateRequest
[16/02/2023, 07:56:44] [TuyaWebPlatform] [Geyser thermostat] - Unsetting debouncedDeviceStateRequestPromise
[16/02/2023, 07:56:44] [TuyaWebPlatform] [Geyser thermostat] - Resolving resolveDeviceStateRequest from cache
[16/02/2023, 07:56:44] [TuyaWebPlatform] [Geyser thermostat] Characteristic.CurrentHeatingCoolingState - [GET] { state: 'true', mode: undefined }
[16/02/2023, 07:56:44] [TuyaWebPlatform] [Geyser thermostat] Characteristic.CurrentHeatingCoolingState - [UPDATE] HEAT
[16/02/2023, 07:56:44] [TuyaWebPlatform] [Geyser thermostat] Characteristic.TargetHeatingCoolingState - [GET] { state: 'true', mode: undefined }
[16/02/2023, 07:56:44] [TuyaWebPlatform] [Geyser thermostat] Characteristic.TargetHeatingCoolingState - [UPDATE] AUTO
[16/02/2023, 07:56:44] [TuyaWebPlatform] [Geyser thermostat] Characteristic.CurrentTemperature - [GET] 525
[16/02/2023, 07:56:44] [TuyaWebPlatform] [Geyser thermostat] Characteristic.CurrentTemperature - [UPDATE] 525
[16/02/2023, 07:56:44] [@milo526/homebridge-tuya-web] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 525 exceeded maximum of 150. See https://homebridge.io/w/JtMGR for more info.
[16/02/2023, 07:56:44] [@milo526/homebridge-tuya-web] Error: 
    at CurrentTemperature.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at CurrentTemperature.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2927:14)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2488:24
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:15:18
    at CurrentTemperatureCharacteristic.updateValue (/var/lib/homebridge/node_modules/@milo526/homebridge-tuya-web/src/accessories/characteristics/currentTemperature.ts:50:19)
    at /var/lib/homebridge/node_modules/@milo526/homebridge-tuya-web/src/accessories/characteristics/currentTemperature.ts:31:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[16/02/2023, 07:56:44] [TuyaWebPlatform] [Geyser thermostat] Characteristic.TargetTemperature - [GET] 50
[16/02/2023, 07:56:44] [TuyaWebPlatform] [Geyser thermostat] Characteristic.TargetTemperature - [UPDAT
```

### Configuration

```json
{
    "name": "TuyaWebPlatform",
    "options": {
        "username": "07-rifling.heather@icloud.com",
        "password": "(Tuya1209))34",
        "countryCode": "27",
        "platform": "tuya"
    },
    "defaults": [
        {
            "id": "bf036626cb04d0c4aapnd5",
            "device_type": "climate",
            "min_temper": "35",
            "max_temper": "65"
        }
    ],
    "scenes": false,
    "platform": "TuyaWebPlatform"
}
```

### Environment

- OS: raspberry pi
- Software: homebridge
- Node: not sure
- npm: not sure

### Process Supervisor

not applicable

**Comment by NorthernMan54** [comment]
Please raise this issue against the plugin itself, so that the plugin developer is aware of the issue, and can look into it.  Tks
