### ISSUE TITLE
Problem with changing colour on Led Digital Strip-v2.0-rgbcct Product Category dd

### ISSUE THREAD

**Issue by DriesBeast** [homebridge/homebridge#3337]
### Current Situation

I am trying to set the colour on the LED Strip via the Apple Homekit app on my iPhone.
Brightness does work
colour doesn't

### Logs

```markdown
[19-3-2023 13:55:57] [TuyaPlatform] [Smart Digital LED Strip] Characteristic.Saturation set to: 100
[19-3-2023 13:55:57] [@0x5e/homebridge-tuya-platform] This plugin threw an error from the characteristic 'Saturation': Unhandled error thrown inside write handler for characteristic: Unexpected number in JSON at position 1. See https://homebridge.io/w/JtMGR for more info.
[19-3-2023 13:55:57] [@0x5e/homebridge-tuya-platform] SyntaxError: Unexpected number in JSON at position 1
at JSON.parse ()
at getColorValue (/usr/lib/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/characteristic/Light.ts:63:28)
at Saturation.setHandler (/usr/lib/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/characteristic/Light.ts:260:26)
at Saturation. (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2547:42)
at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
at new Promise ()
at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:16)
at Saturation.Characteristic.handleSetRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:871:24)
[19-3-2023 13:55:57] [TuyaPlatform] [Smart Digital LED Strip] Characteristic.Hue set to: 60
[19-3-2023 13:55:57] [@0x5e/homebridge-tuya-platform] This plugin threw an error from the characteristic 'Hue': Unhandled error thrown inside write handler for characteristic: Unexpected number in JSON at position 1. See https://homebridge.io/w/JtMGR for more info.
[19-3-2023 13:55:57] [@0x5e/homebridge-tuya-platform] SyntaxError: Unexpected number in JSON at position 1
at JSON.parse ()
at getColorValue (/usr/lib/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/characteristic/Light.ts:63:28)
at Hue.setHandler (/usr/lib/node_modules/@0x5e/homebridge-tuya-platform/src/accessory/characteristic/Light.ts:225:26)
at Hue. (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2547:42)
at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
at new Promise ()
at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:16)
at Hue.Characteristic.handleSetRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:871:24)
```

### Configuration

```json
{
    "bridge": {
        "name": 
        "username": 
        "port": 
        "pin": 
        "bind": [
            "eth0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": 
            "port": 
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": 
                "password": 
                "countryCode": 
                "platform": "tuya",
                "pollingInterval": 600
            },
            "defaults": [
                {
                    "id": 
                    "device_type": "light",
                    "light_characteristics": [
                        "Brightness",
                        "Color",
                        "Color Temperature"
                    ]
                }
            ],
            "scenes": true,
            "scenesWhitelist": [
                "LED Rainbow",
                "Moodlight rainbow",
                "Lampen Aan",
                "Lampen Uit"
            ],
            "hiddenAccessories": [
                "Slaapkamer Lamp Kast",
                "Slaapkamer Lamp Bureau",
                "Slaapkamer Lamp Grond",
                "Slaapkamer Lamp Bed",
                "Bureau Stroom",
                "Bureau Lamp RGB",
                "Ventilator",
                "Stroom Laptop",
                "Stroom Camera’s",
                "Stroom XPS",
                "LED Bed"
            ],
            "platform": "TuyaWebPlatform"
        },
        {
            "options": {
                "projectType": "2",
                "accessId": 
                "accessKey": 
                "countryCode": 
                "username": 
                "password": 
                "appSchema": "tuyaSmart",
                "deviceOverrides": [
                    {
                        "id":
                        "category": "hidden",
                        "schema": [
                            {
                                "type": "Boolean"
                            }
                        ]
                    },
                    {
                        "id": 
                        "category": "hidden",
                        "schema": [
                            {
                                "type": "Boolean"
                            }
                        ]
                    },
                    {
                        "id": 
                        "category": "hidden",
                        "schema": [
                            {
                                "type": "Boolean"
                            }
                        ]
                    },
                    {
                        "id": 
                        "category": "hidden",
                        "schema": [
                            {
                                "type": "Boolean"
                            }
                        ]
                    },
                    {
                        "id": 
                        "category": "hidden",
                        "schema": [
                            {
                                "type": "Boolean"
                            }
                        ]
                    },
                    {
                        "id":
                        "category": "hidden",
                        "schema": [
                            {
                                "type": "Boolean"
                            }
                        ]
                    },
                    {
                        "id": 
                        "category": "hidden",
                        "schema": [
                            {
                                "type": "Boolean"
                            }
                        ]
                    },
                    {
                        "id": 
                        "category": "hidden",
                        "schema": [
                            {
                                "type": "Boolean"
                            }
                        ]
                    },
                    {
                        "id": 
                        "category": "hidden",
                        "schema": [
                            {
                                "type": "Boolean"
                            }
                        ]
                    },
                    {
                        "id": 
                        "category": "hidden",
                        "schema": [
                            {
                                "type": "Boolean"
                            }
                        ]
                    },
                    {
                        "id": 
                        "category": "hidden",
                        "schema": [
                            {
                                "type": "Boolean"
                            }
                        ]
                    },
                    {
                        "id": 
                        "category": "hidden",
                        "schema": [
                            {
                                "type": "Boolean"
                            }
                        ]
                    },
                    {
                        "id": "scene",
                        "category": "hidden",
                        "schema": [
                            {
                                "type": "Boolean"
                            }
                        ]
                    },
                    {
                        "id": 
                        "category": "hidden",
                        "schema": [
                            {
                                "type": "Boolean"
                            }
                        ]
                    }
                ]
            },
            "platform": "TuyaPlatform"
        }
    ],
    "disabledPlugins": [
        "@milo526/homebridge-tuya-web"
    ]
}
```

### Environment

- OS: Raspberry Pi OS
- Software: 1.6.0
- Node: 14.21.3
- npm: 6.14.18

### Process Supervisor

hb-service

**Comment by DriesBeast** [comment]
Updated Node.js to 18.15.0 and problem is fixed
