### ISSUE TITLE
Warning: Heating Threshold Temperature

### ISSUE THREAD

**Issue by isaiahfranco** [homebridge/homebridge#3355]
### Analysis

I keep seeing this warning in the Homebridge log:

`This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 4.3999999999999995 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info.`

Is there anything I need to do to remedy this?

### Expected Behavior

No warnings.

### Steps To Reproduce

Just let the plug-in run.

### Logs

```markdown
[4/26/2023, 7:49:48 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 4.3999999999999995 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info.
[4/26/2023, 7:49:48 AM] [homebridge-nest] Error: 
    at HeatingThresholdTemperature.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at HeatingThresholdTemperature.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2923:14)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2488:24
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:15:18
    at NestThermostatAccessory.<anonymous> (/var/lib/homebridge/node_modules/homebridge-nest/lib/nest-device-accessory.js:76:27)
    at HeatingThresholdTemperature.emit (node:events:513:28)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2463:14
    at new Promise (<anonymous>)
    at HeatingThresholdTemperature.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2461:12)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
[4/26/2023, 7:49:49 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 4.3999999999999995 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info.
[4/26/2023, 7:49:49 AM] [homebridge-nest] Error: 
    at HeatingThresholdTemperature.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at HeatingThresholdTemperature.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2923:14)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2488:24
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:15:18
    at NestThermostatAccessory.<anonymous> (/var/lib/homebridge/node_modules/homebridge-nest/lib/nest-device-accessory.js:76:27)
    at HeatingThresholdTemperature.emit (node:events:513:28)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2463:14
    at new Promise (<anonymous>)
    at HeatingThresholdTemperature.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2461:12)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
[4/26/2023, 7:49:49 AM] [Nest] Temperature for Living Room Thermostat is: 17.822 °C / 64.08 °F
[4/26/2023, 7:49:49 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 4.3999999999999995 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info.
[4/26/2023, 7:49:49 AM] [homebridge-nest] Error: 
    at HeatingThresholdTemperature.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at HeatingThresholdTemperature.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2923:14)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2488:24
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:15:18
    at NestThermostatAccessory.<anonymous> (/var/lib/homebridge/node_modules/homebridge-nest/lib/nest-device-accessory.js:76:27)
    at HeatingThresholdTemperature.emit (node:events:513:28)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2463:14
    at new Promise (<anonymous>)
    at HeatingThresholdTemperature.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2461:12)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
[4/26/2023, 7:49:52 AM] [homebridge-nest] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 4.3999999999999995 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info.
[4/26/2023, 7:49:52 AM] [homebridge-nest] Error: 
    at HeatingThresholdTemperature.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at HeatingThresholdTemperature.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2923:14)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2488:24
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:15:18
    at NestThermostatAccessory.<anonymous> (/var/lib/homebridge/node_modules/homebridge-nest/lib/nest-device-accessory.js:76:27)
    at HeatingThresholdTemperature.emit (node:events:513:28)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2463:14
    at new Promise (<anonymous>)
    at HeatingThresholdTemperature.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2461:12)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
```

### Configuration

```json
{
    "name": "Nest",
    "googleAuth": {
        "issueToken": "https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token id_token&login_hint=AJDLj6LQu-SMCQLMJfOUep6S7tCegrIGd96BA446A3N_kcjy-f35RVbwlh23fMvUIHNhZDC1s6cBDPV7we8q9DtsCsJW7W1Mvw&client_id=733249279899-44tchle2kaa9afr5v9ov7jbuojfr9lrq.apps.googleusercontent.com&origin=https://home.nest.com&scope=openid profile email https://www.googleapis.com/auth/nest-account&ss_domain=https://home.nest.com&include_granted_scopes=true",
        "cookies": "__Secure-3PSID=VghCL14X9kbLgS4QKpHBKtl_9-dYDwYTd_pAdGU74fc6ehqLJhu-AcF0qNVdNwHSWpblsQ.; __Host-3PLSID=s.youtube:VghCL51ZDpk-ls5SJpjm_C9eFKWpTuP2I4K0wj8LHXGhDj8Z1o-HLN4pu8H5YwF5SZi0aQ.; __Secure-3PAPISID=JJYkVvPLsUTQak1d/AkgflLLomKGaRjdaE; __Secure-3PSIDCC=AP8dLtwqo2RkYaDnli2lQrqbfaP7TXwJwSakF8ynK0UM3FqTulYqSvOGm1DU8JVJpFaA6prQ; NID=511=FiJfm6nGbsVVVuVZErOqou4cQIjThwHeMNhTcWX35mMOGYx4wX2Uk_8OlpvHiPe2-1fyD1mOoXoDqnR-hqliF0XXAGOMM6_JWVlO8zSBGK0laHmFeGygVtRSEfQC8pqqaFRzPqScq3RvYDTK73mog9KZEZz17mjS7CHw_cGpdTg"
    },
    "platform": "Nest",
    "_bridge": {
        "username": "0E:D0:59:94:8B:F7",
        "port": 34034
    }
}
```

### Environment

- OS: Debian 5.10.162-1
- Software: Homebridge 5.10.0-21-amd64
- Node: 18.16.0
- npm: 7.5.2

### Process Supervisor

hb-service

### Additional Context

I think hb-service is the supervisor. How would I check?

**Comment by isaiahfranco** [comment]
> Pls raise this against the nest plugin

Is there a way to move it or do I need to submit a new bug on the plug-in?

**Comment by NorthernMan54** [comment]
Unfortunately GitHub doesn't support the ability to move issues, so you need to raise a new issue
