### ISSUE TITLE
Homebridge looping after updates

### ISSUE THREAD

**Issue by DaveGraham123456** [homebridge/homebridge#3376]
### Current Situation

when attempting to start, the system attempts to start, but the console logs show

 [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
 [HB Supervisor] Restarting Homebridge...

### Logs

```markdown
Log attached
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge BA7D",
        "username": "removed",
        "port": 51966,
        "pin": "827-68-082"
    },
    "accessories": [
        {
            "accessory": "OccupancyDelay",
            "name": "OccupancyLaundry",
            "delay": 30,
            "slaveCount": 1
        },
        {
            "accessory": "OccupancyDelay",
            "name": "Shower",
            "delay": 30,
            "slaveCount": 3
        },
        {
            "accessory": "OccupancyDelay",
            "name": "OccupancyBoysHall",
            "delay": 20,
            "slaveCount": 1
        },
        {
            "accessory": "OccupancyDelay",
            "name": "Study",
            "delay": 1200,
            "slaveCount": 1
        },
        {
            "accessory": "OccupancyDelay",
            "name": "Store",
            "delay": 1200,
            "slaveCount": 1
        },
        {
            "accessory": "OccupancyDelay",
            "name": "Lounge",
            "delay": 120,
            "slaveCount": 1
        },
        {
            "accessory": "OccupancyDelay",
            "name": "Family",
            "delay": 120,
            "slaveCount": 1
        },
        {
            "accessory": "OccupancyDelay",
            "name": "Dining",
            "delay": 120,
            "slaveCount": 1
        },
        {
            "accessory": "OccupancyDelay",
            "name": "Master",
            "delay": 180,
            "slaveCount": 1
        },
        {
            "accessory": "OccupancyDelay",
            "name": "Stairwell",
            "delay": 1,
            "slaveCount": 2
        },
        {
            "accessory": "OccupancyDelay",
            "name": "RumpusCupShelves",
            "delay": 10,
            "slaveCount": 1
        },
        {
            "accessory": "OccupancyDelay",
            "name": "Rumpus",
            "delay": 20,
            "slaveCount": 1
        },
        {
            "accessory": "OccupancyDelay",
            "name": "Hallway",
            "delay": 20,
            "slaveCount": 1
        },
        {
            "accessory": "OccupancyDelay",
            "name": "Garage",
            "delay": 120,
            "slaveCount": 2
        },
        {
            "accessory": "OccupancyDelay",
            "name": "Occupancyensuite",
            "delay": 600,
            "slaveCount": 2
        },
        {
            "accessory": "OccupancyDelay",
            "name": "OutsideFront",
            "delay": 600,
            "slaveCount": 2
        },
        {
            "accessory": "OccupancyDelay",
            "name": "Outsiderumpus",
            "delay": 600,
            "slaveCount": 1
        },
        {
            "accessory": "OccupancyDelay",
            "name": "BoysToilet",
            "delay": 600,
            "slaveCount": 1
        },
        {
            "name": "Home Security",
            "default_mode": "Off",
            "arm_seconds": 30,
            "trigger_seconds": 10,
            "reset_minutes": 10,
            "audio": false,
            "audio_language": "en-US",
            "save_state": true,
            "proxy_mode": false,
            "test_mode": false,
            "override_off": false,
            "reset_off_flow": false,
            "siren_sensor": false,
            "siren_sensor_seconds": 5,
            "reset_sensor": false,
            "mode_switches": false,
            "mode_off_switch": false,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "siren_switch": false,
            "siren_mode_switches": false,
            "double_knock": false,
            "double_knock_seconds": 90,
            "audio_volume": "100",
            "audio_arming_looped": false,
            "audio_alert_looped": false,
            "accessory": "security-system"
        },
        {
            "name": "ColourCircle",
            "delay": 300,
            "sensors": 5,
            "accessory": "MultisensorTrigger"
        },
        {
            "name": "Dad Bedside",
            "delay": 1000,
            "sensors": 1,
            "accessory": "MultisensorTrigger"
        },
        {
            "name": "SolarEdge Inverter",
            "manufacturer": "SolarEdge",
            "model": "Inverter",
            "serial": "solaredge-inverter-1",
            "site_id": "removed",
            "api_key": "removed",
            "update_interval": 15,
            "current": true,
            "last_day": true,
            "accessory": "SolarEdge Inverter"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "green",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "platform": "homebridge-cbus.CBus",
            "name": "CBus",
            "client_ip_address": "127.0.0.1",
            "client_controlport": 20023,
            "client_cbusname": "removed",
            "client_network": 254,
            "client_application": 56,
            "client_debug": false,
            "platform_export": "/home/pi/my-platform.json",
            "accessories": [
                {
                    "type": "dimmer",
                    "id": 1,
                    "name": "Bed1Mum"
                },
                {
                    "type": "dimmer",
                    "id": 2,
                    "name": "Bed1Dad"
                },
                {
                    "type": "dimmer",
                    "id": 3,
                    "name": "Bed1LightPair"
                },
                {
                    "type": "dimmer",
                    "id": 4,
                    "name": "Sewing"
                },
                {
                    "type": "dimmer",
                    "id": 5,
                    "name": "Family"
                },
                {
                    "type": "dimmer",
                    "id": 6,
                    "name": "Bed1Mid"
                },
                {
                    "type": "dimmer",
                    "id": 7,
                    "name": "Bed3"
                },
                {
                    "type": "dimmer",
                    "id": 8,
                    "name": "Kitchen"
                },
                {
                    "type": "dimmer",
                    "id": 9,
                    "name": "Benchtop"
                },
                {
                    "type": "dimmer",
                    "id": 10,
                    "name": "BigRoomLeft"
                },
                {
                    "type": "dimmer",
                    "id": 11,
                    "name": "BigRoomMidLeft"
                },
                {
                    "type": "dimmer",
                    "id": 12,
                    "name": "BigRoomMidRight"
                },
                {
                    "type": "dimmer",
                    "id": 13,
                    "name": "BigRoomRight"
                },
                {
                    "type": "dimmer",
                    "id": 14,
                    "name": "Meals"
                },
                {
                    "type": "dimmer",
                    "id": 15,
                    "name": "DiningOverhead"
                },
                {
                    "type": "dimmer",
                    "id": 16,
                    "name": "DiningWall"
                },
                {
                    "type": "dimmer",
                    "id": 17,
                    "name": "ExtHallway"
                },
                {
                    "type": "dimmer",
                    "id": 18,
                    "name": "Bed4"
                },
                {
                    "type": "dimmer",
                    "id": 19,
                    "name": "Study"
                },
                {
                    "type": "dimmer",
                    "id": 20,
                    "name": "Stairs"
                },
                {
                    "type": "light",
                    "id": 21,
                    "name": "Recess"
                },
                {
                    "type": "light",
                    "id": 22,
                    "name": "FrontOutside"
                },
                {
                    "type": "light",
                    "id": 23,
                    "name": "Pantry"
                },
                {
                    "type": "light",
                    "id": 25,
                    "name": "KidsToiletLight"
                },
                {
                    "type": "dimmer",
                    "id": 26,
                    "name": "SuspectKidsBathDown"
                },
                {
                    "type": "light",
                    "id": 28,
                    "name": "Bed1Wardrobe"
                },
                {
                    "type": "light",
                    "id": 29,
                    "name": "RumpusOutside"
                },
                {
                    "type": "light",
                    "id": 30,
                    "name": "ComedyStore"
                },
                {
                    "type": "light",
                    "id": 31,
                    "name": "SunRoom1"
                },
                {
                    "type": "light",
                    "id": 32,
                    "name": "SunRoom2"
                },
                {
                    "type": "fan",
                    "id": 33,
                    "name": "Bath3Fan"
                },
                {
                    "type": "dimmer",
                    "id": 40,
                    "name": "KidsBathHall"
                },
                {
                    "type": "light",
                    "id": 41,
                    "name": "EnsuiteLight"
                },
                {
                    "type": "light",
                    "id": 42,
                    "name": "EnsuiteHeat"
                },
                {
                    "type": "fan",
                    "id": 43,
                    "name": "EnsuiteFan"
                },
                {
                    "type": "dimmer",
                    "id": 44,
                    "name": "EnsuiteBasinLight"
                },
                {
                    "type": "light",
                    "id": 45,
                    "name": "LaundryLight"
                },
                {
                    "type": "fan",
                    "id": 46,
                    "name": "LaundryFan"
                },
                {
                    "type": "light",
                    "id": 47,
                    "name": "Bath2Light"
                },
                {
                    "type": "light",
                    "id": 48,
                    "name": "Bath2Heat1"
                },
                {
                    "type": "light",
                    "id": 49,
                    "name": "Bath2Heat2"
                },
                {
                    "type": "fan",
                    "id": 50,
                    "name": "Bath2Fan"
                },
                {
                    "type": "light",
                    "id": 51,
                    "name": "Bath3Light"
                },
                {
                    "type": "light",
                    "id": 52,
                    "name": "Bath3Heat"
                },
                {
                    "type": "dimmer",
                    "id": 55,
                    "name": "EnsuiteBathLight"
                },
                {
                    "type": "switch",
                    "id": 56,
                    "name": "MumGaragebellpress",
                    "activeDuration": "2s"
                },
                {
                    "type": "switch",
                    "id": 57,
                    "name": "DadGaragebellpress",
                    "activeDuration": "2s"
                },
                {
                    "type": "switch",
                    "id": 58,
                    "name": "EnsuiteBathWater",
                    "activeDuration": "10 minutes"
                },
                {
                    "type": "dimmer",
                    "id": 63,
                    "name": "RumpusTV"
                },
                {
                    "type": "dimmer",
                    "id": 64,
                    "name": "RumpusKitch"
                },
                {
                    "type": "dimmer",
                    "id": 37,
                    "name": "RumpusCupboards"
                },
                {
                    "type": "light",
                    "id": 66,
                    "name": "RumpusMood"
                },
                {
                    "type": "light",
                    "id": 67,
                    "name": "GarageFrontLight"
                },
                {
                    "type": "light",
                    "id": 68,
                    "name": "GarageBackLight"
                },
                {
                    "type": "light",
                    "id": 69,
                    "name": "UnderHouse"
                },
                {
                    "type": "contact",
                    "id": 71,
                    "name": "MumGarageStatus"
                },
                {
                    "type": "contact",
                    "id": 72,
                    "name": "DadGarageStatus"
                },
                {
                    "type": "motion",
                    "id": 75,
                    "name": "Boys Bath Hall"
                },
                {
                    "type": "light",
                    "id": 91,
                    "name": "FairyLights"
                },
                {
                    "type": "light",
                    "id": 99,
                    "name": "MasterBedMotionOverRide"
                },
                {
                    "type": "light",
                    "id": 98,
                    "name": "LaundryOutside"
                },
                {
                    "type": "light",
                    "id": 90,
                    "name": "HueOnOff"
                }
            ]
        },
        {
            "username": "removed",
            "password": "removed",
            "disableFan": true,
            "disableDry": true,
            "ignoreHomeKitDevices": false,
            "enableSyncButton": true,
            "syncButtonInAccessory": false,
            "enableOccupancySensor": true,
            "enableClimateReactSwitch": true,
            "enableHistoryStorage": true,
            "disableHorizontalSwing": true,
            "disableLightSwitch": false,
            "externalHumiditySensor": true,
            "allowRepeatedCommands": true,
            "debug": false,
            "platform": "SensiboAC"
        },
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": true,
            "accessories": [
                {
                    "name": "MiddleSwitch-Shed",
                    "type": "switch",
                    "enableAutoOff": true,
                    "onDuration": 3,
                    "data": {
                        "on": "removed"
                    }
                }
            ]
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome"
        },
        {
            "devices": [
                {
                    "name": "Upstairs TV",
                    "ip": "192.168.1.106",
                    "mac": "removed",
                    "pollingInterval": 5,
                    "volumeLimit": 100,
                    "volumeControl": "both",
                    "channelControl": false,
                    "mediaControl": true
                },
                {
                    "name": "Downstairs TV",
                    "ip": "192.168.1.105",
                    "mac": "removed",
                    "pollingInterval": 5,
                    "volumeLimit": 100,
                    "volumeControl": "both",
                    "channelControl": false,
                    "mediaControl": true,
                    "screenControl": true
                }
            ],
            "platform": "webostv"
        },
        {
            "name": "Konnected",
            "panels": [
                {
                    "name": "Konnected Pro",
                    "uuid": "removed",
                    "ipAddress": "192.168.1.60",
                    "port": 9123,
                    "blink": false,
                    "zones": [
                        {
                            "enabled": true,
                            "zoneNumber": "1",
                            "zoneType": "smoke",
                            "zoneLocation": "Garage",
                            "switchSettings": {
                                "trigger": "1"
                            }
                        },
                        {
                            "enabled": true,
                            "zoneNumber": "2",
                            "zoneType": "motion",
                            "zoneLocation": "Master Bedroom",
                            "switchSettings": {
                                "trigger": "1"
                            }
                        },
                        {
                            "enabled": true,
                            "zoneNumber": "3",
                            "zoneType": "motion",
                            "zoneLocation": "Dining Room",
                            "switchSettings": {
                                "trigger": "1"
                            }
                        },
                        {
                            "enabled": true,
                            "zoneNumber": "4",
                            "zoneType": "motion",
                            "zoneLocation": "Lounge",
                            "switchSettings": {
                                "trigger": "1"
                            }
                        },
                        {
                            "enabled": true,
                            "zoneNumber": "5",
                            "zoneType": "motion",
                            "zoneLocation": "Hallway",
                            "switchSettings": {
                                "trigger": "1"
                            }
                        },
                        {
                            "enabled": true,
                            "zoneNumber": "6",
                            "zoneType": "motion",
                            "zoneLocation": "Rumpus",
                            "switchSettings": {
                                "trigger": "1"
                            }
                        },
                        {
                            "enabled": true,
                            "zoneNumber": "7",
                            "zoneType": "motion",
                            "zoneLocation": "Family",
                            "switchSettings": {
                                "trigger": "1"
                            }
                        },
                        {
                            "enabled": true,
                            "zoneNumber": "8",
                            "zoneType": "motion",
                            "zoneLocation": "Garage",
                            "switchSettings": {
                                "trigger": "1"
                            }
                        },
                        {
                            "enabled": true,
                            "zoneNumber": "9",
                            "zoneType": "contact",
                            "zoneLocation": "Door Glass Sliding",
                            "switchSettings": {
                                "trigger": "1"
                            }
                        },
                        {
                            "enabled": true,
                            "zoneNumber": "10",
                            "zoneType": "contact",
                            "zoneLocation": "Door Laundry",
                            "switchSettings": {
                                "trigger": "1"
                            }
                        },
                        {
                            "enabled": true,
                            "zoneNumber": "11",
                            "zoneType": "contact",
                            "zoneLocation": "Door Front",
                            "switchSettings": {
                                "trigger": "1"
                            }
                        }
                    ]
                },
                {
                    "blink": false,
                    "zones": [
                        {
                            "switchSettings": {
                                "trigger": "1"
                            }
                        }
                    ]
                }
            ],
            "platform": "konnected"
        },
        {
            "name": "Hubitat-v2",
            "app_url_local": "http://192.168.1.9/apps/api/",
            "app_url_cloud": "removed",
            "use_cloud": false,
            "app_id": 200,
            "access_token": "removed",
            "direct_port": 8000,
            "temperature_unit": "C",
            "round_levels": true,
            "adaptive_lighting": true,
            "adaptive_lighting_offset": 0,
            "consider_fan_by_name": false,
            "consider_light_by_name": false,
            "validateTokenId": true,
            "logConfig": {
                "debug": false,
                "showChanges": true
            },
            "platform": "Hubitat-v2"
        },
        {
            "name": "Hubitat",
            "MakerAPI": "removed",
            "lowBatteryThreshold": 35,
            "roundUp": true,
            "temperatureUnits": "C",
            "createButtonDevices": "Never",
            "platform": "Hubitat"
        },
        {
            "refreshToken": "removed",
            "platform": "Ring"
        }
    ],
    "disabledPlugins": [
        "homebridge-webos-tv",
        "homebridge-hubitat",
        "homebridge-hubitat-tonesto7"
    ]
}
```

### Environment

- OS: Raspbian GNU/Linux Buster (10)
- Software:
- Node: [v18.16.0]
- npm:

### Process Supervisor

hb-service

### Additional Context

worked until update.
[Log.txt](https://github.com/homebridge/homebridge/files/11581593/Log.txt)

**Comment by NorthernMan54** [comment]
Before that in the log it will indicate why it shut down, pls share more of the log

**Comment by DaveGraham123456** [comment]
> Before that in the log it will indicate why it shut down, pls share more of the log

Hi there

i thought I supplied and entire boot loop, from the failure all the way thru to the next failure

**Comment by NorthernMan54** [comment]
Your log.txt is just your config.json

**Comment by DaveGraham123456** [comment]
[homebridge.log (2).txt](https://github.com/homebridge/homebridge/files/11583138/homebridge.log.2.txt)

Doh!!!  copied wrong file here it is

**Comment by DaveGraham123456** [comment]
I left it overnight and homebridge seemed to start, but with no accessories.  I restarted it and the looping returned.

**Comment by DaveGraham123456** [comment]
so, I disabled my ring plugin, took my homebridge to 1.6.0 and then back to 1.6.1 and it all started working again   Very very strange

**Comment by NorthernMan54** [comment]
This is the error in the log

```
[27/05/2023, 20:14:46] [SensiboAC] Found valid token in storage
[27/05/2023, 20:14:46] [SensiboAC] Creating GET request to Sensibo API --->
[27/05/2023, 20:14:46] [SensiboAC] https://home.sensibo.com/api/v2/users/me/pods?fields=id,acState,measurements,remoteCapabilities,room,temperatureUnit,productModel,location,occupancy,smartMode,motionSensors,filtersCleaning,serial,pureBoostConfig,homekitSupported
[27/05/2023, 20:14:46] TypeError: log is not a function
    at /usr/local/lib/node_modules/homebridge-broadlink-rm-pro/helpers/checkForUpdates.js:16:7
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/github-version-checker/lib/query/rest.js:69:17)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[27/05/2023, 20:14:46] Got SIGTERM, shutting down Homebridge...
```

your homebridge-broadlink-rm-pro plugin is triggering this, please raise this as an issue with the homebridge-broadlink-rm-pro plugin

**Comment by adamlwatson** [comment]
I'm also experiencing this problem. Wyze Smart Home is the only plugin I'm using. Here are the logs:

`[6/13/2023, 11:09:08 AM] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 5706) is running on port 51729.
[6/13/2023, 11:09:08 AM] TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at WyzeLock.lockGetProperty (/usr/lib/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:422:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[6/13/2023, 11:09:08 AM] TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at WyzeLock.lockGetProperty (/usr/lib/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:422:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[6/13/2023, 11:09:08 AM] Got SIGTERM, shutting down Homebridge...
[6/13/2023, 11:09:08 AM] TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at WyzeLock.lockGetProperty (/usr/lib/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:422:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[6/13/2023, 11:09:08 AM] TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at WyzeLock.lockGetProperty (/usr/lib/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:422:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[6/13/2023, 11:09:09 AM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[6/13/2023, 11:09:09 AM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[6/13/2023, 11:09:09 AM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[6/13/2023, 11:09:09 AM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[6/13/2023, 11:09:09 AM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[6/13/2023, 11:09:09 AM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[6/13/2023, 11:09:09 AM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[6/13/2023, 11:09:09 AM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[6/13/2023, 11:09:09 AM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'Color Temperature': characteristic value expected valid finite number and received "Infinity" (number). See https://homebridge.io/w/JtMGR for more info.
[6/13/2023, 11:09:09 AM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'Color Temperature': characteristic was supplied illegal value: number 548 exceeded maximum of 500. See https://homebridge.io/w/JtMGR for more info.
[6/13/2023, 11:09:13 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null`

I've attempted disabling the plugin, downgrading and upgrading, as well as completely remove and reinstalling the plugin to no avail.

**Comment by movy** [comment]
For those googling, in case you face err 143 w/o any Ring or Wyze plugins, this might help: https://github.com/homebridge/homebridge/issues/3536#issuecomment-2012078868
