### ISSUE TITLE
Homebridge Hikvision plug in crashes after Node.js upgrade 18.16.0

### ISSUE THREAD

**Issue by jamesngob** [homebridge/homebridge#3377]
### Current Situation

Hello there,

I have the latest homebridge installed on Ubuntu server. I have Hikvision plugin installed. All has been working fine since couple of years... until the Homebridge system request for Node upgrade.
After upgrading the Node.js to version 18.16.0 using sudo hb-service update-node, the Homebridge crashes and the error was looping again and again. I need to disable the plugin or, uninstall it in order to make homebridge works again

The log show

"TypeError: Cannot read properties of undefined (reading 'status')
at AxiosDigest.getWwwAuth (/usr/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios-digest/index.ts:69:13)
at processTicksAndRejections (node:internal/process/task_queues:95:5)"

UPDATES:
---> So I decided to create a new Ubuntu server version 22.04.2, 64 bit, install fresh Homebridge using the official page, then install Hikvision plugin via Homebridge UX page as recommended. The same error happens, meaning it is now unusable under even new build, fresh install...

Any idea how to fix this?
Thank you

### Logs

```markdown
"TypeError: Cannot read properties of undefined (reading 'status')
at AxiosDigest.getWwwAuth (/usr/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios-digest/index.ts:69:13)
at processTicksAndRejections (node:internal/process/task_queues:95:5)"

"TypeError: Cannot read properties of undefined (reading 'status')
at AxiosDigest.getWwwAuth (/usr/lib/node_modules/@evops/homebridge-hikvision/node_modules/axios-digest/index.ts:69:13)
at processTicksAndRejections (node:internal/process/task_queues:95:5)"
```

### Configuration

```json
{
  "platforms": [
    {
      "platform": "Hikvision",
      "name": "hikvision-nvr",
      "port": 443,
      "username": "admin",
      "password": "test1234"
    }
  ]
}
```

### Environment

- OS: Ubuntu Focal Fossa (20.04.6 LTS)
- Software: 1.6.1
- Node: 18.16.0

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Please raise this as a issue with the homebridge-hikvision plugin
