### ISSUE TITLE
Ring doorbell - Homebridge

### ISSUE THREAD

**Issue by shaileshck** [homebridge/homebridge#3413]
### Current Situation

Implemented Ring pluggin over Homebridge. 
I can see motion alerts and snapshot images in HomeKit camera.
Live Video does work. It tries and then finally get Camera not responding error.

Sharing Logs fyi.

Edited token for security reasons.

### Logs

```markdown
[12/08/2023, 15:24:18] [Ring] Preparing Live Stream for Front Door
[12/08/2023, 15:24:19] [Ring] Stream Prepared for Front Door (0.957s)
[12/08/2023, 15:24:19] [Ring] Activating stream for Front Door (1.06s)
[12/08/2023, 15:24:19] [Ring] RangeError: offset is out of bounds
    at Uint8Array.set (<anonymous>)
    at Function.padStart (/usr/local/lib/node_modules/homebridge-ring/node_modules/webcrypto-core/build/webcrypto-core.js:972:13)
    at Function.encodeSignature (/usr/local/lib/node_modules/homebridge-ring/node_modules/webcrypto-core/build/webcrypto-core.js:940:22)
    at Function.sign (/usr/local/lib/node_modules/homebridge-ring/node_modules/@peculiar/webcrypto/build/webcrypto.js:1575:54)
    at EcdsaProvider.onSign (/usr/local/lib/node_modules/homebridge-ring/node_modules/@peculiar/webcrypto/build/webcrypto.js:1737:25)
    at EcdsaProvider.sign (/usr/local/lib/node_modules/homebridge-ring/node_modules/webcrypto-core/build/webcrypto-core.js:157:28)
    at SubtleCrypto.sign (/usr/local/lib/node_modules/homebridge-ring/node_modules/webcrypto-core/build/webcrypto-core.js:1405:39)
    at Function.create (/usr/local/lib/node_modules/homebridge-ring/node_modules/@peculiar/x509/build/x509.cjs.js:2407:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.value [as createSelfSignedCertificateWithKey] (/usr/local/lib/node_modules/homebridge-ring/node_modules/dtls/src/context/cipher.ts:108:18)
[12/08/2023, 15:24:19] [Ring] connectionStateChange: closed
[12/08/2023, 15:24:19] [Ring] iceConnectionStateChange: closed
[12/08/2023, 15:24:22] [homebridge-ring] Error: 
    at Accessory.sendCharacteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:2031:14)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1732:14)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
[12/08/2023, 15:24:28] [homebridge-ring] This plugin slows down Homebridge. The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Front Door CBC8' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[12/08/2023, 15:24:28] [homebridge-ring] Error: 
    at Accessory.sendCharacteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:2031:14)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1747:16)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
[12/08/2023, 15:24:28] [Ring] Stopped Live Stream for Front Door
```

### Configuration

```json
"refreshToken": "dfjdhfhjjfnd1Oc2FXVnVkQ0pkTENKeVpXWnlaWE5vWDNWelpYSmZhV1FpT2prd05USTNOQ3dpY201a0lqb2lkRXg0WkZKT05GTjJkaUlzSW5ObGMzTnBiMjVmYVdRaU9pSmxaR1UxTURRMk5DMW1OalJqTFRSbU4ySXRPVEJoTVMwek5UQTNNakEzTldKbU4yWWlMQ0owZVhCbElqb2ljbVZtY21WemFDMTBiMnRsYmlKOS5SYlNQekZQNTZ2OXBERFZjY1FubU82djhLaFEybGNnY1dXQVhtOTZOUlRJUk5qXzN1RmxXamQxNEIySkRlbDlLbW40bUlhTTFoVzB5a3ZNNmJMQ2RSVHdoazFjX0taajkzRjZZkfdkfskdlfkdsUG1Za3BKd2ZGeVg3eG9lZG5zWGJlVW1paEEiLCJoaWQiOiI4YzM1Yjk1MS05OThjLTU4YWQtYjllZC1iNmJiYjE4NjQ1NTMiLCJwbmMiOnsiZ2NtIjp7InRva2VuIjoiZGN0TF9lemlBMDg6QVBBOTFiRm1zWWsxYmhEdWJxUktjS0pGTU01S2tZOTh0Ni0xUXBJRjdLM2o5NktNZXBERU0yTDRjdms4NUFxbVpSLS1nVllSS3ZDU0ItQ0tSMk1TYnZxdFVaM0hNbWJidTd2TmlJZUJRR1BXbzR3a2lxOW1FZmpyU2xCcjRneVo3dnhlS1prTW5sTjciLCJhbmRyb2lkSWQiOiI0ODUxMjAwNzkyNzk4Mjg3MjQ3Iiwic2VjdXJpdHlUb2tlbiI6IjIwODI0NTUxNzg4MjA2MjMzODciLCJhcHBJZCI6IndwOnJlY2VpdmVyLnB1c2guY29tI2E4YzNlNTk3LWQ3MzctNGE5Ny1iODQzLTQyOTRlYzE4Y2NiNSJ9LCJrZXlzIjp7InByaXZhdGVLZXkiOiJqY3VickRDS2ZIWFA0ZjRZNUx3dTJnZ3htSm9EcHlOSUhXZWlyZGFuVkVjIiwicHVibGljS2V5IjoiQkRQdG5FdGdmUjlYenNtaDZwZ0RGZ1VsX0hoZGRqNVJJNUZPY2JHN0MxTkZ1OTJWQnY0Ml9MeFdvN1NCY0pNNjNHcHJSZTRuNVBtcXNGdWFUcG82dUQ0IiwiYXV0aFNlY3JldCI6IldhLVdrQ2lGOVFnSHhnMFpHRnNodVEifSwiZmNtIjp7InRva2VuIjoiZDRhWGlxV3dSaTA6QVBBOTFiRkNwcm1XZ01ReWtWVFcySTRSeWVBcDVtU3M0dVBRMDVIZTNSV0lQbWVBRmNINzNBUkZuT3VaMDVFbWlPWHUwd2xOdUZubEU0ZGxIVktXMW9wR09sOHNNeG1vMVhaSHNySmlxbkZnTjVGTTZ1ZllsSjROU1BtS1BSejdfM0VKRkdjkjdkjfkjdkfBsM0YyTHpCSFhRX0g3YThHQWpleW1ybEFSNnBxM3YifX19",
            "unbridgeCameras": true,
            "alarmOnEntryDelay": true,
            "hideCameraLight": true,
            "hideCameraSirenSwitch": true,
            "hideAlarmSirenSwitch": true,
            "platform": "Ring"
```

### Environment

- OS:Raspbian PI
- Software: Homebridge
- Node:v18.17.1
- npm:

### Process Supervisor

hb-service

**Comment by ruudbol** [comment]
Me too

**Comment by dgreif** [comment]
This error is being tracked over on the `homebridge-ring` plugin, [here](https://github.com/dgreif/ring/issues/1286).
