### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getCharacteristic')

### ISSUE THREAD

**Issue by richierockskool** [homebridge/homebridge#3414]
### Current Situation

Trying to install a bridge accessory (Wifi Gateway)

### Logs

```markdown
TypeError: Cannot read properties of undefined (reading 'getCharacteristic')
    at new InkbirdPlatform (file:///Users/richjagger/Documents/GitHub/homebridge-inkbird-wifi-gateway/src/InkbirdPlatform.js:108:28)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:474:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:401:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:176:29)
```

### Configuration

```json
// Create and configure Inkbird Wifi Gateway Service

      this.log.warn(devicesDiscovered):

        this.log.debug('Creating and configuring new bridge')
        bridgeAccessory=(devicesDiscovered)
        bridgeService=(Service.Tunnel)
        bridgeService=(devicesDiscovered)
        this.bridgeService.getCharacteristic(Characteristic.StatusFault).updateValue(!devicesDiscovered.is_connected)
        this.bridgeAccessory.addService(bridgeService)
        this.accessories[uuid]=bridgeAccessory
        this.log.info('Adding Inkbird Wifi Gateway')
        this.log.debug('Registering platform accessory')
        this.api.registerPlatformAccessories(PluginName, PlatformName, [bridgeAccessory])
```

### Environment

- OS: 12.6.8
- Software: VS 1.81.0
- Node: 20.5.0
- npm: 9.8.1

### Process Supervisor

hb-service

**Comment by bwp91** [comment]
Closing this on the basis that this is not an issue with Homebridge but the plugin you are developing.

Here is not the place for plugin issues, rather for specifically homebridge issues

Cheers
