### ISSUE TITLE
Homebridge not running - View Logs

### ISSUE THREAD

**Issue by droopdog7** [homebridge/homebridge#3417]
### Current Situation

Bascially everything stopped running yesterday.  Those with native homekit capability are running but everything else is unresponsive.  As the title says, I am getting the error that homebridge is not running.  I cannot think of anything that preceded, but I did notice that one of my homepod minis (I have six of them plug two OG homepods) stopped reponding.

While I am here, I do want to also say that I never have been able to remove any plug ins.  Or should I say, I always get an error when I try.  

Hopefully I have all of the log, but it seems to just keep repeating over and over again.

### Logs

```markdown
[22/08/2023, 06:05:21] [Harmony Hub] INFO - stopping hub discovery, hubs found : undefined
[22/08/2023, 06:05:34] [Deebot] ***** Disabling plugin. *****
[22/08/2023, 06:05:34] [Deebot] ***** connect EHOSTUNREACH 34.208.149.223:443 at Function.AxiosError.from (/var/lib/homebridge/node_modules/homebridge-deebot/node_modules/axios/lib/core/AxiosError.js:89:14). *****
[22/08/2023, 06:05:34] Error: connect EHOSTUNREACH 54.188.51.105:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
[22/08/2023, 06:05:34] [Harmony Hub] (Harmony Hub)Error - Error retrieving info from hub : network timeout at: http://192.168.7.176:8088/-(1)
[22/08/2023, 06:05:35] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 8B67) is running on port 51271.
[22/08/2023, 06:05:35] [myQ] connect EHOSTUNREACH 13.83.98.203:443
[22/08/2023, 06:05:35] [myQ] myQ API: Unable to access the OAuth authorization endpoint.
[22/08/2023, 06:05:35] Got SIGTERM, shutting down Homebridge...
[22/08/2023, 06:05:35] [Harmony Hub] INFO - shutdown
[22/08/2023, 06:05:36] [Smartthings Plug (IK)] Child bridge process ended
[22/08/2023, 06:05:36] [Nest] Child bridge process ended
[22/08/2023, 06:05:36] [homebridge-bond] Child bridge process ended
[22/08/2023, 06:05:36] [homebridge-lg-thinq] Child bridge process ended
[22/08/2023, 06:05:36] [Nest] Process Ended. Code: null, Signal: SIGTERM
[22/08/2023, 06:05:36] [homebridge-lg-thinq] Process Ended. Code: null, Signal: SIGTERM
[22/08/2023, 06:05:36] [homebridge-bond] Process Ended. Code: null, Signal: SIGTERM
[22/08/2023, 06:05:36] [Smartthings Plug (IK)] Process Ended. Code: null, Signal: SIGTERM
[22/08/2023, 06:05:39] [Harmony Hub] (Harmony Hub)INFO - Loading activities...
[22/08/2023, 06:05:40] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[22/08/2023, 06:05:45] [HB Supervisor] Restarting Homebridge...
[22/08/2023, 06:05:45] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[22/08/2023, 06:05:45] [HB Supervisor] Started Homebridge v1.6.1 with PID: 19197
[22/08/2023, 06:05:57] Loaded config.json with 1 accessories and 10 platforms.
[22/08/2023, 06:05:58] Loaded 8 cached accessories from cachedAccessories.
[22/08/2023, 06:05:58] ---
[22/08/2023, 06:05:59] Loaded plugin: homebridge-bond@3.2.10
[22/08/2023, 06:05:59] Registering platform 'homebridge-bond.Bond'
[22/08/2023, 06:05:59] ---
[22/08/2023, 06:06:01] Loaded plugin: homebridge-deebot@6.0.5
[22/08/2023, 06:06:01] Registering platform 'homebridge-deebot.Deebot'
[22/08/2023, 06:06:01] ---
[22/08/2023, 06:06:01] Loaded plugin: homebridge-dummy@0.9.0
[22/08/2023, 06:06:01] Registering accessory 'homebridge-dummy.DummySwitch'
[22/08/2023, 06:06:01] ---
[22/08/2023, 06:06:03] Loaded plugin: homebridge-harmony@1.6.3
[22/08/2023, 06:06:03] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
[22/08/2023, 06:06:03] ---
[22/08/2023, 06:06:07] Loaded plugin: homebridge-lg-thinq@1.5.3
[22/08/2023, 06:06:07] Registering platform 'homebridge-lg-thinq.LGThinQ'
[22/08/2023, 06:06:07] ---
[22/08/2023, 06:06:12] Loaded plugin: homebridge-meross@9.2.2
[22/08/2023, 06:06:12] Registering platform 'homebridge-meross.Meross'
[22/08/2023, 06:06:12] ---
[22/08/2023, 06:06:16] Loaded plugin: homebridge-myq@2.12.0
[22/08/2023, 06:06:16] Registering platform 'homebridge-myq.myQ'
[22/08/2023, 06:06:16] ---
[22/08/2023, 06:06:18] Loaded plugin: homebridge-nest@4.6.9
[22/08/2023, 06:06:18] Registering platform 'homebridge-nest.Nest'
[22/08/2023, 06:06:18] ---
[22/08/2023, 06:06:19] Loaded plugin: homebridge-smartthings-ik@1.5.13
[22/08/2023, 06:06:19] Registering platform 'homebridge-smartthings-ik.HomeBridgeSmartThings'
[22/08/2023, 06:06:19] ---
[22/08/2023, 06:06:27] Loaded plugin: @0x5e/homebridge-tuya-platform@1.7.0-beta.49
[22/08/2023, 06:06:27] Registering platform '@0x5e/homebridge-tuya-platform.TuyaPlatform'
[22/08/2023, 06:06:27] ---
[22/08/2023, 06:06:27] Loading 10 platforms...
[22/08/2023, 06:06:27] [myQ] Initializing myQ platform...
[22/08/2023, 06:06:27] No plugin was found for the platform "HarmonyHub" in your config.json. Please make sure the corresponding plugin is installed correctly.
[22/08/2023, 06:06:27] [Harmony Hub] Initializing HarmonyHubWebSocket platform...
[22/08/2023, 06:06:27] [Harmony Hub] HarmonyPlatform Init
[22/08/2023, 06:06:27] [Smartthings Plug (IK)] Initializing HomeBridgeSmartThings platform...
[22/08/2023, 06:06:27] [Smartthings Plug (IK)] Initializing child bridge 0E:11:5A:8C:27:05
[22/08/2023, 06:06:27] [Deebot] Initializing Deebot platform...
[22/08/2023, 06:06:27] [Deebot] Initialising plugin v6.0.5 | System linux | Node v18.17.0 | HB v1.6.1 | HAPNodeJS v0.11.1...
[22/08/2023, 06:06:27] [Tuya] Initializing TuyaPlatform platform...
[22/08/2023, 06:06:27] [Nest] Initializing Nest platform...
[22/08/2023, 06:06:27] [Nest] Initializing child bridge 0E:85:73:45:54:C7
[22/08/2023, 06:06:27] [Bond] Initializing Bond platform...
[22/08/2023, 06:06:27] [Bond] Initializing child bridge 0E:9F:9D:BA:E5:77
[22/08/2023, 06:06:27] [LGThinQ] Initializing LGThinQ platform...
[22/08/2023, 06:06:27] [LGThinQ] Initializing child bridge 0E:87:E3:23:1E:39
[22/08/2023, 06:06:27] Loading 1 accessories...
[22/08/2023, 06:06:27] [Dummy Switch] Initializing DummySwitch accessory...
[22/08/2023, 06:06:30] [Tuya] Loading accessory from cache: Smart Outdoor Plug
[22/08/2023, 06:06:30] [Tuya] Loading accessory from cache: Smart Indoor Plug
[22/08/2023, 06:06:30] [Harmony Hub] DidFinishLaunching
[22/08/2023, 06:06:30] [Harmony Hub] (Harmony Hub)INFO - Loading activities...
[22/08/2023, 06:06:31] [Harmony Hub] (undefined)WARNING - platform undefined is empty
[22/08/2023, 06:06:31] [Harmony Hub] INFO - starting hub discovery
[22/08/2023, 06:06:32] [Deebot] Plugin initialised. Setting up accessories....
[22/08/2023, 06:06:32] [Deebot] Using ecovacs-deebot library v0.9.5.
[22/08/2023, 06:06:39] [Tuya] Log in to Tuya Cloud.
[22/08/2023, 06:06:39] [Tuya] [TuyaOpenAPI] Login to: https://openapi.tuyaus.com
Setup Payload:
X-HM://00251XXXXXXWR
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge 8B67",
        "username": "0EXXXXXXXX:F0",
        "port": 51271,
        "pin": "955-09-690",
        "advertiser": "avahi"
    },
    "accessories": [
        {
            "name": "Dummy Switch",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 1000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "email": "aXXXXXXXXz@XXXXXX.com",
            "password": "7XXXXXXX65",
            "name": "myQ",
            "platform": "myQ"
        },
        {
            "platform": "HarmonyHub",
            "name": "HarmonyHub"
        },
        {
            "name": "Harmony Hub",
            "hubIP": "19XXXXXXX76",
            "hubName": "Harmony Hub",
            "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000,
            "HUB_CONNECT_TIMEOUT": 10000,
            "HUB_SEND_TIMEOUT": 30000,
            "TVAccessory": true,
            "sortInput": 0,
            "configureAccesscontrol": false,
            "mainActivity": "Watch Smart TV",
            "playPauseBehavior": true,
            "switchAccessories": true,
            "publishGeneralMuteSwitch": true,
            "publishGeneralVolumeSlider": true,
            "publishGeneralVolumeSwitches": true,
            "linkVolumeControlToTV": true,
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "otherPlatforms": [
                {
                    "TVAccessory": false,
                    "sortInput": 0
                }
            ],
            "platform": "HarmonyHubWebSocket"
        },
        {
            "name": "Smartthings Plug (IK)",
            "BaseURL": "https://api.smartthings.com/v1/",
            "AccessToken": "5e527710-c6bc-49c3-a240-ee060b9bed64",
            "GarageDoorMaxPoll": 40,
            "PollLocksSeconds": 10,
            "PollDoorsSeconds": 10,
            "PollSensorsSeconds": 5,
            "PollSwitchesAndLightsSeconds": 10,
            "PollWindowShadesSeconds": 20,
            "platform": "HomeBridgeSmartThings",
            "_bridge": {
                "username": "0E:XXXXXXX:05",
                "port": 36906
            }
        },
        {
            "name": "Deebot",
            "countryCode": "US",
            "username": "ajXXXXXXX@XXXcom",
            "password": "iXXXXXXXXXXHJ",
            "disableDeviceLogging": true,
            "platform": "Deebot"
        },
        {
            "name": "Tuya",
            "options": {
                "projectType": "2",
                "endpoint": "https://openapi.tuyaus.com",
                "accessId": "y9qXXXXXXXXXXXXf4qm8y",
                "accessKey": "7c70XXXXXXXXXXXXXXXXXXe76f2cc",
                "countryCode": 1,
                "username": "aXXXXXXXXXXXXXcom",
                "password": "QXXXXXXXXXXXXX#6",
                "appSchema": "smartlife"
            },
            "platform": "TuyaPlatform"
        },
        {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&login_hint=AJDLj6LQu-SMCQLMJfOUep6S7tCepb6TqB3tlgh55_9dvg15uZzbadd_Y5zlqv-x2jUU32d1hYXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXid=733249279899-44tchle2kaa9afr5v9ov7jbuojfr9lrq.apps.googleusercontent.com&origin=https%3A%2F%2Fhome.nest.com&scope=openid%20profile%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fnest-account&ss_domaiXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.com&include_granted_scopes=true",
                "cookies": "NID=511=Cw26yoQ_11ELYwZWIZmxPsoLJPbcmj-lfxjVfrwKDpwnnZ45vD9QknXRrOYHuq59BcnTG8RdGo1S7G7QM_dn2ZdTSKva_LFbsJ2yXqh88VrZLkufDKAj33m7JsmlXXXXXXXXXXXXXXXXXXXXXX8JTPobrLAUzQMbpim_-zGzvl_0ih7XCOvwppMhbrU_HKQKY6jZICd_8IbsaJ5n0MnOO01WQ3gJrbmu1CAMSzXpT89RPFWKWFqVc; __SecXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYvddLqfN6hIamJA552BA6WGw.; __Secure-3PAPISID=EKivdFocPEKlKAcx/A4zZlMln9WwLN7JBz; __Host-3PLSID=s.youtube:Zwi5pvTkRqn2J8mmAXbbaVt0HWd8MK_BMI0xQvo69VgbJywYySAGVjneqoCCd8fuWEJxzQ.; __Secure-3PSIDCC=APoG2W8pMWQVeiiRWhuaDhlUrFmDktwvSiDqsM6R0_O9Rz-G9wlAdjIyI4UvMeMAHe6jV_amCA",
                "apiKey": "AIzaSyAdXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXsZE4"
            },
            "platform": "Nest",
            "_bridge": {
                "username": "0EXXXXXXXXXXXXXC7",
                "port": 44274
            }
        },
        {
            "bonds": [
                {
                    "ip_address": "192.168.4.168",
                    "token": "XXXXXXXXXXXXXXXXX2cd"
                }
            ],
            "include_dimmer": true,
            "include_toggle_state": true,
            "fan_speed_values": true,
            "_bridge": {
                "username": "XXXXXXXXXXXXxX:77",
                "port": 42356
            },
            "request_timeout": {
                "title": "Timeout for requests to the bond bridge.",
                "type": "number",
                "default": 1000,
                "required": false,
                "description": "Request timeout for network requests to the bond bridge."
            },
            "delay_in_seconds": {
                "title": "Delay in seconds between commands issued by the bond.",
                "type": "number",
                "default": 0,
                "required": false,
                "description": "A delay in seconds between commands issued by the bridge. This solves issues with too many commands being issued on automations and signals not getting to devices"
            },
            "platform": "Bond"
        },
        {
            "country": "US",
            "language": "en-US",
            "auth_mode": "token",
            "refresh_token": "2f7840XXXXXXXXXXXXXXXXXXXXXXXXXXXXX06f804b006d595bacad68c75f689e1687e0826abdb860dad8c86f5e3d1",
            "username": "aXXXXXXXXXXXXXXom",
            "password": "XXXXXXXXXXXXXXXXXX@07*",
            "devices": [
                {
                    "id": "b5XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0de6",
                    "name": "Front Load Washer",
                    "type": "WASHER",
                    "washer_trigger": true,
                    "washer_door_lock": true
                }
            ],
            "thinq1": false,
            "refresh_interval": 60,
            "platform": "LGThinQ",
            "_bridge": {
                "username": "XXXXXXXXXXXXXXXX:39",
                "port": 38363
            }
        }
    ],
    "disabledPlugins": []
}
```

### Environment

- OS: Raspbian GNU/Linux Bullseye (11)
- Software:
- Node: [v18.17.0](https://homebridge.io/w/JTKEF)
- npm:

### Process Supervisor

hb-service

### Additional Context

Sorry, not sure of the answer to everything above

**Comment by NorthernMan54** [comment]
Looks like one of the plugins is causing homebridge to crash

This portion of the log is the tail end of a crash, triggered by one of your plugins/devices misbehaving.

```
[22/08/2023, 06:05:21] [Harmony Hub] INFO - stopping hub discovery, hubs found : undefined
[22/08/2023, 06:05:34] [Deebot] ***** Disabling plugin. *****
[22/08/2023, 06:05:34] [Deebot] ***** connect EHOSTUNREACH 34.208.149.223:443 at Function.AxiosError.from (/var/lib/homebridge/node_modules/homebridge-deebot/node_modules/axios/lib/core/AxiosError.js:89:14). *****
[22/08/2023, 06:05:34] Error: connect EHOSTUNREACH 54.188.51.105:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
[22/08/2023, 06:05:34] [Harmony Hub] (Harmony Hub)Error - Error retrieving info from hub : network timeout at: http://192.168.7.176:8088/-(1)
[22/08/2023, 06:05:35] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 8B67) is running on port 51271.
[22/08/2023, 06:05:35] [myQ] connect EHOSTUNREACH 13.83.98.203:443
[22/08/2023, 06:05:35] [myQ] myQ API: Unable to access the OAuth authorization endpoint.
[22/08/2023, 06:05:35] Got SIGTERM, shutting down Homebridge...
[22/08/2023, 06:05:35] [Harmony Hub] INFO - shutdown
[22/08/2023, 06:05:36] [Smartthings Plug (IK)] Child bridge process ended
[22/08/2023, 06:05:36] [Nest] Child bridge process ended
[22/08/2023, 06:05:36] [homebridge-bond] Child bridge process ended
[22/08/2023, 06:05:36] [homebridge-lg-thinq] Child bridge process ended
[22/08/2023, 06:05:36] [Nest] Process Ended. Code: null, Signal: SIGTERM
[22/08/2023, 06:05:36] [homebridge-lg-thinq] Process Ended. Code: null, Signal: SIGTERM
[22/08/2023, 06:05:36] [homebridge-bond] Process Ended. Code: null, Signal: SIGTERM
[22/08/2023, 06:05:36] [Smartthings Plug (IK)] Process Ended. Code: null, Signal: SIGTERM
[22/08/2023, 06:05:39] [Harmony Hub] (Harmony Hub)INFO - Loading activities...
[22/08/2023, 06:05:40] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[22/08/2023, 06:05:45] [HB Supervisor] Restarting Homebridge...
```

As you have a lot of network timeout/connectivity errors, am thinking something is wrong with your network or ??

**Comment by bwp91** [comment]
Hi @droopdog7 

Looks like there is indeed a network issue in general, but looks like my deebot plugin is to blame for the homebridge crashing.

Could you file an issue here with some more details about (eg) the version of the deebot plugin you are running?

https://github.com/bwp91/homebridge-deebot/issues/new?assignees=&labels=&projects=&template=new-issue.md&title=
