### ISSUE TITLE
SyntaxError: totalConsumption: duplicate key

### ISSUE THREAD

**Issue by KatyPurry** [homebridge/homebridge#3445]
### Current Situation

I'm not sure how long I've had this error, but I realized it today, and it keeps coming back. 

### Logs

```markdown
[10/11/2023, 7:22:23 PM] [deCONZ-alex] Phoscon-GW: Prise SilverCrest 2: add accessory
[10/11/2023, 7:22:23 PM] [deCONZ-alex] Prise SilverCrest 2: _TZ3000_ynmowqk2 TS011F v1.0.5 (3 resources)
[10/11/2023, 7:22:23 PM] [deCONZ-alex] Prise Lidl Inutilisée: Configured Name: warning: 11 listeners
[10/11/2023, 7:22:23 PM] [deCONZ-alex] Prise Lidl Inutilisée: On: warning: 11 listeners
[10/11/2023, 7:22:23 PM] [deCONZ-alex] Prise SilverCrest 2 Consumption: Configured Name: warning: 11 listeners
[10/11/2023, 7:22:23 PM] [deCONZ-alex] Prise SilverCrest 2 Consumption: Enabled: warning: 11 listeners
[10/11/2023, 7:22:23 PM] [deCONZ-alex] Prise Lidl Inutilisée: Lock Physical Controls: warning: 11 listeners
[10/11/2023, 7:22:23 PM] [deCONZ-alex] Phoscon-GW: error: SyntaxError: totalConsumption: duplicate key
    at Power.addCharacteristicDelegate (/homebridge/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/ServiceDelegate/index.js:229:13)
    at new Light (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Light.js:92:57)
    at Gateway.addAccessory (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:625:25)
    at Gateway.analyseFullState (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:1122:20)
    at Gateway.poll (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:966:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Gateway.heartbeat (/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:358:9)
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 identify listeners added to [PlatformAccessory]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [ConfiguredName]. Use emitter.setMaxListeners() to increase limit
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [On]. Use emitter.setMaxListeners() to increase limit
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [ConfiguredName]. Use emitter.setMaxListeners() to increase limit
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [Characteristic]. Use emitter.setMaxListeners() to increase limit
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [LockPhysicalControls]. Use emitter.setMaxListeners() to increase limit
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 identify listeners added to [PlatformAccessory]. Use emitter.setMaxListeners() to increase limit
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [ConfiguredName]. Use emitter.setMaxListeners() to increase limit
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [On]. Use emitter.setMaxListeners() to increase limit
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [ConfiguredName]. Use emitter.setMaxListeners() to increase limit
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [Characteristic]. Use emitter.setMaxListeners() to increase limit
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [LockPhysicalControls]. Use emitter.setMaxListeners() to increase limit
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 identify listeners added to [PlatformAccessory]. Use emitter.setMaxListeners() to increase limit
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [ConfiguredName]. Use emitter.setMaxListeners() to increase limit
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [On]. Use emitter.setMaxListeners() to increase limit
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [ConfiguredName]. Use emitter.setMaxListeners() to increase limit
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [Characteristic]. Use emitter.setMaxListeners() to increase limit
(node:803) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set listeners added to [LockPhysicalControls]. Use emitter.setMaxListeners() to increase limit
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge 1B9A",
        "username": "xxx",
        "port": 51070,
        "pin": "xxx",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "deCONZ-alex",
            "hosts": [
                "xxx"
            ],
            "platform": "deCONZ",
            "_bridge": {
                "username": "xxx",
                "port": 50905
            }
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome",
            "_bridge": {
                "username": "xxx",
                "port": 50777
            }
        }
    ]
}
```

### Environment

- OS: Unraid
- homebridge-deconz v1.0.4 
- Node: 18.13
- npm: 8.19.3

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

oznu/homebridge:ubuntu

**Comment by ebaauw** [comment]
This is not an issue with Homebridge, but with the Homebridge deCONZ plugin.  It should have been solved in v1.0.4, see https://github.com/ebaauw/homebridge-deconz/issues/174.  Did you restart Homebridge after upgrading the plugin?  If that doesn't remedy the error, please open an issue with the plugin, attaching the debug dump file and capturing and attaching the log file, from Homebridge startup to when the error first occurs.
