### ISSUE TITLE
Upgraded Node using hb-service update-node and web UI is no longer available

### ISSUE THREAD

**Issue by nebosphere19** [homebridge/homebridge#3468]
### Current Situation

Used hb-service update-node in order to go from Node 16.x to 20.x and homebridge  gets stuck in a startup loop now. 

### Logs

```markdown
Here is where the error is during the startup process:

[10/29/2023, 1:44:43 PM] [HB Supervisor] Homebridge Storage Path: /Users/barons/.homebridge
[10/29/2023, 1:44:43 PM] [HB Supervisor] Homebridge Config Path: /Users/barons/.homebridge/config.json
[10/29/2023, 1:44:43 PM] [HB Supervisor] Logging to /Users/barons/.homebridge/homebridge.log
[10/29/2023, 1:44:43 PM] [HB Supervisor] OS: Darwin 21.6.0 x64
[10/29/2023, 1:44:43 PM] [HB Supervisor] Node.js v20.9.0 /usr/local/bin/node
[10/29/2023, 1:44:43 PM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[10/29/2023, 1:44:43 PM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[10/29/2023, 1:44:44 PM] [HB Supervisor] ERROR: The user interface threw an unhandled error
Error: unsupported
    at configSecureContext (node:internal/tls/secure-context:278:15)
    at Object.createSecureContext (node:_tls_common:116:3)
    at Server.setSecureContext (node:_tls_wrap:1471:27)
    at Server (node:_tls_wrap:1335:8)
    at new Server (node:https:75:3)
    at Object.createServer (node:https:132:10)
    at getServerInstance (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/fastify/lib/server.js:355:22)
    at createServer (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/fastify/lib/server.js:25:18)
    at fastify (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/fastify/fastify.js:196:30)
    at new FastifyAdapter (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/platform-fastify/adapters/fastify-adapter.js:90:37)
    at bootstrap (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/main.js:30185:22)
    at HomebridgeServiceHelper.runUi (/usr/local/lib/node_modules/homebridge-config-ui-x/src/bin/hb-service.ts:535:18)
    at HomebridgeServiceHelper.launch (/usr/local/lib/node_modules/homebridge-config-ui-x/src/bin/hb-service.ts:377:5)
[10/29/2023, 1:44:44 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -K
[10/29/2023, 1:44:44 PM] [HB Supervisor] Started Homebridge v1.6.1 with PID: 3147
[10/29/2023, 1:44:45 PM] Loaded config.json with 5 accessories and 7 platforms.
```

### Configuration

```json
barons-mac-pro:.homebridge barons$ cat config.json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154",
        "advertiser": "bonjour-hap",
        "bind": [
            "en0"
        ]
    },
    "platforms": [
        {
            "name": "Home Alarm",
            "cameras": true,
            "debug": false,
            "sensorRefresh": 15,
            "persistAccessories": true,
            "cameraOptions": {
                "enableHwaccelRpi": true
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
        },
        {
            "name": "Config",
            "port": 8585,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "ssl": {
                "pfx": "/etc/ssl/certs/homebridgeUIX.pfx",
                "passphrase": "XXXXXXX"
            },
            "platform": "config"
        },
        {
            "devices": [
                {
                    "name": "Playroom TV",
                    "ip": "10.0.0.74",
                    "mac": "38:8C:50:F0:E8:44",
                    "prefsDir": "~/.webosTv",
                    "pollingInterval": 1,
                    "deepDebugLog": false,
                    "volumeLimit": 100,
                    "volumeControl": "false",
                    "channelControl": false,
                    "mediaControl": false,
                    "screenControl": false,
                    "inputs": [
                        {
                            "name": "Denon Receiver",
                            "appId": "com.webos.app.hdmi2"
                        },
                        {
                            "name": "HDMI 1",
                            "appId": "com.webos.app.hdmi1"
                        }
                    ]
                }
            ],
            "platform": "webostv"
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "switchModels": [
                "KP400"
            ],
            "broadcast": "10.0.0.255",
            "pollingInterval": 5,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "excludeMacAddresses": [
                "D8:07:B6:2E:99:44"
            ],
            "devices": [
                {
                    "host": "10.0.0.22"
                }
            ],
            "platform": "TplinkSmarthome"
        },
        {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "XXXXXXX",
                "cookies": "XXXXXXXXXX"
            },
            "fanDurationMinutes": 240,
            "options": [
                "Thermostat.SeparateBuiltInHumiditySensor.Enable",
                "Thermostat.SeparateBuiltInTemperatureSensor.Enable",
                "HomeAway.AsOccupancySensorAndSwitch"
            ],
            "platform": "Nest"
        },
        {
            "platform": "NotifyEvents",
            "action": {
                "enabled": false,
                "listen": "0.0.0.0",
                "port": 53535,
                "host": "",
                "path": "/"
            },
            "channels": [
                {
                    "title": "SMS",
                    "token": "XXXXXXXXXXXXX",
                    "messages": [
                        {
                            "name": "Fridge Door Notifier",
                            "title": "ALERT: A Fridge Door is Open!!!!",
                            "text": "Please close it. ",
                            "priority": "highest",
                            "level": "warning",
                            "images": [],
                            "files": [],
                            "actions": []
                        }
                    ]
                }
            ]
        },
        {
            "devices": [
                {
                    "name": "Denon-AVR-X3800H",
                    "host": "10.0.0.40",
                    "port": 8080,
                    "zoneControl": 0,
                    "getInputsFromDevice": true,
                    "getFavoritesFromDevice": true,
                    "getQuickSmartSelectFromDevice": true,
                    "sensorPower": true,
                    "sensorVolume": true,
                    "sensorMute": true,
                    "sensorInput": true,
                    "enableDebugMode": false,
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "disableLogConnectError": false,
                    "supportOldAvr": false,
                    "masterPower": false,
                    "masterVolume": false,
                    "masterMute": false,
                    "refreshInterval": 5,
                    "enableRestFul": false,
                    "restFulDebug": false,
                    "enableMqtt": false,
                    "mqttDebug": false,
                    "mqttAuth": false
                }
            ],
            "platform": "DenonTv"
        }
    ],
    "accessories": [
        {
            "name": "Fujitsu Mini Split",
            "username": "XXXXXXXXXXX",
            "password": "XXXXXXXXXXX",
            "deviceIndex": "0",
            "interval": "300",
            "region": "us",
            "accessory": "FGLairThermostat"
        },
        {
            "name": "TV Lights Timer",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 180001,
            "random": false,
            "resettable": true,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "Bypass Motion Light",
            "stateful": true,
            "reverse": false,
            "time": 1001,
            "random": false,
            "resettable": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "Utility Lights Timer",
            "stateful": false,
            "reverse": false,
            "time": 180001,
            "random": false,
            "resettable": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "Theo Piano Practice",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 1500000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        }
    ],
    "disabledPlugins": [
        "homebridge-nest-cam",
        "homebridge-nest"
    ]
}
```

### Environment

- OS: MacOS 12.7.1
- Software: 1.6.1
- Node: 20.9.0
- npm: 10.1.0

### Process Supervisor

hb-service

### Additional Context

Works fine with Node version 16.x

**Comment by donavanbecker** [comment]
Have you tried:

```
sudo hb-service rebuild
```

**Comment by nebosphere19** [comment]
I did - same result

**Comment by nebosphere19** [comment]
SOLVED!!! Turns out the https config in my config.json was messing things up. I'll just turn it off for now, but perhaps there's an update for it?

**Comment by jsiegenthaler** [comment]
@nebosphere19  if this issue has been resolved please consider closing this issue
