### ISSUE TITLE
npm ERR! Invalid Version: 1.4.1-01

### ISSUE THREAD

**Issue by deflao** [homebridge/homebridge#3478]
### Current Situation

I'm trying to update from v1.6.1 to 1.7.0 but it kept giving me this error:

          npm ERR! Invalid Version: 1.4.1-01
          
          npm ERR! A complete log of this run can be found in: /home/pi/.npm/_logs/2023-11-04T21_17_37_978Z-debug-0.log
          
          Operation failed. Please review log for details.

![Untitled](https://github.com/homebridge/homebridge/assets/90084270/a7c3d888-72fe-452e-be0b-61ddedc04ff3)

### Logs

```markdown
0 verbose cli /opt/homebridge/bin/node /opt/homebridge/bin/npm
1 info using npm@10.2.1
2 info using node@v20.9.0
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 5ms
5 timing config:load:file:/opt/homebridge/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 7ms
8 warn config global-style This option has been deprecated in favor of `--install-strategy=shallow`
9 timing config:load:env Completed in 2ms
10 warn config global-style This option has been deprecated in favor of `--install-strategy=shallow`
11 timing config:load:file:/var/lib/homebridge/.npmrc Completed in 5ms
12 timing config:load:project Completed in 7ms
13 timing config:load:file:/home/pi/.npmrc Completed in 0ms
14 timing config:load:user Completed in 0ms
15 timing config:load:file:/opt/homebridge/etc/npmrc Completed in 0ms
16 timing config:load:global Completed in 1ms
17 timing config:load:setEnvs Completed in 3ms
18 timing config:load Completed in 28ms
19 timing npm:load:configload Completed in 28ms
20 timing config:load:flatten Completed in 7ms
21 timing npm:load:mkdirpcache Completed in 0ms
22 timing npm:load:mkdirplogs Completed in 1ms
23 verbose title npm install homebridge@1.7.0
24 verbose argv "install" "--save" "homebridge@1.7.0"
25 timing npm:load:setTitle Completed in 2ms
26 timing npm:load:display Completed in 1ms
27 verbose logfile logs-max:10 dir:/home/pi/.npm/_logs/2023-11-04T21_17_37_978Z-
28 verbose logfile /home/pi/.npm/_logs/2023-11-04T21_17_37_978Z-debug-0.log
29 timing npm:load:logFile Completed in 24ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 106ms
33 timing arborist:ctor Completed in 2ms
34 silly logfile start cleaning logs, removing 1 files
35 timing arborist:ctor Completed in 0ms
36 silly logfile done cleaning log files
37 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
38 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
39 timing idealTree:init Completed in 2859ms
40 timing idealTree:userRequests Completed in 3ms
41 silly idealTree buildDeps
42 silly fetch manifest homebridge@1.7.0
43 http fetch GET 200 https://registry.npmjs.org/homebridge 324ms (cache revalidated)
44 silly placeDep ROOT homebridge@1.7.0 REPLACE for:  want: 1.7.0
45 silly fetch manifest commander@^7.2.0
46 silly fetch manifest semver@^7.5.4
47 http fetch GET 200 https://registry.npmjs.org/semver 88ms (cache revalidated)
48 http fetch GET 200 https://registry.npmjs.org/commander 197ms (cache revalidated)
49 timing idealTree:#root Completed in 635ms
50 silly placeDep node_modules/homebridge commander@7.2.0 OK for: homebridge@1.7.0 want: ^7.2.0
51 silly placeDep node_modules/homebridge semver@7.5.4 OK for: homebridge@1.7.0 want: ^7.5.4
52 silly fetch manifest lru-cache@^6.0.0
53 http fetch GET 200 https://registry.npmjs.org/lru-cache 53ms (cache revalidated)
54 timing idealTree:node_modules/homebridge Completed in 74ms
55 silly fetch manifest noble-device@AMoo-Miki/noble-device
56 timing idealTree Completed in 4793ms
57 timing command:install Completed in 4815ms
58 verbose stack TypeError: Invalid Version: 1.4.1-01
58 verbose stack     at new SemVer (/opt/homebridge/lib/node_modules/npm/node_modules/semver/classes/semver.js:38:13)
58 verbose stack     at compare (/opt/homebridge/lib/node_modules/npm/node_modules/semver/functions/compare.js:3:3)
58 verbose stack     at Object.gte (/opt/homebridge/lib/node_modules/npm/node_modules/semver/functions/gte.js:2:30)
58 verbose stack     at CanPlaceDep.checkCanPlaceCurrent (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/can-place-dep.js:173:51)
58 verbose stack     at CanPlaceDep.checkCanPlace (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/can-place-dep.js:157:27)
58 verbose stack     at new CanPlaceDep (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/can-place-dep.js:114:26)
58 verbose stack     at new PlaceDep (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:87:19)
58 verbose stack     at #buildDepStep (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:933:18)
58 verbose stack     at async Arborist.buildIdealTree (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js>
58 verbose stack     at async Promise.all (index 1)
59 verbose cwd /var/lib/homebridge
60 verbose Linux 6.1.21-v7l+
61 verbose node v20.9.0
62 verbose npm  v10.2.1
63 error Invalid Version: 1.4.1-01
64 verbose exit 1
65 timing npm Completed in 5465ms
66 verbose unfinished npm timer reify 1699132658631
67 verbose unfinished npm timer reify:loadTrees 1699132658636
68 verbose unfinished npm timer idealTree:buildDeps 1699132661503
69 verbose unfinished npm timer idealTree:node_modules/homebridge-switchmate-ble 1699132662216
70 verbose code 1
71 error A complete log of this run can be found in: /home/pi/.npm/_logs/2023-11-04T21_17_37_978Z-debug-0.log
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge 7D6E",
        "username": "xxxxx",
        "port": xxxx,
        "pin": "xxxxx",
        "advertiser": "avahi"
    },
    "accessories": [
        {
            "name": "Roku TV State",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 5000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "host": "localhost",
            "https": false,
            "port": 3000,
            "username": "xxxx",
            "password": "xxxx",
            "name": "AdGuard Home",
            "type": "SWITCH",
            "autoOnTimer": [
                0
            ],
            "hideNonTimer": false,
            "stateLogging": true,
            "accessory": "AdGuardHome"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "options": {
                "projectType": "2",
                "accessId": "xxxx",
                "accessKey": "xxxx",
                "countryCode": 1,
                "username": "xxxxx",
                "password": "xxxx",
                "appSchema": "tuyaSmart"
            },
            "platform": "TuyaPlatform"
        },
        {
            "name": "Govee",
            "username": "xxxx",
            "password": "xxxx",
            "bleDisable": true,
            "platform": "Govee"
        },
        {
            "name": "SwitchBot",
            "credentials": {
                "token": "xxxx",
                "secret": "xxxx",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "irdevices": [
                    {
                        "deviceId": "xxxx",
                        "configRemoteType": "DIY Fan",
                        "irfan": {
                            "swing_mode": false
                        },
                        "logging": "none"
                    }
                ]
            },
            "platform": "SwitchBot"
        },
        {
            "name": "orbit",
            "email": "xxxx",
            "password": "xxxx",
            "platform": "orbit"
        },
        {
            "devices": [
                {
                    "name": "Smartmi Air Purifier",
                    "ip": "xxxx",
                    "token": "xxxxx",
                    "deviceId": "xxxx",
                    "model": "zhimi.airpurifier.za1",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "buzzerControl": false,
                    "ledControl": false,
                    "childLockControl": false,
                    "modeControl": false
                }
            ],
            "platform": "miot"
        },
        {
            "platform": "SwitchmateBLE",
            "devices": [
                {
                    "name": "Patio Lights",
                    "id": "xxxxx"
                },
                {
                    "name": "Garage Lights",
                    "id": "xxxxx"
                }
            ]
        }
    ]
}
```

### Environment

- OS: Raspbian GNU/Linux Bullseye (11)
- Software: homebridge 1.6.1
- Node: 20.9.0
- npm: 10.2.1

### Process Supervisor

hb-service

**Comment by donavanbecker** [comment]
Have you update Homebridge UI to 4.52.1, and tried again?

**Comment by deflao** [comment]
I just did. Still the same error

**Comment by donavanbecker** [comment]
Did you have a plugin installed called `homebridge-switchmate-ble`? it looks like this is where this is potentially resulting from.

**Comment by deflao** [comment]
Yes, I do have that plugin. I tried to remove it to see if it helped but it won't even let me remove the plugin. Same error: npm ERR! Invalid Version: 1.4.1-01

**Comment by donavanbecker** [comment]
This definitely has something to do with the plugin: [homebridge-switchmate-ble#22](https://github.com/AMoo-Miki/homebridge-switchmate-ble/issues/22)

**Comment by donavanbecker** [comment]
from Homebridge UI terminal can you type `ls` and then enter? please post output here for next steps.

**Comment by deflao** [comment]
accessories  adguardhome_timer.config  auth.json  backups  bwp91_cache  config.json  homebridge.log  node_modules  package.json  persist

**Comment by deflao** [comment]
I don't know if this help
https://stackoverflow.com/questions/71383116/npm-err-invalid-version-on-npm-install

**Comment by deflao** [comment]
pi@homebridge:/var/lib/homebridge $ ls
accessories  adguardhome_timer.config  auth.json  backups  bwp91_cache  config.json  homebridge.log  node_modules  package.json  persist

![Untitled](https://github.com/homebridge/homebridge/assets/90084270/09a0114f-82a0-4f83-aaff-7cb4f0994cb8)

**Comment by donavanbecker** [comment]
1. enter `cd node_modules`
2. enter `ls`
3. post output here

**Comment by deflao** [comment]
<img width="1280" alt="Screenshot 2023-11-05 at 12 23 11 AM" src="https://github.com/homebridge/homebridge/assets/90084270/312cd65a-c369-465f-8218-00f60d3705be">

**Comment by donavanbecker** [comment]
if you no longer need homebridge-switchmate-ble then run:

1. `rm -r homebridge-switchmate-ble`
2. finally try upgrading homebridge

**Comment by deflao** [comment]
okay that fixed the problem of upgrading homebridge and another plugin. There's a small problem that after restarting homebridge, the homebridge-switchmate-ble appears again in the plugin tab. The difference now is I can uninstall the plugin without any error and it won't appear again after restarting.

**Comment by donavanbecker** [comment]
@deflao That is a permission issue.
