### ISSUE TITLE
Accessory Not Found - Cannot Add Bridge to HomeKit

### ISSUE THREAD

**Issue by agw421** [homebridge/homebridge#3500]
### Current Situation

Hey all,

I'm having a problem I've seen a few times on this forum, but not lately. I cannot seem to re-add my Homebridge Bridge to HomeKit. About 9 months ago, I got everything setup flawlessly and was enjoying HomeBridge. However, it failed to start one day and the accessories became unresponsive in Home App. 

That's when I stopped and restarted the service. That didn't work, so I tried many things:

- Updated Homebridge
- Updated Homebridge UI
- Checked and updated Node and NPM versions
- Eventually, I got Homebridge back online without any accessories displaying, but the log showed them working and connecting
- Removed all related bridges from Home app and Homebridge
- Updated my iOS to the latest 17.1.1
- Reinstalled and reconfigured every plugin manually (lost my configuration)
- Struggled to get the main Bridge added back into Home app
- Still struggling at this step. It is slightly possible that I have two Nodes installed? Not sure how to look.

Would be greatly appreciative to anyone that can help get my accessories added back to HomeKit!

### Logs

```markdown
[11/27/2023, 8:36:31 AM] [Homebridge UI] Homebridge restart request received
[11/27/2023, 8:36:31 AM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[11/27/2023, 8:36:31 AM] [Homebridge UI] Sending SIGTERM to Homebridge
[11/27/2023, 8:36:31 AM] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGTERM
[11/27/2023, 8:36:36 AM] [HB Supervisor] Restarting Homebridge...
[11/27/2023, 8:36:36 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[11/27/2023, 8:36:36 AM] [HB Supervisor] Started Homebridge v1.7.0 with PID: 119440
[11/27/2023, 8:36:36 AM] Loaded config.json with 0 accessories and 4 platforms.
[11/27/2023, 8:36:36 AM] ---
[11/27/2023, 8:36:37 AM] Loaded plugin: homebridge-config-ui-x@4.53.0
[11/27/2023, 8:36:37 AM] Registering platform 'homebridge-config-ui-x.config'
[11/27/2023, 8:36:37 AM] ---
[11/27/2023, 8:36:37 AM] Loaded plugin: homebridge-node-alarm-dot-com@1.10.0
[11/27/2023, 8:36:37 AM] Registering platform 'homebridge-node-alarm-dot-com.Alarmdotcom'
[11/27/2023, 8:36:37 AM] ---
[11/27/2023, 8:36:37 AM] Loaded plugin: homebridge-samsungtv-2014@1.2.5
[11/27/2023, 8:36:37 AM] Registering platform 'homebridge-samsungtv-2014.SamsungTV2014'
[11/27/2023, 8:36:37 AM] ---
[11/27/2023, 8:36:38 AM] Disabled plugin: @switchbot/homebridge-switchbot@2.12.1
[11/27/2023, 8:36:38 AM] ---
[11/27/2023, 8:36:38 AM] Loading 4 platforms...
[11/27/2023, 8:36:38 AM] [ADT] Initializing Alarmdotcom platform...
[11/27/2023, 8:36:38 AM] [ADT] Initializing child bridge 0E:A4:EE:FA:97:41
[11/27/2023, 8:36:38 AM] [SamsungTV2014] Initializing SamsungTV2014 platform...
[11/27/2023, 8:36:38 AM] Ignoring config for the platform "SwitchBot" in your config.json as the plugin "@switchbot/homebridge-switchbot" has been disabled.
[11/27/2023, 8:36:38 AM] [SamsungTV2014] Initializing child bridge 0E:6C:EE:4D:6D:43
[11/27/2023, 8:36:38 AM] Publishing bridge accessory (name: Homebridge E285, publishInfo: {
  username: '0E:B1:DC:F9:32:F7',
  port: 51336,
  pincode: '***-**-***',
  category: 2,
  bind: [ 'Ethernet', 'vEthernet (Default Switch)', [length]: 2 ],
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'bonjour-hap'
}).
Setup Payload:
X-HM://0024LL0GU8M17
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 682-78-942 │     
    └────────────┘     
                       
[11/27/2023, 8:36:38 AM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge E285) is running on port 51336.
[11/27/2023, 8:36:38 AM] [homebridge-samsungtv-2014] Launched child bridge with PID 111696
[11/27/2023, 8:36:38 AM] [ADT] Launched child bridge with PID 111188
[11/27/2023, 8:36:38 AM] Registering platform 'homebridge-samsungtv-2014.SamsungTV2014'
[11/27/2023, 8:36:38 AM] [homebridge-samsungtv-2014] Loaded homebridge-samsungtv-2014 v1.2.5 child bridge successfully
[11/27/2023, 8:36:38 AM] Registering platform 'homebridge-node-alarm-dot-com.Alarmdotcom'
[11/27/2023, 8:36:38 AM] [ADT] Loaded homebridge-node-alarm-dot-com v1.10.0 child bridge successfully
[11/27/2023, 8:36:38 AM] [homebridge-samsungtv-2014] Created TV Samsung 65 at IP address 10.108.1.238
[11/27/2023, 8:36:38 AM] Initializing platform accessory 'Samsung 65'...
[11/27/2023, 8:36:38 AM] Loaded 12 cached accessories from cachedAccessories.0EA4EEFA9741.
[11/27/2023, 8:36:39 AM] [ADT] Loaded from cache: Panel (105683454-127)
[11/27/2023, 8:36:39 AM] [ADT] Loaded from cache: BR WIN (105683454-3)
[11/27/2023, 8:36:39 AM] [ADT] Loaded from cache: BR WIN 2 (105683454-4)
[11/27/2023, 8:36:39 AM] [ADT] Loaded from cache: Front Door (105683454-1)
[11/27/2023, 8:36:39 AM] [ADT] Loaded from cache: Garage Door (105683454-2)
[11/27/2023, 8:36:39 AM] [ADT] Loaded from cache: Main Heat (105683454-7)
[11/27/2023, 8:36:39 AM] [ADT] Loaded from cache: Main Motion (105683454-5)
[11/27/2023, 8:36:39 AM] [ADT] Loaded from cache: Main SMK (105683454-6)
[11/27/2023, 8:36:39 AM] [ADT] Loaded from cache: Panel Camera (251) (105683454-251)
[11/27/2023, 8:36:39 AM] [ADT] Loaded from cache: System (105683454-5513)
[11/27/2023, 8:36:39 AM] [ADT] Loaded from cache: Front Lock (105683454-1200)
[11/27/2023, 8:36:39 AM] [ADT] Loaded from cache: Garage (105683454-1201)
[11/27/2023, 8:36:39 AM] Publishing bridge accessory (name: ADT, publishInfo: {
  username: '0E:A4:EE:FA:97:41',
  port: 55083,
  pincode: '***-**-***',
  category: 2,
  bind: [ 'Ethernet', 'vEthernet (Default Switch)', [length]: 2 ],
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'bonjour-hap'
}).
[11/27/2023, 8:36:39 AM] Publishing bridge accessory (name: homebridge-samsungtv-2014, publishInfo: {
  username: '0E:6C:EE:4D:6D:43',
  port: 57158,
  pincode: '***-**-***',
  category: 2,
  bind: [ 'Ethernet', 'vEthernet (Default Switch)', [length]: 2 ],
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'bonjour-hap'
}).
[11/27/2023, 8:36:39 AM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-samsungtv-2014) is running on port 57158.
[11/27/2023, 8:36:39 AM] Homebridge v1.7.0 (HAP v0.11.1) (ADT) is running on port 55083.
[11/27/2023, 8:36:39 AM] [ADT] Received 1 partitions from Alarm.com
[11/27/2023, 8:36:39 AM] [ADT] Restoring accessory with ID 105683454-127
[11/27/2023, 8:36:39 AM] [ADT] Received 9 sensors from Alarm.com
[11/27/2023, 8:36:39 AM] [ADT] Restoring accessory with ID 105683454-3
[11/27/2023, 8:36:39 AM] [ADT] Restoring accessory with ID 105683454-4
[11/27/2023, 8:36:39 AM] [ADT] Restoring accessory with ID 105683454-1
[11/27/2023, 8:36:39 AM] [ADT] Restoring accessory with ID 105683454-2
[11/27/2023, 8:36:39 AM] [ADT] Restoring accessory with ID 105683454-7
[11/27/2023, 8:36:39 AM] [ADT] Restoring accessory with ID 105683454-5
[11/27/2023, 8:36:39 AM] [ADT] Restoring accessory with ID 105683454-6
[11/27/2023, 8:36:39 AM] [ADT] Restoring accessory with ID 105683454-251
[11/27/2023, 8:36:39 AM] [ADT] Restoring accessory with ID 105683454-5513
[11/27/2023, 8:36:39 AM] [ADT] Received 1 locks from Alarm.com
[11/27/2023, 8:36:39 AM] [ADT] Restoring accessory with ID 105683454-1200
[11/27/2023, 8:36:39 AM] [ADT] Received 1 garages from Alarm.com
[11/27/2023, 8:36:39 AM] [ADT] Restoring accessory with ID 105683454-1201
[11/27/2023, 8:36:40 AM] [homebridge-node-alarm-dot-com] This plugin generated a warning from the characteristic 'Target Door State': characteristic was supplied illegal value: number 2 exceeded maximum of 1. See https://homebridge.io/w/JtMGR for more info.
[11/27/2023, 8:36:40 AM] [homebridge-node-alarm-dot-com] Error: 
    at TargetDoorState.Characteristic.characteristicWarning (C:\Users\AGW\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:3011:105)
    at TargetDoorState.Characteristic.validateUserInput (C:\Users\AGW\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:2927:14)
    at C:\Users\AGW\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:2488:24
    at C:\Users\AGW\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\util\once.ts:15:18
    at TargetDoorState.<anonymous> (C:\Users\AGW\AppData\Roaming\npm\node_modules\homebridge-node-alarm-dot-com\src\index.ts:1288:59)
    at TargetDoorState.emit (node:events:514:28)
    at C:\Users\AGW\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:2463:14
    at new Promise (<anonymous>)
    at TargetDoorState.<anonymous> (C:\Users\AGW\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:2461:12)
    at step (C:\Users\AGW\AppData\Roaming\npm\node_modules\homebridge\node_modules\tslib\tslib.js:195:27)
[11/27/2023, 8:36:41 AM] [homebridge-samsungtv-2014] TV is offline: 1
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge E285",
        "username": "0E:B1:DC:F9:32:F7",
        "port": 51336,
        "pin": "682-78-942",
        "advertiser": "bonjour-hap",
        "bind": [
            "Ethernet",
            "vEthernet (Default Switch)"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "ADT",
            "username": "***",
            "password": "***",
            "useMFA": true,
            "mfaCookie": "***",
            "logLevel": 3,
            "armingModes": {
                "away": {
                    "noEntryDelay": false,
                    "silentArming": false,
                    "nightArming": false
                },
                "night": {
                    "noEntryDelay": false,
                    "silentArming": false,
                    "nightArming": false
                },
                "stay": {
                    "noEntryDelay": false,
                    "silentArming": false,
                    "nightArming": false
                }
            },
            "_bridge": {
                "username": "0E:A4:EE:FA:97:41",
                "port": 55083
            },
            "platform": "Alarmdotcom"
        },
        {
            "tvs": [
                {
                    "name": "Samsung 65",
                    "ipAddress": "***",
                    "sendDelay": 600,
                    "useFan": true
                }
            ],
            "platform": "SamsungTV2014",
            "_bridge": {
                "username": "0E:6C:EE:4D:6D:43",
                "port": 57158
            }
        },
        {
            "name": "SwitchBot",
            "credentials": {
                "token": "***",
                "secret": "***",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "devices": [
                    {
                        "lock": {
                            "activate_latchbutton": false
                        }
                    }
                ]
            },
            "platform": "SwitchBot"
        }
    ],
    "disabledPlugins": [
        "@switchbot/homebridge-switchbot"
    ]
}
```

### Environment

- OS: Microsoft Windows 10 Pro (10.0.19045)
- Homebridge: 1.7.0
- Homebridge UI: 4.53.0
- Node: 20.9.0
- npm: 10.2.2

### Process Supervisor

hb-service

**Comment by agw421** [comment]
I've gone ahead and updated to Node 20.10.0 and updated all plugins to newest versions. Accessories list looks good, but getting no data xfer in the network activity area.

Attempting to add to HomeKit times out after a few minutes.

![image](https://github.com/homebridge/homebridge/assets/5245337/17bc1a78-825a-4eca-9029-b075e26f8bf5)

![image](https://github.com/homebridge/homebridge/assets/5245337/1334ddac-d50d-4e68-b3aa-643869fe2b8d)

**Comment by axelra82** [comment]
I'm encountering a similar issue with homebridge in docker behind Nginx Proxy Manager setup.

- I can access homebrdige UI fine.
- The homebridge hub shows up in HomeKit and I can start the pairing process, but it always times out and displays the "connection lost" message.

Not really sure what's going on here. I've tried different mDNS advertisers but get:
_The selected advertiser, "resolved", isn't available on this platform. Reverting to "bonjour-hap"_

I've seen similar messages when trying out Ciao and Avahi

It seems as though **bonjour-hap** is the only one that is working "properly".

## System

**OS:** Ubuntu 22.04.03 LTS
**Docker:** 24.0.7, build afdd53b
**Docker Compose:** v2.23.0-desktop.1
**Docker Desktop:** 4.25.2 (129061)

## Homebridge system information from UI:

**OS** | Ubuntu Jammy Jellyfish (22.04.3 LTS)
**IPv4 (eth0)** | 192.168.65.9
**IPv6 (eth0)** | IPv6 addr // <-- EDITED: It shows an actual IPv6 address here.
**Hostname** | linuxkit-525400123456
**User** | root
**Node.js Version** | v20.10.0 // <-- I've manually updated to 20 from 18. This was just to see rule out version issues.
**Node.js Path** | /opt/homebridge/bin
**Storage Path** | /var/lib/homebridge
**Config Path** | /var/lib/homebridge/config.json
**Plugin Path** | /var/lib/homebridge/node_modules
**Timezone** | GMT+0100
**Docker** | Yes

#### homebrdige config file

```JSON
{
    "bridge": {
        "name": "Homebridge",
        "username": "...",
        "port": 51776,
        "pin": "656-29-108",
        "advertiser": "bonjour-hap",
        "bind": [
            "eth0"
        ],
        "debug": true
    },
    "description": "",
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "en",
            "platform": "config"
        }
    ],
    "accessories": []
}
```

While **eth0** is the only selected interface, these are also available but not selected (I've tried different configurations of selecting some, all etc. I've experienced no difference):

- eth0 | 192.168.65.9 <-- Currently the only one selected
- services1 | 192.168.65.6
- br-50174c53b07b | 172.19.0.1
- br-a9daa78fdec4 | 172.18.0.1
- vethdf68637 | IPv6 addr
- veth9236597 | IPv6 addr
- veth91f6336 | IPv6 addr
- veth06db8aa | IPv6 addr
- vethd7f6138 | IPv6 addr
- veth6998ce9 | IPv6 addr
- veth464563b | IPv6 addr
- vethf5a1934 | IPv6 addr
- veth2599a13 | IPv6 addr
- vethb0b380f | IPv6 addr
- vethb767575 | IPv6 addr

## docker-compose.yml

```YAML
version: "3.8"
services:
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    network_mode: host
    volumes:
      - ./homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    healthcheck:
      test: curl --fail localhost:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s
    restart: unless-stopped
```

## Nginx Proxy Manager
version v2.10.4

Homebridge UI accessible with proxy host config: 
homebrdige.my-domain.com | http://192.168.65.9:8581 | Let's Encrypt | Public | Online

## NOTE

I've removed all accessories, just to rule them out as the cause. So recreating this issue should simply involve running the above docker-compose.yml in Docker Desktop on Ubuntu 22.04.

I created the docker-compose file and ran `docker-compose up -d` in the terminal where the file is located.

**Comment by axelra82** [comment]
I just got this working and wanted to share with anyone else who might have this same issue. For me the solution was running the homebridge container in `sudo`, i.e. `sudo docker-compose up -d`.

Now I'm able to properly access homebridge on the client IP:PORT.

**NOTE** Don't forget to set your NAT for any ports that needs access.

**Comment by ogroves** [comment]
Resolved for me, if you have a Ubiquiti / UniFi setup, ensure you have "IoT Auto-Discovery / mDNS" enabled for the network you're connected to.

**Comment by arsenal6** [comment]
I am having this issue again, everything else seems to be working.
