### ISSUE TITLE
Both port 51162 and 8581 already in use error

### ISSUE THREAD

**Issue by BenEylon1** [homebridge/homebridge#3513]
### Current Situation

Homebridge was never able to connect to Homekit. I ran debug mode and found two errors stating that the ports were already in use, I tried changing the ports, port forwarding, and scanning the network, but no matter what I got the same output.

### Logs

```markdown
[12/16/2023, 9:59:46 AM] Error: listen EADDRINUSE: address already in use :::51162
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)

[12/16/2023, 9:59:50 AM] [Homebridge UI] Error: listen EADDRINUSE: address already in use :::8581
[12/16/2023, 9:59:50 AM] [Homebridge UI] Another process or service on this host is using port 8581.
[12/16/2023, 9:59:50 AM] [Homebridge UI] Please stop the other service or change the port you have assigned to homebridge-config-ui-x.
[12/16/2023, 9:59:50 AM] [Homebridge UI] Ending process now.
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge F9D9",
        "username": "0E:CC:AC:B7:96:5E",
        "port": 51162,
        "pin": "495-19-275",
        "advertiser": "ciao"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

### Environment

- OS: Mac OS 14.1.2
- Software: 1.7.0
- Node: 20.10.0
- npm: 10.2.3

### Process Supervisor

hb-service

**Comment by bwp91** [comment]
Hi @BenEylon1 

There is a small section in a wiki page about this:

https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting#error---eaddrinuse

Also you can try (if possible) changing the advertiser to bonjour or avahi.

**Comment by BenEylon1** [comment]
Thanks for the help @bwp91 How would I make it not homebridge not start up to fix the error? I uninstalled homebridge and had it run standalone without it being a service on my Mac. Unfortunately, that did not fix the issue.

**Comment by ck3mp** [comment]
Could homebridge/homebridge-syno-spk#147 be related?
