### ISSUE TITLE
homebridge not running after update 3.1.0

### ISSUE THREAD

**Issue by jfegea3869** [homebridge/homebridge#3527]
### Current Situation

homebridge restart again ....

### Logs

```markdown
[1/4/2024, 10:03:14 AM] Error: listen EADDRINUSE: address already in use :::51828
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at EventedHTTPServer.listen (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
    at step (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[1/4/2024, 10:03:14 AM] Got SIGTERM, shutting down Homebridge...
[1/4/2024, 10:03:19 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[1/4/2024, 10:03:24 AM] [HB Supervisor] Restarting Homebridge...
[1/4/2024, 10:03:24 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /volume1/homebridge/node_modules --strict-plugin-resolution
[1/4/2024, 10:03:24 AM] [HB Supervisor] Started Homebridge v1.7.0 with PID: 4582
[1/4/2024, 10:03:26 AM] Loaded config.json with 0 accessories and 3 platforms.
[1/4/2024, 10:03:26 AM] Loaded 0 cached accessories from cachedAccessories.
[1/4/2024, 10:03:26 AM] ---
[1/4/2024, 10:03:26 AM] Loaded plugin: homebridge-camera-ffmpeg@3.1.4
[1/4/2024, 10:03:26 AM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[1/4/2024, 10:03:26 AM] ---
[1/4/2024, 10:03:28 AM] Disabled plugin: homebridge-eufy-security@2.3.7
[1/4/2024, 10:03:28 AM] ---
[1/4/2024, 10:03:28 AM] Disabled plugin: homebridge-samsung-tizen@5.2.7
[1/4/2024, 10:03:28 AM] ---
[1/4/2024, 10:03:29 AM] Disabled plugin: homebridge-thermostat-netatmo@0.0.12
[1/4/2024, 10:03:29 AM] ---
[1/4/2024, 10:03:29 AM] Loading 3 platforms...
[1/4/2024, 10:03:29 AM] Ignoring config for the platform "SamsungTizen" in your config.json as the plugin "homebridge-samsung-tizen" has been disabled.
[1/4/2024, 10:03:29 AM] Ignoring config for the platform "EufySecurity" in your config.json as the plugin "homebridge-eufy-security" has been disabled.
Setup Payload:
X-HM://0023UM5Y6WEWQ
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 229-83-070 │     
    └────────────┘     
                       
[1/4/2024, 10:03:29 AM] Error: listen EADDRINUSE: address already in use :::51828
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at EventedHTTPServer.listen (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
    at step (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[1/4/2024, 10:03:29 AM] Got SIGTERM, shutting down Homebridge...
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge 3A3D new",
        "username": "0E:74:E7:EE:39:B6",
        "port": 51828,
        "pin": "229-83-070",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "fr",
            "platform": "config"
        },
        {
            "name": "SamsungTizen",
            "app_list": true,
            "devices": [
                {
                    "name": "TV",
                    "ip": "192.168.1.66",
                    "mac": "D4:9D:C0:F5:11:18",
                    "uuid": "A2",
                    "options": [
                        "Frame.RealPowerMode"
                    ],
                    "inputs": [
                        {
                            "type": "app"
                        }
                    ],
                    "switches": [
                        {
                            "name": "Mute",
                            "mute": true
                        },
                        {
                            "name": "Vol Up",
                            "command": "KEY_VOLUP"
                        },
                        {
                            "name": "Vol Down",
                            "command": "KEY_VOLDOWN"
                        },
                        {
                            "name": "CH Up",
                            "command": "KEY_CHUP"
                        },
                        {
                            "name": "CH Down",
                            "command": "KEY_CHDOWN"
                        },
                        {
                            "name": "HOME",
                            "command": "KEY_HOME"
                        },
                        {
                            "name": "Netflix",
                            "app": "3201907018807"
                        },
                        {
                            "name": "AmazonPrime",
                            "app": "3201910019365"
                        }
                    ]
                }
            ],
            "platform": "SamsungTizen"
        },
        {
            "enableDetailedLogging": true,
            "CameraMaxLivestreamDuration": 30,
            "pollingIntervalMinutes": 30,
            "hkHome": 1,
            "hkAway": 1,
            "hkNight": 3,
            "hkOff": 63,
            "ignoreStations": [
                "T8410P20212400C0",
                "T8410P312205623D",
                "T8410P4223323B13",
                "T8410P4223324337"
            ],
            "ignoreDevices": [
                "T8410P312205623D",
                "T8410P4223324337",
                "T8410P4223323B13",
                "T8410P20212400C0"
            ],
            "country": "FR",
            "cameras": [
                {
                    "serialNumber": "T8410P20212400C0",
                    "rtsp": false,
                    "talkback": false
                },
                {
                    "serialNumber": "T8410P312205623D",
                    "rtsp": false,
                    "talkback": false
                },
                {
                    "serialNumber": "T8410P4223324337",
                    "rtsp": false,
                    "talkback": false
                },
                {
                    "serialNumber": "T8410P4223323B13",
                    "rtsp": false,
                    "talkback": false
                },
                {
                    "serialNumber": "T8134P2023235D8E",
                    "rtsp": false,
                    "talkback": false
                }
            ],
            "cleanCache": false,
            "unbridge": true,
            "ignoreMultipleDevicesWarning": true,
            "syncStationModes": false,
            "platform": "EufySecurity",
            "name": "EufySecurity",
            "username": "jfegea@gmail.com",
            "password": "Next@ThesUn$1",
            "stations": [
                {
                    "hkHome": 1,
                    "hkAway": 1,
                    "serialNumber": "T8134P2023235D8E",
                    "hkNight": 3,
                    "hkOff": 63
                }
            ]
        }
    ],
    "disabledPlugins": [
       
    ]
}
```

### Environment

- OS: Syno 
- Software: DSM 7.2-64570
- Node: 20
- npm:

### Process Supervisor

hb-service

**Comment by PlasmaPod** [comment]
Same issue

**Comment by ck3mp** [comment]
Same issue in the repo for the syno package:

homebridge/homebridge-syno-spk#145
