### ISSUE TITLE
Stuck in a reboot loop, no idea what to do...

### ISSUE THREAD

**Issue by itsdeyan** [homebridge/homebridge#3531]
### Current Situation

Hey everyone! All of a sudden my homebridge stopped responding. Checked the web UI and the service is not running. Tried disabling the two plugins I'm using (tuya & zigbee2mqtt) but that didn't change anything. I have absolutely no clue what's causing this and any help is greatly appreciated thank you!!!

### Logs

```markdown
[1/5/2024, 5:02:58 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[1/5/2024, 5:03:03 PM] [HB Supervisor] Restarting Homebridge...
[1/5/2024, 5:03:03 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[1/5/2024, 5:03:03 PM] [HB Supervisor] Started Homebridge v1.7.0 with PID: 7382
[1/5/2024, 5:03:03 PM] Homebridge requires Node.js version of ^18.15.0 || ^20.7.0 which does not satisfy the current Node.js version of v21.5.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
[1/5/2024, 5:03:03 PM] Loaded config.json with 0 accessories and 3 platforms.
[1/5/2024, 5:03:03 PM] Loaded 11 cached accessories from cachedAccessories.
[1/5/2024, 5:03:04 PM] TypeError: Cannot read properties of undefined (reading 'getCharacteristic')
    at Accessory._sideloadServices (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1800:13)
    at Function.Accessory.deserialize (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:2188:15)
    at Function.deserialize (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:172:33)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:240:34
    at Array.map (<anonymous>)
    at BridgeService.loadCachedPlatformAccessoriesFromDisk (/usr/lib/node_modules/homebridge/src/bridgeService.ts:239:58)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:170:5)
[1/5/2024, 5:03:04 PM] Got SIGTERM, shutting down Homebridge...
[1/5/2024, 5:03:04 PM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/usr/lib/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/usr/lib/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/usr/lib/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:519:28)
    at process.emit (/usr/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[1/5/2024, 5:03:09 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[1/5/2024, 5:03:14 PM] [HB Supervisor] Restarting Homebridge...
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge 9B2E",
        "username": "XXXXXX",
        "port": 51297,
        "pin": "XXXXXXX",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Tuya",
            "options": {
                "projectType": "2",
                "endpoint": "https://openapi.tuyaeu.com",
                "accessId": "XXXXXXXXXXXXXXXXXX",
                "accessKey": "XXXXXXXXXXXXXXXXXX",
                "countryCode": 359,
                "username": "XXXXXXXXXXXXXXXXXX",
                "password": "XXXXXXXXXXXXXXXXXX",
                "appSchema": "smartlife",
                "debug": false
            },
            "platform": "TuyaPlatform"
        },
        {
            "mqtt": {
                "base_topic": "zigbee2mqtt",
                "server": "mqtt://localhost:1883",
                "reject_unauthorized": false,
                "keepalive": 60,
                "version": 4,
                "disable_qos": false
            },
            "defaults": {
                "exclude": false
            },
            "exclude_grouped_devices": false,
            "platform": "zigbee2mqtt"
        }
    ],
    "disabledPlugins": []
}
```

### Environment

- OS: Arch Linux
- Homebridge: 1.7.0
- Node: v21.5.0
- npm: 10.2.5

### Process Supervisor

systemd

**Comment by NorthernMan54** [comment]
Unsupported yet NodeJS version ? `which does not satisfy the current Node.js version of v21.5.0`

**Comment by itsdeyan** [comment]
> Unsupported yet NodeJS version ? `which does not satisfy the current Node.js version of v21.5.0`

I foolishly updated to an unsupported nodejs version in my poor attempt to fix my issue. It wasn't working previously on 18.5 as well...

**Comment by NorthernMan54** [comment]
Okay then, one of your accessories appear to be corrupt - https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting#reset-pairingaccessories

**Comment by MansVeer** [comment]
Could be related to the zigbee2mqtt 1.35.0 version, which contains a quite fundamental change on how Zigbee2MQTT handles unsupported devices.
Are you using / did you update to that version?

**Comment by gentlecat** [comment]
Having the same issue after updating to the latest version (Docker image). Also have a Zigbee2MQTT plugin which I didn't update prior.

Disabling or updating Zigbee2MQTT plugin also doesn't help.

**Comment by MansVeer** [comment]
Excluding Coordinator and Remove Single Cached Accessory fixed all for me.

Now running:
Homebridge v1.7.0
UI v4.55.1
Node.js v20.10.0
Zigbee2MQTT 1.35.1

See also
https://github.com/Koenkk/zigbee2mqtt/issues/20504
https://github.com/itavero/homebridge-z2m/issues/794

**Comment by gentlecat** [comment]
Same here. Had to remove some generated directories/files under `/homebridge` but now it's working fine.

**Comment by itsdeyan** [comment]
Neither disabling nor removing the plugin stopped Homebridge from crashing, so I removed Homebridge and did a fresh install, now it's working again (with zigbee2mqtt 1.35.1)
