### ISSUE TITLE
Plugin crashes on Raspberry Pi5

### ISSUE THREAD

**Issue by pofamacska** [homebridge/homebridge#3544]
### Analysis

GPIO-device plugin (and any other similar) crashes after entering details into config.json file. Then the HB goes into a cycle of crash-restart-crash-restart endlessly

### Expected Behavior

After installation of GPIO-device plugin the HB should run normally and allow the control of dedicated GPIO port

### Steps To Reproduce

Install HB on raspberry pi 5
Install gpio-device plugin
After restart - until here no issue - enter name, type and pin into json file
After restart of HB it will go into a crash-restart cycle which does not end unless you stop HB

### Logs

```markdown
[21/01/2024, 15:37:56] [HB Supervisor] Restarting Homebridge...
[21/01/2024, 15:37:56] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[21/01/2024, 15:37:56] [HB Supervisor] Started Homebridge v1.7.0 with PID: 7193
[21/01/2024, 15:37:56] Loaded config.json with 1 accessories and 1 platforms.
[21/01/2024, 15:37:56] Loaded 0 cached accessories from cachedAccessories.
[21/01/2024, 15:37:56] ---
[21/01/2024, 15:37:56] Loaded plugin: homebridge-gpio-device@0.4.9
homebridge-gpio-device API version: 2.7
[21/01/2024, 15:37:56] Registering accessory 'homebridge-gpio-device.GPIODevice'
[21/01/2024, 15:37:56] ---
[21/01/2024, 15:37:56] Loading 1 platforms...
[21/01/2024, 15:37:56] Loading 1 accessories...
[21/01/2024, 15:37:56] [LEGO Loop] Initializing GPIODevice accessory...
[21/01/2024, 15:37:56] Error: EINVAL: invalid argument, write
    at Object.writeSync (node:fs:929:3)
    at Object.writeFileSync (node:fs:2328:26)
    at exportGpio (/var/lib/homebridge/node_modules/homebridge-gpio-device/node_modules/onoff/onoff.js:18:8)
    at new Gpio (/var/lib/homebridge/node_modules/homebridge-gpio-device/node_modules/onoff/onoff.js:172:36)
    at Object.init (/var/lib/homebridge/node_modules/homebridge-gpio-device/index.js:22:19)
    at new DigitalOutput (/var/lib/homebridge/node_modules/homebridge-gpio-device/index.js:298:7)
    at new DeviceAccesory (/var/lib/homebridge/node_modules/homebridge-gpio-device/index.js:129:18)
    at /var/lib/homebridge/node_modules/homebridge/src/server.ts:379:50
    at Array.forEach (<anonymous>)
    at Server.loadAccessories (/var/lib/homebridge/node_modules/homebridge/src/server.ts:299:29)
```

### Configuration

```json
config.json
{
    "accessory": "GPIODevice",
    "name": "LEGO Loop",
    "type": "Switch",
    "pin": 21
}
```

### Environment

- OS: debian gnu linux 12 bookworm
- Software: HB
- Node: 18.19
- npm: 9.2

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
This is an issue within the homebridge-gpio-device, please raise this there so the plugin developer is aware
