### ISSUE TITLE
Updating Node.js

### ISSUE THREAD

**Issue by Phoendor** [homebridge/homebridge#3555]
### Current Situation

Sorry if this is a stupid question, I do not have a lot of experience in Linux
I haven't updated my Homebridge for a while. Now I se that there is a version 1.7 which requires Node.js v18.15.0 or later. I have Node.js v12.22.12.
GLIBC version is 2.28
When I follow the guide and use `sudo hb-service update-node`, I encounter 2 errors stating:
 - `npm v10.4.0 is known not to run on Node.js v12.22.12.  This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.`
 - `/usr/lib/node_modules/npm/lib/utils/exit-handler.js:19
  const hasLoadedNpm = npm?.config.loaded`

As far as I understood, I my npm is more new than my Node.js, and usually people recommend updating Node.js with nvm, but I don't have nvm because I installed Node.js with HB... what should I do?

Ful log below

### Logs

```markdown
pi@raspberrypi:~ $ sudo hb-service update-node
ℹ Updating Node.js from v12.22.12 to v20.11.0...
ℹ Updating from NodeSource...
2024-02-03 19:21:34 - Installing pre-requisites
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease                
Get:3 https://deb.nodesource.com/node_12.x buster InRelease [4,584 B]          
Ign:4 https://packagecloud.io/ookla/speedtest-cli/raspbian buster InRelease    
Err:5 https://packagecloud.io/ookla/speedtest-cli/raspbian buster Release
  404  Not Found [IP: 52.8.62.34 443]
Reading package lists... Done                 
E: The repository 'https://packagecloud.io/ookla/speedtest-cli/raspbian buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
2024-02-03 19:21:39 - Error: Failed to run 'apt-get update' (Exit Code: 0)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (12.22.12-deb-1nodesource1).
The following packages were automatically installed and are no longer required:
  gconf-service gconf2-common gyp libbluetooth3 libc-ares2 libdav1d3
  libexiv2-14 libgconf-2-4 libgfortran3 libgmime-2.6-0 libjs-inherits
  libjs-is-typedarray libmicrodns0 libncurses5 libpipewire-0.2-1 libssl-dev
  libssl1.0.2 libuv1 libuv1-dev lxplug-volume node-abbrev node-ajv node-ansi
  node-ansi-align node-ansi-regex node-ansi-styles node-ansistyles node-aproba
  node-archy node-are-we-there-yet node-asn1 node-assert-plus node-asynckit
  node-aws-sign2 node-aws4 node-balanced-match node-bcrypt-pbkdf node-bluebird
  node-boxen node-brace-expansion node-builtin-modules node-builtins
  node-cacache node-call-limit node-camelcase node-caseless node-chalk
  node-chownr node-cli-boxes node-cliui node-clone node-co node-color-convert
  node-color-name node-combined-stream node-concat-map node-concat-stream
  node-config-chain node-console-control-strings node-copy-concurrently
  node-core-util-is node-cross-spawn node-cyclist node-dashdash
  node-decamelize node-decompress-response node-deep-extend node-defaults
  node-delayed-stream node-delegates node-detect-indent node-detect-newline
  node-duplexer3 node-duplexify node-ecc-jsbn node-editor node-encoding
  node-end-of-stream node-errno node-escape-string-regexp node-execa
  node-extend node-extsprintf node-find-up node-flush-write-stream
  node-forever-agent node-form-data node-from2 node-fs-vacuum
  node-fs-write-stream-atomic node-fs.realpath node-gauge node-get-caller-file
  node-get-stream node-getpass node-glob node-got node-graceful-fs
  node-har-schema node-har-validator node-has-flag node-has-symbol-support-x
  node-has-to-string-tag-x node-has-unicode node-hosted-git-info
  node-http-signature node-iconv-lite node-iferr node-import-lazy
  node-imurmurhash node-inflight node-inherits node-ini node-invert-kv
  node-is-builtin-module node-is-npm node-is-object node-is-plain-obj
  node-is-retry-allowed node-is-stream node-is-typedarray node-isarray
  node-isexe node-isstream node-isurl node-jsbn node-json-parse-better-errors
  node-json-schema node-json-stable-stringify node-json-stringify-safe
  node-jsonify node-jsonparse node-jsonstream node-jsprim node-latest-version
  node-lazy-property node-lcid node-libnpx node-locate-path node-lockfile
  node-lowercase-keys node-lru-cache node-mem node-mime-types node-mimic-fn
  node-mimic-response node-minimatch node-minimist node-mississippi
  node-mkdirp node-move-concurrently node-mute-stream node-node-uuid node-nopt
  node-normalize-package-data node-npm-package-arg node-npm-run-path
  node-npmlog node-oauth-sign node-object-assign node-once node-opener
  node-os-locale node-osenv node-p-cancelable node-p-finally node-p-limit
  node-p-locate node-p-timeout node-package-json node-parallel-transform
  node-path-exists node-path-is-absolute node-path-is-inside
  node-performance-now node-prepend-http node-process-nextick-args
  node-promise-inflight node-promzard node-proto-list node-prr node-pump
  node-pumpify node-punycode node-qs node-qw node-rc node-read
  node-read-package-json node-readable-stream node-registry-auth-token
  node-registry-url node-request node-require-directory
  node-require-main-filename node-resolve-from node-retry node-rimraf
  node-run-queue node-safe-buffer node-semver node-semver-diff
  node-set-blocking node-sha node-shebang-command node-shebang-regex
  node-signal-exit node-slash node-slide node-sorted-object node-spdx-correct
  node-spdx-expression-parse node-spdx-license-ids node-sshpk node-ssri
  node-stream-each node-stream-iterate node-stream-shift node-string-decoder
  node-string-width node-strip-ansi node-strip-eof node-strip-json-comments
  node-supports-color node-tar node-term-size node-text-table node-through
  node-through2 node-timed-out node-tough-cookie node-tunnel-agent
  node-tweetnacl node-typedarray node-uid-number node-unique-filename
  node-unpipe node-url-parse-lax node-url-to-options node-util-deprecate
  node-uuid node-validate-npm-package-license node-validate-npm-package-name
  node-verror node-wcwidth.js node-which node-which-module node-wide-align
  node-widest-line node-wrap-ansi node-wrappy node-write-file-atomic
  node-xdg-basedir node-xtend node-y18n node-yallist node-yargs
  node-yargs-parser python-colorzero rpi-eeprom-images rtimucli uuid-dev
  xdg-desktop-portal xdg-desktop-portal-gtk
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
ℹ Rebuilding for Node.js v20.11.0...
ERROR: npm v10.4.0 is known not to run on Node.js v12.22.12.  This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.

ERROR:
/usr/lib/node_modules/npm/lib/utils/exit-handler.js:19
  const hasLoadedNpm = npm?.config.loaded
                           ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at module.exports (/usr/lib/node_modules/npm/lib/cli-entry.js:15:23)
    at module.exports (/usr/lib/node_modules/npm/lib/es6/validate-engines.js:39:10)
    at module.exports (/usr/lib/node_modules/npm/lib/cli.js:4:31)
ERROR: npm v10.4.0 is known not to run on Node.js v12.22.12.  This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.

ERROR:
/usr/lib/node_modules/npm/lib/utils/exit-handler.js:19
  const hasLoadedNpm = npm?.config.loaded
                           ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at module.exports (/usr/lib/node_modules/npm/lib/cli-entry.js:15:23)
    at module.exports (/usr/lib/node_modules/npm/lib/es6/validate-engines.js:39:10)
    at module.exports (/usr/lib/node_modules/npm/lib/cli.js:4:31)
Error: Command failed: npm rebuild --unsafe-perm
✖ ERROR: Failed Operation
ℹ Restarting Homebridge Service...
✔ Homebridge Restarted
```

### Configuration

```json
not applicable
```

### Environment

- OS: Linux raspberrypi 5.10.103-v7l+
- Homebridge: 1.4.1
- Node: v12.22.12.
- npm: v10.4.0

### Process Supervisor

hb-service

**Comment by Phoendor** [comment]
Additionally, if any of the solutions would require uninstalling, please specify how to keep the configuration
I only have a remote connection to the home where HB is located unfortunately

**Comment by NorthernMan54** [comment]
As your install is so far out of date, it may be best to just obtain a new SD card for your RPI, install the latest homebridge Raspbian image on it ( https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started ).

Then create a backup from your existing homebridge, and restore it to the new raspbian image.

I presume your are running the homebridge UI ?

PS I’m recommending a new SD card that you can easily go back to the old one in case of issues.
