### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by djsmix** [homebridge/homebridge#3576]
### Current Situation

(node:306690) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 initialised listeners added to [Gateway]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:306690) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Gateway]. Use emitter.setMaxListeners() to increase limit

### Logs

```markdown
(node:306690) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 initialised listeners added to [Gateway]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:306690) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Gateway]. Use emitter.setMaxListeners() to increase limit
```

### Configuration

```json
{
    "name": "deCONZ",
    "platform": "deCONZ",
    "_bridge": {
        "username": "0E:3E:1C:67:6B:99",
        "port": 58882
    }
}
```

### Environment

- OS: raspberry pi
- Software: [v1.7.0]
- Node: v20.11.1
- npm: ?

### Process Supervisor

hb-service

**Comment by djsmix** [comment]
Still a issue

**Comment by bwp91** [comment]
Hi @djsmix 

From the Homebridge UI settings, you can set the node options to `--trace-warnings`, restart homebridge, and the logs should provide more information about from where this warning is being generated.

![Screenshot 2024-04-13 at 16 03 54](https://github.com/homebridge/homebridge/assets/43026681/6e1626a9-ba53-4d50-8723-59e224c11d9a)

**Comment by djsmix** [comment]
(node:1608878) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 initialised listeners added to [Gateway]. Use emitter.setMaxListeners() to increase limit
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at _addListener (node:events:592:17)
    at Gateway.addListener (node:events:610:10)
    at Gateway.once (node:events:654:8)
    at eventTargetAgnosticAddListener (node:events:1035:15)
    at node:events:997:5
    at new Promise (<anonymous>)
    at Function.once (node:events:977:10)
    at DeconzPlatform.foundGateway (/var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzPlatform.js:115:18)
(node:1608878) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Gateway]. Use emitter.setMaxListeners() to increase limit
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at _addListener (node:events:592:17)
    at Gateway.addListener (node:events:610:10)
    at Gateway.once (node:events:654:8)
    at node:events:1001:15
    at new Promise (<anonymous>)
    at Function.once (node:events:977:10)
    at DeconzPlatform.foundGateway (/var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzPlatform.js:115:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by ebaauw** [comment]
That’s an issue with Homebridge deCONZ alright, but I cannot seem to transfer it across GitHub organisations.  Please continue with the Homebridge deCONZ issue mentioned above.
