### ISSUE TITLE
Homebridge not starting after update - cachedAccessories

### ISSUE THREAD

**Issue by BKrnk1337** [homebridge/homebridge#3622]
### Current Situation

Unfortunately, after I updated my Homebridge version, I can no longer start Homebridge. An endless loop occurs. I have already done some research and found the following error message (issue).

https://github.com/homebridge/homebridge/issues/3536

I don't want to delete all of my accessories and thus restore my entire installation. I would therefore be very happy about your help. I'm a bit at a loss at the moment. I took @movy's comments to heart, but unfortunately that didn't lead to success.

I mean these two comments:
https://github.com/homebridge/homebridge/issues/3536#issuecomment-1899833277
https://github.com/homebridge/homebridge/issues/3536#issuecomment-2012078868

### Logs

```markdown
[30/05/2024, 18:26:56] [HB Supervisor] Restarting Homebridge...
[30/05/2024, 18:26:56] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[30/05/2024, 18:26:56] [HB Supervisor] Started Homebridge v1.8.2 with PID: 4281
[30/05/2024, 18:26:58] Loaded config.json with 4 accessories and 5 platforms.
[30/05/2024, 18:26:58] Loaded 24 cached accessories from cachedAccessories.
[30/05/2024, 18:26:59] TypeError: Cannot read properties of undefined (reading 'getCharacteristic')
    at Accessory._sideloadServices (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1803:13)
    at Function.Accessory.deserialize (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:2191:15)
    at Function.deserialize (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:173:33)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:240:34
    at Array.map (<anonymous>)
    at BridgeService.loadCachedPlatformAccessoriesFromDisk (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:239:58)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:158:5)
[30/05/2024, 18:26:59] Got SIGTERM, shutting down Homebridge...
[30/05/2024, 18:26:59] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/usr/local/lib/node_modules/homebridge/src/server.ts:143:45)
    at Server.teardown (/usr/local/lib/node_modules/homebridge/src/server.ts:187:10)
    at signalHandler (/usr/local/lib/node_modules/homebridge/src/cli.ts:94:12)
    at process.emit (node:events:514:28)
    at process.emit (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[30/05/2024, 18:27:04] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
```

### Configuration

```json
{
    "id": "config",
    "platforms": [
        {
            "tempUnits": "c",
            "platform": "config",
            "lang": "en",
            "port": 8581,
            "theme": "green",
            "auth": "form",
            "name": "Config",
            "sessionTimeout": 28800
        },
        {
            "platform": "TplinkSmarthome",
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "addCustomCharacteristics": false,
            "name": "TplinkSmarthome",
            "broadcast": "192.168.188.255"
        },
        {
            "callmonitor": {
                "group": true,
                "ip": "192.168.188.1",
                "active": false,
                "port": 1012
            },
            "telegram": {
                "active": true,
                "token": "<removed>,
                "messages": {
                    "network": {
                        "off": "Das Gerät @ ist nicht mehr im Netzwerk aktiv/angemeldet.",
                        "on": "Das Gerät @ ist wieder im Netzwerk aktiv/angemeldet."
                    },
                    "presence": {
                        "user_in": "Willkommen zu Hause @",
                        "anyone_in": "Jemand ist zu Hause! Folgende Informationen sind bekannt: @"
                    },
                    "callmonitor": {
                        "incoming": "Ankommender Anruf von @ auf dem Festnetz."
                    }
                },
                "chatID": "215882701"
            },
            "devices": [
                {
                    "username": "<removed>",
                    "active": true,
                    "options": {
                        "wifi_2ghz": "characteristic",
                        "wifi_guest": "switch",
                        "wps": "characteristic",
                        "aw": "characteristic",
                        "reconnect": "switch",
                        "wifi_5ghz": "characteristic",
                        "led": "characteristic"
                    },
                    "password": "<removed>",
                    "igd": true,
                    "master": true,
                    "name": "FRITZ!Box",
                    "manufacturer": "AVM Computersysteme Vertriebs GmbH",
                    "model": "FRITZ!Box 7490",
                    "serialNumber": "<removed>",
                    "ssl": false,
                    "readOnly": true,
                    "tr064": true,
                    "connection": "dsl",
                    "hide": false,
                    "wifiUnits": 2,
                    "port": 49000,
                    "host": "192.168.188.1"
                },
                {
                    "username": "FritzBoxAdmin1337",
                    "active": true,
                    "options": {
                        "led": "switch"
                    },
                    "password": "<removed>",
                    "igd": false,
                    "name": "FritzRepeater",
                    "manufacturer": "AVM",
                    "model": "FRITZ!WLAN Repeater 1750E",
                    "ssl": true,
                    "readOnly": true,
                    "connection": "repeater",
                    "tr064": true,
                    "wifiUnits": 2,
                    "host": "192.168.188.18"
                }
            ],
            "network": [
                {
                    "offDelay": 50,
                    "active": true,
                    "address": "192.168.188.3",
                    "name": "Pi-Hole"
                },
                {
                    "offDelay": 50,
                    "active": true,
                    "address": "192.168.188.5",
                    "name": "AppleTV"
                },
                {
                    "offDelay": 50,
                    "active": true,
                    "address": "192.168.188.6",
                    "name": "PhilipsHue"
                },
                {
                    "offDelay": 50,
                    "active": false,
                    "address": "192.168.188.27",
                    "name": "Sina Laptop DRV"
                }
            ],
            "warn": true,
            "extendedError": true,
            "options": {
                "presence": {
                    "anyone": false,
                    "guest": false
                },
                "polling": {
                    "timerSmarthomeButtons": 5,
                    "timer": 15
                }
            },
            "error": true,
            "childLock": [
                {
                    "name": "ChildLock: Xiaomi Fan",
                    "active": false,
                    "ips": [
                        "192.168.188.30"
                    ]
                },
                {
                    "name": "ChildLock: Aqara Hub",
                    "active": false,
                    "ips": [
                        "192.168.188.9"
                    ]
                }
            ],
            "extras": {
                "wakeup": {
                    "active": false
                },
                "alarm": {
                    "active": false
                },
                "ringlock": {
                    "active": false
                },
                "phoneBook": {
                    "active": false
                }
            },
            "debug": false,
            "name": "FritzPlattform",
            "smarthome": [
                {
                    "accType": "thermostat",
                    "humidity": false,
                    "active": true,
                    "temperature": true,
                    "window": true,
                    "name": "Thermostat KU",
                    "battery": true,
                    "ain": "19590 330512"
                },
                {
                    "accType": "thermostat",
                    "humidity": false,
                    "active": true,
                    "temperature": true,
                    "window": true,
                    "name": "Thermostat BZ",
                    "battery": true,
                    "openWindow": false,
                    "ain": "11959 0331616"
                },
                {
                    "accType": "thermostat",
                    "humidity": false,
                    "active": true,
                    "temperature": true,
                    "window": true,
                    "name": "Thermostat SZ",
                    "battery": true,
                    "ain": "11959 0331400"
                },
                {
                    "accType": "thermostat",
                    "humidity": false,
                    "active": true,
                    "temperature": true,
                    "window": true,
                    "name": "Thermostat WZ",
                    "battery": true,
                    "ain": "11959 0387528"
                },
                {
                    "temperature": true,
                    "name": "Steckdose Multimedia",
                    "accType": "switch",
                    "active": true,
                    "energy": true,
                    "ain": "08761 0372173"
                },
                {
                    "temperature": true,
                    "name": "Steckdose Schirmlampe",
                    "accType": "switch",
                    "active": true,
                    "energy": true,
                    "ain": "08761 0372015"
                }
            ],
            "platform": "FritzPlatform",
            "presence": [
                {
                    "ping": false,
                    "name": "Sina Laptop",
                    "accType": "occupancy",
                    "blockTelegram": true,
                    "active": false,
                    "address": "48:2A:E3:29:18:98"
                },
                {
                    "name": "iPhone DRV",
                    "accType": "occupancy",
                    "blockTelegram": true,
                    "active": false,
                    "address": "192.168.188.28"
                }
            ]
        },
        {
            "devices": [
                {
                    "volumeControl": "both",
                    "name": "webOS TV",
                    "pictureModeButtons": [
                        {
                            "pictureMode": "cinema"
                        },
                        {
                            "pictureMode": "eco"
                        },
                        {
                            "pictureMode": "hdrCinema"
                        }
                    ],
                    "triggers": {
                        "volume": {
                            "threshold": 80,
                            "name": "Lautstärke über 80"
                        }
                    },
                    "ip": "192.168.188.4",
                    "pollingInterval": 10,
                    "mediaControl": false,
                    "mac": "38:8C:50:16:DE:3E",
                    "channelControl": false,
                    "appButtons": [
                        {
                            "appId": "com.webos.app.hdmi3",
                            "name": "AppleTV"
                        },
                        {
                            "appId": "com.webos.app.hdmi4",
                            "name": "PS4"
                        }
                    ],
                    "volumeLimit": 100
                }
            ],
            "_bridge": {
                "port": 37373,
                "username": "<removed>"
            },
            "platform": "webostv"
        },
        {
            "devices": [
                {
                    "ledControl": false,
                    "ioniserControl": false,
                    "ip": "192.168.188.30",
                    "moveControl": true,
                    "shutdownTimer": true,
                    "token": "<removed>",
                    "pollingInterval": 5,
                    "name": "Xiaomi Smart Fan 2",
                    "fanLevelControl": true,
                    "angleButtons": [
                        30,
                        60,
                        90,
                        120
                    ],
                    "deepDebugLog": false,
                    "naturalModeControl": true,
                    "model": "zhimi.fan.za4",
                    "buzzerControl": true,
                    "sleepModeControl": true
                }
            ],
            "_bridge": {
                "username": "C2:4D:4F:61:15:DC",
                "port": 37395
            },
            "platform": "xiaomifan"
        }
    ],
    "bridge": {
        "pin": "263-20-373",
        "name": "Homebridge 43E3",
        "username": "0E:80:B4:3B:43:E3",
        "advertiser": "ciao",
        "port": 51087
    },
    "disabledPlugins": [
        "homebridge-webos-tv",
        "homebridge-xiaomi-fan",
        "homebridge-tplink-smarthome"
    ],
    "accessories": [
        {
            "port": 80,
            "accessory": "Pihole",
            "name": "Pihole",
            "host": "192.168.188.3",
            "auth": "<removed>",
            "logLevel": 1,
            "time": 0
        },
        {
            "name": "Homebridge Messenger",
            "messages": [
                {
                    "urltitle": "Homebridge Webinterface",
                    "priority": 1,
                    "sound": "pushover",
                    "text": "Homebridge Service wird in 30 Sekunden neu gestartet",
                    "type": "pushover",
                    "url": "http://192.168.188.2/",
                    "name": "Restart Homebridge ",
                    "device": "iPhoneBasti"
                },
                {
                    "name": "FritzBox offline",
                    "sound": "pushover",
                    "type": "pushover",
                    "text": "FRITZ!Box ist offline",
                    "priority": 0,
                    "event": null
                },
                {
                    "urltitle": "FritzBox Webinterface",
                    "priority": 1,
                    "sound": "pushover",
                    "text": "FritzBox wird in 60 Sekunden neu gestartet",
                    "type": "pushover",
                    "url": "http://192.168.188.1/",
                    "name": "Restart FritzBox ",
                    "device": "iPhoneBasti"
                }
            ],
            "services": {
                "email": {
                    "smtpPort": 8080
                },
                "pushover": {
                    "user": „<removed>“,
                    "token": "<removed>"
                },
                "ifttt": {}
            },
            "accessory": "HomebridgeMessenger"
        },
        {
            "name": "Restart homebridge",
            "stateful": false,
            "logCmd": true,
            "onCmd": "echo Homebridge wird in 30 Sekunden neu gestartet",
            "offCmd": "sudo systemctl restart homebridge",
            "delay": 30,
            "delayUnit": "s",
            "accessory": "CmdTriggerSwitch2"
        },
        {
            "name": "Restart FritzBox",
            "stateful": false,
            "logCmd": true,
            "onCmd": "echo FRITZBox, Repeater und Homebridge Services werden in 60 Sekunden neu gestartet",
            "offCmd": "/usr/local/bin/fritzbox-reboot.sh",
            "delay": 60,
            "delayUnit": "s",
            "accessory": "CmdTriggerSwitch2"
        }
    ]
}
```

### Environment

- OS: Raspbian GNU/Linux Buster (10)
- Software:
- Node: v18.17.1
- npm:

### Process Supervisor

hb-service

**Comment by BKrnk1337** [comment]
After investigating my setup and the plugins I found the plugin that caused the error. It is the following. https://github.com/plasticrake/homebridge-tplink-smarthome

I had three wall plugs configured. After I removed all three cached devices via the homebridge UI I was able to restart my homebridge without any errors.


```

[31/05/2024, 22:27:591 [TplinkSmarthome] [Balkonleuchte] Removing stale Characteristic: [Outlet.Brightness] uuid: 00000008-0000-1000-8000-0026BB765291]
[31/05/2024, 22:27:59] [TplinkSmarthome] Device First Online: [HS-100] plug [8006DC503714E365B943CBA56EE159981B042872] 192.168.188.31 9999
[31/05/2024, 22:27:59] [TplinkSmarthome] Adding : [HS-100] plug [8006DC503714E365B943CBA56EE159981B042872]
[31/05/2024, 22:27:591 [TplinkSmarthome] [HS-1001 Removing stale (stale Characteristic: [Outlet.Brightness] uuid: 00000008-0000-1000-8000-0026BB765291]
[31/05/2024, 22:27:591 [TplinkSmarthome] Device First Online: [Luftentfeuchter] plug [8006B37C51E756D1E1F65595A439DA0B1B043B91] 192.168.188.23 9999
[31/05/2024, 22:27:591 [TplinkSmarthome] Adding : [Luftentfeuchter] plug [8006B37C51E756D1E1F65595A439DA0B1B043B91]
[31/05/2024, 22:27:591 [TplinkSmarthome] [Luftentfeuchter] Removing stale Characteristic: [Outlet.Brightness] uuid: 00000008-0000-1000-8000-0
026BB765291]

```
