### ISSUE TITLE
ipv4-mapped ipv6 address

### ISSUE THREAD

**Issue by bony618** [homebridge/homebridge#3640]
### Current Situation

After every restart (and occasionally at random while running) the server (and some child bridges) run through a loop of several continuous restarts before settling down. The log error mentions "ipv4-mapped ipv6 addresses".
Everything functions as expected while it is not cycling through these continuous restarts.
Any guidance would be appreciated.

### Logs

```markdown
AssertionError [ERR_ASSERTION]: ipv4-mapped ipv6 addresses are currently unsupported!
    at enlargeIPv6 (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/util/domain-formatter.ts:137:9)
    at getNetAddress (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/util/domain-formatter.ts:296:26)
    at Function.HAPConnection.getLocalNetworkInterface (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:868:26)
    at new HAPConnection (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:390:43)
    at EventedHTTPServer.onConnection (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:229:24)
    at Server.emit (node:events:514:28)
    at TCP.onconnection (node:net:2157:8)
[6/27/2024, 4:19:50 AM] [@balansse/homebridge-vivint] Child bridge process ended
[6/27/2024, 4:19:50 AM] [Blink] Child bridge process ended
[6/27/2024, 4:19:50 AM] [Blink] Process Ended. Code: 1, Signal: null
[6/27/2024, 4:19:50 AM] [@balansse/homebridge-vivint] Process Ended. Code: 1, Signal: null
[6/27/2024, 4:19:55 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[6/27/2024, 4:20:00 AM] [HB Supervisor] Restarting Homebridge...
[6/27/2024, 4:20:00 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[6/27/2024, 4:20:00 AM] [HB Supervisor] Started Homebridge v1.8.2 with PID: 49206
[6/27/2024, 4:20:00 AM] Loaded config.json with 1 accessories and 4 platforms.
[6/27/2024, 4:20:00 AM] Loaded 0 cached accessories from cachedAccessories.
[6/27/2024, 4:20:00 AM] ---
[6/27/2024, 4:20:01 AM] Loaded plugin: homebridge-blink-for-home@3.9.2
[6/27/2024, 4:20:01 AM] Registering platform 'homebridge-blink-for-home.Blink'
[6/27/2024, 4:20:01 AM] ---
[6/27/2024, 4:20:01 AM] Loaded plugin: homebridge-config-ui-x@4.56.2
[6/27/2024, 4:20:01 AM] Registering platform 'homebridge-config-ui-x.config'
[6/27/2024, 4:20:01 AM] ---
[6/27/2024, 4:20:01 AM] Loaded plugin: homebridge-dummy@0.9.0
[6/27/2024, 4:20:01 AM] Registering accessory 'homebridge-dummy.DummySwitch'
[6/27/2024, 4:20:01 AM] ---
[6/27/2024, 4:20:01 AM] Loaded plugin: homebridge-rainbird@2.0.3
[6/27/2024, 4:20:01 AM] Registering platform 'homebridge-rainbird.RainBird'
[6/27/2024, 4:20:01 AM] ---
[6/27/2024, 4:20:02 AM] Loaded plugin: @balansse/homebridge-vivint@1.8.5
[6/27/2024, 4:20:02 AM] Registering platform '@balansse/homebridge-vivint.Vivint'
[6/27/2024, 4:20:02 AM] ---
[6/27/2024, 4:20:02 AM] Loading 4 platforms...
[6/27/2024, 4:20:02 AM] [Vivint] Initializing Vivint platform...
[6/27/2024, 4:20:02 AM] [Vivint] Initializing child bridge 0E:2B:2F:46:88:31
[6/27/2024, 4:20:02 AM] [Blink] Initializing Blink platform...
[6/27/2024, 4:20:02 AM] [Blink] Initializing child bridge 0E:BD:43:2B:12:76
[6/27/2024, 4:20:02 AM] [RainBird] Initializing RainBird platform...
[6/27/2024, 4:20:02 AM] [RainBird] Initializing child bridge 0E:56:34:8A:3D:F9
[6/27/2024, 4:20:02 AM] Loading 1 accessories...
[6/27/2024, 4:20:02 AM] [open up] Initializing DummySwitch accessory...
Setup Payload:
X-HM://0024IQJJWGVLT
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 634-98-108 │     
    └────────────┘     
                       
[6/27/2024, 4:20:02 AM] Homebridge v1.8.2 (HAP v0.12.1) (Homebridge FBB9) is running on port 51089.
[6/27/2024, 4:20:02 AM] [@balansse/homebridge-vivint] Launched child bridge with PID 49212
[6/27/2024, 4:20:02 AM] [RainBird] Launched child bridge with PID 49214
[6/27/2024, 4:20:02 AM] [Blink] Launched child bridge with PID 49213
[6/27/2024, 4:20:02 AM] Registering platform 'homebridge-blink-for-home.Blink'
[6/27/2024, 4:20:03 AM] [Blink] Loaded homebridge-blink-for-home v3.9.2 child bridge successfully
[6/27/2024, 4:20:03 AM] Loaded 5 cached accessories from cachedAccessories.0EBD432B1276.
[6/27/2024, 4:20:03 AM] [Blink] Init Blink
[6/27/2024, 4:20:03 AM] Registering platform 'homebridge-rainbird.RainBird'
[6/27/2024, 4:20:03 AM] [RainBird] Loaded homebridge-rainbird v2.0.3 child bridge successfully
[6/27/2024, 4:20:03 AM] Loaded 1 cached accessories from cachedAccessories.0E56348A3DF9.
[6/27/2024, 4:20:03 AM] [RainBird] Loading accessory from cache: ESP-ME3
[6/27/2024, 4:20:03 AM] Homebridge v1.8.2 (HAP v0.12.1) (RainBird) is running on port 40721.
[6/27/2024, 4:20:03 AM] Homebridge v1.8.2 (HAP v0.12.1) (Blink) is running on port 44638.
[6/27/2024, 4:20:03 AM] Registering platform '@balansse/homebridge-vivint.Vivint'
[6/27/2024, 4:20:03 AM] [@balansse/homebridge-vivint] Loaded @balansse/homebridge-vivint v1.8.5 child bridge successfully
[6/27/2024, 4:20:03 AM] Loaded 26 cached accessories from cachedAccessories.0E2B2F468831.
[6/27/2024, 4:20:03 AM] Homebridge v1.8.2 (HAP v0.12.1) (@balansse/homebridge-vivint) is running on port 51766.
[6/27/2024, 4:20:04 AM] [RainBird] Model: ESP-ME3, [Version: 2.12, Serial Number: 01e0420d500316, Zones: [1,2,3,4,5,6,7]]
[6/27/2024, 4:20:04 AM] [RainBird] Restoring existing accessory from cache: ESP-ME3
[6/27/2024, 4:20:04 AM] [Blink] ADD: Blink:Network:355084
[6/27/2024, 4:20:04 AM] [Blink] ADD: Blink:Network:355084:Camera:672091
[6/27/2024, 4:20:04 AM] [Blink] ADD: Blink:Network:355084:Camera:672716
[6/27/2024, 4:20:04 AM] [Blink] ADD: Blink:Network:355084:Camera:904270
[6/27/2024, 4:20:04 AM] [Blink] ADD: Blink:Network:355084:Camera:904271
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:15 [Type]:primary_touch_link_device [EquipmentCode]:undefined [Name]:Panel
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:29 [Type]:wireless_sensor [EquipmentCode]:1248 [Name]:Glass Break
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:54 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Front Door
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:55 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Back Door
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:56 [Type]:binary_switch_device [EquipmentCode]:undefined [Name]:Porch
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:63 [Type]:binary_switch_device [EquipmentCode]:undefined [Name]:Spare
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:70 [Type]:binary_switch_device [EquipmentCode]:undefined [Name]:Sunroom
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:77 [Type]:camera_device [EquipmentCode]:undefined [Name]:Doorbell
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Device not (yet) supported [ID]:78 [Type]:lgit_poe_wifi_device [EquipmentCode]:undefined [Name]:Front Yard-Bridge
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:79 [Type]:camera_device [EquipmentCode]:undefined [Name]:Front Yard
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Device not (yet) supported [ID]:80 [Type]:lgit_poe_wifi_device [EquipmentCode]:undefined [Name]:Yard-Bridge
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:81 [Type]:camera_device [EquipmentCode]:undefined [Name]:Yard
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:82 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Garage Door
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:83 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Kitchen Window Left
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:84 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Kitchen Window Right
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:85 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Master Bedroom Window
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:86 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Master Bedroom Window
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:87 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Master Bedroom Window
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:88 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Dining Room Window
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:89 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Dining Room Window
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:90 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Dining Room Window
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:91 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Office Window
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:92 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Office Window
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:93 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Front Bedroom Window
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:94 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Back Bedroom Window
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:111 [Type]:wireless_sensor [EquipmentCode]:1269 [Name]:Fire Alert
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:117 [Type]:door_lock_device [EquipmentCode]:undefined [Name]:Front Doorlock
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Managing device [ID]:9001672 [Type]:garage_door_device [EquipmentCode]:undefined [Name]:Garage Door
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Device not (yet) supported [ID]:129 [Type]:mqtt_audio_sync_service [EquipmentCode]:undefined [Name]:undefined
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Removing 0 accessories
[6/27/2024, 4:20:06 AM] [@balansse/homebridge-vivint] Adding 0 accessories
AssertionError [ERR_ASSERTION]: ipv4-mapped ipv6 addresses are currently unsupported!
    at enlargeIPv6 (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/util/domain-formatter.ts:137:9)
    at getNetAddress (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/util/domain-formatter.ts:296:26)
    at Function.HAPConnection.getLocalNetworkInterface (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:868:26)
    at new HAPConnection (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:390:43)
    at EventedHTTPServer.onConnection (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:229:24)
    at Server.emit (node:events:514:28)
    at TCP.onconnection (node:net:2157:8)
[6/27/2024, 4:20:18 AM] [@balansse/homebridge-vivint] Child bridge process ended
[6/27/2024, 4:20:18 AM] [@balansse/homebridge-vivint] Process Ended. Code: 1, Signal: null
[6/27/2024, 4:20:25 AM] [@balansse/homebridge-vivint] Restarting Process...
[6/27/2024, 4:20:25 AM] [@balansse/homebridge-vivint] Launched child bridge with PID 49249
[6/27/2024, 4:20:26 AM] Registering platform '@balansse/homebridge-vivint.Vivint'
[6/27/2024, 4:20:26 AM] [@balansse/homebridge-vivint] Loaded @balansse/homebridge-vivint v1.8.5 child bridge successfully
[6/27/2024, 4:20:26 AM] Loaded 26 cached accessories from cachedAccessories.0E2B2F468831.
[6/27/2024, 4:20:26 AM] Homebridge v1.8.2 (HAP v0.12.1) (@balansse/homebridge-vivint) is running on port 51766.
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:15 [Type]:primary_touch_link_device [EquipmentCode]:undefined [Name]:Panel
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:29 [Type]:wireless_sensor [EquipmentCode]:1248 [Name]:Glass Break
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:54 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Front Door
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:55 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Back Door
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:56 [Type]:binary_switch_device [EquipmentCode]:undefined [Name]:Porch
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:63 [Type]:binary_switch_device [EquipmentCode]:undefined [Name]:Spare
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:70 [Type]:binary_switch_device [EquipmentCode]:undefined [Name]:Sunroom
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:77 [Type]:camera_device [EquipmentCode]:undefined [Name]:Doorbell
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Device not (yet) supported [ID]:78 [Type]:lgit_poe_wifi_device [EquipmentCode]:undefined [Name]:Front Yard-Bridge
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:79 [Type]:camera_device [EquipmentCode]:undefined [Name]:Front Yard
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Device not (yet) supported [ID]:80 [Type]:lgit_poe_wifi_device [EquipmentCode]:undefined [Name]:Yard-Bridge
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:81 [Type]:camera_device [EquipmentCode]:undefined [Name]:Yard
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:82 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Garage Door
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:83 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Kitchen Window Left
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:84 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Kitchen Window Right
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:85 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Master Bedroom Window
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:86 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Master Bedroom Window
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:87 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Master Bedroom Window
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:88 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Dining Room Window
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:89 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Dining Room Window
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:90 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Dining Room Window
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:91 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Office Window
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:92 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Office Window
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:93 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Front Bedroom Window
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:94 [Type]:wireless_sensor [EquipmentCode]:655 [Name]:Back Bedroom Window
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:111 [Type]:wireless_sensor [EquipmentCode]:1269 [Name]:Fire Alert
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:117 [Type]:door_lock_device [EquipmentCode]:undefined [Name]:Front Doorlock
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Managing device [ID]:9001672 [Type]:garage_door_device [EquipmentCode]:undefined [Name]:Garage Door
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Device not (yet) supported [ID]:129 [Type]:mqtt_audio_sync_service [EquipmentCode]:undefined [Name]:undefined
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Removing 0 accessories
[6/27/2024, 4:20:29 AM] [@balansse/homebridge-vivint] Adding 0 accessories
AssertionError [ERR_ASSERTION]: ipv4-mapped ipv6 addresses are currently unsupported!
    at enlargeIPv6 (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/util/domain-formatter.ts:137:9)
    at getNetAddress (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/util/domain-formatter.ts:296:26)
    at Function.HAPConnection.getLocalNetworkInterface (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:868:26)
    at new HAPConnection (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:390:43)
    at EventedHTTPServer.onConnection (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:229:24)
    at Server.emit (node:events:514:28)
    at TCP.onconnection (node:net:2157:8)
[6/27/2024, 4:20:31 AM] [RainBird] Child bridge process ended
[6/27/2024, 4:20:31 AM] [RainBird] Process Ended. Code: 1, Signal: null
[6/27/2024, 4:20:31 AM] [Blink] Blink marone home - Blink marone home Arm: Manual Arm
[6/27/2024, 4:20:31 AM] [Blink] Blink marone home - Blink marone home Arm: ✅
[6/27/2024, 4:20:31 AM] [Blink] Blink junior front - Temperature: 22.80000000000001°C
[6/27/2024, 4:20:31 AM] [Blink] Blink junior front - Enabled: ✅
[6/27/2024, 4:20:31 AM] [Blink] Blink young front - Temperature: 22.80000000000001°C
[6/27/2024, 4:20:31 AM] [Blink] Blink young front - Enabled: ✅
[6/27/2024, 4:20:31 AM] [Blink] Blink Young Back - Temperature: 21.700000000000003°C
[6/27/2024, 4:20:31 AM] [Blink] Blink Young Back - Enabled: ✅
[6/27/2024, 4:20:31 AM] [Blink] Blink Junior Back - Temperature: 21.700000000000003°C
[6/27/2024, 4:20:31 AM] [Blink] Blink Junior Back - Enabled: ✅
[6/27/2024, 4:20:31 AM] [Blink] Blink marone home - Blink marone home Armed (Target): ✅
[6/27/2024, 4:20:31 AM] [Blink] Blink marone home - Blink marone home Armed (Current): ✅
[6/27/2024, 4:20:38 AM] [RainBird] Restarting Process...
[6/27/2024, 4:20:38 AM] [RainBird] Launched child bridge with PID 49275
[6/27/2024, 4:20:38 AM] Registering platform 'homebridge-rainbird.RainBird'
[6/27/2024, 4:20:38 AM] [RainBird] Loaded homebridge-rainbird v2.0.3 child bridge successfully
[6/27/2024, 4:20:38 AM] Loaded 1 cached accessories from cachedAccessories.0E56348A3DF9.
[6/27/2024, 4:20:38 AM] [RainBird] Loading accessory from cache: ESP-ME3
[6/27/2024, 4:20:38 AM] Homebridge v1.8.2 (HAP v0.12.1) (RainBird) is running on port 40721.
[6/27/2024, 4:20:39 AM] [RainBird] Model: ESP-ME3, [Version: 2.12, Serial Number: 01e0420d500316, Zones: [1,2,3,4,5,6,7]]
[6/27/2024, 4:20:39 AM] [RainBird] Restoring existing accessory from cache: ESP-ME3
[6/27/2024, 5:58:47 AM] [Blink] Blink junior front - Temperature: 21.700000000000003°C
[6/27/2024, 5:58:47 AM] [Blink] Blink Junior Back - Refreshing snapshot
```

### Configuration

```json
"bridge": {
        "name": "Homebridge FBB9",
        "username": "0E:AB:27:2A:29:E5",
        "port": 51089,
        "pin": "***-**-***",
        "advertiser": "bonjour-hap"
    },
    "accessories": [
        {
            "name": "open up",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 1000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "refreshToken": "s=da8438bd-08fb-4072-840b-82c5d5135f9c",
            "apiLoginRefreshSecs": 1200,
            "logDeviceList": true,
            "useExternalVideoStreams": true,
            "_bridge": {
                "username": "0E:2B:2F:46:88:31",
                "port": 51766
            },
            "platform": "Vivint"
        },
        {
            "name": "Blink",
            "username": "bony618@gmail.com",
            "password": "************!",
            "pin": ******,
            "disable-thumbnail-refresh": false,
            "enable-startup-diagnostic": false,
            "platform": "Blink",
            "_bridge": {
                "username": "0E:BD:43:2B:12:76",
                "port": 44638
            }
        },
        {
            "name": "RainBird",
            "devices": [
                {
                    "ipaddress": "192.168.1.214",
                    "password": "****",
                    "external": false,
                    "includeZones": "1,2,3,4,5",
                    "syncTime": false
                }
            ],
            "platform": "RainBird",
            "_bridge": {
                "username": "0E:56:34:8A:3D:F9",
                "port": 40721
            }
        }
    ],
    "disabledPlugins": []
}
```

### Environment

- OS: macOS Monterey
- Software: Homebridge v1.8.2
- Node: 20.9.0
- npm: 10.1.0

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Duplicate of https://github.com/homebridge/ciao/issues/41

We believe this is triggered by your Apple TV being on the development version of tvOS 18 or mac being on macOS 15.  Please confirm

**Comment by bony618** [comment]
@NorthernMan54 Yes both of my Apple TV's are running tvOS 18 beta. Is there a fix for my issue?

**Comment by NorthernMan54** [comment]
@bony618 We are working thru a fix at this time, and should have something released within a few days.  If you unplug your Apple TV's homebridge will stop restarting.  But you will loose remote access, and automations. 

As a workaround, you could downgrade one of your AppleTV's to the previous release ( google shows a couple of methods ), and leave the other unplugged.  Or look at disabling IPV6 on the device your running homebridge on ( I'm guessing that this will work )

**Comment by bony618** [comment]
@NorthernMan54  Thanks.
Will this come in the form of a version update? (when I tried updating from 1.8.2 to 1.8.3 the problem became MUCH worse.)
I've disabled ipv6 on the mac running Homebridge but can't find any way to downgrade tvOS on a 4k Apple TV.

**Comment by NorthernMan54** [comment]
Did you set this on your Mac 

<img width="633" alt="image" src="https://github.com/homebridge/homebridge/assets/19808920/0146bf3f-c6cd-4e34-bbba-295b4f953d27">

**Comment by NorthernMan54** [comment]
Our initial fix is available as a homebridge alpha release - 
![image](https://github.com/homebridge/homebridge/assets/19808920/3be7aeb9-3510-472c-b856-4d1b74f8f1db)

**Comment by bony618** [comment]
@NorthernMan54  That seems to work smoothly thanks. The only unusual things showing up in the logs are many 
"HAP-NodeJS WARNINGs" about "not following HomeKit naming rules".....
Aside from that, everything appears to be functioning as expected.

**Comment by NorthernMan54** [comment]
Can you share the warning message ?  That is from a new warning we are working on

https://github.com/homebridge/HAP-NodeJS/pull/1049

**Comment by bony618** [comment]
There's a LOT of these (I think they're all identical):

HAP-NodeJS WARNING: The accessory 'Configured Name' is getting published with the characteristic 'ConfiguredName' not following HomeKit naming rules (''), with a pattern that'is empty'.Use only alphanumeric, space, and apostrophe characters, start and end with an alphabetic or numeric character, and don't include emojis. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!

**Comment by NorthernMan54** [comment]
Tks for the feedback on the new warning message.  Where it shows  'Configured Name' it should show the accessory name with the issue.

**Comment by bony618** [comment]
Just got this for a new alpha ver:

Screen Shot 2024-06-28 at 8.39.42 AM

**Comment by bony618** [comment]
(It's 1.8.4 alpha. 13)

**Comment by NorthernMan54** [comment]
We are in active development on the alpha branch, so it will change on a frequent basis.

No need to update further at this time.

**Comment by bony618** [comment]
I went ahead and updated already (I'm in the habit of keeping things up to date) and all seems the same (fine besides the naming issue).
Would you suggest going forward I wait for the next stable version?

I really appreciate all the help here!

**Comment by donavanbecker** [comment]
@bony618 the latest alpha should be validly validating on the ConfiguredName Characteristic now. So if you are still seeing this after updating and restarting, then this is valid and you need to change the name of the accessory and may need to potentially remove it from cache.

**Comment by bony618** [comment]
@donavanbecker   alpha 16 produced only two HAP-NodeJS WARNINGs:


```
HAP-NodeJS WARNING: The accessory '@balansse/homebridge-vivint' is getting published with the characteristic 'name' not following HomeKit naming rules ('@balansse/homebridge-vivint'), with a pattern that ('doesn't have only letter, numbers, apostrophe, or dash'). Use only alphanumeric, space, and apostrophe characters, start and end with an alphabetic or numeric character, and don't include emojis. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
[6/28/2024, 9:47:42 AM] Loaded 26 cached accessories from cachedAccessories.0E2B2F468831.
HAP-NodeJS WARNING: The accessory '@balansse/homebridge-vivint E925' is getting published with the characteristic 'Name' not following HomeKit naming rules ('@balansse/homebridge-vivint E925'), with a pattern that ('doesn't have only letter, numbers, apostrophe, or dash'). Use only alphanumeric, space, and apostrophe characters, start and end with an alphabetic or numeric character, and don't include emojis. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
```

...as opposed to the dozens previously.

Again, everything appears to be functioning normally.
I don't see any suspiciously named devices either in the accessories tab or in "remove single cached accessory"(?)

**Comment by donavanbecker** [comment]
> ```
> HAP-NodeJS WARNING: The accessory '@balansse/homebridge-vivint' is getting published with the characteristic 'name' not following HomeKit naming rules ('@balansse/homebridge-vivint'), with a pattern that ('doesn't have only letter, numbers, apostrophe, or dash'). Use only alphanumeric, space, and apostrophe characters, start and end with an alphabetic or numeric character, and don't include emojis. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
> [6/28/2024, 9:47:42 AM] Loaded 26 cached accessories from cachedAccessories.0E2B2F468831.
> HAP-NodeJS WARNING: The accessory '@balansse/homebridge-vivint E925' is getting published with the characteristic 'Name' not following HomeKit naming rules ('@balansse/homebridge-vivint E925'), with a pattern that ('doesn't have only letter, numbers, apostrophe, or dash'). Use only alphanumeric, space, and apostrophe characters, start and end with an alphabetic or numeric character, and don't include emojis. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
> ```

Right, this is a value Warning. The accessory name is `@balansse/homebridge-vivint` which it can't have a `@` or `/` in the name of the accessory.

**Comment by bony618** [comment]
@donavanbecker I get that 100%. I just can't locate any such named accessories. 
(?)
Also I don't see any detrimental effects of the naming format as far as functionality.

**Comment by donavanbecker** [comment]
@bony618 can you try upgrading from the Homebridge alpha branch to the Homebridge beta branch? latest Homebridge beta version should be `1.8.4-beta.13`

**Comment by donavanbecker** [comment]
This is resolved with Homebridge v2

**Comment by bwp91** [comment]
@bony618 are you able to update(/downgrade if on v2-beta) your homebridge version to `v1.8.5-beta.3`?

we would like to release a fix version of homebridge on the v1 stream so that users do not need to be on the v2 beta for this to be fixed
