### ISSUE TITLE
homebridge-cmdswitch2 plugin using depreciated HAP-NodeJS Code which cases Homebridge restart loop

### ISSUE THREAD

**Issue by PappyChappy1** [homebridge/homebridge#3654]
### Analysis

Not sure if this is better to report here or somewhere else, just a note that something in the Alpha for version 2 of Homebridge is causing the plugin homebridge-cmdswitch2-no-logs to break: 

```
Homebridge v2.0.0-alpha.2 (HAP v1.0.0) (homebridge-cmdswitch2) is running on port 48904.

/opt/homebrew/lib/node_modules/homebridge-cmdswitch2-no-logs/index.js:145
  accessory.updateReachability(true);
            ^
TypeError: accessory.updateReachability is not a function
    at cmdSwitchPlatform.getInitState (/opt/homebrew/lib/node_modules/homebridge-cmdswitch2-no-logs/index.js:145:13)
    at cmdSwitchPlatform.addAccessory (/opt/homebrew/lib/node_modules/homebridge-cmdswitch2-no-logs/index.js:99:8)
    at cmdSwitchPlatform.didFinishLaunching (/opt/homebrew/lib/node_modules/homebridge-cmdswitch2-no-logs/index.js:36:37)
    at HomebridgeAPI.emit (node:events:519:28)
    at HomebridgeAPI.signalFinished (/opt/homebrew/lib/node_modules/homebridge/src/api.ts:271:10)
    at ChildBridgeFork.startBridge (/opt/homebrew/lib/node_modules/homebridge/src/childBridgeFork.ts:194:14)
```

### Expected Behavior

If the plugin is enabled, it crashes the entire homebridge server; running in child bridge causes just the bridge to crash.

### Steps To Reproduce

Happy to submit more details or post this somewhere else

### Logs

```logs
Homebridge v2.0.0-alpha.2 (HAP v1.0.0) (homebridge-cmdswitch2) is running on port 48904.

/opt/homebrew/lib/node_modules/homebridge-cmdswitch2-no-logs/index.js:145
  accessory.updateReachability(true);
            ^
TypeError: accessory.updateReachability is not a function
    at cmdSwitchPlatform.getInitState (/opt/homebrew/lib/node_modules/homebridge-cmdswitch2-no-logs/index.js:145:13)
    at cmdSwitchPlatform.addAccessory (/opt/homebrew/lib/node_modules/homebridge-cmdswitch2-no-logs/index.js:99:8)
    at cmdSwitchPlatform.didFinishLaunching (/opt/homebrew/lib/node_modules/homebridge-cmdswitch2-no-logs/index.js:36:37)
    at HomebridgeAPI.emit (node:events:519:28)
    at HomebridgeAPI.signalFinished (/opt/homebrew/lib/node_modules/homebridge/src/api.ts:271:10)
    at ChildBridgeFork.startBridge (/opt/homebrew/lib/node_modules/homebridge/src/childBridgeFork.ts:194:14)
```

### Configuration

```json
Can send if helpful
```

### Environment

- OS: macOS Sonoma
- Software: 2.0.0 Alpha
- Node: Latest
- npm: Latest

### Process Supervisor

hb-service

**Comment by donavanbecker** [comment]
This is a plugin issue and not a Homebridge issue. Alpha is a major version change and depreciated functionality that was going to be removed 4 years ago is finally being removed. The plugin developer must update their plugins to use non depreciated code. You will want to close this issue and open it on the plugin side.

**Comment by donavanbecker** [comment]
[Updating To Homebridge v2.0](https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0)
