### ISSUE TITLE
iOS 18 Connexion Issues

### ISSUE THREAD

**Issue by robertavram-md** [homebridge/homebridge#3663]
### Analysis

Seems like the raspberry Pi with HomeBridge v1.8.4 has issues connecting to several services (NPMJS, Alarm.com etc). All my accessories are not responding. I updated to last version of Node JS + HomeBridge, restarted it, reconnected Wi-Fi to no avail.

### Expected Behavior

Accessories should eb responding

### Steps To Reproduce

1. Update your homeKit setup to IOS 18 Beta 3.
2. All accessories are not responding.

### Logs

```markdown
[21/07/2024, 09:29:06] [Security System] Child bridge process ended
[21/07/2024, 09:29:06] [Security System] Process Ended. Code: 1, Signal: null
[21/07/2024, 09:29:10] [homebridge-pico] [192.168.7.194] Writing Keep Alive
[21/07/2024, 09:29:10] [homebridge-pico] [192.168.7.194] Bus Data: GNET> 
[21/07/2024, 09:29:11] [Homebridge UI] [homebridge] Failed to check registry.npmjs.org for updates: "getaddrinfo ENOTFOUND registry.npmjs.org" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:13] [Security System] Restarting Process...
[21/07/2024, 09:29:16] [Security System] Launched child bridge with PID 2794
[21/07/2024, 09:29:16] Registering platform 'homebridge-node-alarm-dot-com.Alarmdotcom'
[21/07/2024, 09:29:16] [Security System] Loaded homebridge-node-alarm-dot-com v1.10.0 child bridge successfully
[21/07/2024, 09:29:16] Loaded 22 cached accessories from cachedAccessories.0E8E87837DE4.
[21/07/2024, 09:29:16] [Homebridge UI] [homebridge-broadlink-rm-pro] Failed to check registry.npmjs.org for updates: "getaddrinfo ENOTFOUND registry.npmjs.org" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:16] [Homebridge UI] [homebridge-alexa] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:16] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:16] [Homebridge UI] [homebridge-connexoon] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:16] [Homebridge UI] [homebridge-alexa] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:16] [Homebridge UI] [homebridge-broadlink-rm-pro] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:16] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:16] [Homebridge UI] [homebridge-connexoon] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:16] [Security System] Loaded from cache: partition1 (102394819-127)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: 2nd Floor Glass Sensor (102394819-10)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: 2nd Floor Motion (102394819-20)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: Basement Windows (102394819-19)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: Basement Wins (102394819-18)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: Entry Glass Sensor (102394819-14)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: Entry Motion (102394819-13)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: Front Door (102394819-15)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: Garage Door (102394819-16)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: Hallway Motion Detector (102394819-11)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: Hardwire Exp 1 (102394819-3)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: Hardwire Exp 2 (102394819-12)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: IQ Remote 2 (102394819-5514)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: kitchen glass (102394819-7)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: Laundry Water (102394819-24)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: Motion Detector (102394819-6)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: Panel Camera (102394819-229)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: Patio and Back door (102394819-17)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: Smoke Detector (102394819-5)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: Upstairs CO Detector (102394819-26)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: Upstairs Smoke Detector (102394819-8)
[21/07/2024, 09:29:16] [Security System] Loaded from cache: IQ Remote 1 (102394819-5513)
[21/07/2024, 09:29:17] Homebridge v1.8.3 (HAP v0.12.2) (Security System) is running on port 40261.
[21/07/2024, 09:29:22] [Security System] loginSession Error: GET https://www.alarm.com/login failed: GET https://www.alarm.com/login failed: request to https://www.alarm.com/login failed, reason: getaddrinfo ENOTFOUND www.alarm.com
[21/07/2024, 09:29:22] [Security System] Refreshing session authentication.
[21/07/2024, 09:29:22] [homebridge-pico] [192.168.7.194] Bus Data: ~OUTPUT,14,1,0.00
[21/07/2024, 09:29:26] [homebridge-pico] [192.168.7.194] Bus Data: ~OUTPUT,14,1,100.00
[21/07/2024, 09:29:26] [Homebridge UI] [homebridge-dummy-contact] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:26] [Homebridge UI] [homebridge-flair] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:26] [Homebridge UI] [homebridge-node-alarm-dot-com] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:26] [Homebridge UI] [homebridge-pico] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:26] [Homebridge UI] [homebridge-dummy-contact] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:26] [Homebridge UI] [homebridge-flair] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:26] [Homebridge UI] [homebridge-node-alarm-dot-com] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:26] [Homebridge UI] [homebridge-pico] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
Error: GET https://www.alarm.com/web/api/identities failed: GET https://www.alarm.com/web/api/identities failed: request to https://www.alarm.com/web/api/identities failed, reason: getaddrinfo ENOTFOUND www.alarm.com
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:150:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getIdentitiesState (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:134:12)
    at ADCPlatform.getAccountSettings (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:380:24)
    at ADCPlatform.registerAlarmSystem (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:213:5)
[21/07/2024, 09:29:27] [Security System] Child bridge process ended
[21/07/2024, 09:29:27] [Security System] Process Ended. Code: 1, Signal: null
[21/07/2024, 09:29:34] [Security System] Restarting Process...
[21/07/2024, 09:29:36] [Homebridge UI] [homebridge-rachio-irrigation] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:36] [Homebridge UI] [homebridge-roomba2] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:36] [Homebridge UI] [homebridge-rachio-irrigation] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:36] [Homebridge UI] [homebridge-roomba2] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.
[21/07/2024, 09:29:37] [Security System] Launched child bridge with PID 2842
[21/07/2024, 09:29:37] Registering platform 'homebridge-node-alarm-dot-com.Alarmdotcom'
[21/07/2024, 09:29:37] [Security System] Loaded homebridge-node-alarm-dot-com v1.10.0 child bridge successfully
[21/07/2024, 09:29:37] Loaded 22 cached accessories from cachedAccessories.0E8E87837DE4.
[21/07/2024, 09:29:37] [Security System] Loaded from cache: partition1 (102394819-127)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: 2nd Floor Glass Sensor (102394819-10)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: 2nd Floor Motion (102394819-20)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: Basement Windows (102394819-19)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: Basement Wins (102394819-18)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: Entry Glass Sensor (102394819-14)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: Entry Motion (102394819-13)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: Front Door (102394819-15)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: Garage Door (102394819-16)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: Hallway Motion Detector (102394819-11)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: Hardwire Exp 1 (102394819-3)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: Hardwire Exp 2 (102394819-12)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: IQ Remote 2 (102394819-5514)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: kitchen glass (102394819-7)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: Laundry Water (102394819-24)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: Motion Detector (102394819-6)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: Panel Camera (102394819-229)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: Patio and Back door (102394819-17)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: Smoke Detector (102394819-5)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: Upstairs CO Detector (102394819-26)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: Upstairs Smoke Detector (102394819-8)
[21/07/2024, 09:29:37] [Security System] Loaded from cache: IQ Remote 1 (102394819-5513)
[21/07/2024, 09:29:37] Homebridge v1.8.3 (HAP v0.12.2) (Security System) is running on port 40261.
[21/07/2024, 09:29:42] [Security System] loginSession Error: GET https://www.alarm.com/login failed: GET https://www.alarm.com/login failed: request to https://www.alarm.com/login failed, reason: getaddrinfo ENOTFOUND www.alarm.com
[21/07/2024, 09:29:42] [Security System] Refreshing session authentication.
Error: GET https://www.alarm.com/web/api/identities failed: GET https://www.alarm.com/web/api/identities failed: request to https://www.alarm.com/web/api/identities failed, reason: getaddrinfo ENOTFOUND www.alarm.com
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:150:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getIdentitiesState (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:134:12)
    at ADCPlatform.getAccountSettings (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:380:24)
    at ADCPlatform.registerAlarmSystem (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:213:5)
[21/07/2024, 09:29:48] [Security System] Child bridge process ended
[21/07/2024, 09:29:48] [Security System] Process Ended. Code: 1, Signal: null
[21/07/2024, 09:29:48] [homebridge-pico] [192.168.7.194] Bus Data: ~OUTPUT,14,1,0.00
[21/07/2024, 09:29:54] [homebridge-pico] [192.168.7.194] Bus Data: ~OUTPUT,19,1,0.00
[21/07/2024, 09:29:55] [Security System] Restarting Process...
[21/07/2024, 09:29:57] [Security System] Launched child bridge with PID 2894
[21/07/2024, 09:29:57] Registering platform 'homebridge-node-alarm-dot-com.Alarmdotcom'
[21/07/2024, 09:29:58] [Security System] Loaded homebridge-node-alarm-dot-com v1.10.0 child bridge successfully
[21/07/2024, 09:29:58] Loaded 22 cached accessories from cachedAccessories.0E8E87837DE4.
[21/07/2024, 09:29:58] [Security System] Loaded from cache: partition1 (102394819-127)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: 2nd Floor Glass Sensor (102394819-10)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: 2nd Floor Motion (102394819-20)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: Basement Windows (102394819-19)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: Basement Wins (102394819-18)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: Entry Glass Sensor (102394819-14)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: Entry Motion (102394819-13)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: Front Door (102394819-15)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: Garage Door (102394819-16)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: Hallway Motion Detector (102394819-11)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: Hardwire Exp 1 (102394819-3)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: Hardwire Exp 2 (102394819-12)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: IQ Remote 2 (102394819-5514)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: kitchen glass (102394819-7)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: Laundry Water (102394819-24)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: Motion Detector (102394819-6)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: Panel Camera (102394819-229)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: Patio and Back door (102394819-17)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: Smoke Detector (102394819-5)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: Upstairs CO Detector (102394819-26)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: Upstairs Smoke Detector (102394819-8)
[21/07/2024, 09:29:58] [Security System] Loaded from cache: IQ Remote 1 (102394819-5513)
[21/07/2024, 09:29:58] Homebridge v1.8.3 (HAP v0.12.2) (Security System) is running on port 40261.
ERROR: getaddrinfo ENOTFOUND alexa.homebridge.ca ENOTFOUND Error: getaddrinfo ENOTFOUND alexa.homebridge.ca
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'alexa.homebridge.ca'
}
[21/07/2024, 09:30:03] [Security System] loginSession Error: GET https://www.alarm.com/login failed: GET https://www.alarm.com/login failed: request to https://www.alarm.com/login failed, reason: getaddrinfo ENOTFOUND www.alarm.com
[21/07/2024, 09:30:03] [Security System] Refreshing session authentication.
Error: GET https://www.alarm.com/web/api/identities failed: GET https://www.alarm.com/web/api/identities failed: request to https://www.alarm.com/web/api/identities failed, reason: getaddrinfo ENOTFOUND www.alarm.com
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:150:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getIdentitiesState (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:134:12)
    at ADCPlatform.getAccountSettings (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:380:24)
    at ADCPlatform.registerAlarmSystem (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:213:5)
[21/07/2024, 09:30:09] [Security System] Child bridge process ended
[21/07/2024, 09:30:09] [Security System] Process Ended. Code: 1, Signal: null
[21/07/2024, 09:30:10] [homebridge-pico] [192.168.7.194] Writing Keep Alive
[21/07/2024, 09:30:10] [homebridge-pico] [192.168.7.194] Bus Data: GNET> ```
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge 57F6",
        "username": "0E:C1:A1:CF:57:F6",
        "port": 51003,
        "pin": "218-88-293",
        "advertiser": "ciao"
    },
    "accessories": [
        {
            "name": "Fireplace Living Room",
            "stateful": true,
            "switch": true,
            "contact": true,
            "reverse": false,
            "time": 1000,
            "debug": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "Fireplace Kitchen",
            "stateful": true,
            "switch": true,
            "contact": true,
            "reverse": false,
            "time": 1000,
            "debug": false,
            "accessory": "DummySwitch"
        },
        {
            "dockContactSensor": true,
            "runningContactSensor": true,
            "homeSwitch": true,
            "stopBehaviour": "home",
            "accessory": "Roomba2"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "buslog": "full",
            "servers": [
                {
                    "switches": [
                        {
                            "pico": [
                                13
                            ],
                            "name": "Family Room Pico",
                            "type": "PJ2-3BRL",
                            "repeatmax": 10
                        },
                        {
                            "pico": [
                                21
                            ],
                            "name": "Main Hallway Pico",
                            "type": "PJ2-2B",
                            "repeatmax": 10
                        },
                        {
                            "pico": [
                                17
                            ],
                            "name": "Living Room Pico",
                            "type": "PJ2-2B",
                            "repeatmax": 10
                        },
                        {
                            "pico": [
                                20
                            ],
                            "name": "Top Hallway Pico",
                            "type": "PJ2-2B",
                            "repeatmax": 10
                        },
                        {
                            "pico": [
                                18
                            ],
                            "name": "Master Bedroom Pico",
                            "type": "PJ2-2B",
                            "repeatmax": 10
                        },
                        {
                            "pico": [
                                26
                            ],
                            "name": "Dining Table Pico",
                            "type": "PJ2-2B",
                            "repeatmax": 10
                        }
                    ],
                    "host": "192.168.7.194",
                    "port": 23
                }
            ],
            "longname": true,
            "clicktime": 500,
            "slowextra": 250,
            "repeattime": 500,
            "slowbuttons": [
                5,
                6
            ],
            "_bridge": {
                "username": "0E:1C:0E:86:8C:A1",
                "port": 43570
            },
            "platform": "Pico"
        },
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": false
        },
        {
            "name": "Security System",
            "username": "XXXX",
            "password": "XXXX!",
            "useMFA": true,
            "mfaCookie": "XXXXX",
            "logLevel": 3,
            "armingModes": {
                "away": {
                    "noEntryDelay": false,
                    "silentArming": false,
                    "nightArming": true
                },
                "night": {
                    "noEntryDelay": false,
                    "silentArming": true,
                    "nightArming": false
                },
                "stay": {
                    "noEntryDelay": false,
                    "silentArming": true,
                    "nightArming": false
                }
            },
            "ignoredDevices": [
                "102394819-4"
            ],
            "_bridge": {
                "username": "0E:8E:87:83:7D:E4",
                "port": 40261
            },
            "platform": "Alarmdotcom"
        },
        {
            "name": "Alexa",
            "username": "XXXX",
            "password": "XXXX",
            "pin": "XXXX",
            "routines": true,
            "blind": false,
            "door": false,
            "debug": false,
            "deviceListHandling": "allow",
            "platform": "Alexa",
            "_bridge": {
                "username": "0E:0B:30:6A:08:CC",
                "port": 37118
            }
        },
        {
            "platform": "Connexoon",
            "name": "My Connexoon Hub",
            "username": "XXX",
            "password": "XXXX",
            "service": "TaHomaUSA",
            "_bridge": {
                "username": "0E:AF:7A:0F:0B:F7",
                "port": 45694
            }
        },
        {
            "clientId": "XXXX",
            "clientSecret": "XXXXX",
            "username": "XXXX",
            "password": "XXXX",
            "pollInterval": 240,
            "hidePuckSensors": false,
            "hidePuckRooms": true,
            "hidePrimaryStructure": true,
            "hideVentTemperatureSensors": true,
            "ventAccessoryType": "hidden",
            "_bridge": {
                "username": "0E:13:C2:96:A0:53",
                "port": 56375
            },
            "platform": "Flair"
        },
        {
            "name": "Rachio",
            "api_key": "XXXX",
            "default_runtime": 3,
            "runtime_source": 0,
            "use_irrigation_display": true,
            "show_standby": false,
            "show_runall": false,
            "show_schedules": false,
            "internal_IP_address": "127.0.0.1",
            "external_webhook_port": 12453,
            "internal_webhook_port": 27546,
            "use_basic_auth": false,
            "delete_webhooks": false,
            "showAPIMessages": false,
            "showWebhookMessages": false,
            "platform": "rachio",
            "_bridge": {
                "username": "0E:13:AE:19:90:B0",
                "port": 37147
            }
        }
    ],
    "disabledPlugins": [
        "homebridge-gsh-kazari",
        "homebridge-roomba2"
    ]
}
```

### Environment

- OS: Raspbian 10
- Software: 1.8.4
- Node: v18.18.0
- npm: 9.8.1

### Process Supervisor

hb-service

**Comment by robertavram-md** [comment]
This could also be related to Erero v.7.4.2 OS which updated yesterday.

**Comment by bwp91** [comment]
issue includes credentials for your connexoon account. please change that password immediately

**Comment by donavanbecker** [comment]
Restart your eero networks and report back

**Comment by robertavram-md** [comment]
Restarting Eero worked
