### ISSUE TITLE
Upgrade 

### ISSUE THREAD

**Issue by hyperbart** [homebridge/homebridge#3673]
### Current Situation

I have been using a rPi running https://github.com/homebridge/homebridge-raspbian-image.
This rPi controls my garage door via the GPIO pins and a relay and detects if the door is open via a reed sensor.
The plugin I have been using is https://github.com/benlamonica/homebridge-rasppi-gpio-garagedoor.
This has been working absolutely amazing but I wanted to do some lifecycle management since I was still running on an older version and remember there were some issues a while back with NPM and versions, not wanting to face any security issues and just do proper life cycle management in my home automation I wanted to upgrade.

Current running version which I wanted to upgrade:

![image](https://github.com/user-attachments/assets/01950b27-be21-4c46-b2e4-52a71ba031c2)

I imaged a new SD card and imported the configuration backup in the /setup web interface.
After importing the backup I had some warnings that the plugin wouldn't be able to control GPIO since it wasn't running as root, so I modified the service file to make sure it runs as root (https://www.reddit.com/r/homebridge/comments/urxivs/comment/i90guzx/)

After having it run as root it still gives me problems and apparently something has changed in the way GPIO pins are presented? Between the version I am running now versus the newer version of the image

![image](https://github.com/user-attachments/assets/1858d0b2-717d-42ad-8c80-fe901b3181f6)

While on the current version it shows as:
![image](https://github.com/user-attachments/assets/1d3e98ed-9946-434a-92b9-3fbd2e13c7d6)

I have no memory or documentation stating that I had to do something with symlinks to expose the GPIO pins, but I might be mistaken.

With the current plugin, how could I make sure this keeps on working with the newer versions of Homebridge, also taking into account v2 coming up.

### Logs

```markdown
[11/08/2024, 14:16:20] [HB Supervisor] Restarting Homebridge...
[11/08/2024, 14:16:20] [HB Supervisor] Starting Homebridge with extra flags: -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[11/08/2024, 14:16:20] [HB Supervisor] Started Homebridge v1.8.4 with PID: 4939
[11/08/2024, 14:16:21] Loaded config.json with 2 accessories and 1 platforms.
[11/08/2024, 14:16:22] Loaded 0 cached accessories from cachedAccessories.
[11/08/2024, 14:16:22] ---
[11/08/2024, 14:16:22] Loaded plugin: homebridge-rasppi-gpio-garagedoor@1.0.10
[11/08/2024, 14:16:22] Registering accessory 'homebridge-rasppi-gpio-garagedoor.RaspPiGPIOGarageDoor'
[11/08/2024, 14:16:22] ---
[11/08/2024, 14:16:22] Loaded plugin: homebridge-relays@2.0.0
[11/08/2024, 14:16:22] Registering accessory 'homebridge-relays.Relay'
[11/08/2024, 14:16:22] ---
[11/08/2024, 14:16:22] Loading 1 platforms...
[11/08/2024, 14:16:22] Loading 2 accessories...
[11/08/2024, 14:16:22] [Relay 2 board] Initializing Relay accessory...
[11/08/2024, 14:16:22] [Garage Door] Initializing RaspPiGPIOGarageDoor accessory...
[11/08/2024, 14:16:22] [Garage Door] RaspPiGPIOGarageDoorAccessory version 1.0.10
[11/08/2024, 14:16:22] [Garage Door] Door Switch Pin: 17
[11/08/2024, 14:16:22] [Garage Door] Door Switch Val: ACTIVE_HIGH
[11/08/2024, 14:16:22] [Garage Door] Door Switch Active Time in ms: 500
[11/08/2024, 14:16:22] [Garage Door] Door Closed Sensor: Configured
[11/08/2024, 14:16:22] [Garage Door]     Door Closed Sensor Pin: 18
[11/08/2024, 14:16:22] [Garage Door]     Door Closed Sensor Val: ACTIVE_HIGH
[11/08/2024, 14:16:22] [Garage Door] Door Open Sensor: Not Configured
[11/08/2024, 14:16:22] [Garage Door] Sensor Poll in ms: 500
[11/08/2024, 14:16:22] [Garage Door] Door Opens in seconds: 24
[11/08/2024, 14:16:22] Error: ENOENT: no such file or directory, open '/sys/class/gpio/gpio18/value'
    at Object.readFileSync (node:fs:457:20)
    at RaspPiGPIOGarageDoorAccessory.readPin (/var/lib/homebridge/node_modules/homebridge-rasppi-gpio-garagedoor/index.js:149:26)
    at RaspPiGPIOGarageDoorAccessory.isClosed (/var/lib/homebridge/node_modules/homebridge-rasppi-gpio-garagedoor/index.js:158:21)
    at RaspPiGPIOGarageDoorAccessory.initService (/var/lib/homebridge/node_modules/homebridge-rasppi-gpio-garagedoor/index.js:124:25)
    at new RaspPiGPIOGarageDoorAccessory (/var/lib/homebridge/node_modules/homebridge-rasppi-gpio-garagedoor/index.js:66:8)
    at /var/lib/homebridge/node_modules/homebridge/src/server.ts:367:50
    at Array.forEach (<anonymous>)
    at Server.loadAccessories (/var/lib/homebridge/node_modules/homebridge/src/server.ts:287:29)
    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:167:12)
[11/08/2024, 14:16:22] Got SIGTERM, shutting down Homebridge...
[11/08/2024, 14:16:22] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1004:11)
    at Server.setServerStatus (/var/lib/homebridge/node_modules/homebridge/src/server.ts:143:45)
    at Server.teardown (/var/lib/homebridge/node_modules/homebridge/src/server.ts:187:10)
    at signalHandler (/var/lib/homebridge/node_modules/homebridge/src/cli.ts:94:12)
    at process.emit (node:events:518:28)
    at process.emit (/var/lib/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[11/08/2024, 14:16:27] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[11/08/2024, 14:16:28] [Homebridge UI] Terminal session ended.
```

### Configuration

```json
"accessories": [
        {
            "accessory": "Relay",
            "name": "Relay 2 board",
            "pin": 13,
            "invert": false,
            "default_state": false
        },
        {
            "accessory": "RaspPiGPIOGarageDoor",
            "name": "Garage Door",
            "doorSwitchPin": 17,
            "doorSwitchPressTimeInMs": 500,
            "doorSwitchValue": 1,
            "closedDoorSensorPin": 18,
            "closedDoorSensorValue": 1,
            "doorPollInMs": 500,
            "doorOpensInSeconds": 24
        }
    ],
```

### Environment

- OS:  Raspbian GNU/Linux Buster (10) 
- Software: Homebridge v1.7.0 
- Node:  v18.18.2 
- npm:

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
With the newer homebridge image, we have updated the underlying OS to the Ubuntu Bookworm release.  For the GPIO pins, this is controlled by the operating system, so please look at the changes in regards to GPIO and the ubuntu bookworm release.

**Comment by NorthernMan54** [comment]
You may also want to raise this against `homebridge-rasppi-gpio-garagedoor` so the plugin developer is aware.
