### ISSUE TITLE
Backup/Restore from Raspbian to Mac OS - homebridge keeps restarting: EACCES: permission denied, mkdir '/var/lib/homebridge'

### ISSUE THREAD

**Issue by Kositch** [homebridge/homebridge#3691]
### Current Situation

After performing Restore of backup made on Raspbian instance, it Recovers on new instance running Mac OS withou problems, plugins were installed, but Homebridge keeps restarting with errors below. 

Not sure, what to do, because on Raspbian Homebridge home folder was located in /var/local/Homebridge and on Mac OS it is locates in Users/michal/.homebridge and it seems something is trying to write to original Raspbian homebridge location which is not allowed in Mac - this folder is restricted on Mac OS and it is not even Homebridge home location.

From logs below I cant identify if it is caused by any plugins I use or homebridge instance itself.

When this error happens, homebridge restarts, is running for 4 seconds and it keeps repeating in loop. I thought that Homebridge can handle those home folder location changes during the Backup/Restor as it is stated that Backup/Restore function is platform independent.

### Logs

```markdown
Logs of specific error:

9/4/2024, 7:08:12 PM] Error: EACCES: permission denied, mkdir '/var/lib/homebridge'
[9/4/2024, 7:08:12 PM] Got SIGTERM, shutting down Homebridge...
[9/4/2024, 7:08:12 PM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1004:11)
    at Server.setServerStatus (/usr/local/lib/node_modules/homebridge/src/server.ts:143:45)
    at Server.teardown (/usr/local/lib/node_modules/homebridge/src/server.ts:187:10)
    at signalHandler (/usr/local/lib/node_modules/homebridge/src/cli.ts:94:12)
    at process.emit (node:events:519:28)
    at process.emit (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)


Logs of Restore process if something can be found here:

[9/4/2024, 7:02:12 PM] [Homebridge UI] Starting backup restore...
[9/4/2024, 7:02:14 PM] [Homebridge UI] Running Command: npm install -g @0x5e/homebridge-tuya-platform@1.7.0-beta.54
[9/4/2024, 7:02:25 PM] [Homebridge UI] Running Command: npm install -g @switchbot/homebridge-switchbot@3.4.0
[9/4/2024, 7:02:45 PM] [Homebridge UI] Running Command: npm install -g homebridge-airthings@1.1.0
[9/4/2024, 7:02:49 PM] [Homebridge UI] Running Command: npm install -g homebridge-camera-ui@5.0.27
[9/4/2024, 7:03:18 PM] [Homebridge UI] Running Command: npm install -g homebridge-connexoon@2.2.4
[9/4/2024, 7:03:20 PM] [Homebridge UI] Running Command: npm install -g homebridge-delay-switch@3.2.5
[9/4/2024, 7:03:22 PM] [Homebridge UI] Running Command: npm install -g homebridge-dummy@0.9.0
[9/4/2024, 7:03:24 PM] [Homebridge UI] Running Command: npm install -g homebridge-eveatmo@1.1.2
[9/4/2024, 7:03:29 PM] [Homebridge UI] Running Command: npm install -g homebridge-harmony@1.6.3
[9/4/2024, 7:03:39 PM] [Homebridge UI] Running Command: npm install -g homebridge-http-advanced-accessory@1.3.0
[9/4/2024, 7:03:42 PM] [Homebridge UI] Running Command: npm install -g homebridge-hue@0.13.70
[9/4/2024, 7:03:47 PM] [Homebridge UI] Running Command: npm install -g homebridge-shelly-ng@1.6.0
[9/4/2024, 7:03:50 PM] [Homebridge UI] Running Command: npm install -g homebridge-vera@0.8.2
[9/4/2024, 7:03:57 PM] [Homebridge UI] Sending SIGKILL to Homebridge
[9/4/2024, 7:03:57 PM] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGKILL
[9/4/2024, 7:03:58 PM] [HB Supervisor] Homebridge Storage Path: /Users/michal/.homebridge
[9/4/2024, 7:03:58 PM] [HB Supervisor] Homebridge Config Path: /Users/michal/.homebridge/config.json
[9/4/2024, 7:03:58 PM] [HB Supervisor] Logging to /Users/michal/.homebridge/homebridge.log
[9/4/2024, 7:03:58 PM] [HB Supervisor] OS: Darwin 23.6.0 arm64
[9/4/2024, 7:03:58 PM] [HB Supervisor] Node.js v20.17.0 /usr/local/bin/node
[9/4/2024, 7:03:58 PM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[9/4/2024, 7:03:58 PM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[9/4/2024, 7:03:59 PM] [Homebridge UI] Homebridge UI v4.57.1 is listening on :: port 8581
[9/4/2024, 7:03:59 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[9/4/2024, 7:03:59 PM] [HB Supervisor] Started Homebridge v1.8.4 with PID: 16082
[9/4/2024, 7:03:59 PM] Loaded config.json with 30 accessories and 10 platforms.
[9/4/2024, 7:03:59 PM] Loaded 4 cached accessories from cachedAccessories.
[9/4/2024, 7:03:59 PM] ---
[9/4/2024, 7:03:59 PM] Loaded plugin: homebridge-airthings@1.1.0
[9/4/2024, 7:03:59 PM] Registering accessory 'homebridge-airthings.Airthings'
[9/4/2024, 7:03:59 PM] ---
[9/4/2024, 7:04:00 PM] Loaded plugin: homebridge-camera-ui@5.0.27
[9/4/2024, 7:04:00 PM] Registering platform 'homebridge-camera-ui.CameraUI'
[9/4/2024, 7:04:00 PM] ---
[9/4/2024, 7:04:00 PM] Loaded plugin: homebridge-config-ui-x@4.57.1
[9/4/2024, 7:04:00 PM] Registering platform 'homebridge-config-ui-x.config'
[9/4/2024, 7:04:00 PM] ---
[9/4/2024, 7:04:00 PM] Loaded plugin: homebridge-connexoon@2.2.4
[9/4/2024, 7:04:00 PM] Registering platform 'homebridge-connexoon.Connexoon'
[9/4/2024, 7:04:00 PM] ---
[9/4/2024, 7:04:00 PM] Loaded plugin: homebridge-delay-switch@3.2.5
[9/4/2024, 7:04:00 PM] Registering accessory 'homebridge-delay-switch.DelaySwitch'
[9/4/2024, 7:04:00 PM] ---
[9/4/2024, 7:04:00 PM] Loaded plugin: homebridge-dummy@0.9.0
[9/4/2024, 7:04:00 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[9/4/2024, 7:04:00 PM] ---
[9/4/2024, 7:04:00 PM] Loaded plugin: homebridge-eveatmo@1.1.2
[9/4/2024, 7:04:00 PM] Registering platform 'homebridge-eveatmo.eveatmo'
[9/4/2024, 7:04:00 PM] ---
[9/4/2024, 7:04:00 PM] Loaded plugin: homebridge-harmony@1.6.3
[9/4/2024, 7:04:00 PM] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
[9/4/2024, 7:04:00 PM] ---
[9/4/2024, 7:04:00 PM] Loaded plugin: homebridge-http-advanced-accessory@1.3.0
[9/4/2024, 7:04:00 PM] Registering accessory 'homebridge-http-advanced-accessory.HttpAdvancedAccessory'
[9/4/2024, 7:04:00 PM] ---
[9/4/2024, 7:04:00 PM] Loaded plugin: homebridge-hue@0.13.70
[9/4/2024, 7:04:00 PM] Registering platform 'homebridge-hue.Hue'
[9/4/2024, 7:04:00 PM] ---
[9/4/2024, 7:04:00 PM] Loaded plugin: homebridge-shelly-ng@1.6.0
[9/4/2024, 7:04:00 PM] Registering platform 'homebridge-shelly-ng.ShellyNG'
[9/4/2024, 7:04:00 PM] ---
[9/4/2024, 7:04:01 PM] Loaded plugin: homebridge-vera@0.8.2
VeraLink initializing
[9/4/2024, 7:04:01 PM] Registering platform 'homebridge-vera.Vera'
[9/4/2024, 7:04:01 PM] ---
[9/4/2024, 7:04:01 PM] Loaded plugin: @0x5e/homebridge-tuya-platform@1.7.0-beta.54
[9/4/2024, 7:04:01 PM] Registering platform '@0x5e/homebridge-tuya-platform.TuyaPlatform'
[9/4/2024, 7:04:01 PM] ---
[9/4/2024, 7:04:01 PM] Loaded plugin: @switchbot/homebridge-switchbot@3.4.0
[9/4/2024, 7:04:01 PM] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
[9/4/2024, 7:04:01 PM] ---
```

### Configuration

```json
N/A
```

### Environment

Backup made on:
OS: Raspbian GNU/Linux Buster (10)
Node.js: v20.16.0
Homebridge version: 1.8.4
NPM version: 10.8.2
Node.js Path: /usr/local/bin
Homebridge location: /var/lib/homebridge
Config location: /var/lib/homebridge/config.json
Plugin location: /usr/local/lib/node_modules

Restore performed on:
OS: Mac OS 14.6.1
Node.js: v20.17.0
Homebridge version: 1.8.4
NPM version: 10.8.2
Node.js Path: /usr/local/bin
Homebridge location: /Users/michal/.homebridge
Config location: /Users/michal/.homebridge/config.json
Plugin location: /usr/local/lib/node_modules

### Process Supervisor

hb-service

**Comment by Kositch** [comment]
Update: Solved by editing Camera.UI plugin file database.json which was trying to write to var/lib/homebridge forbidden location on Mac OS instead of users/username/homebridge. Solution found here: https://www.reddit.com/r/homebridge/comments/xiuraq/error_when_transferring_hb_config_from_mac_to_mac/
