### ISSUE TITLE
Homebridge stuck on reboot loop after Update to latetst beta.

### ISSUE THREAD

**Issue by Feinfinger380** [homebridge/homebridge#3701]
### Current Situation

I use homebridge version 1.8.4. After the update to latest beta via the web interface, the homebridge gets stuck in a reboot loop.
As soon as I install the last stable version via the console, it works perfectly again.

### Logs

```markdown
[9/20/2024, 4:48:36 AM] TypeError: Cannot read properties of undefined (reading 'UINT8')
    at FHEMAccessory.getServices (/usr/local/lib/node_modules/homebridge-fhem/index.js:3143:101)
    at BridgeService.createHAPAccessory (file:///usr/local/lib/node_modules/homebridge/src/bridgeService.ts:439:41)
    at file:///usr/local/lib/node_modules/homebridge/src/bridgeService.ts:509:34
    at Array.forEach (<anonymous>)
    at file:///usr/local/lib/node_modules/homebridge/src/bridgeService.ts:500:21
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:15:14
    at FHEMPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/index.js:1222:22)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:313:12)
    at Request.emit (node:events:519:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1638:10)
    at Request.emit (node:events:519:28)
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/homebridge-fhem/node_modules/postman-request/request.js:1509:12)
    at Object.onceWrapper (node:events:633:28)
    at Gunzip.emit (node:events:519:28)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[9/20/2024, 4:48:36 AM] Got SIGTERM, shutting down Homebridge...
[9/20/2024, 4:48:36 AM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.setupURI (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:897:11)
    at Server.setServerStatus (file:///usr/local/lib/node_modules/homebridge/src/server.ts:146:45)
    at Server.teardown (file:///usr/local/lib/node_modules/homebridge/src/server.ts:190:10)
    at signalHandler (file:///usr/local/lib/node_modules/homebridge/src/cli.ts:94:12)
    at process.emit (node:events:519:28)
    at process.emit (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[9/20/2024, 4:48:36 AM] [Homebridge UI] Homebridge UI v4.58.0 is listening on :: port 8080


Websocket failed to connect. Is the server running?
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge FHEM",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXXXX,
        "pin": "000-00-000"
    },
    "platforms": [
        {
            "platform": "FHEM",
            "name": "FHEM",
            "server": "XXX.XXX.XXX.X",
            "auth": {
                "user": "XXXXXX",
                "pass": "XXXXXXXXXXXXX"
            },
            "port": "8083",
            "filter": "room=Homekit"
        },
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "blue",
            "restart": "sudo -n systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": true,
            "debug": false,
            "log": {
                "method": "custom",
                "command": "journalctl -o cat -n 500 -f -u homebridge"
            },
            "accessoryControl": {
                "debug": false,
                "instanceBlacklist": [
                    "XX:XX:XX:XX:XX:XX",
                    "XX:XX:XX:XX:XX:XX",
                    "XX:XX:XX:XX:XX:XX",
                    "XX:XX:XX:XX:XX:XX"
                ]
            },
            "platform": "config"
        }
    ],
    "accessories": [],
    "id": "config"
}
```

### Environment

- OS: Ubuntu 20.04.6 LTS
- Software: Homebridge 1.8.4
- Node: 20.17.0
- npm: 10.8.2

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
The appears to be a plugin issue with homebridge 2.0.  Pls raise this against `homebridge-fhem` so that the developer is aware.
