### ISSUE TITLE
Disastrous attempt to update node.js on Mac

### ISSUE THREAD

**Issue by sddgit** [homebridge/homebridge#3726]
### Current Status:

`hb-service update-node` is failing on MacOS, on M/Arm based Mac's.  As a workaround, it has been reported that if you just re-run the `hb-service update-node` command, it will repair itself.

### Current Situation

My node.js was on 18.something, so I thought I’d update it. I ran hb-service update-node from Terminal, but it failed miserably, even complaining that Python wasn’t installed. After that, I couldn’t access the Homebridge GUI. Then I installed node.js 20.9.0 by following the link at https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-macOS. Homebridge still wouldn’t start. So then I installed Homebridge using ``sudo npm install -g --unsafe-perm homebridge homebridge-config-ui-x`` and the service too using ``sudo hb-service install``. After that, Homebridge was fine again.

What went wrong using the preferred node update method?

### Logs

```markdown
steve@mac ~ % sudo hb-service update-node
Password:
ℹ Updating Node.js from v18.18.0 to v22.11.0...
ℹ Target: /usr/local
✔ Download complete.
✔ Cleaned up npm at at /usr/local/lib/node_modules/npm
✔ Installed Node.js v22.11.0
npm error code 1
npm error path /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch
npm error command failed
npm error command sh -c node scripts/check-prebuild.js || prebuild-install --verbose || node scripts/install.js
npm error Prebuild binary missing for platform.
npm error prebuild-install info begin Prebuild-install version 7.1.2
npm error prebuild-install info looking for local prebuild @ prebuilds/node-pty-prebuilt-multiarch-v0.11.14-node-v127-darwin-arm64.tar.gz
npm error prebuild-install info looking for cached prebuild @ /Users/steve/.npm/_prebuilds/392543-node-pty-prebuilt-multiarch-v0.11.14-node-v127-darwin-arm64.tar.gz
npm error prebuild-install http request GET https://github.com/homebridge/node-pty-prebuilt-multiarch/releases/download/v0.11.14/node-pty-prebuilt-multiarch-v0.11.14-node-v127-darwin-arm64.tar.gz
npm error prebuild-install http 200 https://github.com/homebridge/node-pty-prebuilt-multiarch/releases/download/v0.11.14/node-pty-prebuilt-multiarch-v0.11.14-node-v127-darwin-arm64.tar.gz
npm error prebuild-install info downloading to @ /Users/steve/.npm/_prebuilds/392543-node-pty-prebuilt-multiarch-v0.11.14-node-v127-darwin-arm64.tar.gz.42681-a954583494fe3.tmp
npm error prebuild-install info renaming to @ /Users/steve/.npm/_prebuilds/392543-node-pty-prebuilt-multiarch-v0.11.14-node-v127-darwin-arm64.tar.gz
npm error prebuild-install info unpacking @ /Users/steve/.npm/_prebuilds/392543-node-pty-prebuilt-multiarch-v0.11.14-node-v127-darwin-arm64.tar.gz
npm error prebuild-install info unpack resolved to /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/build/Release/pty.node
npm error sh: line 1: 42681 Killed: 9               prebuild-install --verbose
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.2.0
npm error gyp info using node@22.11.0 | darwin | arm64
npm error gyp ERR! find Python 
npm error gyp ERR! find Python Python is not set from command line or npm configuration
npm error gyp ERR! find Python Python is not set from environment variable PYTHON
npm error gyp ERR! find Python checking if "python3" can be used
npm error gyp ERR! find Python - executable path is ""
npm error gyp ERR! find Python - "" could not be run
npm error gyp ERR! find Python checking if "python" can be used
npm error gyp ERR! find Python - executable path is ""
npm error gyp ERR! find Python - "" could not be run
npm error gyp ERR! find Python 
npm error gyp ERR! find Python **********************************************************
npm error gyp ERR! find Python You need to install the latest version of Python.
npm error gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm error gyp ERR! find Python you can try one of the following options:
npm error gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm error gyp ERR! find Python (accepted by both node-gyp and npm)
npm error gyp ERR! find Python - Set the environment variable PYTHON
npm error gyp ERR! find Python - Set the npm configuration variable python:
npm error gyp ERR! find Python npm config set python "/path/to/pythonexecutable"
npm error gyp ERR! find Python For more information consult the documentation at:
npm error gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm error gyp ERR! find Python **********************************************************
npm error gyp ERR! find Python 
npm error gyp ERR! configure error 
npm error gyp ERR! stack Error: Could not find any Python installation to use
npm error gyp ERR! stack at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:306:11)
npm error gyp ERR! stack at PythonFinder.findPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:164:17)
npm error gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
npm error gyp ERR! stack at async configure (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:27:18)
npm error gyp ERR! stack at async run (/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
npm error gyp ERR! System Darwin 24.1.0
npm error gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm error gyp ERR! cwd /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch
npm error gyp ERR! node -v v22.11.0
npm error gyp ERR! node-gyp -v v10.2.0
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: /Users/steve/.npm/_logs/2024-11-02T07_04_34_364Z-debug-0.log
Error: Command failed: npm rebuild --unsafe-perm
✖ ERROR: Failed Operation
ℹ Stopping Homebridge Service...
✔ Homebridge Stopped
ℹ Starting Homebridge Service...
✔ Homebridge Started
```

### Configuration

```json
NA
```

### Environment

- OS: Mac Sequoia 15.1
- Software: Homebridge 1.8.5
- Node: 20.9.0 (now)
- npm: 10.1.0 (now)

### Process Supervisor

hb-service

### Additional Context

Also reported here - https://www.reddit.com/r/homebridge/comments/1gvtlnv/updating_nodejs_fail/

_No response_

**Comment by NorthernMan54** [comment]
Tks for sharing this

Will take a deeper look into why our https://github.com/homebridge/node-pty-prebuilt-multiarch package failed like that

**Comment by sddgit** [comment]
Thank you very much. I’d appreciate that.

**Comment by sddgit** [comment]
Was there an outcome from this @NorthernMan54 ?

**Comment by sddgit** [comment]
Should this be opened again pending a resolution @NorthernMan54 ?

**Comment by NorthernMan54** [comment]
If you try the latest UI beta, the beta 5.0.0 I believe I have resolved this.  I was the annual update of the underlying node-pty package, including support for NodeJS 23

**Comment by sddgit** [comment]
Thank you for your efforts. Now I feel more comfortable doing the update again when the time comes.

**Comment by NorthernMan54** [comment]
Had another report of the same on reddit today, and found something similar between this and reddit

```
npm error prebuild-install info unpack resolved to /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/build/Release/pty.node
npm error sh: line 1: 1687 Killed: 9 prebuild-install --verbose
```

So I went and tried the scenario again, and can not recreate the reported issue, using hb-service update-node, to update from 20.18.0 to the latest version on my Intel Mac, running Montery 12.7.5.  This was running with the latest UI release.  This is the machine I do release testing etc on

Then I also went and tried with my other M1 Mac, running Sequoia 15.0.1, and was able to recreate the issue.

Now to dig further

**Comment by kmnedd** [comment]
Ran into the same issue when updating to v20.10.0 on an M1 Mac Mini with Sequoia 15.1.1. I was able to upgrade to v22.11.0 without any issues.

**Comment by sddgit** [comment]
So how did you update to v22 @kmnedd ?

**Comment by kmnedd** [comment]
> So how did you update to v22 @kmnedd ?

sudo hb-service update-node 22.11.0

**Comment by sddgit** [comment]
Using the same command to update to V20 failed, but worked to V22?

**Comment by NorthernMan54** [comment]
After more digging, I can not recreate the issue on my Intel Mac, but on my M1 Mac, every time.

And have identified the line of code causing the issue, now to see about workarounds etc

The problem - https://github.com/prebuild/prebuild-install/issues/201

**Comment by kmnedd** [comment]
> Using the same command to update to V20 failed, but worked to V22?

Yes...the command worked.  If your mac prompts you to reinstall Xcode as a result of the initial failure, do this first before attempting to install v22.11.0

**Comment by JasonGoldenDDT** [comment]
I'm finding the lack of visibility in to Plug in Node version dependencies a problem with Homebridge.  Is there a plan to made this dependency more visible?  I saw an improvement with some plugins when upgrading based on HB update notices, but other plugins are dependent on older versions of node.  This dependency isn't visible in the UI and it's unclear when these developers will resolve their builds to align with HB.  Since downgrading (18.20.4)  HB has become more unstable.

**Comment by linkx2252** [comment]
Posting in case it helps anyone:

Tried sudo hb-service update-node today , broke my homebridge. It tried to update to 22.12.0.

Was able to fix by using:

sudo hb-service update-node 22.11.0

**Comment by JasonGoldenDDT** [comment]
I'm curious if you've noticed an impact on your setup, for me 22.12.0 produces these random errors the plugin developers say are resolved.

I noticed changing my node version to address these errors improved the reliability of the Home App, in that devices seemed to remain in sync more often. 

With 20.22 I am noticing my Samsung TV, and LG AC are often shown as "On" when they are "off."   Automation often fail to work with them because they will fail to connect when triggered by automation criteria.  If I use their remotes, or turn the on/off via the home app they work fine. 

```
[37m[11/27/2024, 9:19:04 AM] [39m[33mThe plugin "homebridge-appletv-enhanced" requires Node.js version of ^22.10.0 || ^20.18.0 || ^18.20.4 which does not satisfy the current Node.js version of v20.15.1. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[11/27/2024, 9:19:04 AM] [39m[33mThe plugin "homebridge-shortcuts-buttons" requires Node.js version of ^18.20.4 || ^20.16.0 || ^22.6.0 which does not satisfy the current Node.js version of v20.15.1. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/5/2024, 7:35:04 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/5/2024, 7:35:05 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/5/2024, 10:34:08 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/5/2024, 10:34:09 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/5/2024, 10:39:39 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/5/2024, 10:39:39 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/5/2024, 11:33:26 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/5/2024, 11:33:27 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/5/2024, 8:17:35 PM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/5/2024, 8:17:35 PM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/5/2024, 8:18:43 PM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/5/2024, 8:18:43 PM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/8/2024, 10:42:17 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/8/2024, 10:42:18 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/9/2024, 11:02:53 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/9/2024, 11:02:54 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/10/2024, 6:51:32 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/10/2024, 6:51:32 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/10/2024, 6:57:57 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/10/2024, 6:57:57 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/10/2024, 7:04:09 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/10/2024, 7:04:09 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/10/2024, 9:01:54 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/10/2024, 9:01:54 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/11/2024, 1:01:21 PM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/11/2024, 1:01:22 PM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/11/2024, 1:12:05 PM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/11/2024, 1:12:06 PM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/11/2024, 5:33:43 PM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/11/2024, 5:33:44 PM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/11/2024, 5:39:44 PM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/11/2024, 5:39:45 PM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/16/2024, 11:16:59 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/16/2024, 11:17:00 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/17/2024, 9:59:50 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/17/2024, 9:59:51 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/17/2024, 11:53:37 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/17/2024, 11:53:38 AM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/17/2024, 7:38:30 PM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[12/17/2024, 7:38:31 PM] [39m[33mThe plugin "homebridge-lg-thinq" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.12.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m

```

**Comment by NorthernMan54** [comment]
@JasonGoldenDDT Those Warnings are mostly non-impactful and are just saying that the installed version of NodeJS differs from what is specified.  There may be a case where a particular plugin has an issue with a particular NodeJS version like the `Homebridge Eufy Security` plugin.

But with that said, is your homebridge-lq-thinq plugin restarting infrequently triggering the message ?

**Comment by JasonGoldenDDT** [comment]
@NorthernMan54  thank you for that clarification.  Still trying to track down issues with Device and Home App not staying in sync with the LG and Samsung Plugins. 

Here's the Samsung thread: https://github.com/tavicu/homebridge-samsung-tizen/issues/702#issuecomment-2552251609

This error message sent me changing my node version, as at it was causing the LG plugin to rapidly reboot at one point. 

I notice switching between 18 and 22.12 that both the LG and the Samsung plugins 
![Screenshot 2024-12-18 at 10 57 14 AM](https://github.com/user-attachments/assets/426aaa8a-ca84-4f1f-9f26-0b3587db0866)

![Screenshot 2024-12-18 at 10 57 17 AM](https://github.com/user-attachments/assets/469a6511-2650-43b3-b215-5b04f3d7f6c0)

![Screenshot 2024-12-18 at 10 57 20 AM](https://github.com/user-attachments/assets/b206036d-d9a3-4bb3-b5e0-fe741eaca66d)

Became less reliable on 22.12 than on 18. 

Seeing the Node message in the log about the required version threw a flag, hence the question. 

The LG developers see no issues or have capacity to investigate Node impact. Same with Samsung. 

As I mentioned these devices are used in automation criteria, so it's daily interaction when they fall out of sync.  Seems like 22.12.0 made it worse. 

I've enabled expanded Node logging today and my debug log can span multiple days.  I'll report any patterns that come out of that.  If there is something specific I should look for LMK.   Sharing log data is cumbersome with the amount of masking needed to share here.  If you have any tools to assist besides Sublime and Regx, would love to hear it.

**Comment by NorthernMan54** [comment]
@JasonGoldenDDT I'm an old school unix command line person, so the OS provides all the tools I need.

Hopefully when the plugins go unstable they log something useful.  

PS NodeJS 22 for me has been very stable, and besides my own messing about 100% solid.

**Comment by JasonGoldenDDT** [comment]
Difficult for a non-dev to research, but it seems like these plugins operate differently on various versions of Node. 

With recent updates affecting how devices appear on when off in the home app.
