### ISSUE TITLE
Getting NPM ERR_REQUIRE_ESM on Homebridge update 

### ISSUE THREAD

**Issue by rionshin** [homebridge/homebridge#3744]
### Analysis

Get:1 https://repo.homebridge.io stable/main armhf homebridge armhf 1.3.11 [36.8 MB]
Fetched 36.8 MB in 3s (13.2 MB/s)      
Reading changelogs... Done
(Reading database ... 83955 files and directories currently installed.)
Preparing to unpack .../homebridge_1.3.11_armhf.deb ...
Running pre-upgrade steps...
Stopping Homebridge service...
Unpacking may take several minutes on low powered devices.
Unpacking homebridge (1.3.11) over (1.3.10) ...
Setting up homebridge (1.3.11) ...
Merging package.json file...
Refreshing user plugins, this may take a few minutes, please wait...

npm error code ERR_REQUIRE_ESM
npm error require() of ES Module /opt/homebridge/lib/node_modules/npm/node_modules/cacache/node_modules/p-map/index.js from /opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/entry-index.js not supported.
npm error Instead change the require of index.js in /opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/entry-index.js to a dynamic import() which is available in all CommonJS modules.
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-12-02T19_25_04_975Z-debug-0.log
npm error code ERR_REQUIRE_ESM
npm error require() of ES Module /opt/homebridge/lib/node_modules/npm/node_modules/cacache/node_modules/p-map/index.js from /opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/entry-index.js not supported.
npm error Instead change the require of index.js in /opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/entry-index.js to a dynamic import() which is available in all CommonJS modules.
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-12-02T19_25_05_717Z-debug-0.log

Running post-install steps...
Warning: The home dir /home/homebridge you specified already exists.
The system user `homebridge' already exists. Exiting.

### Expected Behavior

No errors when updating the homebridge 

### Steps To Reproduce

I am running Homebridge OS on Raspberry Pi4  when doing sudo apt update and upgrade i am getting the error. 
 

### Logs

```markdown
verbose cli /opt/homebridge/bin/node /opt/homebridge/bin/npm
1 info using npm@10.8.2
2 info using node@v20.18.0
3 silly config load:file:/opt/homebridge/lib/node_modules/npm/npmrc
4 warn config global-style This option has been deprecated in favor of `--install-strategy=shallow`
5 silly config load:file:/var/lib/homebridge/.npmrc
6 warn config global-style This option has been deprecated in favor of `--install-strategy=shallow`
7 silly config load:file:/root/.npmrc
8 silly config load:file:/var/lib/homebridge/etc/npmrc
9 verbose title npm rebuild
10 verbose argv "--prefix" "/var/lib/homebridge" "rebuild"
11 verbose logfile logs-max:10 dir:/root/.npm/_logs/2024-12-02T19_25_05_717Z-
12 verbose logfile /root/.npm/_logs/2024-12-02T19_25_05_717Z-debug-0.log
13 silly logfile start cleaning logs, removing 1 files
14 verbose stack Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/homebridge/lib/node_modules/npm/node_modules/cacache/node_modules/p-map/index.js from /opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/entry-index.js not supported.
14 verbose stack Instead change the require of index.js in /opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/entry-index.js to a dynamic import() which is available in all CommonJS modules.
14 verbose stack     at Object.<anonymous> (/opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/entry-index.js:22:14)
15 error code ERR_REQUIRE_ESM
16 error require() of ES Module /opt/homebridge/lib/node_modules/npm/node_modules/cacache/node_modules/p-map/index.js from /opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/entry-index.js not supported.
16 error Instead change the require of index.js in /opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/entry-index.js to a dynamic import() which is available in all CommonJS modules.
17 verbose cwd /
18 verbose os Linux 6.1.21-v8+
19 verbose node v20.18.0
20 verbose npm  v10.8.2
21 verbose exit 1
22 verbose code 1
23 error A complete log of this run can be found in: /root/.npm/_logs/2024-12-02T19_25_05_717Z-debug-0.log
```

### Configuration

```json
Not applicable
```

### Environment

- OS: Linux homebridge 6.1.21-v8+   aarch64
- Software:  1.8.5
- Node:v20.18.0
- npm: v10.8.2

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
I believe this is a duplicate, but your title it better - https://github.com/homebridge/homebridge/issues/3741

**Comment by rionshin** [comment]
Sorry didn't notice there are anything issue like mine. Strange is that i have   PI5 with same HB installation same config however i don't get error when i update it.  I have the same NPM and Node version.

**Comment by NorthernMan54** [comment]
Yeah something odd with the npm package is going on.  I had the same message, but never saw it again afterwards.  Pls monitor and let us know if you have other issues.

I think I will close the other, and keep your title

**Comment by bondskin** [comment]
same issue here

**Comment by buzz-dee81** [comment]
I‘m getting the exact same error, had it already during install of package version 1.3.10
It doesn’t seem to keep homebridge from running smoothly afterwards, error does only show up during install / package update

**Comment by dacarson** [comment]
I got this error when updating home bridge that happened via apt-get update, as originally reported. But I also get it when I try to update plugins that I am editing
```
/var/lib/homebridge/node_modules/homebridge-weather-plus $ npm install
npm error code ERR_REQUIRE_ESM
npm error require() of ES Module /opt/homebridge/lib/node_modules/npm/node_modules/cacache/node_modules/p-map/index.js from /opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/entry-index.js not supported.
npm error Instead change the require of index.js in /opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/entry-index.js to a dynamic import() which is available in all CommonJS modules.
npm error A complete log of this run can be found in: /home/homebridge/.npm/_logs/2024-12-06T19_51_38_015Z-debug-0.log

**Comment by dacarson** [comment]
Is there any work around? My home bridge is currently broken as it fails to load plugs due to the ESM issue.

I tried rolling back to the version I had before I did a apt-get update, and that failed:
```
$ sudo apt-get install homebridge=1.2.1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be DOWNGRADED:
  homebridge
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 16 not upgraded.
Need to get 0 B/39.6 MB of archives.
After this operation, 2,529 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
dpkg: warning: downgrading homebridge from 1.3.11 to 1.2.1
(Reading database ... 229645 files and directories currently installed.)
Preparing to unpack .../homebridge_1.2.1_arm64.deb ...
Running pre-upgrade steps...
Stopping Homebridge service...
Unpacking may take several minutes on low powered devices.
Unpacking homebridge (1.2.1) over (1.3.11) ...
dpkg: warning: unable to delete old directory '/opt/homebridge/lib/node_modules/npm/node_modules/node-gyp/node_modules': Directory not empty
dpkg: warning: unable to delete old directory '/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/hap-client/node_modules/axios/lib/helpers': Directory not empty
dpkg: warning: unable to delete old directory '/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/hap-client/node_modules/axios/lib/adapters': Directory not empty
dpkg: warning: unable to delete old directory '/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/hap-client/node_modules/axios/lib': Directory not empty
dpkg: warning: unable to delete old directory '/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/hap-client/node_modules/axios': Directory not empty
dpkg: warning: unable to delete old directory '/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/hap-client/node_modules': Directory not empty
Setting up homebridge (1.2.1) ...
Merging package.json file...
Refreshing user plugins, this may take a few minutes, please wait...

/opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/verify.js:11
const pMap = require('p-map')
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/homebridge/lib/node_modules/npm/node_modules/cacache/node_modules/p-map/index.js from /opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/verify.js not supported.
Instead change the require of index.js in /opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/verify.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/verify.js:11:14) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.12.2
/opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/verify.js:11
const pMap = require('p-map')
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/homebridge/lib/node_modules/npm/node_modules/cacache/node_modules/p-map/index.js from /opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/verify.js not supported.
Instead change the require of index.js in /opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/verify.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/opt/homebridge/lib/node_modules/npm/node_modules/cacache/lib/verify.js:11:14) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.12.2

Running post-install steps...
The system user `homebridge' already exists. Exiting.
Starting Homebridge service....

**Comment by dacarson** [comment]
There is discussion of the issue here: https://github.com/sindresorhus/p-map/issues/35

**Comment by NorthernMan54** [comment]
@dacarson You have two things going on, try going forward again and look for any messages from the apt install stage.

The ESM error so far has been benign to homebridge

**Comment by dacarson** [comment]
Thank you for your help.

I did go forward again, and I searched for all installed versions of p-map and found that I had version 7.0.0 installed, when everything seemed to call for ^4.0.0
When I manually deleted the 7.0.0 version, and copied in a 4.0.0 version, I was able to see the issue. I changed the plugin I was debugging to use the `got` package (I'm migrating off the long deprecated `request` package) and it seems that that was the root of the issue. The `got` package is ESM. 
I am now migrating to `axios` package instead.
