### ISSUE TITLE
EADDRINUSE 

### ISSUE THREAD

**Issue by Ser-Loras** [homebridge/homebridge#3759]
### Analysis

At launch Homebridge encounters an EADDRINUSE error, shuts down, restarts, then encounters the same error and restarts, and so on and so on in an endless loop.

The following section on the wiki seems related to this error:

> This error is a Generic TCP/IP message thrown by Node.js apps trying to listen on a port already being listened to. This is normally caused by a homebridge process running in the background without you realizing it. If you've set your homebridge install to run when your system starts up, try removing this until your setup/config is complete.

It does appear I have multiple processes running. I see 2 different "Homebridge" processes in Activity Monitor in addition to the "homebridge-config-ui-x" process. If I try to force quit one of the processes, the issue does not stop. If I restart my computer or just restart Homebridge the issue still continues.

Homebridge does run when my system starts up, but I can't find any setting in Homebridge for this, and I don't see Homebridge in the Login Items in my System Preferences, so I am not sure how to stop this.

### Expected Behavior

No looping error messages

### Steps To Reproduce

1. Start Homebridge
2. Looping error message

### Logs

```markdown
[12/29/2024, 8:19:47 PM] Loaded config.json with 7 accessories and 1 platforms.
[12/29/2024, 8:19:47 PM] Loaded 0 cached accessories from cachedAccessories.
[12/29/2024, 8:19:47 PM] ---
[12/29/2024, 8:19:48 PM] Loaded plugin: homebridge-config-ui-x@4.67.0
[12/29/2024, 8:19:48 PM] Registering platform 'homebridge-config-ui-x.config'
[12/29/2024, 8:19:48 PM] ---
[12/29/2024, 8:19:48 PM] Loaded plugin: homebridge-dummy@0.9.0
[12/29/2024, 8:19:48 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[12/29/2024, 8:19:48 PM] ---
[12/29/2024, 8:19:48 PM] Loading 1 platforms...
[12/29/2024, 8:19:48 PM] [Config] Initializing config platform...
[12/29/2024, 8:19:48 PM] [Config] Spawning homebridge-config-ui-x with PID 20305
[12/29/2024, 8:19:48 PM] Loading 7 accessories...
[12/29/2024, 8:19:48 PM] [SAPPHIRE] Initializing DummySwitch accessory...
[12/29/2024, 8:19:48 PM] [RUBY] Initializing DummySwitch accessory...
[12/29/2024, 8:19:48 PM] [RUBY] Setting switch to false
[12/29/2024, 8:19:48 PM] [EMERALD] Initializing DummySwitch accessory...
[12/29/2024, 8:19:48 PM] [EMERALD] Setting switch to false
[12/29/2024, 8:19:48 PM] [AMETHYST] Initializing DummySwitch accessory...
[12/29/2024, 8:19:48 PM] [AMETHYST] Setting switch to false
[12/29/2024, 8:19:48 PM] [SHINE] Initializing DummySwitch accessory...
[12/29/2024, 8:19:48 PM] [DOWN] Initializing DummySwitch accessory...
[12/29/2024, 8:19:48 PM] [COLOR] Initializing DummySwitch accessory...
[12/29/2024, 8:19:48 PM] [COLOR] Setting switch to false
Setup Payload:
X-HM://xxxxxxxxxxxxxxxx
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:                                                                                                 
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:                       
    ┌────────────┐     
    │ xxx-xx-xxx │     
    └────────────┘                          
[12/29/2024, 8:19:48 PM] Error: listen EADDRINUSE: address already in use :::51826
    at Server.setupListenHandle [as _listen2] (node:net:xxxx:xx)
    at listenInCluster (node:net:xxxx:xx)
    at Server.listen (node:net:xxxx:x)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:166:20)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:380:21)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1378:18)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:196:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:177:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:170:75
    at new Promise (<anonymous>)
[12/29/2024, 8:19:48 PM] Got SIGTERM, shutting down Homebridge...
[12/29/2024, 8:19:50 PM] [Homebridge UI] Homebridge UI v4.67.0 is listening on :: port 8182
[12/29/2024, 8:19:50 PM] [Homebridge UI] Error: listen EADDRINUSE: address already in use :::8182
[12/29/2024, 8:19:50 PM] [Homebridge UI] Another process or service on this host is using port 8182.
[12/29/2024, 8:19:50 PM] [Homebridge UI] Please stop the other service or change the port you have assigned to homebridge-config-ui-x.
[12/29/2024, 8:19:50 PM] [Homebridge UI] Ending process now.
[12/29/2024, 8:19:57 PM] Loaded config.json with 7 accessories and 1 platforms.
[12/29/2024, 8:19:57 PM] Loaded 0 cached accessories from cachedAccessories.
[12/29/2024, 8:19:57 PM] ---
[12/29/2024, 8:19:58 PM] Loaded plugin: homebridge-config-ui-x@4.67.0
[12/29/2024, 8:19:58 PM] Registering platform 'homebridge-config-ui-x.config'
[12/29/2024, 8:19:58 PM] ---
[12/29/2024, 8:19:58 PM] Loaded plugin: homebridge-dummy@0.9.0
[12/29/2024, 8:19:58 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[12/29/2024, 8:19:58 PM] ---
[12/29/2024, 8:19:58 PM] Loading 1 platforms...
[12/29/2024, 8:19:58 PM
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "xxxxxxxxxx",
        "port": 51826,
        "pin": "xxx-xx-xxx"
    },
    "accessories": [
        {
            "name": "SAPPHIRE",
            "stateful": true,
            "dimmer": false,
            "reverse": false,
            "time": 1000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "RUBY",
            "stateful": true,
            "dimmer": false,
            "reverse": false,
            "time": 1000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "EMERALD",
            "stateful": true,
            "dimmer": false,
            "reverse": false,
            "time": 1000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "AMETHYST",
            "stateful": true,
            "dimmer": false,
            "reverse": false,
            "time": 1000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "SHINE",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 1000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "DOWN",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 1000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "COLOR",
            "stateful": true,
            "dimmer": false,
            "reverse": false,
            "time": 1000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8182,
            "auth": "none",
            "theme": "auto",
            "lightingMode": "dark",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        }
    ]
}
```

### Environment

- OS: Mac OS 10.14.4
- Software: v1.8.5
- Node: 20.9.0
- npm:

### Process Supervisor

hb-service

**Comment by ShastLeLow** [comment]
I have run into this as well. Tried everything to add to Apple Home and nothing. 

My situation 

- Was running for about a year on an old Toshiba amd 64 laptop that I installed Ubuntu on. Machine was incredibly loud, and everything else in my house is Apple. 
- Bought a Mac mini M4 (base model) this week. 
- Installed all macOS updates. On 15.2
- Set up HomeBridge per install instructions, did not initially notice the macOS 15.2 section. Restored from backup. Everything worked. 
- Yesterday, all my devices were showing in Home as not connected. 
- Tried troubleshooting, noticed the macOS 15.2 section, tried all that. 
- Removed everything, tried again. 

Nothing. Can’t add to my home. Home app doesn’t “see” it running, manually adding never adds. 

Ended up back on the loud, old Toshiba for now. 

Komga, Plex and everything else working fine on the mini

really hoping for a resolution soon.

**Comment by NorthernMan54** [comment]
This typically indicates a challenge with your install/setup and two copies of homebridge trying to use the same port.

You could try incrementing the port in the config to see if that resolves the issue.

**Comment by ShastLeLow** [comment]
> This typically indicates a challenge with your install/setup and two copies of homebridge trying to use the same port.
> 
> You could try incrementing the port in the config to see if that resolves the issue.

Would this be the case even if I stopped the service on the old instance and powered it off?

If I choose a new port, like 8582, try before doing the self-signed SSL? I’d rather avoid that step if I can.

**Comment by NorthernMan54** [comment]
Port and ssl are different, so no need to redo SSL
